### ISSUE TITLE
Stick Man 2015 - Movie not found error in search results

### ISSUE THREAD

**Issue by stuart0001** [Radarr/Radarr#1002]
Results show up in manual search but won't download due to error "Unknown release. Movie not found"
TMDB entry - https://www.themoviedb.org/movie/374251-stick-man

**Radarr Version:**
0.2.0.375

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by jOOc** [comment]
@stuart0001 thats probably not a Radarr issue, thats because TMDB has it as released 2016 and that is wrong. Official it was released in 2015 and the releases have 2015 in the release name.
Either download it manual in Radarr or go to TMDB and updated the info. You can get the right release date from eg IMDB and put it in TMDB. Dont know how fast the update will take though.

**Comment by onedr0p** [comment]
I pushed a update to use the lowest year returned from tmdb, should be in nightly soon.

**Comment by onedr0p** [comment]
![image](https://cloud.githubusercontent.com/assets/213795/23581331/d0a3f5c2-00df-11e7-96ab-e148fc40aab1.png)
 
All good now :)
