### ISSUE TITLE
Automatic download does not work

### ISSUE THREAD

**Issue by jOOc** [Radarr/Radarr#101]
I'm on Win 10, Radarr version: 0.2.0.44 and using Deluge as my download client.

When I add a movie the DL is not started automatic, I need to push the magnifying glass to search or do a manual search. I even tried starting all the background tasks to see if they did anything, but nothing happend.

In Sonarr if I add a TV Series, its watched and episodes is automaticlly downloaded (depending on the option like missing, future ..)

**Comment by donldmn** [comment]
When you add a movie do you push the plus (add) or the magnifying glass (add and search for movie)?

I'm using usenet and it seems to do a search whenever I add using the magnifying glass when adding.

**Comment by jOOc** [comment]
@donldmn *blushing* 
I pressed to plus sign *banging my head*
I havent even noticed there were 2 different options, even in Sonarr.

This can be closed.

**Comment by galli-leo** [comment]
Well Sonarr still automatically searches for newly added episodes. We should do the same.

**Comment by evulhotdog** [comment]
Just keeping notes:

![image](https://cloud.githubusercontent.com/assets/365456/21870648/72390018-d82b-11e6-87c3-711ea70defcb.png)

**Comment by NP726** [comment]
I'm running 0.2.0.288 in an Unraid docker.

Downloads won't automatically start for a movie, regardless of whether I push the plus or the magnifying glass. I am able to go into the movie and manually search for a movie, and it works, but auto search on add doesn't. Was this resolved above, or is it a known issue?

**Comment by galli-leo** [comment]
@NP726 Do you see anything in the logs?

**Comment by NP726** [comment]
Had a brainfart and was looking at unraid/docker logs instead of radarr logs. Found error messages reported in #638. Updated inside radarr to 0.2.0.299 and the issue seems to be resolved.

**Comment by mzaur** [comment]
I seem to be having this issue in 0.2.0.535

Log shows 0 indexers for some reason yet when I go to indexers, PTP tests fine. 

`17-3-26 12:36:23.3|Info|MovieService|Adding Movie [][Deadpool] Path: [/mnt/mpathc/orange/media/Movies/Deadpool (2016)]
17-3-26 12:36:23.5|Info|RefreshMovieService|Updating Info for Deadpool
17-3-26 12:36:23.7|Info|DiskScanService|Scanning disk for Deadpool
17-3-26 12:36:23.7|Info|MovieScannedHandler|[Deadpool] was recently added, performing post-add actions
17-3-26 12:36:23.8|Info|MediaCoverService|Downloading Poster for [tt1431045][Deadpool] http://image.tmdb.org/t/p/original/inVq3FRqcYIRl2la8iZikYYxFNR.jpg
17-3-26 12:36:23.8|Info|NzbSearchService|Searching 0 indexers for [Deadpool]
17-3-26 12:36:23.8|Info|DownloadDecisionMaker|No results found
17-3-26 12:36:23.8|Info|MovieSearchService|Movie search completed. 0 reports downloaded.`

Then later I did it manually and it worked fine

`17-3-26 17:13:15.8|Info|DownloadDecisionMaker|Processing 226 releases
17-3-26 17:13:24.5|Info|RssSyncService|RSS Sync Completed. Reports found: 226, Reports grabbed: 0
17-3-26 17:37:50.3|Info|NzbSearchService|Searching 1 indexers for [Deadpool]
17-3-26 17:37:50.6|Info|DownloadDecisionMaker|Processing 13 releases
17-3-26 17:38:18.5|Info|DownloadService|Report sent to Deluge. Deadpool.2016.Extras.720p.BluRay.x264-DON `

This does not happen all the time, just sometimes.

**Comment by giorgyss** [comment]
Same issue here
I can search and choose a download, but is not working automating
Version 525 recently installed from scratch

**Comment by galli-leo** [comment]
@giorgyss Can you update to .535? Also do you see anything in the logs?

@mzaur Did you try removing PTP and adding it again?

**Comment by jclemons7** [comment]
I was experiencing the same thing and clicking the spyglass icon prompted a download on movies that have been released or appear in indexers.  However, I'm wondering.. for movies that have not been released and are not available in indexers when I add them.. can I expect Sonarr to check for them periodically on a chron job or something?

The reason I ask is because the movie I added which had been released never got fetched for download until I added it again and used the spyglass icon even after 4 or 5 days. 

My question is, going forward.. if I'm just sure to click the spyglass and not the + even on movies that haven't been released.. will they download?  

For the record.. Sonarr works as I would expect it.. regardless of how I add the TV show.. it will download once available, if the behavior is different by design, I just need to know that I guess.

**Comment by galli-leo** [comment]
@jclemons7 You probably have minimum availability set to PreDB. Please see this wiki page for our recommended settings and why your movie probably not downloaded: https://github.com/Radarr/Radarr/wiki/Minimum-Availability

**Comment by giorgyss** [comment]
@galli-leo with spyglass it works BUT im facing the same problem of @jclemons7, if movie was not released yet, and its released, let say... in a month, is no longer search and downloaded... :(

**Comment by galli-leo** [comment]
@giorgyss Have you read the wiki page I linked above?

**Comment by jclemons7** [comment]
All mine are set to physical...
________________________________

**Comment by galli-leo** [comment]
@jclemons7 Which is the same as PreDB.

**Comment by jclemons7** [comment]
Oh, ok...so, what should I set all newly added movies as?  Cinema?

________________________________

**Comment by galli-leo** [comment]
@jclemons7 Depends on your indexers. Please see the wiki article (https://github.com/Radarr/Radarr/wiki/Minimum-Availability) for detailed information on what we recommend.

**Comment by jclemons7** [comment]
Sorry, I'm still having trouble understanding...even after reading the wiki.

I added a mix of movies to Radarr where some are in the theaters still, and some are older movies already released and available on my indexers...in order to get Radarr to download them auto-magically as soon as they are available on Blu-ray or web download (or immediately for currently available movies)... in your opinion, what should settings should I use on the movies I add to my queue going forward?

I only ask because my wife and family will be using Radarr to pick movies and I want to make it as simple as possible on them.

________________________________

**Comment by galli-leo** [comment]
@jclemons7 It depends on your indexers. If you are using private torrent indexers without any fakes, go ahead and set all of your movies to Announced. If you are using public trackers or newznab indexers which have a lot of fakes, set it to Physical / Web and set an Availability Delay of -21 days in Settings -> Indexers
