### ISSUE TITLE
First character of german movie titles changed to uppercase

### ISSUE THREAD

**Issue by wdghub** [Radarr/Radarr#1017]
**Description:**
After importing movies all titles are modified so that the first character is shown as uppercase (i guess  as it would be in english). Why is the movie Name modified at all? It should be correct when you retrieve it from TMDB or IMDB anyway.

Example:
German title "Ab durch die Hecke" is changed to "Ab Durch Die Hecke"

**Radarr Version:**
0.2.0.375

**Comment by Rusk85** [comment]
Looking through the milestone issues for 0.2 I could take a stab at I found this. Now I am a bit unclear how you want this handled. 
I would keep the capitalisation as returned from TMDb/IMDb including the first letter. If it is aesthetically more appealing to keep the letter of the first word in the title uppercase than that's a different story.
So how do you want this handled?

**Comment by wdghub** [comment]
Hi!

 

I think you should to keep the capitalisation as returned from TMDB or IMDb. In German it is simply wrong to show the first letter of every word in a title uppercase. I would expect that the correct movie title in every language is maintained at TMDB/IMDb and should be used by Radarr 1:1 without modifications.

 

Thank you!

 

Von: Rusk85 [mailto:notifications@github.com] 
Gesendet: Samstag, 18. März 2017 07:01
An: Radarr/Radarr <Radarr@noreply.github.com>
Cc: wdghub <oliver.waldmann@gmx.at>; Author <author@noreply.github.com>
Betreff: Re: [Radarr/Radarr] First character of german movie titles changed to uppercase (#1017)

 

Looking through the milestone issues for 0.2 I could take a stab at I found this. Now I am a bit unclear how you want this handled.
I would keep the capitalisation as returned from TMDb/IMDb including the first letter. If it is aesthetically more appealing to keep the letter of the first word in the title uppercase than that's a different story.
So how do you want this handled?

**Comment by Rusk85** [comment]
Allet klar wird so jemacht, Meister! ;)

All's well. That's about all the clarification I need and is pretty much in line with my original intention. Currently doing a bit of refactoring. Still getting acquainted with the code base. Too bad I only discovered the project toward the end of my vacation otherwise I would've had more time to crunch away on this. 

Speaking of which ReSharper announced to me upon opening the radarr solution my (default as it is) coding conventions were to be overwritten with those provided by the solution. Do you have any specific coding conventions in place or is that merely something pulled in at the time of the initial fork from sonarr? Because I am all for coding conventions - hot topic at work as well ;) - but haven't set any. If anybody has a good template I'll gladly pick it up.

**Comment by galli-leo** [comment]
@Rusk85 Not really any special conventions that I know of. For now I just have followed the style of Sonarr.

**Comment by Rusk85** [comment]
I mean for starters there is the whole to `var` or not to `var` discussion that can fill entire work days with discussion but I feel that should be sorted in a different discussion.

**Comment by galli-leo** [comment]
@Rusk85 From what I've seen, if the exact Type is not required (e.g. like in `Movie theMovie = null;`) we are using `var`. Feel free to join us on discord for further questions, so that we don't clutter this issue here ;)

**Comment by Rusk85** [comment]
Oh yeah I read something about Discord somewhere. Good idea. Definitively good for talking about specific issues in order to get answers quickly but when it's about making decisions that impact others that are not present at that moment or when talking about said Coding Conventions the results of such exchanges should be affixed for posterity somewhere. Makes it easier for new devs to get a hang of things and might attract new contributors more easily if there are some good base line principles and guidelines along with some general documentation to read up upon. That's at least the way I feel.

**Comment by wdghub** [comment]
Still not fixed yet - Radarr Version 0.2.0.995, so please do not close.

**Comment by galli-leo** [comment]
@wdghub Is that only shown in the UI? e.g. are files named correctly?

**Comment by wdghub** [comment]
The files are named correctly in german, also the movie names are shown fine in the search window when you start typing them - only the UI Shows them with the first character of every word in uppercase.

**Comment by galli-leo** [comment]
Ok, so this is just because of the css, I don't think this will be changed on the current UI.

**Comment by wdghub** [comment]
And why not? It is an error, because it is wrong that way :)

**Comment by galli-leo** [comment]
Because it's a UI decision. We will revisit whether we want title casing or not with the new UI, but with the current one it's staying as it is.
