### ISSUE TITLE
Not able to find any release from the german release group "PsO"

### ISSUE THREAD

**Issue by y4m4aa** [Radarr/Radarr#1021]
**Description:**

No such release is found whether in automatic nor in manual search. The releases are there on the usenet indexer and the torrent tracker but nothing can be found. Every release from other groups work perfectly.
Tried with NZB Hydra and directly with api to the indexer. For the torrent tracker with jackett.

Example: 
Passengers.German.DL.AC3.Dubbed.720p.BluRay.x264-PsO is not found on any of my indexers/trackers but everything seems to be ok with the release i can find them with imdbID search if i search manually on the indexer website. Checked it for 5 other releases from PsO same result.
Couchpotato is able to find and download them.

**Radarr Version:**
0.2.0.375

**Comment by onedr0p** [comment]
Did you set the profile language to be German for that movie?

**Comment by y4m4aa** [comment]
yes i did and like i said it's the same for every release from PsO.  The release is not found with manual search i don't think it has something to do with the profile  because other languages than the profile languages are found with manual search.
Because there is nothing found i thought there is no need for a log... anyway here are the logs 

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/819613/radarr.trace.txt)
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/819614/radarr.debug.txt)
[radarr.txt](https://github.com/Radarr/Radarr/files/819615/radarr.txt)

**Comment by y4m4aa** [comment]
here are the logs with every other indexer off.  I guess thats better..

[radarr.debug (1).txt](https://github.com/Radarr/Radarr/files/819628/radarr.debug.1.txt)
[radarr (1).txt](https://github.com/Radarr/Radarr/files/819627/radarr.1.txt)
[radarr.trace (1).txt](https://github.com/Radarr/Radarr/files/819626/radarr.trace.1.txt)

**Comment by onedr0p** [comment]
Yeap that's the problem :) what is this crap? `{{5tLEwZGCZ@}}`

**Comment by y4m4aa** [comment]
i don't know but i got that on almost every release like for example this one which is found without any trouble:
![radarr](https://cloud.githubusercontent.com/assets/25848830/23590474/133c12aa-01e1-11e7-90f7-3cf74404fa7b.jpg)

**Comment by onedr0p** [comment]
I think it doesn't like year not being in the release name for `Passengers.German.DL.AC3.Dubbed.720p.BluRay.x264-PsO`

**Comment by onedr0p** [comment]
Year needs to be in the release name for Radarr to know what to do.

**Comment by onedr0p** [comment]
Tell PsO to get their shit together ;)

**Comment by y4m4aa** [comment]
ok I see... so there is no way for radarr to add these releases without the year?

**Comment by onedr0p** [comment]
not automatically, you need to manually send the releases.

**Comment by y4m4aa** [comment]
how would i do that?

**Comment by onedr0p** [comment]
Got confused for a moment, disregard that post. The releases aren't showing up at all in the movie search tab is what you are saying. If the indexer supports searching by imdbid it should show up.

**Comment by y4m4aa** [comment]
yes they are not showing up. I'm not 100% percent sure but i thought that my indexer (https://newz-complex.org/www/) does support searching by imdbid. Is there a way to find out?

**Comment by onedr0p** [comment]
Usually they have a endpoint that shows XML like:

https://newz-complex.org/www/?t=caps&apikey= or https://newz-complex.org?t=caps&apikey=

**Comment by onedr0p** [comment]
Get a hold of me on discord and I can help you more.

**Comment by d4re** [comment]
Is there any way we could add releases even when the year is missing if the indexer returns the right imdb id? 
This should get rid of the issue of potentially getting the wrong movie and would be really helpful, since this problem occurs quite often with german releases.

**Comment by galli-leo** [comment]
@d4re This would only increase the problem of wrongly matching movies. Sadly I have seen multiple times how indexers mislabel the imdbids of movies. If we stop matching years, suddenly Beauty and the Beast 2013 might get downloaded :/ I am thinking about building a few things to help with german and french releases.

**Comment by d4re** [comment]
@galli-leo I guess you sadly are right about that. I guess there is no way to enable automatic imports for such releases then. Except maybe searching the release on predb and read the release date from the nfo file, but that would probably still be error prone and way too much work for a problem caused just by a few release groups. 

But it would still be good if they are at least shown when doing a manual search. That way, we could see that they exist and with your proposed solution for issue https://github.com/Radarr/Radarr/issues/1407 there would be a nice way to import it manually.

Anyway, thanks that you are trying to improve the handling of releases even though the problem with the year is not on your side but caused by not following the scene rules!

**Comment by AnthraxLeprosyPi** [comment]
@galli-leo Having the same issue with missing year info from my german indexer I'd like to humbly weigh in.
Allthough I understand what you're saying I really don't understand why IMDB-ID isn't sufficient...
Let's take your example:

When Beauty and the beast comes out it might be called like this on our german sites:
"Beauty.and.the.Beast.German.DL.AC3.Dubbed.1080p.BluRay.x264-PsO"
As of now this release would be ignored because of the missing year constraint even though the search result came back spcifically for this imdbid :-(

If I understand you correctly there (might) be some sites that return wrong results for imdbids?!
But what is the harm in that?

I'd rather download a wrong movie from time to time and having to manually redownload than having no automatic downloads at all ;-/

Cheers and thank you for this absolutly great piece of software
Anthrax

PS: there is a pull request that should fix this - any plans to look into it?

**Comment by galli-leo** [comment]
@AnthraxLeprosyPi Once I get a bit more time (after finals), I should have no problem going over the pr.

Regarding the Beauty and the Beast example. There are like 3 different B&B movies all called the same (2x animated, 1x live action, 2017). If the indexers now return the wrong imdbid (maybe the one for the 2017, while it is actually the animated one from 1978), we would download the wrong version and of course the user wouldn't be happy about that.

Additionally, even if we did still put it up in the search tab, Radarr wouldn't be able to import it anyways, since again, it cannot parse it from the filename. And there it does not have the helpful imdbid from the indexer :/

**Comment by AnthraxLeprosyPi** [comment]
@galli-leo your last paragraph doesn't make sense to me...(maybe because I haven't seen your datamodel yet) 

My train of thought:
1. Movie exists as monitored in the database
2. IMDb id from meta data gets used for indexer api call when search is started
3. Results including returned filename (without year) get stored under original movie entry and release downloaded
4. Selected Result (based on tags) are connected to original movie entry in database
5. Parser/post processor checks if filename exists in any of the monitored movies and moves/renames accordingly
6.boom done ;)

?

Regards
Anthrax

**Comment by galli-leo** [comment]
The problem is we do not do 3. (But I have a plan on integrating that as well as with the upcoming xem for movies). Also during 5., often the filename may be different to the release name we get from the indexer. So 5. may still fail, even if we store it at 3.

**Comment by AnthraxLeprosyPi** [comment]
Well I keep my hopes up with you guys. Amazing job thus far...

**Comment by MoeJoe87** [comment]
@y4m4aa can you please tell me which Indexer for german content u are using? I would also like content from PsO. We can talk in discord....

Regards,
Moli
