### ISSUE TITLE
[Feature Request] Unselect All in Movie Editor

### ISSUE THREAD

**Issue by perrin** [Radarr/Radarr#1025]
**Description:**

When using the Movie Editor to manage a movies matching a particular filter; if they are updated that they no longer match the filter they remain selected and subsequent save/organize apply to those non-visible entries as well.  This caught me by surprise when updating Monitored and Profile status of existing movies that I imported.

An Unselect All button next to the count would allow easily resetting of selected entries without having to exit the Movie Editor screen and going back in (or manually finding and unselecting previous changed entries)

**Radarr Version:**
0.2.0.452

**Logs:**

**Comment by onedr0p** [comment]
This doesn't do what you ask?

![image](https://cloud.githubusercontent.com/assets/213795/23591290/eead2a5c-01bb-11e7-90ed-9edfeda3d958.png)

**Comment by perrin** [comment]
I open up Movie Editor, select the _Monitored Only_ filter, and then select 4 movies and change the Monitor dropdown to Unmonitored.
<img width="1368" alt="screen shot 2017-03-05 at 2 17 28 pm" src="https://cloud.githubusercontent.com/assets/118446/23591543/15a857e2-01af-11e7-9435-2ae22b661145.png">

After hitting save, the status of those movies is updated and they are filtered out of the list but are still selected.
<img width="1355" alt="screen shot 2017-03-05 at 2 17 48 pm" src="https://cloud.githubusercontent.com/assets/118446/23591575/86dcd2b2-01af-11e7-9777-51e5a261a85f.png">

Clicking on the select box next to Title only toggles the visible entries, not the filtered ones.
<img width="1359" alt="screen shot 2017-03-05 at 2 18 37 pm" src="https://cloud.githubusercontent.com/assets/118446/23591579/9735d514-01af-11e7-9b8c-7f3b3d239bd0.png">

Switching the filter back to _All_ shows the 4 movies still selected.
<img width="1364" alt="screen shot 2017-03-05 at 2 19 00 pm" src="https://cloud.githubusercontent.com/assets/118446/23591583/a4a521be-01af-11e7-9176-28ecf86f12f6.png">

Because the movies being changed may not always be on the first page when going back to _All_ you have to search for the selected titles to unselect them, or exit the Movie Editor and go back in.

**Comment by onedr0p** [comment]
I think this is working as intended @geogolem can chime in as to why we had to do it this way.

**Comment by geogolem** [comment]
I can confirm that this is working as intended; however, I do think a "Select all or Unselect all" button would be beneficial.

I originally implemented it this way... as I was having trouble manipulating the selection state etc.; however, I should now be able to do it... I could toggle everything to unselected after saving; however, I think it is better to leave that as is - and just provide an unselect all button... Regarding items staying selected even when not in view (due to filtering) this is behaving as expected. We could change it to deselect all items that do not exist in the current filter view.... but then what happens when changing filtering views back, are they again selected - it becomes confusing. I think providing a global "unselect all" that sets the selection count back to zero will resolve the issue in the most flexible possible way - the reason it hasn't been done already is simply because we know the user can do this manually by reloading the movie editor; however, you are right, the user shouldnt have to do that.

**Comment by geogolem** [comment]
OK - so I want to implement a "Select ALL" and/or "Unselect ALL" button  but we need to have a little discussion regarding what is best to implement.

Currently, selections persist across pages and across filters....

For example, items remain selected when changing filters and are considered selected even if the corresponding items are not displayed due to the current filtering ---> i.e. filtering and page changes, do not effect selection.

I think this is the best behavior.. since it would be confusing if changing filters toggled the selected state of entries.... because what shoud things be like when the filtered state is switched back... etc.

but this also leads to some confusion regarding what a "Select ALL" or "Unselect All" button would do...

My first inclination would be to have a "Select ALL items in current filter" which would select all the items in the current filter... this would subsequently handle a generic "Select ALL" since switching the filter to ALL and clicking this button would select ALL movies.. where as if the filter is missing, it will allow the user to select ALL missing movies by changing the filter to Missing and clicking this button...

I believe this is the best way to implement a select ALL button --> make it a Select All Currently Filtered Movies.

I could have the text of the button change with as the filter changes... so if the user is in filterMode: ALL.. it will say Select ALL Movies.. If the user is in filterMode Missing, it will say Select ALL Missing Movies and perform the task accordingly..

regarding the unselect All --> i think I should implement this in the same way...  Does naybody have any concerns or thoughts before I go ahead and do this... Doing it this way, gives the user the most flexibility... but they just have to keep in mind that these buttons will only select or unselect all the items in the current filter (across all pages) but by having the button indicate this it shouldnt be a problem.

The reason to do it this way is it encapsulates a generic Select ALL button while also allowing more specific "Select ALL" type requests -- i.e. select all missing.

**Comment by geogolem** [comment]
Im giong to go ahead and try to implement it this way. since I really cant see a better way to do it... that covers all the cases the user might want and makes the most sense.

**Comment by eriksneff** [comment]
I know I'm a bit late to the party in this discussion, but thought I'd throw my $0.02 in on the topic of how to implement a select-all/clear selection that spans pagination: Gmail does this the best I've seen. Here's how I'd prescribe it for Radarr:

When the select-all button in the upper right is clicked, a new first row in the table shows that says:
All XX movies on this page are selected. _**Select all 1,305 movies**_

When that second sentence link is clicked, it changes the entire row to read:
All 1,305 movies are selected. _**Clear selection**_

When Clear selection is clicked, it removes the checkmark from all rows. Thoughts?

**Comment by nibble4bits** [comment]
I would like some kind of functionality that eriksneff described. Given that PreDB doesn't work, there's no fast way for me to change all of my movies to "Physical" status unless I go through hundreds of pages of select all for the ten items displayed.

**Comment by galli-leo** [comment]
@nibble4bits You can increase the page size in the settings under UI. This should allow you to edit up to a 1000 movies at a time.

**Comment by eriksneff** [comment]
@galli-leo this is technically a solution to people wanting the see more on the /movieeditor page. Two things to add to that:
1) I found it unintuitive that this setting affected the /movieeditor page, but not other pages that use the same pagination UI, such as /wanted/missing, /wanted/cutoff, /activity/queue, /activity/history, and /activity/blacklist. Maybe it'd be worth having all those pages use this setting?
2) Because the

**Comment by galli-leo** [comment]
@eriksneff Regarding both points, generally speaking that is just because of the pagination library we use and also because we are too lazy to correctly implement all that stuff (maybe there also just isn't a way with the current library).

Regarding the second point. I agree it's unintuitive. But from a dev standpoint: That page size controls the page size of the main movie collection (all movies seen on the front page). This is the same collection we use for the movie editor.

Regarding the first point. Yeah I wanna overhaul it a little bit to make it more clear what that setting affects for the first 0.2 version.

**Comment by eriksneff** [comment]
@galli-leo thanks for the transparency about what dev challenges may be limiting our options. Here's my suggestion:

So, depending on how much you want a quick fix for now versus not waste time on that and just do it right the first time, my reco is to have all things that use pagination to use that page size setting, and then later work out a better way to control page size inline in the context where it appears. Or just let it all slide if this isn't a priority. Regardless, thanks for weighing in!

**Comment by galli-leo** [comment]
@eriksneff While that might make it more consistent, I don't think it's really that great of an option. Because usually I don't want my wanted tab to be 500 movies at once. So I will just have to do it right straight away.

**Comment by eriksneff** [comment]
Sounds like a plan
