### ISSUE TITLE
Tasks Thrashing Raid Array\Hard Drives

### ISSUE THREAD

**Issue by FoldZero** [Radarr/Radarr#10655]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

This was requested before, i dont see an active request. 
MyArray is getting thrashed since installing Radarr\Sonarr\Prowlarr
I would dearly love to schedule tasks to run Daily at a minimum to ease off processing.
I would only like downloads to happen during a certain time period (night) which mean a lot of the follow on tasks certainly dont need to be executed so often

![image](https://github.com/user-attachments/assets/c6bd093d-4645-4f9f-9fca-6d66ce3ed17d)

I see that indexer refresh is hard limited to 120 minutes also, Wondered why the reason.

![image](https://github.com/user-attachments/assets/6cdbc82e-7365-4de5-b1c1-37847dd6dd1d)

### Describe the solution you'd like

Ability to set custom task schedules.

### Describe alternatives you've considered

I could disable the Application on my Synology or stop Docker. 

### Anything else?

No

**Comment by bakerboy448** [comment]
> This was requested before, i dont see an active request.

Invalid request, duplicate

**Comment by bakerboy448** [comment]
> MyArray is getting thrashed since installing Radarr\Sonarr\Prowlarr
I would dearly love to schedule tasks to run Daily at a minimum to ease off processing.


No plans. Starr are designed to run 24/7/365 - they by design would not function with only daily tasks.  The FAQ covers how to reduce some IO. https://wiki.servarr.com/radarr/faq#can-i-disable-the-refresh-movies-task

> I see that indexer refresh is hard limited to 120 minutes also, Wondered why the reason.

it is not hardcoded to 120 minutes. Are you talking about a maximum of 120 minutes? Refer to the first FAQ entry to understand how radarr works and why querying an rss feed would not be logical.

> Ability to set custom task schedules.

no plans. Duplicate request. Please do not check the box claiming you search when you don't reference related issues. Please do not open duplicate, denied feature requests with no material change in reasoning or solution.

Duplicate of https://github.com/Radarr/Radarr/issues/3556
Duplicate of https://github.com/Radarr/Radarr/issues/2975
Duplicate of https://github.com/Radarr/Radarr/issues/3563

**Comment by zakkarry** [comment]
To clarify, RSS running at extended intervals would still only query the same amount, resulting in potentially missed entries. RSS is not meant to be extended to intervals as a search mechanism.

I think the better solution would be for you to narrow down why the IO is high, because other than daily disk scan/refresh, there should not be any "thrashing" going on for simple RSS queries and parsing.

Even downloading should not thrash a reasonable RAID array or HDD. Most single disks can easily surpass the average 1gbit write/read speed, and assuming you have any striping of any sort, there should be a multiple of this speed.

You can schedule download times in most download clients, FYI.

I suggest you investigate your actual IO usage, and find out what exactly is causing this rather than arbitrarily choose scheduled tasks and ask for them to be extended. You will find that even if this was accommodated, you're usage would likely remain the same and your experience with the arr's would be severely degraded.

Correlation does not equate to causation. I doubt this is arr related...
