### ISSUE TITLE
Radarr not setting the category correctly in qBittorrent 3.3.11

### ISSUE THREAD

**Issue by Toasterthegamer** [Radarr/Radarr#1132]
**Description:**

I'm not sure if this is a bug in radarr or qBittorrent but the category is no longer being set correct in qBittorrent 3.3.11. I'm also seeing the same issue in Sonarr as well. I should point out that if I manually set the category in qBittorrent it is fine.

**Radarr Version:**
0.2.0.453

**Comment by onedr0p** [comment]
You may want to open a issue on sonarr GitHub too.

**Comment by galli-leo** [comment]
Is this problem still occuring on the latest versions of Radarr and qBittorrent?

**Comment by majora2007** [comment]
This seems to be an issue with qBittorrent. Can confirm that v3.3.14 of qBittorrent is having this issue.

**Comment by Arathen** [comment]
This is the result of a changed API response from qBittorrent, and has been fixed in Sonarr as of commit [126b849c270391f912d7ce3d125fd7fbdc82268c](https://github.com/Sonarr/Sonarr/commit/126b849c270391f912d7ce3d125fd7fbdc82268c). If it can also be fixed in Radarr, it would be greatly appreciated.

Thanks.

**Comment by galli-leo** [comment]
This should be fixed on the latest nightly.
