### ISSUE TITLE
Feature Change: Swap pagination for Alpha choice

### ISSUE THREAD

**Issue by GregoryGHarding** [Radarr/Radarr#1134]
if the title does not explain it well enough, i am requesting you swap the pagination on the movies tab for something like whats in couch: #,A,B,C, etc

**Comment by galli-leo** [comment]
Not gonna happen with the current UI. We may think about it when we rebuild our UI.

**Comment by geogolem** [comment]
I was thinking, instead of swapping pagination... Why not have an alphabet dropdown (with A - Z).. 

when that is selected the filtering will filter to movies that satart with that letter of the alphabet... pagination will still work as normal.. but it will just be a filtering issue. Of course if the page size is large enough, it will give the effect the original poster mentioned.. 

ConstructFilterExpression already has a filterKey, filterValue and filterType for this type of title filtered .. (or something similar to what is necessary)..

I might try and implement something simple like this just to try it out.. but its definitely not a high priority.
