### ISSUE TITLE
is movie editor broken in nightly?

### ISSUE THREAD

**Issue by GregoryGHarding** [Radarr/Radarr#1150]
if i go into movie editor on the nightly branch ,i get the header until search then a blank white screen

**Comment by onedr0p** [comment]
Clear cache, try incognito.

**Comment by GregoryGHarding** [comment]
![image](https://cloud.githubusercontent.com/assets/12652473/23871814/e9a4cbce-080e-11e7-8cfc-7d1817446ea8.png)

**Comment by ctroncoso** [comment]
@GregoryGHarding  give it some time. It seems it's broken but it's working.  Had the same impression. 
Maybe a progress indicator might be handy.

**Comment by geogolem** [comment]
It also might be taking a long time because you have the "refreshMovie" going on in the background... Maybe.. When loading the MovieEditor - the entire movie collection is fetched because it is paged in clientMode.. this differs from the movieIndex where it is paged in serverMode and thus each page is loaded individually as you access it... The movieEditor is slightly faster when loaded (i.e. paging, sorting and filtering etc.) but taks longer to load than the MovieIndex...

When the refresh Movie process is running... things could take longer.
