### ISSUE TITLE
WebUI error after installing on Windows Server 2012 R2

### ISSUE THREAD

**Issue by mdaviesnz** [Radarr/Radarr#1214]
**Description:**

Radarr runs but interface throws an error in the browser:
{
  "message": "NotFound"
}

**Radarr Version:** 
v0.2.0.535

**Logs:**
`17-3-18 23:18:47.3|Warn|IndexHtmlMapper|File C:\programdata\Radarr\Bin\UI\index.html not found
`

Files are definitely present in the mentioned folder.
Issue occurs when running as a service or interactively as a normal and elevated user. 
Procmon sees Radarr successfully opening/reading index.html before throwing the error.
Sonarr runs fine on this system.

**Comment by galli-leo** [comment]
Can you try and reinstall Radarr?

**Comment by mdaviesnz** [comment]
Yep, already had two clean runs through following the instructions. 
Tried it on my Win 10 machine the same way and it was fine.

**Comment by gthrift** [comment]
I'm having the same issue

**Comment by Thayios** [comment]
Not happening on Server 2016.

**Comment by Thayios** [comment]
Scratch that, happening on Server 2016 after rebooting as well after a reboot. I originally lost contact with NZBget (putting files in the queue but not tracking activity) and Radarr wouldn't reboot.

KB4015217, KB4013418 were installed on 4/7 and the VM didn't get rebooted until just now.

**Comment by galli-leo** [comment]
@gthrift Maybe it's a permission issue? Were you able to start Radarr once or was it from the beginning like this?

**Comment by gthrift** [comment]
I don't believe it is permissions because it has been working great for
months and I have not made any system changes other than automatic windows
updates.

When uninstalling and reinstalling, it will work on the first run but not
again after.  I have it installed and running as a service now but I have
not rebooted or restarted since the first run.

**Comment by Thayios** [comment]
I went ahead and did an entire reinstall due to the issues I was having today (I was on nightly, but my other half is complaining about Plex being "crazy"). 

I think I narrowed it down to following because after I logged in, I could actually go back to the root port/index page and be able to get back into Radarr without an error (almost as if the login script is sending the redirect to the wrong URL).

URL:8989/login?returnUrl=/ - you're able to login, but it randomly has issues getting back to the main page
URL:8989/ - worked just fine, and after I logged in the above URL, I was able to see everything.

Regardless, I'll be following this closely to see if it happens again. I was on Nightly, but now I'm back on Develop

**Comment by galli-leo** [comment]
@gthrift @mdaviesnz Is this still occurring on the latest release?

**Comment by kghantous** [comment]
@galli-leo I'm experiencing this issue after a new install. Followed the install steps, then when I navigated to the site (localhost:7878) I receive 
`{
  "message": "NotFound"
}`

**Comment by galli-leo** [comment]
Can you post logs of the Radarr install? (Located in your AppData directory https://github.com/Radarr/Radarr/wiki/AppData-Directory)

**Comment by kghantous** [comment]
@galli-leo See attached.  
I think the line in question is below:
**17-6-18 08:37:47.2|Warn|IndexHtmlMapper|File C:\programdata\Radarr\Bin\UI\index.html not found**
I verified that the file and path exist.

[old_radarr.txt](https://github.com/Radarr/Radarr/files/1083082/old_radarr.txt)

**Comment by galli-leo** [comment]
Maybe it has something to do with permissions or the path being lowercase? Can you try downloading the latest release package and starting Radarr directly from the downloads directory? (You first would have to kill all running instances of Radarr)

**Comment by kghantous** [comment]
@galli-leo I'm good to go - everything is working! Thanks for the guidance.

**Comment by darylm88** [comment]
Just wanted to jump in here- I experienced the same issue (17-6-18 08:37:47.2|Warn|IndexHtmlMapper|File C:\programdata\Radarr\Bin\UI\index.html not found).

Radarr web UI was returning "not found" even though the path DID exist.

The fix was to stop the service from running in windows, then change "Bin" to lowercase "bin". Started back the service and all works as expected. So the path now reads:

C:\programdata\Radarr\bin\UI\index.html not found
