### ISSUE TITLE
"Indexer feed is not supported: Empty feed, cannot check if feed is parsable."

### ISSUE THREAD

**Issue by bradtn** [Radarr/Radarr#1231]
**Description: When adding a url for a valid xml rss feed I am met with ""Indexer feed is not supported: Empty feed, cannot check if feed is parsable."

When looking into logs this error is attached 
"Rss feed must have a pubDate element with a valid publish date."

can we gain the ability to add a rss feed without PubDate as my xml is valid?

**Radarr Version: 0.2.0.535

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
Is this for an indexer or a list? Also Is this for Torrents or Usenet?

**Comment by bradtn** [comment]
my apologies, this is for torrents rss feed , list private tracker

**Comment by galli-leo** [comment]
So do you want to add it under Lists or Indexers in the settings?

**Comment by bradtn** [comment]
error occurs when adding as indexer not list

**Comment by galli-leo** [comment]
Well maybe we can support indexers without a pubDate, but generally an RSS feed needs a PubDate. Maybe tell your indexer to add that?

**Comment by bradtn** [comment]
Yea I have also went that route but apparently doing so would be very low on a fix priority list for them seeing as does work just fine about everywhere else...

**Comment by hradec** [comment]
I'm also having the same problem. 95% of my downloads come from a private tracker, and their RSS feed also don't have a pubdate.

So, I second this!!

**Comment by galli-leo** [comment]
@hradec Then please tell them to add the pubDate. I think that's really essential for an RSS feed. I will try to remove the dependency on that nonetheless. The Ui will then just show 0 days for age, which is not ideal.

**Comment by edrock200** [comment]
I'm getting this error too even though my newznab client has a pub date. I'm using nzbmega search to aggregate, and it's working with Sonarr, but Radarr throws this error: 

An error occurred while processing feed item from http://localhost:5000/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100: String was not recognized as a valid DateTime because the day of week was incorrect.

When I load the xml feed, it does have a pub date:
<newznab:response offset="0" total="137362" />
<item>
	<title>World.NZB.Megasearch.Tour.S01E01</title>
	<guid isPermaLink="true">http://bogusurl.bog/details/1234567890123432523523</guid>
	<link>http://bogusurl.bog/getnzb/1234567890123432523523.nzb&amp;i=470&amp;r=438204209348230</link>
	<comments>http://bogusurl.info/details/1234567890123432523523#comments</comments> 	
	<pubDate>Mon, 1 Jan 1970 00:00:00 +0000</pubDate> 
	<category>TV &gt; SD</category> 	
	<description>World.NZB.Megasearch.Tour.S01E01-0byte</description>
	<enclosure url="http://bogusurl.info/getnzb/1234567890123432523523.nzb&amp;i=470&amp;r=438204209348230" length="12" type="application/x-nzb" />

	<newznab:attr name="category" value="5000" />
	<newznab:attr name="category" value="5030" />
	<newznab:attr name="size" value="12" />
	<newznab:attr name="guid" value="438204209348230" />
</item>

From a google search, Jan 1 1970 was a thurs, not a Monday, and it seems like Radarr doesn't like that. However, this is just dummy data nzbmega throws out for the initial test/link, once it's added it should provide accurate date/time info. Anyway I can add this as a indexer or get around the error?

**Comment by galli-leo** [comment]
@edrock200 Maybe request a fix for your client? I don't think there's much we can do there, since the Datetime stuff is a standard library and we won't be able to just overwrite that.

**Comment by edrock200** [comment]
Understood, appreciate the response.

**Comment by Goofyguf** [comment]
I have the same problem, when adding a valid RSS xml feed (which works in Sonarr, and my browser) to Radarr it gives me this error: Indexer feed is not supported: Empty feed, cannot check if feed is parsable.

I cannot paste the xml feed since it has my passkey in the URL for a private torrent tracker. 

Adding the feed as torrent RSS feed under indexers.

**Comment by galli-leo** [comment]
@Goofyguf Without even a snippet of the feed I cannot tell what’s wrong.

**Comment by Goofyguf** [comment]
Hi Leo.

Can i paste it in private to you?

tor. d. 3. maj 2018 09.13 skrev Leonardo Galli <notifications@github.com>:

**Comment by galli-leo** [comment]
@Goofyguf Can you post the output of that feed, since I cannot view it without a passkey?

**Comment by Goofyguf** [comment]
[rss.txt](https://github.com/Radarr/Radarr/files/1970241/rss.txt)

**Comment by galli-leo** [comment]
@Goofyguf  can you also post the full exception info?

**Comment by Goofyguf** [comment]
[exception.txt](https://github.com/Radarr/Radarr/files/1970636/exception.txt)
