### ISSUE TITLE
Enhancement: Default minimum availability

### ISSUE THREAD

**Issue by Quiksmage** [Radarr/Radarr#1254]
Hello,

It would be nice to be able to define the default "minimum availability" or have it remember the last used for future additions like it does with profiles.

Currently, the default is Pre-DB and requires a manual change from the drop down to change to something else on every movie added. 

This is not a big deal, but definitely a quality of life change.

**Comment by galli-leo** [comment]
Finally put in latest nightly :)

**Comment by galli-leo** [comment]
@davemanster There is nothing we can do about that.

**Comment by davemanster** [comment]
There is no way to force an availability for all items added? 
Sorry not a developer. Just not sure who I should alert this to.

**Comment by galli-leo** [comment]
@davemanster Default in code is Physical / Web, you can edit the minimum availability for all movies in the Movie Editor.

**Comment by mjdgoldeneye** [comment]
There must be a way to configure it so that, if an external source adds a movie, if an availability setting is not provided or is invalid, it'll set it to Physical / Web (or a selectable option).

Otherwise, almost all the utility of Radarr is lost for anybody running a recommendation application because automation capability is lost.

I mean, Ombi really should add it as an option, too, but it's not like enforcing data integrity for something this fundamental is a bad idea.

**Comment by davemanster** [comment]
I agree, but know that Ombi did add this functionality.

**Comment by galli-leo** [comment]
@mjdgoldeneye Automation capability is not lost. If you even just add a global availability delay ot will work just fine.

Anyways we are already doing what you propose minuse the setting a default by the user part. Sonarr also has a lot of configurable options when adding a series (type, monitored, path) and they do not have a default setting for that.

IMO an API shouldn’t have to correct the errors of its users.
