### ISSUE TITLE
Profile Cutoff Ignored

### ISSUE THREAD

**Issue by wonkieinc** [Radarr/Radarr#1283]
Description: I added Doctor Strange, with the profile set to HD - 720p/1080p. My cutoff is WEBDL-1080P.

Radarr downloaded a Remux-1080p copy at 26.6 GB in size, when my cutoff for WEBDL-1080P is 13.67 GB.

Radarr Ver. 0.2.0.570

Logs and screenshots attached.

[radarr.1.txt](https://github.com/Radarr/Radarr/files/877553/radarr.1.txt)

![image](https://cloud.githubusercontent.com/assets/7991537/24435229/d3de3078-147f-11e7-9b8f-9e4200130122.png)
![image](https://cloud.githubusercontent.com/assets/7991537/24435259/ec4fa4b6-147f-11e7-82d0-ddc70f02f170.png)
![image](https://cloud.githubusercontent.com/assets/7991537/24435275/021482b2-1480-11e7-9cf9-7cceeda59d2d.png)

**Comment by darknessgp** [comment]
I'll address the first issue that seems to appear, the way cutoff works is it is the minimum quality (lowest on that list) that must be obtained before Radarr stops grabbing. So, in your setup, if it grabs a blu-ray 720p, it'll keep downloading.  It won't stop until it gets that WEBDL-1080p.

The second issue, under those selected qualities, Radarr should not have grabbed a blu-ray 1080p or a Remux 1080p at all because you don't have those selected.

The real issue here seems to be Radarr ignoring a profiles' selected qualities.

**Comment by galli-leo** [comment]
Seems like Radarr did not grab the remux movie? Or at least it grabbed what it thought was a Bluray, but after downloading it, it found it to be a remux movie?
