### ISSUE TITLE
Keep seeding after moving a movie.

### ISSUE THREAD

**Issue by DaLuke** [Radarr/Radarr#1299]
I can't find something on the site or in the issues. But after moving a movie, the movie keeps seeding for like 24 hours but after this the local data seems to be missing. 

How is Radarr handling the move? Does it make it possible to keep seeding the torrent until the required seed ratio is met or does it delete the torrent completely after moving the movie? 

Sorry, not really a bug I know, it's more a question for help.

Greetz

**Comment by fent** [comment]
Use the hardlink option.

**Comment by theCheek** [comment]
The default should be as @fent suggested above, found it Settings - Media Management under Importing section - 'Use Hardlinks instead of copy'. If this is switched on and not working for you, then please describe your platform/setup. 
An alternative is to use the reverse symlinking script, as detailed at the bottom of this page https://github.com/Radarr/Radarr/wiki/Custom-Post-Processing-Scripts

**Comment by DaLuke** [comment]
It seems to work with the 'Use Hardlinks instead of copy' but doesn't Radarr leave the entire file in the download folder? And then after the ratio is met he delete's the entire file from the download folder? 

It would be a nice setup if he moves the downloaded movie and adjusts the Torrent client so it states the movie has been moved. Because my download Folder is limited in space I always try to move the downloaded movies asap.

**Comment by theCheek** [comment]
A hard link is a reference to the actual data of the file, so when a downloaded file is hard linked you can access the data from the new location without taking up extra space. Therefore you can tell your download client to remove the torrent (with data) and have no affect on the new location.

**Comment by galli-leo** [comment]
As theCheek explained Hardlink does exactly what you need. You can keep seeding, but no extra space is taken up.
