### ISSUE TITLE
Change filters to be 2 separate checks [Feature request]

### ISSUE THREAD

**Issue by pbrink231** [Radarr/Radarr#1317]
Radarr Ver. 0.2.0.535

Basically Here are the current filters
[All] [Monitred] [Missing] [Released] [Announced] [Cinemas]

What I am asking for is to make this 2 different searches for fine tuning (switched Announced and Cinemas aslo)
{[All] [Monitred] [Missing]} && {[All] [Released] [Cinemas] [Announced]}

Same icons and everything.  Just make just like above with the space between sort & grid options.

This would make it much easier to see what I am looking for.  This was not needed for Sonarr because everything releases on the one date so you dont need to worry about it.

**Comment by galli-leo** [comment]
Yeah, as said before, this will probably have to wait until a new UI is here, where we can do that much easier and better.

**Comment by pbrink231** [comment]
Ok.  Sorry. I looked around before but didnt see it mentioned.

Side note - I really like the UI, minor changes like this and sort by year, hide already have.  Hope its not a big change.

**Comment by galli-leo** [comment]
@pbrink231 Probably semi big. Mainly related to changing the underlying library (something you are not going to see very much) to something more dev friendly, so that we can more easily add things such as this and get better performance. We also have some mockups of how the new UI might look like. Not too different, but in the same direction Sonarr is heading with their new UI.

**Comment by Metigoth** [comment]
This would be helpful since I only want to see monitored released movies or upcoming dvd/blu-rays.

**Comment by pbrink231** [comment]
I wanted to follow up.  I believe this is still relivent.  I believe the backed has been updated and couple months ago that will allow this now.  Is that right?
