### ISSUE TITLE
Folder is not writable by user abc

### ISSUE THREAD

**Issue by stefanschramek** [Radarr/Radarr#1380]
Hi,
I installed the Docker version (0.2.0.596) on FreeNAS Corral but when trying to add my movie folder I get the error "Folder is not writable by user abc".
I know that this is related to the user in the container and the permissions it needs on this folder.

The container is configured to use
PGID 1001
PUID 2006

The corresponding group with the same ID has the needed permissions on the FreeNAS path and the corresponding user in FreeNAS with same ID is member of this group.

![group_superusers](https://cloud.githubusercontent.com/assets/921342/25020386/5c176fe4-208e-11e7-81c4-b6b2f29abce5.png)
![user_radarr](https://cloud.githubusercontent.com/assets/921342/25020388/5c1b9dc6-208e-11e7-8e0e-a3725bac5db7.png)
![folder_permissions_outside](https://cloud.githubusercontent.com/assets/921342/25020387/5c180a62-208e-11e7-860f-3f78dabf386f.png)
![passwd_inside](https://cloud.githubusercontent.com/assets/921342/25020385/5c17504a-208e-11e7-9db0-c249b8280ff6.png)
![folder_permissions_inside](https://cloud.githubusercontent.com/assets/921342/25020384/5c172052-208e-11e7-8507-25cba6889bd2.png)

As far is I know this should give the needed permissions. What I am missing here?

Thanks
Stefan

**Comment by Firemad03** [comment]
If I understand correctly your problem I think it's because the 1001 group need to be rename to abc and 2006 ID username need to be rename to abc because right now the group is superusers and the username is svc_radar (not abc) and your screenshot for directories the username/group is abc/abc...

If you don't want to rename the group or the username well you need to change the permission on the folder for svc_radarr/superusers.

I know about Freenas but I'm not the author of the docker image and I never used the docker image because I prefer VM.

**Comment by stefanschramek** [comment]
The 1001 group is named "superusers" and the 2006 user is named "svc_radarr" in the FreeNAS. As far as I know for ACL only the ID counts. And it works for other container e.g. for sonarr (which should work similar).

**Comment by Firemad03** [comment]
I suggest that maybe you post your issue at the docker github of Freenas that maintain it. It isn't a specific problem with Radarr because the problem is related to a permission problem for the docker image not the software.

https://github.com/freenas/docker-images

**Comment by stefanschramek** [comment]
Unfortunately there is no issues-area on there GitHub account :(

**Comment by jOOc** [comment]
Maybe try their forum
https://forums.freenas.org/index.php

**Comment by Firemad03** [comment]
@stefanschramek Also Freenas dropped the Corral update. They have too much in it. Check it out this very important thread: https://forums.freenas.org/index.php?threads/important-announcement-regarding-freenas-corral.53502/

**Comment by hotio** [comment]
I think you can ignore all of the freenas part of settings, docker probably runs as root so that will probably have no permissions problems, you just need to focus on what's going on inside the container...if I'm guessing correct.

Can you manually write files inside the container to /movies with user abc? To rule out Radarr...

**Comment by jamesla** [comment]
For anybody who comes across this, just check your uid and gid with "sudo id" on your docker host and then pass them in using the env vars puid and pgid as explained on the containers readme.

**Comment by bl4mm0** [comment]
> For anybody who comes across this, just check your uid and gid with "sudo id" on your docker host and then pass them in using the env vars puid and pgid as explained on the containers readme.

Thanks!  Mine was "0"
