### ISSUE TITLE
Movies are searched by their original name - Custom language not work.

### ISSUE THREAD

**Issue by deeex87** [Radarr/Radarr#1398]
In profiles I have set up Spanish as a language, but the movies are searched by their name in English. For example, El Ilusionista (The Illusionist):
![captura de pantalla 2017-04-16 a las 18 56 09](https://cloud.githubusercontent.com/assets/27634551/25072703/66265046-22d6-11e7-94ea-00e4d5c35797.png)
but in the search tab are searched for "The Illusionist":
![captura de pantalla 2017-04-16 a las 19 03 51](https://cloud.githubusercontent.com/assets/27634551/25072744/7994120c-22d7-11e7-8e2f-997e332198a1.png)

I'm using 0.2.0.630 nightly.

**Comment by Firemad03** [comment]
I got the same problem with Risen 2016. In french I found it with "La Résurrection Du Christ" if I do a manual search.

**Comment by alneven** [comment]
For me the other way around...

I'm adding movies by their ENGLISH title as they are shown like that on my indexer (torrent site), just with Hungarian language and "\.HUN|Hungarian tags in their folders.
But Radarr automatically "translate" the movie page in Hungarian, and therefore the search is not working at all.

I couldn't found where to modify this behaviour, to search based on the alternative Title, nor how to search manually on a "string" and pair it to the movie..

**Comment by kotysoft** [comment]
Radarr Ver. 0.2.0.696 (develop)
Jackett Version 0.7.1397.0 (as torznab indexer)

**Issue:**
- Radarr translating the original title to the language of selected _PROFILE_ and searching for that translated string only. 
- Also NOT searching for original (US) title
- Unfortunately all movie releases using the original title in their name
- so simply: **no search result**

So basically it should search for **original title** instead of localized title OR BOTH.

### **Example 1.**
Profile set to "720 HU" (hungarian language)
![Profile settings](http://kotysoft.hu/files/20170514/001.jpg)

Adding movie: OZZY
![add new movie](http://kotysoft.hu/files/20170514/002.jpg)

Translated to that language you set for Profile. And there is no search result.
![movie page](http://kotysoft.hu/files/20170514/003.jpg)

**Problems:**
- The search string is the localized title and not search for original title
- And also unable to handle special characters, like **ö**

Jackett log:
![jackett](http://kotysoft.hu/files/20170514/004.jpg)


### **Example 2.**
- Profile set to "720 EN" (english language)
- Adding movie: OZZY
![add new movie](http://kotysoft.hu/files/20170514/005.jpg)

![add new movie](http://kotysoft.hu/files/20170514/006.jpg)

**All results found well, but unfortunately I would like to download the hungarian version, not the english one.**

**Comment by galli-leo** [comment]
@kotysoft I have a pr open for searching for more than one language (if indexer does not support searching by imdbid). Blame @onedr0p For not responding on that one 😜

**Comment by alneven** [comment]
+1 from myself. 👍 
I would really need this too, atm I'm not using radarr because of this missing feature.
I'm still using flexget to transfer torrent for my DL-client. :-(

**Comment by galli-leo** [comment]
This is merged into the latest nightly release, so closing issue.

**Comment by alneven** [comment]
I had the time now to update.
And it's working, thanks!
