### ISSUE TITLE
No files found are eligible for import

### ISSUE THREAD

**Issue by mgiljum** [Radarr/Radarr#1403]
**Description:**

After a movie is finished downloading, Radarr says in activities:

`No files found are eligible for import in /[downloads-folder]/[release-folder]`

In this example, there are clearly files eligible for import:

```
[root@freenas] /mnt/Pool/Multimedia/Downloads/Complete/Movies/Bedknobs.and.Broomsticks.1971.720p.BluRay.x264-x0r# ls
./
../
Bedknobs.and.Broomsticks.1971.720p.BluRay.x264-x0r.fanart.jpg
Bedknobs.and.Broomsticks.1971.720p.BluRay.x264-x0r.jpg
Bedknobs.and.Broomsticks.1971.720p.BluRay.x264-x0r.mkv
Bedknobs.and.Broomsticks.1971.720p.BluRay.x264-x0r.nfo

```

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**

0.2.0.596

**Logs:**

Table logs don't load, it just sits there spinning

File logs don't even mention the movie in question.

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
This is usually a case of permission issues. Are you using docker?

**Comment by mgiljum** [comment]
Yes, in FreeNAS. I already manually imported the release, but the permissions on all the files was:

`-rw-rw-r-- `

**Comment by galli-leo** [comment]
Are the path mappings for Radarr and your download client the same?

**Comment by mgiljum** [comment]
Not sure what you mean by path mappings. They are using the same volume, if that's what you mean.

**Comment by ctroncoso** [comment]
Check how docker itself sees the files. Get inside the docker instance with 

    docker exec -it «containername» bash 

and check them from inside.

**Comment by mgiljum** [comment]
I'm sorry, Radarr is not running in docker, it has the share mounted over NFS. My download clients are in docker, though.

**Comment by galli-leo** [comment]
What's the actual path reported in the error message No files found are eligible for import in ...?

**Comment by mgiljum** [comment]
Yes, in the above example, the error was:

`/downloads/Complete/Movies/Bedknobs.and.Broomsticks.1971.720p.BluRay.x264-x0r`

**Comment by galli-leo** [comment]
Yeah that's the problem. Your download client thinks the file is in /downloads/Complete/Movies/... and tells Radarr that path. But Radarr does not know about that path since it actually is /mnt/Pool/Multimedia/Downloads/Complete/Movies/...

You can fix this by changing remote path mappings in Settings -> Download Clients.
I think this should give you an idea how to set it up: https://forums.sonarr.tv/t/how-to-determine-remote-path-settings/10645/2

**Comment by mgiljum** [comment]
Ah, I see. Didn't notice the paths were different. Thanks!

**Comment by Moulde** [comment]
I had the same problem.
I had been running transmission for a while, but then changed to deluge. And suddenly radarr and sonarr was not able to import the downloaded files.
I'm not exactly sure what changed in terms of paths, as i'm using the exact same paths.

But adding a path mapping so that the path that sonarr and radarr attempts to import from, is mapped to the actual downloads directory fixed the issue :)

**Comment by WriteCodeEveryday** [comment]
Just ran into this one, can confirm this worked perfectly under linuxserver.io's image.

Now transfer 600 linux iso's to other drive.
