### ISSUE TITLE
Radarr Created Directory/Paths <> Radarr Named Movies

### ISSUE THREAD

**Issue by rkmfl** [Radarr/Radarr#1432]
I've searched for this issue here in the Issues list and Radarr Problems/FAQ - but don't see it.

This is *not* an issue with file/directory naming, this is a 100% Radarr-controlled issue.

When Radar downloads a movie with a hyphen (dash"-") in the name, the directory name will not match the movie name.  Therefore, Radarr will claim the movie is MISSING.

I'm referring to using the standard variables:
{Movie Title} ({Release Year})

Examples
(First path shown is the path *Radarr* _created_, once downloaded)
(Second path show is where *Radarr* _searches_ for the movie)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
C:\Movies\Crouching Tiger, Hidden Dragon - Sword of Destiny (2016)
C:\Movies\Crouching Tiger, Hidden Dragon Sword of Destiny (2016)

C:\Movies\Mechanic - Resurrection (2016)\
C:\Movies\Mechanic Resurrection (2016)

**Comment by fryfrog** [comment]
Radarr removes the `-`. When are  you seeing the folder with a `-` in it get created? Is Radarr doing it? Or is it an existing movie on your filesystem?

I just added Sword of Destiny and you're right about the 2nd path being what it'll eventually create. I don't have Radarr set to create directories until the movie is downloaded and I expect when that happens, it won't be trying to put it into the folder with a `-` in the name.

But maybe you have create empty folders option on and that is what is doing it?

**Comment by rkmfl** [comment]
The _key_ point I was hoping to highlight, was that none of this has anything to do with my configuration or anything I'm doing.

These are folders entirely created by Radarr.  Radarr removes the hyphen in one and does not remove it in the other -- that is the bug being presented here.

**Comment by galli-leo** [comment]
I will have to investigate this, as I haven't encountered it.

Regarding fuzzy matching logic, we won't be doing that (respectively, we already are kinda doing that in using a clean title (removes all spaces, special chars, accents and converts the string to lower). We wont be doing any more fuzzy matching, since we will get a lot more false positives this way. There are already three movies in 2016 with the name Split, if we allow fuzzy matching there will just be more false positives than we had false negatives before.

**Comment by galli-leo** [comment]
Also this might be because we changed the way hyphens are replaced. Can you readd those movies?

**Comment by rkmfl** [comment]
> Can you readd those movies?
I don't follow your question here, can you give me a bit more detail on what you'd like me to do?

To clarify, if it will be easier for you to see these things first hand, it's very easy to re-create this issue, it's consistent and very easy to reproduce.  This does not require some obscure logic, special setup, or intermittent issue.

As far as being low on the priority list, keep in mind that Radarr will continue to re-download movies that it has already downloaded, spending a lot of bandwidth.  It may be worth considering some reasonable priority.

As far as not using any level of fuzzy search, I think you're misunderstanding.  I'm suggesting what you've mentioned you're already doing (stripping all irrelevant characters and common strings, etc -- when doing the comparison).  But this is not presently being done.

Doing this is not going to yield a single additional false positive that would not already exist without stripping irrelevant characters.

I think the problem was my use of the term "fuzzy" to simplify my point; in reality, it's not the traditional definition of a "fuzzy" algo, it's simply applying standardized rules to prep and strip irrelevant strings (and property handle "articles" - aka "The") -- prior to comparison.

**Comment by galli-leo** [comment]
@rkmfl In that case we already do the fuzzy matching you are suggesting (e.g. articles are stripped).
As for the priority, currently everything is on low - no priority, since I have my first set of finals in the next three weeks 😬 Usually, even low priority bugs are fixed quickly ;). You could also just unmonitor those movies until I have resolved the issue, so bandwidth can be spared.
I meant deleting the movie from Radarr and readding it, but if you say it's easily reproducible, you probably have already done that.

**Comment by rkmfl** [comment]
@galli-leo - I'm sorry my reply meant to suggest it was a high-priority.  I did not mean that it was a priority for me.  I was responding to the task being set as a low-priority bug, relative to others I've witnessed in the list.

This is not an issue for me, because I've converted everything to UN-monitored and use Radarr purely to help for debugging.  My only goal was to stress the importance of this issue considering a lot of content was being ignored or re-downloaded for others.

I would like to clarify one thing you mentioned, however..   You stated that "we already do fuzzy matching" -- which is not correct.  Fuzzy matching is not working; the very example of this post highlights not only the error in directory creation, but that fuzzy matching is not working.

For example, the file:
\\10.10.10.11\Movies\MoviesNew\John Wick Chapter 2 (2017)\John Wick Chapter 2 (2017).mkv

Will not be found by Radarr Ver. 0.2.0.696
For Radarr to match this file it would have to be named:

\\10.10.10.11\Movies\MoviesNew\John Wick - Chapter 2 (2017)\John Wick - Chapter 2 (2017).mkv

That single hyphen is all it takes to cause Radarr to miss a movie.

In addition, I have a large number of movies that Radarr has found and matched, then later claimed these same files are missing.  I can't find any reason for this ... I'm wondering if it's related to this issue of improper matching.  

To clarify, I have my "quality cutoffs" at the bare minimum, so Radarr wouldn't be deleting them for quality issues.  One example is:

xXx - Return of Xander Cage (2017)

Radarr matched it, showed it as a valid quality, but did not show it as "downloaded" status.  Radarr did show the file on the file tab, when viewing Radarr's movie detail page.  Two hours later Radarr no longer showed the file, and claimed there is no match.  The file remains in the same place it's always been.

Nothing recorded by the log at "info"level.

**Comment by hotio** [comment]
Adding the movie `John Wick: Chapter 2`, results in a folder called `John Wick Chapter 2 (2017)` on my setup, radarr finds a release and puts it in this folder. So, not sure what you mean or how you configured your test bench, but nobody seems to be able to replicate your issue.

IIRC you could even manually change the folder name inside radarr to `humpie2` and it should still work.

**Comment by rkmfl** [comment]
@hotio - it was labeled a bug because it was indeed verified.  Not sure why you're claiming it was not verified.

Perhaps it's fixed in 0.2.0.696, I'm not sure -- but if you read the first post, which was tested in the current version as of 4/23, Radarr most certainly did exactly what is stated in the post.

I don't have some conspiracy theory here and I'm not doing something special.  I'm using the default / vanilla config + sab downloader (alone) + Lists -- and removing the "quality" as part of the naming convention.  Nothing beyond that.

If you think I'm making it up, by all means, close the thread, I'm not going to continue doing my best to communicate any of it with you considering all of your replies imply that I'm the only person with these issues.  If that's your belief, so be it -- let's move on.

**Comment by hotio** [comment]
Sigh, removes quality from the name, is surprised radarr downloads a new version. lol

**Comment by rkmfl** [comment]
@hotio - every one of your replies to me does not need to be a passive-aggressive insult.  It would be great if you could just let the issue be, as it's already been documented.

The original issue, which you can read in the first post clear-as-day, indicates that the naming methodology used is without a quality string.  This is a supported option by Radarr.  

**In Radarr I have the following settings:**
Standard Movie Format  {Movie Title} ({Release Year})
Movie Folder Format  {Movie Title} ({Release Year})

I don't see that as sigh-worthy, and it's pretty clear by the examples shown in the issue which is already committed as a bug.

Or maybe you could elaborate why it is that I'm such an obvious idiot for thinking that it was okay to configure Radarr in this manner?

**Comment by hotio** [comment]
Sorry if I miss certain parts of your responses, but it isn't easy going thru your walls of text that take forever to get to the point.

All I'm trying to say is, me, yes me, an ACTUAL user of Radarr, as in, not somebody who has it running for occasional testing. I have never seen the strange problems you describe, and I don't give a damn if it's marked as a bug or not. Probably was done to shut you up.

But in stead of trying to figure this shit out togheter, all I get from you is:

> Nope, nope, I'm perfect, therefor it's a bug. Did you not read the previous books I've written or did you not understand my published literature?

PS: I still have to see 1 single decent log file that could be helpful in finding a solution for this bug. You as a self proclaimed developer should know better, or are you the kind of developer that likes reading stories instead of actual facts?

I shall no longer reply regarding this issue, because... pointless

**Comment by rkmfl** [comment]
You're right.  I'm a horrible person because I reported a bug and you've continued to treat me like an idiot since your first post.  I explained the reason I didn't have logs.  

I explained it twice.

I also didn't know why I needed logs when the problem was acknowledged.  No one asked for me to reproduce the problem a second time and create logs, it wasn't until you were looking for an insult to levy that it was raised.

You didn't take the time to read the details of my posts, as you've admitted.  That's fine, but I'm not sure why that makes _me_ the idiot.

My text is long because I was attempting to reply with _full details_ and help explain the issues, it's the best I can do as I'm constantly traveling and trying to make time to report what I experience because I'm a huge fan of this project.

**Comment by hotio** [comment]
Where did you see that the problem was acknowledged?

Quote from gallileo
>I will have to investigate this, as I haven't encountered it.

**Comment by rkmfl** [comment]
> I shall no longer reply regarding this issue, because... pointless

Wait, what?

**Comment by hotio** [comment]
> regarding the issue

**Comment by hotio** [comment]
Do you really think that when people are saying that they have never experienced such behaviour in radarr that you have to slam the door in their face?

How does that help? Why would you be to good to come up with some proof/log to give value to your claim? Just because you see a little red tag? Ignoring that gallileo said he will have to investigate, because he has never seen it before?

**Comment by rkmfl** [comment]
@hotio - you're really working hard to keep this going ... and look for an argument.

I'm not here to join your pissing-contest, get on with your life.

**Comment by hotio** [comment]
Will do! You keep going strong in your many wonderfull endeavours...

![1425_3](https://cloud.githubusercontent.com/assets/26902309/26780790/a8b239b6-49eb-11e7-9cd2-a275ec1d2b31.jpg)

**Comment by galli-leo** [comment]
Sorry for not responding, but I must have missed notifications for this issue due to my finals.

Anyways, I was unable to reproduce this issue. And still really can't follow you what's going on here (same with your other issue). What I am guessing is happening:

1. You add your movie to Radarr
2. It set's a path without the colon (e.g. John Wick Chapter 2 (2017)). <- This folder is where it will import movies to as well as search for existing ones.
3. __Some other application__ (either your dl client or CP) moves the file from your dl client to John wick - Chapter 2 (2017) (with the hyphen), so Radarr doesn't have a chance to
  a) Import the file
  b) Search for the movie file, since it's in the wrong path.

**Comment by rkmfl** [comment]
@galli-leo - Thanks for the reply.  This issues was from 10 months ago, it may not exist any longer.

Regarding what you wrote about recreating -- the first post explains the issue very clearly; there is no need to read beyond that, for the details.

And to reiterate once more, there is **no other application** involved.  CP doesn't exist on the system, and sabnzbd is set to leave everything alone / as-is.

If based on the first post, this problem no longer exists, you're welcome to close the issue.  I had only posted because I thought it would help.

**Comment by Starminder** [comment]
I experience this issue whenever a hyphen is present in a folder or filename.  I use The Renamer to rename files to what I thought was a standard convention so Plex will recognize them.  I strip out the quality and use filenames similar to OP, and replace colons with hyphens.  Hyphens seem to be the crux of the issue, if there is a hyphen present when the file is imported by Radarr, Radarr will say it is missing and download it again.  I was looking for a fix to this issue when I found this thread.  Sadly, this thread degenerated into crap.  Is it fixed?  So far my only guess to get around it is to name files in such a way that a hyphen will not be involved, which sucks, because I have hundreds possibly into the thousands.  Help?
