### ISSUE TITLE
Problems when deleting movies with PLEX ("ignore deleted movies"-flag)

### ISSUE THREAD

**Issue by EskaVonGeh** [Radarr/Radarr#1477]
Hey there,

first of all, amazing work! I changed from PLEX/SABNZB/Couch Potato to PLEX/NZBGET/Radarr (with Sonarr) and i am very impressed.

Im running 
- Windows 10 / 64 bit 
- Radarr 0.2.0.654 - 18 Apr 2017 
- PLEX Version 1.5.5.3634 

There is one Problem i have encountered: 

When i am deleting movies with radarr itself, it works flawlessly (they are also now ignored). Sadly, when i am deleting the movies under PLEX, they are still monitored and are getting redownloaded. 

The nature of the thing is, of course, that you normally delete movies you dont want to keep wit PLEX after viewing and it would be perfect, if you dont need to change the app.

Thats what the flag "ignore deleted movies" is for in my mind. So the question is: Am i missing something or is there a bug / not supported behaviour?

Thanks in Advance!

Eska

**Comment by galli-leo** [comment]
Yeah ignore deleted movies should do that. Seems like it does not work. I will have to check again.

**Comment by lostandlost** [comment]
I think this is a new-ish behavior from the PLEX side.  It used to just delete the file when deleting within PLEX.  Now it tries to tidy up as much and possible and deletes the entire folder and parent folders if you are deleting the only file in that folder.  This has been an issue in Sonarr for a while now (caused by the change PLEX made).  The workaround for both Sonarr and Radarr is to set the "Create empty movie folders" to yes.  It is messy and you will have a bunch of empty folders, but it will mark the movie (or episode in Sonarr) as not monitored.  It does take two library scans to mark it as not monitored though. The first scan will see that the movie (or show) folder is missing a recreate it, then the second scan will see that the file itself is gone and unflag it.  I would love to see Radarr and Sonarr just know that the file is missing without needing the folder.  But for now this works for me every time.

**Comment by deadlyknapsack** [comment]
I have tested and experienced the same. File is deleted from Kodi, empty moviefolder remains in place. Still, Radarr will keep on monitoring the movie I just deleted. Is a fix for this planned? I would like Radarr to notice a sudden change in the existance of a movie file and when it disappears, it will switch to unmonitored. Otherwise it is very difficult to work with a combination of PLEX/KODI/OSMC and Radarr.

Awesome product otherwise! :)

**Comment by Mrpink200** [comment]
what could be great would be to have an option in file management to delete movies in radarr when movie has been deleted on disk (like from radarr)
I would really appreciate it as i got the same issue as discribe when delting movies from Radarr

**Comment by barrycraig** [comment]
I know I'm dredging up an old post here, but is this on the roadmap to be fixed. The same behaviour is still present in the latest release, namely:

1. Make sure "Unmonitor Deleted Movies" is checked in Radarr
2. Delete Movie via the Plex interface.
3. Plex deletes the entire folder containing said movie.
4. Radarr recognises that the entire folder has been deleted.
5. Rather than being 'unmonitored' Radarr re-downloads the movie, contrary to the setting in step 1.
