### ISSUE TITLE
Automatic Search Does Not Appear to Be Running

### ISSUE THREAD

**Issue by ChrisColotti** [Radarr/Radarr#1512]
**Description:**

I am trying to figure out if the automatic backlog search is or is not working.  I added some new movies, some released and others not.  It only found the released ones after I went into the "wanted" section and forced a search.  After that they were grabbed, but I do know that Sonarr I have running for TV does manage the auto searches pretty well.  Is this something as a known issue?  Could not find anything related to it not auto searching.  

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**
Docker Latest

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by fryfrog** [comment]
There is no automated backlog search. Go to Wanted -> Missing and/or Wanted -> Cutoff Unmet and trigger some searches.

**Comment by ChrisColotti** [comment]
Thanks.  That would make it much more like Sonarr in that way when you add a new release that's off in the future or one that's already been released.  Would make sense to just start searching I would think that's what "Monitored" would have done :)

**Comment by galli-leo** [comment]
@ChrisColotti Yeah of course it's like Sonarr because we forked them :) When you add a movie you can click add and search. This way an old movie get's downloaded immediately while a not yet released movie is prepared to be downloaded via the RSS sync. Not sure if a backlog search is particularly useful in this case. Since either the movie will be downloaded immediately when you add it to Radarr or it will be downloaded once it hits the RSS feeds. We will implement a backlog search though, but there's an issue already open for this :)
