### ISSUE TITLE
Feature Request - Single Directory

### ISSUE THREAD

**Issue by mrasstits** [Radarr/Radarr#1525]
I see that the support for this is planned on being implemented in the final release, but I and I assume many others, are unable to help develop this software without supporting this feature. Typically the average user may have hundreds and even thousands of video files in their library and if my directory structure is only a single folder with thousands of files, it is extremely unlikely that I am going to place those files into other directories just to use this software when there are other alternatives out there. I am excited to see this program grow but sadly I am unable to use it without this feature so hopefully it can be a priority.

**Comment by galli-leo** [comment]
It is certainly a priority, though since Sonarr relies so heavily on Series in their own folder, it's just taking a long time to implement it. There's already an issue open for this, so I am closing this as a duplicate. Btw. a lot of users switched their structure around just to use Radarr (so the alternatives don't seem to be that good ;)). It's really painless if you use a program and often a matter of minutes.

**Comment by stemwinder** [comment]
Do you have any recommendations on a good script to handle the renaming/restructuring of an existing movies library folder?

**Comment by galli-leo** [comment]
@stemwinder https://github.com/Radarr/Radarr/wiki/Create-a-Folder-for-Each-Movie
