### ISSUE TITLE
Problem with postprocessing: Unknown movie

### ISSUE THREAD

**Issue by petwri** [Radarr/Radarr#1530]
Radarr sends an nzb to nzbget which then is downloaded properly, but postprocessing fails. Manual import shows "Unkown movie".

Radarr version 0.2.0.654

![image](https://cloud.githubusercontent.com/assets/7779420/26054587/70ff9bdc-396d-11e7-96d3-b37c4c72ec51.png)

Debug log not showing any usable info

`17-5-15 11:14:19.0|Debug|QualityParser|Trying to parse quality for Foo_Fighters_-Live_at_Wembley_-2008 1080p x264
17-5-15 11:14:19.0|Debug|Parser|Quality parsed: HDTV-1080p v1
17-5-15 11:14:19.0|Debug|Parser|Release Group parsed: 
17-5-15 11:14:19.1|Debug|ParsingService|No matching movie Foo Fighters -Live at Wembley`

**Comment by galli-leo** [comment]
What is the name of the movie you want it to match to? Also you can just select the movie and manually import it, so not that big of a deal.

**Comment by petwri** [comment]
It is http://www.imdb.com/title/tt1321823/
I know that I can manually add it, but that is not really the idea behind
an automated downloading software, is it?

**Comment by galli-leo** [comment]
@petwri Yeah but that normally does not happen only with really obscure movies ;). Can you post a screenshot of how the movie looks like in Radarr (With full title in Radarr, etc.)?

**Comment by petwri** [comment]
There you go:
![image](https://cloud.githubusercontent.com/assets/7779420/26060381/30042798-3985-11e7-9183-abc0c9da44fa.png)

**Comment by galli-leo** [comment]
Yeah the problem here is that Radarr expects the title to be Foo Fighters: Live At Wembley Stadium, while the title parsed from the File is Foo Fighters: Live At Wembley. This causes Radarr to think they are not the same movie. Nothing we can really do unfortunately. You have two options though:
1. Either manual import (since this is a very obscure movie I wouldn't worry too much about this happening with other movies)
2. Or add the title without Stadium to the themoviedb.org entry for the movie as an alternative title.
