### ISSUE TITLE
Create wiki page detailing how static / dynamic paths work

### ISSUE THREAD

**Issue by janipewter** [Radarr/Radarr#1546]
Can someone please explain what Static Path does and the importance of the "Automatically Rename Folders" option please?

**Comment by fryfrog** [comment]
Do you want the folder names your movies are in to change? If you're using dynamic information in the folder name template, you do. If not, you can choose either way. If you *really* don't want them to change, don't let them be static. Is there a little hover ? w/ a tool tip to help explain it?

**Comment by fryfrog** [comment]
![screen shot 2017-05-18 at 10 32 55 am](https://cloud.githubusercontent.com/assets/87748/26215487/61639ddc-3bb5-11e7-8599-ac1e3834043c.png)

**Comment by janipewter** [comment]
I still don't understand. Why would folder names change?

**Comment by galli-leo** [comment]
@janipewter If you want to have the quality of the current file in the folder name for example: {Movie Title} {Year} {Quality Full}. Here the folder name could change from e.g. My Movie 2016 WEB-DL 720p to My Movie 2016 Bluray 1080p when Radarr e.g. upgrades the file. However, this will only happen if the path of the movie is set to be dynamic (not static). Automatically Rename Folders auto renames folders on each disk scan, so movies with existing files would also get their folder name updated to include their quality.

**Comment by galli-leo** [comment]
I want to add a wiki page describing all this in more detail, so leaving this open for that.

**Comment by janipewter** [comment]
Thank you, it makes sense to me now.

**Comment by CollinChaffin** [comment]
Even coming to Sonarr with experience, this is a new option and I can second that not only is that hover very vaguely worded, but there is still literally zero documentation in the Wiki about it, and even searching this entire repo for that flag seems to actually list many more issues related to it being enabled (and then ultimately telling the issue poster to turn it off without explaining exactly why).

So I pose the same question:  Without digging through the source code can someone give a quick explanation (and perhaps update the doc wiki) on what behavior exactly changes with this new "alpha - danger, Will Robinson" flag that apparently was deemed good/needed enough to set it to enabled by default?  And again, despite it being enabled as default I have yet to find a single issue post recommending someone who has reversed the new default of "enabled/static" to actually re-enable it back to static, but I do find them stating best to kill the default and go dynamic.  So, should I be disabling and going dynamic paths on a new install into an existing library?

Since it's been two full years left open that @galli-leo said it would be added to the wiki I'm guessing it just feel to the wayside - I know folks are busy but this seems to have a large enough impact to warrant a quick explanation.  Also, it is normal that YEARS later this is still labeled as "ALPHA" or has that just not been updated?  TIA!

**Comment by galli-leo** [comment]
@CollinChaffin I want to completely redo the whole import, media files, etc. stuff which would 1. remove the alpha feature, since it‘s no longer needed and 2. work much better. Hence, there hasn‘t been any effort on either improving the feature or really documenting it. Feel free to document it yourself.

Also, I think its worded badly, since the dangerous part is turning it off! On is the behaviour from Sonarr.

The idea is, that normally in Sonarr paths where files are imported are determined when you add a series. You cannot just change the name of the folder for a series based on e.g. media info. What the option does, is make Radarr check whether the folder where your movie is imported would change after an import. If yes, it updates its database with the new path, moves files from the old to the new path and deletes the old path. Then finally does the import. This is considered dangerous, since there are no test cases, I didn‘t test it that much and did not spend that much time on thinking of a correct implementation. Furthermore, it‘s just a bandaid fix, so that makes it imo dangerous already.

**Comment by skidaddl3** [comment]
I have just come to this switch info.
My issue is that Plex is scanning for Movies in folders that are named with "The" at the end of the title, before the year stamp: "****, The (****)" and Plex is not matching correctly (using default "The Movie DB Agent") where I also do not want to individually select the "Plex Movies" agent.
So, I have (so far) a list of about 300 movies that I have begun removing from Radarr root folder, but, still I need to individually remove the movie from the Radarr DB (as the movies were put in DB with the "****, The (****)" styled folders originally). However Radarr's renamer does the normal naming style AFAIK.
I wonder if this "dynamic" feature will solve my time consuming effort?

**Comment by Qstick** [comment]
No longer applicable in v3
