### ISSUE TITLE
Follow 301 redirects when fetching torrents

### ISSUE THREAD

**Issue by ChibiTomo** [Radarr/Radarr#1564]
The demand is the same as [Sonarr/Sonarr/#1929](https://github.com/Sonarr/Sonarr/issues/1929).

I have Jackett behind a Nginx that redirect HTTP connections to HTTPS. The problem is that Radarr does not follow this redirection and think that the torrent file is invalid.

This fix should be in the next Sonarr release.

**Comment by fent** [comment]
Why open an issue referencing the same issue that has already been closed?

**Comment by onedr0p** [comment]
That issue was on sonarr. I'll add this change for us too.

**Comment by Quiksmage** [comment]
Isn't this a problem with the way jackett works with nginx?  
  
At least, for me, I found that I couldn't download any torrents from behind nginx in Jackett's own interface.  
  
I see this error message instead of the torrent download prompt  
http://i.imgur.com/PBuPAQi.jpg  
  
If you do have this working fine from Jackett's interface, what settings are you using in your nginx?
