### ISSUE TITLE
Nested file system

### ISSUE THREAD

**Issue by napoleonsmith** [Radarr/Radarr#157]
I have a lot of movies so for ease of navigation I keep them arranged by their first letter (e.g. "J:\Movies\G\Gladiator (2000)" and so on). An option to rename new downloads in this way would be great and should be easy enough to add - after all, CP has it ;)

Also it would be useful to import a root folder (in my case "J:\Movies") and have it look deeper than one level, because right now it's trying to match movies called "A", "B" and "C" etc

**Comment by onedr0p** [comment]
Closing because #153 is a near duplicate

**Comment by chansearrington** [comment]
@onedr0p @galli-leo can we reopen this because #153 has gone in crazy direction. 

I'm currently unable to unable to import my library right now because of this problem,

I agree with you guys that each movie needs a folder, but think that radarr should look for a proper movie. 

Right now it thinks "1" "A" and "F" etc. are movie folders. If you guys manadate that all movie folders have to contain "Name (year)" in formatting, this should solve 90% of user's problems.

Then Radarr could look in sub directories like individual letters or even collection names because they don't match that format

**Comment by onedr0p** [comment]
Why not add each letter as a root folder? You're movies will get picked up then.

**Comment by chansearrington** [comment]
@onedr0p I know how to work around it, but doing that x26 letters x 3 libraries is lame.

Even sonarr recursively scans deeper into folders to see what seasons and what episodes are in the TV show folder.
