### ISSUE TITLE
Manually deleted movies are not marked as unmonitored.

### ISSUE THREAD

**Issue by KruyKaze** [Radarr/Radarr#1590]
I have a script that removes movies after I watch them. But I noticed that the deleted movies are still marked as monitored.
I did make sure that "Ignore Deleted Movies" is set to yes.
This is working fine for sonarr but not radarr for some reason.

Thanks!

**Radarr Version:**
0.2.0.696

**Comment by KruyKaze** [comment]
Ideally I'd like to be able to remove the deleted movies from Radarr's library either automatically or by bulk selecting ( missing AND unmonitored ) movies and deleting them.
Thanks again.

**Comment by galli-leo** [comment]
Do you see anything in the logs? It works fine for me. Also, did you click on scan disk for the movie?

**Comment by KruyKaze** [comment]
I just performed a scan for two of these movies and here's what the logs say:

> DiskScanService	Scanning disk for Jarhead	02:19
RefreshMovieService	Updating Info for Jarhead	02:19
DiskScanService	Scanning disk for Nausicaä of the Valley of the Wind	02:17
RefreshMovieService	Updating Info for Nausicaä of the Valley of the Wind	02:17

I did not notice any errors in the logs

**Comment by galli-leo** [comment]
Can you enable debug logging and do it again (And see if there's something new in the logs)?

**Comment by KruyKaze** [comment]
Changed to debug and tried again:

> DiskScanService	Scanning disk for Jarhead	02:29
RefreshMovieService	Updating Info for Jarhead	02:29
DiskScanService	Scanning disk for Sophie Scholl: The Final Days	02:27
RefreshMovieService	Updating Info for Sophie Scholl: The Final Days	02:27

I see no difference. note that there about 4 movies that did this others switched to not monitored in stead of missing.

**Comment by joelbrito** [comment]
Same thing here, related with #1191 
It works deleting the movie file only and leaving the folder. If you delete the folder movie keeps monitored.

**Comment by KruyKaze** [comment]
Oh I see. My script deletes the folder as well.

**Comment by sbcrumb** [comment]
I have the same issue, As I have my movies download to a local dir. Then they get uploaded to a cloud drive and removed from local storage. File and folder. Then Radarr says oh this movie is missing let me download it again. and then again, and again, cause the upload and removal is automatic. This wastes time and space on each end and bandwidth. What is the chance of getting this fixed? It works flawless in Sonarr with TV shows.

**Comment by deadlyknapsack** [comment]
I have tested and experienced the same. File is deleted from Kodi interface, the empty moviefolder remains in place. Still, Radarr will keep on monitoring the movie I just deleted and delete is again. Is a fix for this planned? I would like Radarr to notice a sudden change in the existance of a movie file and when it disappears, it will switch to unmonitored. Otherwise it is very difficult to work with a combination of PLEX/KODI/OSMC and Radarr.

**Comment by pannal** [comment]
Same here.

**Comment by Snizh-Fize** [comment]
I have the problem.

**Comment by tomsommer** [comment]
Same here

**Comment by galli-leo** [comment]
Related to #1413

**Comment by hugolapointe** [comment]
And, again, same problem/wish here.

**Comment by cltdba** [comment]
I have enabled this option in hopes it will resolve this issue.  It says that "movies deleted from disk are automatically unmonitored."  I am on version 0.2.0.852.

Settings -> Media Management -> File Management -> Ignore Deleted Movies = Yes

![image](https://user-images.githubusercontent.com/2442660/30547420-39b6eb0a-9c5d-11e7-940e-6dac1d9ea4ea.png)

**Comment by joggs** [comment]
Still having the same problem if I have "Ignore Deleted Movies = Yes"

**Comment by Nyghto** [comment]
Issue is still there and really annoying.

**Comment by joggs** [comment]
Yes, cuses lots of problems.
watched movies are fetched again for instance.

Den mån 18 dec. 2017 15:13Nyghto <notifications@github.com> skrev:

**Comment by digitalface** [comment]
Same issue here, latest (as of Jan 4th) version of Radarr.

**Comment by darksupernova** [comment]
same issue here, deleted a whole bunch of movies (and their folders) only to find they are back a week later! I don't have time to do it all through the radarr interface...

**Comment by joggs** [comment]
Ack, 4 watched movies downloaded again due to this major bug. I will start looking for alternatives as nothing happens here

**Comment by digitalface** [comment]
If you find a decent alternative be sure to let us know. I was using couchpotato before but it was pretty unreliable. Radarr is definitely more stable but as you say there doesn't appear to be any interest in fixing this particular bug.

**Comment by erreib** [comment]
I am also experiencing this, deleting the file from plex doesn't get rid of the folder and doesn't disable the monitored status in sonarr. No problems in radarr.

**Comment by galli-leo** [comment]
So the commit I just pushed fixes the original issue (movie folders deleting not unmonitoring the movie). If you are still experiencing the issue, please enable debug logging and do a disk scan (only after a disk scan will Radarr unmonitor movies). I have tested the latest fix and it worked as expected to me.

@joggs @digitalface Currently there are 535 issues open on here and I am working on Radarr alone in my free time. Sadly I don't have that much time. Also sometimes Github issues slip my Radarr, especially cause I currently have about a 100 notifications. (I also should answer support questsions in the same time as well). And I have a good connection as well as enough storage space, so didn't really care if extra copies got downloaded for me.
Anyways, if you have a major gripe with the app or see a bug such as this, it's open source. Just fork it and fix it, I am always happy to accept PRs. Even if someone just provided a helpful debug log (instead of just saying it doesnt work) and maybe even started looking where the error lies, it would have helped (or will help) a lot in fixing this issue.

**Comment by joggs** [comment]
Unfortunately, the fix does not seem to work for me.
Running windows 10 64bit.
I have enabled debug logging and done a disk scan. The watched movies that I have deleted are still monitored.
Any suggestions what I can try to solve it? Are there any specific settings that have to be enabled/disabled to get it to work?

**Comment by galli-leo** [comment]
@joggs Have you updated to the latest nightly?

**Comment by joggs** [comment]
Ah, i noticed that there was an update today regarding this feature and now
when I try it out, it looks like the deleted movie is unmonitored after a
scan. Great work!

Den sön 4 mars 2018 19:19Leonardo Galli <notifications@github.com> skrev:

**Comment by davis78** [comment]
I recently setup radarr on my unpaid box (v0.2.0.1293) and was hoping to use this feature. At first it seemed to work, but then i noticed it wasn't working anymore. I had moved the movies out of the destination directory configured in radarr, and yet the movies in radarr were not being marked as unmonitored, after running a disk scan for those specific movies. 

I decided to enable debug logging. After doing that, i noticed that radarr was logging a warning that the destination movie directory was empty. I figured maybe if directory is empty, this short-circuits this feature from working. So, i added an empty "HOLDING" directory in my destination movie directory, and then re-ran the disk scan. Now, my movies are being marked as unmonitored again. 

So, if anyone else hits this... for now you can just add a temp directory to your destination folder and leave it there. Maybe this will be fixed in coming releases.

**Comment by Nyghto** [comment]
> I recently setup radarr on my unraid box (v0.2.0.1293) and was hoping to use this feature. At first it seemed to work, but then i noticed it wasn't working anymore. I had moved the movies out of the destination directory configured in radarr, and yet the movies in radarr were not being marked as unmonitored, after running a disk scan for those specific movies.
> 
> I decided to enable debug logging. After doing that, i noticed that radarr was logging a warning that the destination movie directory was empty. I figured maybe if directory is empty, this short-circuits this feature from working. So, i added an empty "HOLDING" directory in my destination movie directory, and then re-ran the disk scan. Now, my movies are being marked as unmonitored again.
> 
> So, if anyone else hits this... for now you can just add a temp directory to your destination folder and leave it there. Maybe this will be fixed in coming releases.

This issue has been fixed for some time now. I don't have had any issues with it sense then.

**Comment by Nyghto** [comment]
You dont use subfolder for each of your movie? Why would you only delete content in it and not remove complete directory?

**Comment by davis78** [comment]
I do use sub-folders for each movie downloaded. So for example, let's say my destination movies folder is /movies, and i have 2 movies (A & B) downloaded by radarr, like so:

/movies/Movie.A.1080p-iND
/movies/Movie.B.1080p-iND

...where each of those folders contains an .mkv or something like that. If i then move those A + B movie folders out of the /movies folder (this leaves /movies empty again), and update library (which does disk scan of /movies folder in radarr), those movies will NOT be marked as unmonitored. 

However, if i change above example to have an arbitrary directory in /movies, like so:

/movies/DONTDELETE
/movies/Movie.A.1080p-iND
/movies/Movie.B.1080p-iND

If i then move the A + B movie folders out, which leaves this:

/movies/DONTDELETE

Now running update library works and movies A + B will be marked as unmonitored in radarr. Does this help to clarify what i was saying above?

It seems like a minor bug in radarr, or maybe it's somehow related to my setup... but i don't think i'm doing anything out of the ordinary with how i have things configured.

**Comment by blinkiz** [comment]
If you delete the movie folder Radarr will not delete the Movie from database. It is still in monitoring list.

```
19-8-24 11:11:22.6|Info|RefreshMovieService|Updating Info for Big Bunny Movie
19-8-24 11:11:27.2|Info|DiskScanService|Scanning disk for Big Bunny Movie
19-8-24 11:11:27.2|Info|MediaCoverService|Testing: NzbDrone.Core.Messaging.Commands.CommandQueueManager, 171
19-8-24 11:11:27.4|Info|MetadataService|Movie folder does not exist, skipping metadata creation
```
