### ISSUE TITLE
Enhance the filtering and add delete option to the movie editor

### ISSUE THREAD

**Issue by nifharv** [Radarr/Radarr#1621]
Enhance the filtering and add delete option to the movie editor.

**Comment by galli-leo** [comment]
Could you be a bit more specific in e.g. what options you would like to see?

**Comment by nifharv** [comment]
It would be nice to be able to add extra columns in the movie editor (or chose your own) such as the date/time the movie was added to radarr so that you can filter and sort with more granularity before performing a multi-movie operation. Also, it would then be nice to get a delete option.

**Comment by Mushin** [comment]
I would like to add to this request regarding the filtering and sorting in the movie editor. It would be nice to have more columns to sort by e.g. release date.  This is possible in the movies and wanted screens, but not in the movie editor. Additional filtering options would also be nice - e.g. release date, profile, date added. I don't see any reason why the movies, movie editor and wanted shouldn't all have exactly the same columns and filters available.

More sorting and filtering options would allow more powerful editing in the movie editor screen. An example scenario is that I would like to change the profile of all missing, released movies, that were released before 2000. Currently the only way I could do this is to look through all the years in the movie editor, manually tick each one and then edit, or go to the wanted screen, filter by missing, then sort by release date, and open each movie to change the profile.

Another option that would make each screen, but particularly the movie editor, more powerful, would be to allow multiple filters at once. Instead of e.g. filtering by missing OR released, allow me to filter by missing AND released.
