### ISSUE TITLE
Disable Year in Title for Release search

### ISSUE THREAD

**Issue by Saboti** [Radarr/Radarr#1631]
**Radarr Version: 0.2.0.696 **

**Logs: **
``` 17-6-6 11:15:36.7|Info|NzbSearchService|Searching 2 indexers for [A Cure for Wellness]
17-6-6 11:15:36.7|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/jackett/torznab/gods/api?t=search&cat=100170,100134,2040,2030&extended=1&apikey=(removed)&offset=0&limit=100&q=cure%20for%20wellness%202016
17-6-6 11:15:36.7|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/jackett/torznab/torrentsyndikat/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=cure%20for%20wellness%202016 
```
I have a Problem with the search for Releases. German Release's are typically without a Year in the Title.
For Example: https://www.xrel.to/movie/153044/A-Cure-for-Wellness.html
So Radarr wont find any Releases for me atm.

Is It Possible to disable the search for Year in the Title? Maybe with a extra Setting?

Regards Saboti

**Comment by galli-leo** [comment]
Even if we add this, radarr won't be able to parse the movie anyways, so doesn't bring much currently. Can you ask that indexer / group to include the year? It's mandated by scene rules.

**Comment by dannyyy** [comment]
I have the same issue. As much as I know, the German release rules does not require the year. Nevertheless, for German releases the matching algorithm does not work either, even a year is present. Mostly due to having 1+ year in the name (released after US official date).

In the list of the found releases, the "not appropriates" will be listed anyway. Way not just add the download icon to do it manually.

**Comment by bubez81** [comment]
+1

**Comment by galli-leo** [comment]
I looked it up, and german rules do require the year. But I added so called lenient parsing and lenient mapping for this. Enable it in Settings -> Indexers :)
