### ISSUE TITLE
Issue with Potato indexer

### ISSUE THREAD

**Issue by onedr0p** [Radarr/Radarr#1644]
Just a reference of multiple issue, potato only returns 1 or no results, solution for now is to use torznab instead.

Issues:
#1120 
#1584

**Comment by galli-leo** [comment]
The issue is that omdbapi.com (The one Jackett uses for imdbid to title mapping IIRC) went private. So this is not actually an issue on our end. We should remove the TorrentPotato indexer alltogether.

**Comment by onedr0p** [comment]
Agreed.

**Comment by Quiksmage** [comment]
Since https://github.com/Radarr/Radarr/issues/1584 was mentioned,

to clarify, the above issue is the built-in indexer, not jackett nor torrentpotato.

I think you meant to mention  

https://github.com/Radarr/Radarr/issues/1491

This is also not torrentpotato.

This is torznab and I have changed the title to further clarify.

Thanks!

**Comment by brimur** [comment]
I think this could be an easily solved problem for the Radarr devs. It should be a case of changing one URL and would be extremely useful to Radarr users.

Currently when you do a search for something in Radarr, say for example Star Trek Beyond, it uses the following Torrentpotato search 
````
[GET] http://localhost:5060/torrentpotato/thepiratebay?passkey=(removed)&user=&imdbid=tt0368709
````
This will fail on Cardigann (and possibly others like Jackett) because of the IMDB access issue

If the request from Radarr was this however...
````
[GET] http://localhost:5060/torrentpotato/thepiratebay?passkey=(removed)&user=&search=Star%20Trek%20Beyond
````
the results are returned. 

Its just a case of replacing imbdid= with search= and the movie name

**Comment by galli-leo** [comment]
@brimur Yeah we could easily fix this, but Torznab is the better choice to use anyways. We are gonna remove TorrentPotato indexer anyways.

**Comment by brimur** [comment]
@galli-leo How do I use Torznab with Radarr? I can use it fine with Jackett-Public and Sonarr but it wont work with Radarr because it will not search for movies.

**Comment by galli-leo** [comment]
Use the latest Jackett version. It supports Public trackers. Anyways, there the error still might come up. You should be able to add it using the add and save dropdown (force add)

**Comment by brimur** [comment]
Great. Thanks for the information
