### ISSUE TITLE
Add Movie by Actor or Genre

### ISSUE THREAD

**Issue by ChrisDurham** [Radarr/Radarr#1685]
Allow a MovieDb search by Actor or Genre in order to easily add movies featuring a given actor or genre.

**Comment by galli-leo** [comment]
You can accomplish this by adding a TMDB discovery list with the appropriate parameters :)

**Comment by distinguished-git** [comment]
Sad to say that this is still not possible.

**Comment by scphantm** [comment]
I would like to work on this.  I've reviewed the code, and my technique would greatly enhance the list capability, but require some big changes.  I would want to keep it simple, a different list for each actor/role type.  The discovery api has 2 roles, Cast and Crew.  so for example clint eastwood, you would have two lists

- Clint Eastwood - Cast
- Clint Eastwood - Crew

sound good?

**Comment by scphantm** [comment]
I can build it so that you can select different roles of the crew, It would have to be pre-defined roles due to the way the config system works.  but I can add things like Director, Producer, Writer to get things started.  then when you select a crew list, you select which jobs they had as well to filter those results.  

the config screen will get increasingly ugly, but i think its worth it.  Need to work out a better config system.  maybe coordinate with sonarr in the future.
