### ISSUE TITLE
Actual movie title should not be listed in the "also known as" section

### ISSUE THREAD

**Issue by crafty35a** [Radarr/Radarr#1700]
Every single movie seems to include the standard title in the "also known as" section. I suggest removing it, and hiding this section entirely if there are no actual alternate titles for that film.

**Comment by galli-leo** [comment]
Fixed on the latest develop release.

**Comment by pszlaci** [comment]
Hello! Since you've removed the feature "Also known as: ", one tracker (ncore) does not work.
I use the radar in Hungarian language.
A few steps from my experience:

1. Seach the movie: ( "swordfish" Hungarian title is "Kardhal" )
![radarr1](https://user-images.githubusercontent.com/29834454/31630177-27a7e652-b2b6-11e7-9eb3-f85860217ffc.JPG)

2. Click "ADD" button, Radarr translate the information:_
![radarr2](https://user-images.githubusercontent.com/29834454/31630476-fa754818-b2b6-11e7-949b-9da3acd9efe3.JPG)

3. Go Wanted section, and click the name of movie, and click search: (no ncore results)
![radarr3](https://user-images.githubusercontent.com/29834454/31630602-56bfab5e-b2b7-11e7-9872-9e9080780ad7.JPG)

4. Click any force add button, and select Hungarian language:
![radarr4](https://user-images.githubusercontent.com/29834454/31630773-f1038ba4-b2b7-11e7-9d49-063c2afd1593.JPG)

5. Will appear the "Also known as: " section:
![radarr5](https://user-images.githubusercontent.com/29834454/31630910-5a884fd8-b2b8-11e7-823e-1b943d2eac9f.JPG)

6. Click search again, and work ncore indexer:
![radarr6](https://user-images.githubusercontent.com/29834454/31630984-9a602b08-b2b8-11e7-9a48-c8f2b1dd425c.JPG)

Ncore web hits for "Kardhal" (swordfish)
![radarr7](https://user-images.githubusercontent.com/29834454/31631251-78528d70-b2b9-11e7-880f-22033c8be5be.JPG)

Sorry for the long post.
Please help solve this problem.

Best regards:
Pszlaci
