### ISSUE TITLE
When directory is removed manually during scan, Radarr keeps on looking

### ISSUE THREAD

**Issue by pven** [Radarr/Radarr#1707]
**Description:**
I accidently deleted a downloaded movie-folder that was just being scanned by Radarr. After the delete Radarr keeps on looking for the missing folder. After I created an empty folder, Radarr proceeded.

**Radarr Version:**
Latest

**Logs:**
```
17-6-21 10:32:33.7|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr:/volume1/downloads/radarr/Film_2017_WEB_x264_mp4/
17-6-21 10:33:03.7|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr:/volume1/downloads/radarr/Film_2017_WEB_x264_mp4/
17-6-21 10:33:33.7|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr:/volume1/downloads/radarr/Film_2017_WEB_x264_mp4/
17-6-21 10:34:04.0|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr:/volume1/downloads/radarr/Film_2017_WEB_x264_mp4/
17-6-21 10:34:33.9|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr:/volume1/downloads/radarr/Film_2017_WEB_x264_mp4/
17-6-21 10:35:04.0|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr:/volume1/downloads/radarr/Film_2017_WEB_x264_mp4/
17-6-21 10:35:34.1|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr:/volume1/downloads/radarr/Film_2017_WEB_x264_mp4/
17-6-21 10:36:04.4|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr:/volume1/downloads/radarr/Film_2017_WEB_x264_mp4/
17-6-21 10:36:34.2|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr:/volume1/downloads/radarr/Film_2017_WEB_x264_mp4/
```

**Comment by galli-leo** [comment]
What is the problem here? If you delete the folder, of course Radarr throws an error.

**Comment by pven** [comment]
It keeps on throwing the error, every 30 seconds. I only expect it once, not all the time until I help Radarr by creating back the directory.

**Comment by pven** [comment]
Maybe there is a relation with https://github.com/Radarr/Radarr/issues/1717 ?

**Comment by galli-leo** [comment]
@pven Good catch. That is definitely the same thing happening.

**Comment by pven** [comment]
Handled in #1717  :)

**Comment by Kalroth** [comment]
I'm seeing the exact same issue as you and it does not seem to be related to #1717.
How did you fix it?

The only way I can squelch the repeat error message is by creating an empty directory, but once I delete that directory the error message comes back.

This feels more like a stuck import that keeps on waiting for the download to finish, but it does not finish because I moved the file manually.

**Comment by AciDCooL** [comment]
I have exactly the same issue as Kalroth describes. Has something todo with items that have failed. And removing them form the queue there is no way to remove the backlog in the ui. Is there a way to edit the database manually?

**Comment by Kalroth** [comment]
I fixed the issue by removing the download completed entry in my download client, which is NZBGet in this case.

I'm guessing the issue is that Radarr gets triggered by the completed download and attempts to import the file, only to find that the file and/or folder is missing. This causes Radarr to abort and retry again indefinitely.

**Comment by AciDCooL** [comment]
You are right, I totally spaced on the possibility that radarr might be watching download history for automation. Since the download is "completed" in the history it want to pick the file up. Now I also get why it is imperative that remove failed downloads from history has to be on for failed download handling to work for what ever client you are using.
