### ISSUE TITLE
Not enough free space (3052113920) to import

### ISSUE THREAD

**Issue by blackwhattack** [Radarr/Radarr#1743]
Radarr correctly sees my disk space.

I think it might have been solved in Sonarr (https://forums.sonarr.tv/t/not-enough-free-space-to-import/712/3), because I don't see an option to disable free space check in Media Management.

**Comment by galli-leo** [comment]
Can you post some logs? Also is this on windows, linux, etc.? Because that option is only available under linux. Also are you using docker or remote drives?

**Comment by blackwhattack** [comment]
`Not enough free space (3052113920) to import: I:\FILMY\Hot.Fuzz.2007.1080p.BluRay.x264.DTS-ETRG\Hot.Fuzz.2007.1080p.BluRay.x264.DTS-ETRG.mkv (5072918110)`

I'm using Windows.
Not using either.

**Comment by galli-leo** [comment]
Well seems like it is what it says: The drive does not have enough free space (3052113920 bytes, or ~3GB) to import the 5GB movie.

**Comment by blackwhattack** [comment]
I get what's happening. It's somehow taking into account my C:\ disk even though my library is on I:\.
http://i.imgur.com/YORt8BQ.png

I see a connection; I've had the problem where for some reason my root folder was set to C:\Windows\System32, but I followed the instructions and made a new list properly and deleted the old one.

**Comment by galli-leo** [comment]
@blackwhattack What path is shown when you view that movie?

**Comment by blackwhattack** [comment]
I:\FILMY\Hot Fuzz (2007)

**Comment by TheOriginalOddsquad** [comment]
I've hit a similar problem, but I may know what the bug is... 

I'm on a Windows machine (Windows Sever 2011 to be exact) and the issue seems to be related to the way you check free space. If you are using the base path that doesn't take into account any physical drives mounting into a logical path and you get false free space reports.

In this case my base path is G:\Videos\Films, so you would check G: free space. The problem is the path I'm actually copying to is G:\Videos\Films\MoviesOnLacie2 where "MoviesOnLacie2" is a mount point for another drive. The G: drive **is** full, which is why its failing, but the drive mapped in at "MoviesOnLacie2" has about > 1TB free. You are probably running into the same issue in Linux drives using links to mount drives in a common path.

Why do this? Because this way you can keep extending/updating the storage without having to continually re-enter paths in Kodi etc. You just point it at the base path and away it goes.

I'll see if I can suggest a fix, it will probably involve walking the path and testing each part of the path, but I'll see if there is a simpler way.

**Comment by mkesler80** [comment]
I'm running a Docker Container and in my case all movies that are added automatically have their path set in the library to /opt/radarr/Select Path/<Movie Name> which causes the error.  I have to go in and manually set the path per movie.

**Comment by fysmd** [comment]
Same issue here:
Docker (linuxserver.io) on Linux with remote storage:
`root@c5f065aaf1ec:/# df -h
Filesystem               Size  Used Avail Use% Mounted on
overlay                   89G   83G  1.9G  98% /
tmpfs                     64M     0   64M   0% /dev
tmpfs                    4.9G     0  4.9G   0% /sys/fs/cgroup
//192.168.0.7/downloads  932G  632G  300G  68% /downloadsunraid
/dev/sda1                 89G   83G  1.9G  98% /config
//192.168.0.7/movies      38T   32T  5.8T  85% /movies
/dev/sdb1                493G  359G  109G  77% /downloads
tmpfs                    999M   11M  989M   2% /tmp/docker.sock
shm                       64M  4.0K   64M   1% /dev/shm
tmpfs                    4.9G     0  4.9G   0% /proc/scsi
tmpfs                    4.9G     0  4.9G   0% /sys/firmware`

and import is complaining for an import larger than 2Gb so it must be looking at  /config rather than /movies which is where it should be moving to..

**Comment by zestyphresh** [comment]
I've just run into this issue - you need to change the filepath on your wanted movies (I did this individually as I didn't have many, there might be a quicker way of doing this).

**Comment by Dewey80** [comment]
I am also facing this issue... I have nested mounts so that I don't have to change my database manager, I just add another hard drive.
Is there anyway to turn-off the check in the meantime?

**Comment by galli-leo** [comment]
Only under linux unfortunately

**Comment by teodorch85** [comment]
I got the same problem under UnRaid OS using Radarr docker.
An auto-added movie (from imdb lists) got a path under /opt so it fullfilled my docker.img

**Comment by teodorch85** [comment]
I had the problem mentioned at the bottom of this page.
The list didn't have a folder set so it default to /opt I think.

I set the correct folder also by creating a new list and if I get it again I will let you know.

**Comment by bobloadmire** [comment]
I have this same issue on windows. Tons of free space, not sure why its reporting it as not having enough. Even Sonarr it self shows over 1tb of free space on the drive it's attempting to move to

**Comment by incorpusyehtee** [comment]
Issue applies to Windows clients copying to Samba/CIFS shares as well, where the share reports 0 bytes free to most up-to-date Windows clients.
