### ISSUE TITLE
Not able to parse M2tS Bluray

### ISSUE THREAD

**Issue by cryptoz** [Radarr/Radarr#1824]
**Description:**
Movies are being snatched with 1080p Bluray quality but actually Bluray disk dumps.  example of title would include "1080p BluRay AVC DTS-HD MA 7.1"  Now other past issues have addressed this and you have said Radarr does not support these files and we should avoid downloading them.  The only problem is we didn't download them, Radarr did.  The 1080p quality is either Bluray, HDTV or WEBDL.  Im looking for a Bluray rip, it will have Bluray in the title but mkv format, or mp4 or whatever but not a disk dump.  I guess the issue is that I do not seem to have a way to avoid M2tS files.  I am going to try and set Bluray-1080p max size to around 18GB but maybe I end up missing a good rip of a long movie because of this?

**Comment by galli-leo** [comment]
Max sizes are calculated per movie runtime. So a long movie (e.g. LOTR) would have a bigger max size allowed. So this should not be a problem. Also I plan on adding support for those file types, so this is only an intermediary solution. (Though often you don't want these kind of rips, since they cannot be played by plex)
