### ISSUE TITLE
Don't remove Sabnzbd download when move failed

### ISSUE THREAD

**Issue by skerit** [Radarr/Radarr#1861]
**Description:**
My download via Sabnzbd was marked as "failed" because Sabnzbd couldn't move it to the correct destination.

Sabnzbd then reports the post-processing of the file has failed, but for Radarr this is enough the scrap the download and remove all files. That's quite unfortunate because the download actually did succeed.

I've since disabled the "Remove Failed download" option, but it might be interesting to let it see the difference between a true corrupt download (missing segments, unable to repair, ...) and things that can be fixed by user interaction.

**Radarr Version:**
Ver. 0.2.0.696

**Comment by galli-leo** [comment]
Do you know if sab reports this differently?

**Comment by manicely6005** [comment]
I am seeing this issue in Radarr version 0.2.0.1293. The file finishes downloading in SABnzbd. Then in Radarr under Activity, the icon next to the movie looks like a yellow file drawer and says the file is not an upgrade to the current release. The file is not removed from SABnzbd or my computer. Eventually, if not checked, the issue prevents other downloads from happening due to limited storage. I'm seeing a pattern with the downloaded filenames. It happens with a filename has BD25.ReEncode.1080P or BD25.ReEncoded.BluRay.1080p. It's like it downloads it thinking it's a Bluray then realizes it's 1080P.
