### ISSUE TITLE
Anyway to prevent spanish titles from getting selected?

### ISSUE THREAD

**Issue by Chas3down** [Radarr/Radarr#1894]
For example I want movie "The Oranges' and I get the spanish version "la hija de mi mejor amigo" downloading, then radarr can't import it because it's the wrong title, also I don't want the spanish version.  Other some crazy broken list of excluded words that would just be a hacky method, is there anyway to fix this?

**Comment by hotio** [comment]
If the indexer does not give a clue that its in spanish, radarr cannot know.

**Comment by hotio** [comment]
I took a closer look on themoviedb and it only has these alternative titles:

```
Scusa, mi piace tuo padre
Любовный переплет
```

So I'm guessing here...perhaps your indexer provided radarr the movie based on an imdb id, but the movie name is not listed as an alternative title, so radarr thinks it's wrong. If the info given by your indexer does not include a language, radarr can't know.

This is all some guess work, since you gave so little info, we might even be talking about different movies, since you did not even mention the release year.

**Comment by Chas3down** [comment]
http://www.imdb.com/title/tt1313139/ Is the movie.

Also, I am using Dog/geek as indexers, it seems most of the spanish releases are coming from Dog.  Sorry about so little information, what more would you like?

**Comment by galli-leo** [comment]
I will prolly add something to make Radarr not read the imdbid on specific indexers, though this should really be the job of your indexers labeling the releases correctly.
