### ISSUE TITLE
Unable to create directory for movies with weird characters like a colon ":"

### ISSUE THREAD

**Issue by djmulder** [Radarr/Radarr#1918]
Hey there, 

My Radarr stopped working and it seems to be stuck trying to move files that it can't move. In my case I get the following error:

`Unable to create directory: /mnt/muldata/Movies/Maze Runner: The Scorch Trials: Invalid handle to path "/mnt/muldata/Movies/Maze Runner: The Scorch Trials"`

My query is as followed: 
![image](https://user-images.githubusercontent.com/10437793/29240779-3e2f8434-7f6c-11e7-94ba-02f215769b7b.png)

So that would suggest it shouldn't be a problem. As it would just replace the colon. The way it looks to me it first moves/hardlinks the movie and then renames it.

I tried creating the directory by hand with no result. Radarr is now stuck it seems, it doesn't want to try new downloads of other movies, just keeps crashing on this error.

This Radarr instance is hosted on a Debian 8.7.1 machine.

**Comment by mikey2p22** [comment]
I also have a problem with colons in movie titles. Its not the same but still related to that. (not sure if I should open a new Ticket).

My Radarr is running on a synology NAS. 
Radarr can name the movie folder with a colon like: 
"Kong: Skull Island" but since colons are not allowed in windows file system, it displays a random sting like "KDd~2". The real title is only visible in the synology filesystem. I could live with that but the problem is: the movie station won't index this movie. It seems that it can't find this directory.

**Comment by chriswiduta** [comment]
+1 on synology

**Comment by timekills** [comment]
Same/Similar issue.
Three movies: Kizumonogatari Part 1: Tekketsu (2016), Kizumonogatari Part 2: Nekketsu (2016), and Kizumonogatari Part 3: Reiketsu (2017).

All three folders and movies were renamed (by me) to the same name minus the colon (:). I.E.
Kizumonogatari Part 1 Tekketsu (2016)/Kizumonogatari Part 1 Tekketsu (2016).mkv

They all still show as missing even after manually pointing Radarr to the correct folder.

**Comment by DoctorIOT** [comment]
This is still an issue for me on 0.2.0.1293 with a move called Alita: Battle Angel (2019)
