### ISSUE TITLE
Add IMDB scores to frontpage

### ISSUE THREAD

**Issue by king8084** [Radarr/Radarr#1940]
Hi !

love Radarr first of all, now i added IMDB popular list and i think it would be really helpful if we can add IMDB scores to the frontpage

i googled and it seems this request been asked few times in the past

**Comment by galli-leo** [comment]
Yeah, sadly not possible since IMDB does not have an api :/

**Comment by king8084** [comment]
there are sites that offer APIs to provide IMDB information though, which is utilized by sites like passthepopcorn for example where you can see all IMDB scores as well as rotten tomato scores directly on PTP, you can even search PTP based on IMDB scores criteria so it is possible

**Comment by galli-leo** [comment]
Sadly the only one I found, has gone private since. PTP are probably doing it via scraping (and creating their own database). Scraping is something I do not want to do, as it is very unreliable.

However, you can still view the TMDB ratings. Also when viewing the list via the discover new movies UI you see the scores for each movie already (IMO that's a better place to view them, since you prolly want to know the rating before adding them to radarr).

**Comment by king8084** [comment]
galli, upon investigating this seems possible easily with 
http://www.omdbapi.com/

which is still active, you just need to join their patron here
https://www.patreon.com/bePatron?u=5038490

for 10$ a month for unlimited API calls server, i would be willing to handle the 10$ cost monthly as long as we finally get this running
