### ISSUE TITLE
Can't import using imdb prefix

### ISSUE THREAD

**Issue by turkeyphant** [Radarr/Radarr#1952]
**Description:**

Can't import at all using imdb: prefix.

e.g. using "imdb:tt1322932" returns noting:

`There Was An Error Searching For 'Imdb: Tt1322932'.
If the movie title contains non-alphanumeric characters try removing them, otherwise try your search again later.`

However, http://www.imdb.com/title/tt1322932/ exists.

**Radarr Version:**

Radarr Ver. 0.2.0.778

**Comment by jamesmacwhite** [comment]
@turkeyphant Interesting. At first I started chasing ghosts in the code on this one, but then I realised the API call is actually working.

Try testing another imdb ID e.g. tt0096895, you should find it works fine. The sample imdb ID you provided though does indeed fail, but its actually The Movie DB API not returning anything either:

https://api.themoviedb.org/3/find/tt1322932?api_key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&external_source=imdb_id (will fail)

```
{"movie_results":[],"person_results":[],"tv_results":[],"tv_episode_results":[],"tv_season_results":[]}
```

https://api.themoviedb.org/3/find/tt0096895?api_key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&external_source=imdb_id (works)

```
{"movie_results":[{"adult":false,"backdrop_path":"/2blmxp2pr4BhwQr74AdCfwgfMOb.jpg","genre_ids":[14,28],"id":268,"original_language":"en","original_title":"Batman","overview":"The Dark Knight of Gotham City begins his war on crime with his first major enemy being the clownishly homicidal Joker, who has seized control of Gotham's underworld.","release_date":"1989-06-23","poster_path":"/kBf3g9crrADGMc2AMAMlLBgSm2h.jpg","popularity":5.618906,"title":"Batman","video":false,"vote_average":7.0,"vote_count":1956}],"person_results":[],"tv_results":[],"tv_episode_results":[],"tv_season_results":[]}
```

Something specific to that IMDB entry with the API by the looks of it.

**Comment by jamesmacwhite** [comment]
@turkeyphant Actually, I've just now noticed, this is a documentary. Not a movie. Did you mean to search:

Journey to the Center of the Earth (2008)
http://www.imdb.com/title/tt0373051/

This works fine :)

**Comment by turkeyphant** [comment]
How are you differentiating between this documentary and all the other documentaries on IMDb you can import into Radarr?

**Comment by jamesmacwhite** [comment]
@turkeyphant To me it looked like a incorrect movie search, however if that's not the case, I apologise. 

The original info however is still valid. The IMDb prefix supplied was not returning anything from the TMDb API which is why you saw that error. If you have an example of another IMDb documentary that does work, let me now.

As far as I know, the IMDb prefix searching works, the error is specific to the supplied IMDb ID.

**Comment by jamesmacwhite** [comment]
@galli-leo This needs investigating, it wasn't an incorrect movie search by OP my assumption was wrong. Here's another IMDB ID that fails `tt3640710`. It is a film but a documentary. That seems to be a theme here. Based on the above its the TMDb API not returning anything meaningful for these types of films.

**Comment by Dnkhatri** [comment]
I cant import this movie and its not a documentary
http://www.imdb.com/title/tt4769482/

**Comment by jtrott** [comment]
Can't add this non documentary either. http://www.imdb.com/title/tt2130117/
Also doesn't exist on tmdb.

**Comment by galli-leo** [comment]
Well if it doesn’t exist on tmdb of course it can’t be added.

**Comment by vatanparvar** [comment]
Hey guys,
I'm new to Radarr and I'm testing it to see whether it can replace CP.
So far everything seems good apart from the fact that it doesn't play well with IMDB and the decision has been made to use TMDB instead! 

E.g. searching for tt2669634 (or imdb:tt2669634) returns no result.

Since IMDB is a much more comprehensive database, would someone explain to me why it's not being used by Radarr as the primary source for looking movies up?

Thank you for all your efforts, keep it up. :-)

**Comment by Dnkhatri** [comment]
Because imbd does not have an api so need to web scraping to get data off it which is more error prone and bound to break if imdb website changes a bit.. Best option if you don't find a movie is to add it to tmbd it is a hassle but if everyone does that fewer and fewer movies will be missing.

**Comment by galli-leo** [comment]
@vatanparvar Because I don't wanna pay 10000 Dollars for API access :P Also TMDB's API is a lot better. It shows a lot more info in fewer API calls. For popular movies it works fine. This is actually the first time someone has asked why we use TMDB. I think most people don't even know what service we use. Also seems like that movie doesn't exist yet on TMDB, you can always expand TMDB, which helps it in the long run.

**Comment by galli-leo** [comment]
@Dnkhatri There is an API, it's just ridiculously expensive

**Comment by RevenantOne** [comment]
I'm currently experiencing the same issue for https://www.imdb.com/title/tt9614090/ which is also a documentary. It also exists on tmdb https://www.themoviedb.org/tv/87518-i-love-you-now-die-the-commonwealth-vs-michelle-carter, however it's listed as a TV show: themoviedb.org/tv.

A quick search of for "themoviedb.org/movie" within the code returns a few results where as a search for "themoviedb.org/tv" returns nothing. Would fixing this issue be a case of detecting whether the url contains "movie" or "tv"?

(Since this is listed as TV I attempted to add it into Sonarr, which in turn uses tvdb, who specifically state documentaries such as above are not permitted.)

**Comment by paulmorabito** [comment]
I'm having exactly the same issue as @RevenantOne with the same documentary.

**Comment by TheLinuxGuy** [comment]
+1 having the same issue for tt9614090

**Comment by pholcroft** [comment]
I too am having exactly the same issue as @RevenantOne with the same documentary.

**Comment by WeirDave** [comment]
Googling my issue and found this thread. Can't seem to find the documentary movie " Mystify: Michael Hutchence (2019)"

It's in TMDB https://www.themoviedb.org/movie/586534-mystify-michael-hutchence?language=en-US

and it's IMDB https://www.imdb.com/title/tt5938950/

But it won't find it....

**Comment by jtrott** [comment]
I just searched in Radarr for "Mystify" and the movie you are after was the top hit.

**Comment by WeirDave** [comment]
> 
> 
> I just searched in Radarr for "Mystify" and the movie you are after was the top hit.

Hmmm well just for the heck of it I tried to search for Star Wars and it's also just spinning... how do I fix it?
