### ISSUE TITLE
Last used "Priority" or "Availability" not remembered when adding movies

### ISSUE THREAD

**Issue by desimaniac** [Radarr/Radarr#1984]
On the recommendations/discovery page, when I add one movie, the one right below resets `availability` and `profile` to the topmost option in the dropdown. 

Radarr version: 0.2.0.840
nightly

**Comment by desimaniac** [comment]
Looks like it has fixed itself somehow..

**Comment by jamesmacwhite** [comment]
@galli-leo I'm not sure about this one, might need more info. I can't seem to replicate it. I know when you select the min availability on one item it changes across all, but that currently happens on the latest develop release, so either that's by design or a bug that's been around.

But that doesn't sound like the issue here, can you clarify @desimaniac?

**Comment by desimaniac** [comment]
Yeah. After the the most recent nightly update, that behavior you mentioned was not working no matter how many times I restarted (changing of all of them across), but today I noticed that had resolved itself. I cant explain it.

**Comment by desimaniac** [comment]
I guess if no one else is experiencing this, it can be closed. I will report it again, if I notice it.

**Comment by jamesmacwhite** [comment]
@desimaniac Keep it open, I'd like @galli-leo to weigh in on it, to make sure it isn't related to recent UI work. Thanks for reporting it.

**Comment by desimaniac** [comment]
No prob and thank you!

**Comment by jamesmacwhite** [comment]
UI changes have been reverted, though not sure if it was the cause, either way. Hopefully restored again.
