### ISSUE TITLE
Failed to import | Access denied

### ISSUE THREAD

**Issue by kaplannn** [Radarr/Radarr#2062]
**Description:**

Ubuntu: 16.04
Radarr: 0.2.0.852

Sometimes it can't import a movie. It always says "Access to the path is denied". Permissions are set to 777. 90% of the movies have no problems beeing imported so i guess its not a permission problem. (automated, everything runs with the same user)

Example:

Couldn't import movie /home/plex/downloaddir/radarr/Paddington 2014 German DTS DL 1080p BluRay x264-Pate/padding.108-pate.mkv: Access to the path is denied.

![image](https://user-images.githubusercontent.com/17184697/30267391-aed7c934-96e2-11e7-9656-b76136b1aee2.png)

**Comment by VHWDev** [comment]
As what user is Radarr running?
Is Radarr running in docker or on the same machine/VM?

**Comment by kaplannn** [comment]
everything is running with user "plex". Radarr is running on the same machine, no docker.

**Comment by VHWDev** [comment]
Can you provide:

`stat /home/plex/downloaddir/radarr/Paddington 2014 German DTS DL 1080p BluRay x264-Pate/padding.108-pate.mkv`

and

`stat /home/plex/downloaddir/radarr/Paddington 2014 German DTS DL 1080p BluRay x264-Pate`

and

`stat /home/plex/downloaddir/radarr`

You might have to escape the paths or wrap them.

**Comment by kaplannn** [comment]
1)
![image](https://user-images.githubusercontent.com/17184697/30284593-a31629ae-971b-11e7-85c3-e20dc0835dce.png)

2)
![image](https://user-images.githubusercontent.com/17184697/30284602-af1467ca-971b-11e7-8daf-70f461583c5f.png)

3)
![image](https://user-images.githubusercontent.com/17184697/30284621-b8634c6a-971b-11e7-8ef7-dab3654921ff.png)

**Comment by VHWDev** [comment]
What kind of filesystem are you using? (`df -T /home/plex/downloaddir/radarr/Paddington 2014 German DTS DL 1080p BluRay x264-Pate/padding.108-pate.mkv`)

It's odd that only "Certain" files are having this. You did compare the permissions on a working file versus a non working file yourself and didn't notice anything odd?

**Comment by kaplannn** [comment]
![image](https://user-images.githubusercontent.com/17184697/30293205-fecc31cc-9738-11e7-85b2-7580d3d396e5.png)

yeah exactly. they have the same permissions... :/

**Comment by NightRider0** [comment]
kind of the same issue here, i dont think radarr is moving the file from were sab drops completed files to there final destination as the user it was started as. my reason behind this is that Sonarr with owner permisson rwx and no other permissons set can move its downloads but in order to get radarr to move the downloads i have to set others to rwx. all services are running under the same username

**Comment by VHWDev** [comment]
I tried to dig into this but personally don't get far, sorry about that. Let's hope a developer sees this and wants to dig in. But it would be hard to troubleshoot as it seems "random".

The files that do work, perhaps they have _ or spaces instead of dots? Perhaps that is somehow causing the issue?

**Comment by kaplannn** [comment]
thank you so far for the support. Gonna check if this is the case :)

**Comment by VHWDev** [comment]
In any case, try to find a method to duplicate this behaviour consistently as that would give the developers a clear pointer.

**Comment by kaplannn** [comment]
Ok now i am confused. i rebooted the server and suddenly it is working. will never know what happened there.... hope it will stay now :D

**Comment by Croman12** [comment]
I had the same issue en maybe this will lead in the right direction. Radarr had to physically move the file to another drive in my Synology. Copying went just fine until the last part. It had copied the whole movie but after that it just deleted the file with the error "Access to the path is denied'.
I checked almost every possible setting en it seemed to occur randomly. Until I noticed that all the folders in the folder /volume1/Downloads/ where available to everyone (0777), ONLY THE MOVIE ITSELF (/volume1/Downloads/filename.mkv) had no write permissions selected for sc-media. Maybe this will correct itself after a reboot but not sure. I manually changed permissions and made NZBGet to set file permissions for every file to 777 (umask setting).
Never had an issue since then, hopefully this will solve it for others.

**Comment by lateparty** [comment]
I had this issue and was caused by what I suspected. A new "trash" folder which the Docker Radarr user or group didn't have write permissions to. 

Because the downloads were upgrades it kept saying access to the downloaded file was denied, but without changing the permissions on the download path or file, and only adding write permissions to the new trash folder outside of Docker, the movies imported without issue.
