### ISSUE TITLE
Continually leeching the same movie, REPACK, DOCU, etc

### ISSUE THREAD

**Issue by c0rnflake** [Radarr/Radarr#2087]
Back in August I noticed that a movie was being repeatedly leeched.  It looked like Radarr really wanted me to watch this one

The release name had REPACK in the title which at the time is what was concluded was the issue.

Back to this week and the issue seems to have popped it's head up again, this time it's a movie with DOCU in the title which is being repeatedly leeched.

Radarr Ver. 0.2.0.852
nightly

**Logs:**

I'll add the log next time this leeches

**Comment by KBlixt** [comment]
are you talking about radarr grabbing the same nzb file over and over again? or the lists adding the same movie to your collection over and over again?

in that last case i have no clue of whats causing it, just red-listing it should do it?

the second issue I have some experience with though. It's either an .iso file, a file without the right taggs in the movie file or the movie file is in a sub folder within the main downloaded folder.  

if you have DVDR quality selected I'd advice de-selecting it since most of those are .iso format. else there isn't much you can do about it besides manually setting the file to "failed download". I suspect that this issue is much rarer among newer movies, so if you know you are importing old movies you should keep an eye out for trouble.

**Comment by c0rnflake** [comment]
I'm talking about Radarr grabbing the same nzb again and again, leeching.  I leech nothing but 1080p.  No other quality is set.

**Comment by henkin67** [comment]
Check if the quality of the movie after grabbed is really 1080p.
Maybe Radarr is predicting a 1080p quality by reading the release name, but after download the real quality is less than 1080p.
Then Radarr continu to monitor the movie to find the wanted quality and found this release (again) which looks 1080p quality.
In any case you can black list this release. Radarr should stop to download it.
