### ISSUE TITLE
update linuxserver/radarr docker container caused DB error

### ISSUE THREAD

**Issue by natelandau** [Radarr/Radarr#2094]
**Description:**

I just updated my docker container (linuxserver/radarr:latest) and it has led to a DB error.  I can successfully see the loading screen of radarr but it never moves past the dark "Radarr ver." screen with the loading circles animation. 

The db error I am seeing is:

```
17-9-17 12:20:35.7|Fatal|NzbDroneErrorPipeline|Request Failed

[v0.2.0.654] System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
no such column: t0.AlternativeTitles
  at System.Data.SQLite.SQLite3.Prepare (System.Data.SQLite.SQLiteConnection cnn, System.String strSql, System.Data.SQLite.SQLiteStatement previous, System.UInt32 timeoutMS, System.String& strRemain) [0x0033c] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLiteCommand.BuildNextCommand () [0x00068] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
```

It seems the docker container is downloading an earlier version of Radarr (v0.2.0.654) which is likely not compatible with the version I last updated to August 30th within the UI.

I saw a similar issue with Sonarr which may be related where my local version had passed the docker version.  That was an easy fix, however, since I could access the Sonarr UI and do a manual update.  Here, with Radarr, I can't get to the UI to do an upgrade.  

I am really hoping there's a relatively easy fix for this rather than having to start over by reimporting my extensive movie library into a blank Radarr install and working to recreate my settings and more importantly my future move watchlist.  any help would be appreciated.

**Comment by hotio** [comment]
This is why you don't update inside a container if you doon't know what you are doing. Easy fix is restore backup.

**Comment by coaxial** [comment]
As a side note, you should specify a particular version when using containers. `latest` has the potential to break your setup because if you go from one version to `latest` which changed the way it stores data, you will corrupt or be unable to use your existing db.

Best practice is to specify a version (`81` is the latest today), and go from there. When you want to upgrade, read the release notes and find out what the upgrade path is. Once you know and have done the necessary changes, switch your container to the next tag, and off you go.
