### ISSUE TITLE
Unable to use "Download Station" download client

### ISSUE THREAD

**Issue by toxic0berliner** [Radarr/Radarr#2120]
Hello,

I have both sonarr and radarr running on my raspberry, and if sonarr (close source-base from radarr as I understand) is perfectly able to send torrents to my Synology DS214play to be downloaded and then grab the files from the locally mounted cifs share to handle the completed downloads, when configuring radarr the very same way, the torrent shows as corrupt in Download Station and cannot be downloaded.
I see no errors in the logs, I suspect when you send the torrent file using the API there must be some issue passing the data...

I can reliably reproduce the issue, in fact it tries every release for a movie one atfter the other since it sees that the download failed.
When I configure it with a torrent blackhole on a monitored cifs folder on my NAS, it does work and properly download the release, so the issue is when you send the torrent to the DownloadStation client only.

I couldn't find anything in the logs as they are right now, if needed,please advise on how to enable more verbose logs so I can reproduce the issue and provide better logs.

But I guess having a diff between radarr and sonarr on the specific file that defines the DownloadStation torrent client or some of the files that passes info to these classes will probably show you the issue as well.

Thank you in advance for your help,

Radarr Ver. 0.2.0.852 branch develop
Running on Raspberry model B (ARMv6)

**Comment by toxic0berliner** [comment]
Well, I have checked all differences between sonnar and radarr code in `src/NzbDrone.Core/Download/Clients/DownloadStation/` and I really can't find where's the difference that makes radarr send invalid torrents to the DownloadStation...

Could someone else, maybe more familiar with the codebase, have a look into this issue ?

I'll be looking at how to enable debug logs in the meantime to try and provide you with better information...

Thank you in advance,
Regards,
ToXiC0

**Comment by Feniz** [comment]
I have the same issue, a walkaround is to set a blackhole as download client or use another one (ie transmission).

Radarr Ver. 0.2.0.900
nightly

**Comment by guich59** [comment]
Have the same issue. The error is that the torrent is not well encoded.
I tried downloading the torrent file back from download station and give it to utorrent, and it's giving me an error about encoding too

**Comment by galli-leo** [comment]
You can enable debug logging in Settings -> General. I have no idea why this would fail, so I am clueless without any logs. Also don't have a diskstation, so not really anyway of debugging this :(

**Comment by Ltek** [comment]
I just installed again, fresh and Download Station doesnt show as an option in the "Download Client" screen

**Comment by galli-leo** [comment]
@Ltek Are you sure you installed the latest version? Shows up fine for me. Very unlikely that just one Download client doesn't show up there.

**Comment by Feniz** [comment]
@galli-leo hi, the issue is still there (Ver. 0.2.0.946). You can find the debug log here:
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/1719921/radarr.debug.txt)

apparently the communication between radarr and DS takes places, but the download is then stuck in DS, progress and file size unknown. I would say the torrent file gets somehow corrupted in the process, and DS is not able to handle it properly.

Let me know if I can help with further testing. Thank you!

**Comment by galli-leo** [comment]
@Feniz This seems interesting:
> 18-2-13 13:37:03.4|Debug|TorrentDownloadStation|TorrentDownloadStation did not return the expected InfoHash for 'magnet:?xt=urn:btih:5ac4ca9fb91a29cf18cf2aabebc4b5aea1b9eb05&dn=Ammore E Malavita 2017 iTALiAN Bluray 1080p x264 FoRaCrEw mkv.torrent', Radarr could potentially lose track of the download in progress.

Can you enable trace logging and do that again?

**Comment by Feniz** [comment]
@galli-leo sure, here you go: 
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/1721160/radarr.trace.txt)

**Comment by galli-leo** [comment]
@Feniz Nevermind, I think that log message has nothing to do with it. However, according to the debug log Radarr actually sends a magnet link over. What happens when you use the following magnet link in DS?: magnet:?xt=urn:btih:5ac4ca9fb91a29cf18cf2aabebc4b5aea1b9eb05&dn=Ammore E Malavita 2017 iTALiAN Bluray 1080p x264 FoRaCrEw mkv.torrent

Also there shouldn't be a difference between Radarr and Sonarr in the implementation. I think something else is wrong here.

**Comment by Feniz** [comment]
> What happens when you use the following magnet link in DS?:
`magnet:?xt=urn:btih:5ac4ca9fb91a29cf18cf2aabebc4b5aea1b9eb05&dn=Ammore E Malavita 2017 iTALiAN Bluray 1080p x264 FoRaCrEw mkv.torrent`

adding that link manually it doesn't work either.

The one from the torrent site works:

`magnet:?xt=urn:btih:5ac4ca9fb91a29cf18cf2aabebc4b5aea1b9eb05&dn=Ammore.E.Malavita.2017.iTALiAN.Bluray.1080p.x264-FoRaCrEw.mkv&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce`

so I guess it is about the tracker part of the link being cut... it is interesting that once the link above is pasted in DS and then the download it's canceled after it started, DS can now properly start the download through Radarr too. I suppose it keeps the tracker somewhere, but I'm no expert.

**Comment by galli-leo** [comment]
Hmm that's very interesting, the above magnet link (without the announce url) worked fine in transmission. Maybe diskstation needs the announce url in the magnet link? What torrent site are you using?

**Comment by Feniz** [comment]
Yup, with transmission everything works just fine.

Anyway, I finally understood what is the issue: i turned off the "Completed Download Handling" from Settings-->Download Client and DS can start the download. Funny thing is that if I look to the magnet link in the DS, it lacks the announce url, so that shouldn't be the issue (maybe).

DS have anyway its own internal options for the complete handling feature, so I think I'll just disable it. 

It would be nice to have some other DS users feedback to see if they confirm my findings.

**Comment by Feniz** [comment]
@galli-leo I have an update on this Issue; since I wasn't really satisfied with drone factory (It works only by time to time, at least for me) I made some other tests.

I use Jackett on which I configured 2 torrent sites for italian movies, (ilcorsaronero and TNTVillage): turns out that ilcorsaronero gives the issue described above, while TNTVillage works fine (Transmission keeps on working with both btw).

So I guess the issue is torrentsite related, maybe it can help.

Cheers!

**Comment by kacole2** [comment]
First time user here... My download station isn't getting any requests to kick off downloads. I believe I have everything setup correctly. The debug log file shows:
```
18-4-20 17:21:53.4|Debug|DownloadStationTaskProxy|Trying to get tasks
18-4-20 17:21:53.5|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (23 ms)
18-4-20 17:22:23.8|Debug|DownloadStationTaskProxy|Trying to get tasks
18-4-20 17:22:23.9|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (19 ms)
18-4-20 17:22:53.8|Debug|DownloadStationTaskProxy|Trying to get tasks
18-4-20 17:22:53.9|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (21 ms)
18-4-20 17:23:23.9|Debug|DownloadStationTaskProxy|Trying to get tasks
18-4-20 17:23:23.9|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (23 ms)
18-4-20 17:23:53.9|Debug|DownloadStationTaskProxy|Trying to get tasks
18-4-20 17:23:54.0|Debug|DSMInfoProxy|Trying to get serial number
18-4-20 17:23:54.1|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (27 ms)
18-4-20 17:24:09.5|Debug|Api|[GET] /api/log/file: 200.OK (6 ms)
18-4-20 17:24:09.5|Debug|Api|[GET] /api/log/file/radarr.debug.txt: 200.OK (5 ms)
18-4-20 17:24:24.0|Debug|DownloadStationTaskProxy|Trying to get tasks
18-4-20 17:24:24.1|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (21 ms)
18-4-20 17:24:54.1|Debug|DownloadStationTaskProxy|Trying to get tasks
18-4-20 17:24:54.2|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (16 ms)
18-4-20 17:25:24.2|Debug|DownloadStationTaskProxy|Trying to get tasks
18-4-20 17:25:24.2|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (16 ms)
18-4-20 17:25:54.2|Debug|DownloadStationTaskProxy|Trying to get tasks
18-4-20 17:25:54.3|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (25 ms)
18-4-20 17:26:12.5|Debug|Api|[GET] /api/log/file: 200.OK (6 ms)
```

**Comment by theeddie** [comment]
Still broke

**Comment by Ltek** [comment]
Been working fine for me for almost a year now  -daily use. Its the only DL
Client I have configured.
