### ISSUE TITLE
Not Importing all movies after bulk download via sabnzbd

### ISSUE THREAD

**Issue by kaplannn** [Radarr/Radarr#2138]
**Description:**

Ubuntu: 16.04
Radar: 0.2.0.852

I recognized that if i download lots of movies (like 50 at the same time), it will just import like 50% in radarr. If i download single movies, this problem never occurred. (Even if i download the same movie, after it failed within these 50 movies, it will succeed.)

The Movies are always monitored in Radarr, when they are downloading. When i open the "manual import" folder, it says sometimes "unknown movie" or just nothing:

![image](https://user-images.githubusercontent.com/17184697/31184253-20dfca92-a929-11e7-9e17-7a99d26e0b05.png)

If i manually import the movies, it works. to import a movie it takes a lot of time due to the loading time of all movies (like 4k+). 

Do you guys have any advice?

Greetings :)

**Comment by redboyke** [comment]
radarr is just crap. when i download something it always shows up as missing and tries to redownload the same copies over and over again. forcing me to stop using it and going back to couchpotato so no donations are going to radarr from me.

**Comment by kaplannn** [comment]
nice, thank you for that constructive comment. Why are you even here??

**Comment by galli-leo** [comment]
@kaplannn Can you enable debug logging and post the debug logs here?

@redboyke This seems like an issue with your configuration (maybe some permission issues?). If you hop on discord and post some logs, someone should be able to help you.

**Comment by RaymondSchnyder** [comment]
@kaplannn Because he tries to warn others who are in the same misery as him -.-
Im in the same boat as him, applying workaround after workaround, and i wasnt even able to import my movie collection yet, as radarr has strong naming conventions as of "Movie (2017)".
"Movie.2016.NOGRP.2016" isnt gonna be imported after all, so i have to rename ALL files from my 20tb collection with filebot, and hope to hell that radarr WANTS TO import these files this time.

// Enough rant

@kaplannn Activate Debugging and send the log over discord to resolve this easier

**Comment by redboyke** [comment]
wel my issue is resolved now.
i had /films linked to /volume1/videos/movies in sabnzbd and i had /movies linked to /volume1/videos/movies. the outcome should be the same cause same folder is mapped but somehow radarr was seeing it as a different folder. it was sending it to sabnzbd but couldn't rename cause it saw it as /films/moviename.mkv and said the file did not exist. also i only noticed it because i actually deleted radarr for the 10 time and i know had them both on /films before and it wasn't working so now they are called both /movies and it works. also my  radarr for some weird reason doesn't let me see the logs in the ui keeps getting a loading stuff. but i'm glad it finally works now after all this frustration cause having to delete all your movies and adding them manually just to get them checked as downloaded was a big issue. hopefully it keep working. i donated 10 dollar.

**Comment by RaymondSchnyder** [comment]
I would really like to mass import my movie collection, but radarr loads the UI since nearly 20 minutes and in the logs is stated nothing. Im really frustrated at this point.

**Comment by redboyke** [comment]
50 movies was already like 20sec so 20TB is just to large to import at once and i think you will be having problems with radarr crashing all the time when opening having such a large library. dont know what system you have. the way i fixed my collection is by redownloading everything and make sure radarr has permission to read/write folder and edit file.

**Comment by RaymondSchnyder** [comment]
@redboyke I wont be redownloading 20TB xD
Couchpotato can manage this amount without problems at the moment, but i gave radarr a chance, since it looks real good and it is in active development, but i begin to worry...

**Comment by kaplannn** [comment]
@galli-leo: here i found an example with the movie "Get The girl":

(whole Log attached)

17-10-24 08:48:19.2|Debug|Parser|Parsing string 'Get the Girl 2017 German 1080p DL DTSHD BluRay AVC Remux-pmHD'
17-10-24 08:48:19.2|Debug|Parser|Movie Parsed. Get the Girl - 2017 
17-10-24 08:48:19.2|Debug|Parser|Language parsed: German
17-10-24 08:48:19.2|Debug|QualityParser|Trying to parse quality for Get the Girl 2017 German 1080p DL DTSHD BluRay AVC Remux-pmHD
17-10-24 08:48:19.2|Debug|Parser|Quality parsed: Remux-1080p v1
17-10-24 08:48:19.2|Debug|Parser|Release Group parsed: pmHD
17-10-24 08:48:19.2|Debug|Parser|Parsing string 'Get.the.Girl.2017.German.1080p.DL.DTSHD.BluRay.AVC.Remux-pmHD{{ZJjgYXzK13}}'
17-10-24 08:48:19.2|Debug|Parser|Movie Parsed. Get the Girl - 2017 
17-10-24 08:48:19.2|Debug|Parser|Language parsed: German
17-10-24 08:48:19.2|Debug|QualityParser|Trying to parse quality for Get.the.Girl.2017.German.1080p.DL.DTSHD.BluRay.AVC.Remux-pmHD{{ZJjgYXzK13}}
17-10-24 08:48:19.2|Debug|Parser|Quality parsed: Remux-1080p v1
17-10-24 08:48:19.2|Debug|Parser|Release Group parsed: pmHD
17-10-24 08:48:19.3|Debug|Parser|Parsing string 'Get the Girl 2017 German 1080p DL DTSHD BluRay AVC Remux-pmHD'
17-10-24 08:48:19.3|Debug|Parser|Movie Parsed. Get the Girl - 2017 
17-10-24 08:48:19.3|Debug|Parser|Language parsed: German
17-10-24 08:48:19.3|Debug|QualityParser|Trying to parse quality for Get the Girl 2017 German 1080p DL DTSHD BluRay AVC Remux-pmHD
17-10-24 08:48:19.3|Debug|Parser|Quality parsed: Remux-1080p v1
17-10-24 08:48:19.3|Debug|Parser|Release Group parsed: pmHD
17-10-24 08:48:19.3|Debug|Parser|Parsing string 'Get the Girl 2017 German 1080p DL DTSHD BluRay AVC Remux-pmHD'
17-10-24 08:48:19.3|Debug|Parser|Movie Parsed. Get the Girl - 2017 
17-10-24 08:48:19.3|Debug|Parser|Language parsed: German
17-10-24 08:48:19.3|Debug|QualityParser|Trying to parse quality for Get the Girl 2017 German 1080p DL DTSHD BluRay AVC Remux-pmHD
17-10-24 08:48:19.3|Debug|Parser|Quality parsed: Remux-1080p v1
17-10-24 08:48:19.3|Debug|Parser|Release Group parsed: pmHD
17-10-24 08:48:19.3|Debug|DownloadedMovieImportService|Unknown Movie Get the Girl 2017 German 1080p DL DTSHD BluRay AVC Remux-pmHD

Seems to be a parsing problem.
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/1409838/radarr.debug.txt)

**Comment by galli-leo** [comment]
@kaplannn Yeah so the issue seems to be that the correct title is Get The Girl - Love can be twisted. Thus Radarr won't import it, as it isn't the same movie to Radarr. you can either enable Lenient Mapping (Settings -> Parsing Leniency, not sure which tab it's at, probably Indexers)

@RaymondSchnyder @redboyke Yeah bulk import is kinda slow, since it has to ask the movie db for info on every movie (TMDB has rate limiting, so 40 movies in a minute at best :(). However, with a small page size a lot of people have managed to import it ok. (Someone imported 40k movies, so it should be fine, just takes some time). The latest updates should also have improvements for large libraries (40k movies loaded in about 15 seconds for me)
