### ISSUE TITLE
Feature Request: Download multiple Formats in different locations

### ISSUE THREAD

**Issue by djderan** [Radarr/Radarr#2203]
I am not sure if this is possible but I figured I'd bring it up.  If you say you have a movie collection and you want to store multiple formats of a movie, say 3D version and regular or in Login you wanted Noir and Theatrical formats there's really no way of doing this other than manually doing it yourself, it would be awesome if you could specify qualities and editions and where you want to store them.

**Comment by hotio** [comment]
I think this is a feature request that might not even show up in 10 years...

What are the benefits for a broader audience? Who is going to watch Logan (not sure if that's what you meant) in color and again in black and white? 3D hasn't really been more than just a gimmick, all the best tv's of 2017 are dropping 3D support anyway, so... .

Let's get radarr stable first, before fucking it up completely.

So my humble advice is to start becoming really good in doing it manually or put up a nice bounty of a couple of thousand dollars.

**Comment by djderan** [comment]
No need to be a dick. Plenty of people keep various different versions of movies... I didn't list more out but if you would like a few more examples you have Star Wars various versions, Rogue Cut of X-Men, Theatrical Cuts, Extended Cuts and Director Cuts, Someone might want to keep a copy of both 4K and 1080p.  It's a nice to have feature.

**Comment by hotio** [comment]
I'M NOT BEING A DICK, GET OVER YOURSELF.

Offcourse it's a nice to have feature, I'm just saying don't get your hopes up. It's a very limited audience who prefers to keep every single "cut" ever made of a movie.

4K and 1080p could be handled with plex just fine, download 4K, let plex convert a 1080p copy. But again you could say that this is something only people using an underpowered server would like to have.

**Comment by djderan** [comment]
If you are using that as a measure, 3D support is in the top 10 which you also said no once cares about.

**Comment by hotio** [comment]
I did not say that nobody cares about it. I said it's on its way out.

This is opensource software, so the features getting in first, are either going to be extremely popular or niche features that the devs like themselves. You obviously haven't really been on discord much. I'm just letting you know what to expect from the bits and pieces I still remember. You are certainly not the first coming up with this idea.

**Comment by phaelon74** [comment]
I would definitely want this capability.  Watching Plex try to encode a 4k 60+GB movie into 1080P is painful.  I would love the ability to setup multiple items for single movies where each one can utilize a different profile and go to a different location.

**Comment by hotio** [comment]
"painful" is relative, I've seen plex do 2 (4K 50GB x265) transcodes to 1080p without really breaking a sweat.

**Comment by phaelon74** [comment]
What was the proc, memory, Setup?  The best I have seen 4k transcode is on an 8th gen i7, 1.1x conversion for a 60+ GB 4k which took between 90-99% of all the cores.  Before I flatly call out bs, i'd love more information on the machine with which you saw those results, because all the tests I've done aren't really close to that.

**Comment by matmuilwijk** [comment]
Well, I've seen a setup with a few xeons that could do this without
breaking a sweat... Buddy has a full blown server with 8 xeons, and one
with 12, and he does this all the time. A single transcode is handled with
about 4x speed with a 60gb HEVC file to 1080p h264. (on the 8 xeons rig)

**Comment by phaelon74** [comment]
Roger, so it's doable with a system that costs more than most people would ever invest in.  Then again, if we're talkg a multitude of 4k files, the person would have to invest in a good size SAN/NAS too.  For me, it would just rock if Radarr would either leave lower resolution files as it continued to get better resolution ones or if it let me add an item multiple times with different destination/profiles.

**Comment by hotio** [comment]
It was an AMD Ryzen R5 1600, do note that the CPU usage was >90% too, but that what the CPU is for. Played two streams without any stutter, did not test if a 3 would work.

**Comment by Ashkaan** [comment]
Back to the actual issue: a lot of people could benefit from this feature request.

I currently have HUNDREDS of movies in 3x formats: Regular Bluray, HDR Bluray, and 3D Bluray.  I have to manually organize them separately because Plex chokes on HDR and 3D movies.  This feature would solve my current issue by placing the 3D and HDR versions in a folder that is not in my Plex Library.  Is this one really hard to implement?

It would also solve an issue that people are having related to multiple quality levels for a single film.  My iPad just can't play HDR or 3D, so I need a Regular version as well.

**Comment by hotio** [comment]
Are all these people storing multiple versions, using a 10$ unlimited Google account from ebay or are they filthy rich with TB's of HDD space, but to cheap to buy something like Threadripper/Epyc/Xeon?

@Ashkaan It's well known that lots of people would benefit from this, sadly as is with most opensource projects, the people that are actually capable of adding such a feature don't see a need to invest their time implementing it.

If tomorrow somebody very good at C# and with a desire to store multiple versions comes along, a week later a pull request popsup.

This is all done voluntarely and something has to make it worthwhile to invest a lot of time, some bounty program would work, but I doubt anybody is going to take a day of work for a 15$ bounty....

**Comment by matmuilwijk** [comment]
@hotio I wouldn't say that you'll need to be filthy rich to get terabytes of storage locally. I'm currenty in the process of upgrading my server, and planning on putting in 10 TB. With a good search, I can get HDD's at 
0.02eur/GB... That's bloody cheap! And, since a buddy of mine owns a cloudservice datacenter with about 5k racks, I can get datacenter grade drives from him for about 0.03eur/GB....

And, I really think that a lot of users would benefit from such a feature, specially since we still can't get a decent transcode from a 3D file to 2D, and most 3D files are neither DTS/DD5.1, or a high bitrate...

**Comment by phaelon74** [comment]
I purposefully upgraded my SAN to hold multiple copies of my library (720/1080/4k).  I wanted to stay internal to my house as well as utilize 10Gbe speeds.  I spent around $2k to get 24TB of usable space with Raid 6 redundancy.  I'm not a fan of the amount of time it would take to move my 10+TB library into the cloud but at some point I am going to want too, as a backup for my local systems.

At the end of the day, I would very much like this feature to be implemented but I do understand open source changes what gets chosen to be developed.

**Comment by matmuilwijk** [comment]
@phaelon74 'At the end of the day, I would very much like this feature to be implemented but I do understand open source changes what gets chosen to be developed.'

In this case, open source means that this software is being developed for the sake of the developers. There's no money to be earned, and they don't have any obligations to any sort of customers. 

In short, they don't need to listen to our requests, and they don't have to add any features they wouldn't use themselves. ;) It may sound ungratefull, but it's absolutely not! 

The only way we can get features we want, is by developing it ourselves... (And I'm still stuck learning basic Python, so I can't help you either)

**Comment by hotio** [comment]
Radarr has suffered from a reduced activity lately comparing to 6-8 months ago. I'm happy however, it works for my needs and I can work around the little kinks.

A situation like the old sickrage is also not desirable, 100 commits a day, nothing really changed and on occasion it broke. As long as we don't take on the tempo from CouchPotato.

**Comment by mrwebsmith** [comment]
without getting into the back and forth.. +1 to this concept/FR to happen someday.. I'd use it.

**Comment by CBers** [comment]
+1 from me too.

Now that Emby permits the different versions of the same movie in the same folder, having Radarr download multiple versions would be excellent. 

Thanks.

**Comment by Ashkaan** [comment]
I get that devs write for themselves, but it can be beneficial to their careers to write something that more people can appreciate.  The need is here.

**Comment by galli-leo** [comment]
@Ashkaan I also want to use this feature, but it's just not that easy to do. We will have to probably rewrite a lot of Importing, Upgrading, Downloading, etc. to get it working properly.

**Comment by DrDrrae** [comment]
I would just like to put my support for this in as well.  For now, I'm downloading 4k movies manually and importing them so that I can keep both that and 1080p.  It's working, although a manual process, for now.

**Comment by Ashkaan** [comment]
@DrDrrae, the solution to that is to have multiple Radarr instances running.  I'm running:

1x for Mobile Device (up to 2160p, NON-HDR)
1x for TV (up to 2160p, HDR Preferred)
1x for 3D

It's a pain, but it's the best workaround that we have for this problem right now.

**Comment by vr6mole** [comment]
@ashkann, can you run multiple instances of radarr on windows?

**Comment by Ashkaan** [comment]
I don't know.  I use Docker.

**Comment by spaceboy76** [comment]
+1 to this from me

**Comment by vr6mole** [comment]
My temporary workaround is to add my Radarr trash folder as a movie directory in Plex. I just have to make sure the 1080p is made available first before the 4K version is available (which normally occurs). 

Also allows me to save a little bit of space because I can disable file duplication (DrivePool) on the trash folder since I don’t mind losing 1080p versions since they are just for my plex users.

**Comment by distributorofpain** [comment]
+1 i keep my 3d in a different library because most everyone using my plex server doesnt have a 3d tv and i didnt want them accidentally clicking on it.  My solution right now is to just ignore my 3d movie folder.  I have plenty of space if it gets downloaded a second time as a non-3d and i can manually get 3d movies if i really want them.  

Surprised to see people already trying to pull in 4k movies.  I would have to build a new server to handle that.

**Comment by evanrich** [comment]
+1...found this topic by searching google for the same thing.  I keep 4k films in a seperate location from 1080p because some clients can't process HDR content, and plex transcoding to SDR via optimize doesn't convert it to SDR...so I have to keep HDR 4k for home and 1080p for streaming to other users..thus two locations.

**Comment by awawis** [comment]
+1 for this feature. It's not a huge deal, but for some movies (LotR, etc) I'd like to have both the theatrical and extended versions

**Comment by DZMM** [comment]
+1 from me.  Not a huge issue yet for me and at the moment I run a second docker instance, but would be nice to have this support in the future when I have more 4k content

**Comment by galli-leo** [comment]
Locking this topic. Please stop with the +1 comments, there is a reason thumbs up emojis exist

**Comment by Qstick** [comment]
Closing for #1910, same concept
