### ISSUE TITLE
Radarr not using tags from PTP

### ISSUE THREAD

**Issue by schwyl** [Radarr/Radarr#2222]
On PTP each file has some tags used by the site to show what Type the release is. Could this be used so that the Indexer restrictions parse these instead of just the torrent name?

![ptp](https://user-images.githubusercontent.com/2615447/32073831-987027f0-ba54-11e7-8fd1-3deccecc541a.png)

**Comment by weirdcrap** [comment]
I am fairly certain radarr already parses your basic ones from the site. What tags are you wanting to suggest radarr parses in addition to what it already pulls from PTP?

**Comment by schwyl** [comment]
It Kinda does. The example is not the best how ever if under indexer restrictions if i set it to MUST NOT CONTAIN ISO but the torrent file name doesn't say ISO in it then radarr would grab it as a valid realse

**Comment by weirdcrap** [comment]
Oh I understand, ok. I'm not sure how we could parse those if they aren't made part of the file name. Unless there is someway to add exclusions for these tags to the search url radarr submits to PTP?

**Comment by schwyl** [comment]
Honestly I have no Idea if those tags are even available to use but it they were it would be very sweet

**Comment by weirdcrap** [comment]
Have you looked at the advanced section of the search area on PTP? It looks like what you are trying to filter for can be filtered and is made a part of the url. I don't know how much work it would be for Radarr to parse those results. 

The filters don't seem to stack, If I say I want an ISO release, sourced from a DVD, encoded with h.264 I see bluray releases mixed in even though they are not DVDs or ISOs but they are encoded in h264...

So for example here is what my filter set is:
![screen shot 2017-11-12 at 6 20 02 am](https://user-images.githubusercontent.com/22824785/32698877-ac8f8bd4-c771-11e7-93a7-51226c498593.png)

This is what is in the url bar: "torrents.php?action=advanced&encoding=ISO&format=H.264&media=DVD"

But I still get some releases that I feel like don't fit into all of my test criteria: 
![screen shot 2017-11-12 at 6 20 18 am](https://user-images.githubusercontent.com/22824785/32698880-cb89dee0-c771-11e7-8f47-40f2ef57f0d1.png)

**Comment by schwyl** [comment]
Yeah I have no programming ability :)

**Comment by weirdcrap** [comment]
I understand I don't either (besides basic Java) that is why I try to help the devs by at least replying to issues and helping other users.

I was simply letting you know that what you were asking about does seem possible from PTP's end (though it does seem to not be perfect).

**Comment by DirtyCajunRice** [comment]
so im looking at the code... and it looks like yall are getting the response with the Codec from the PTP api here: https://github.com/Radarr/Radarr/blob/806ba7e59d6318bc3af07520d03700f49cdc78d0/src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornApi.cs#L19  but arent keeping it when parsing here: https://github.com/Radarr/Radarr/blob/806ba7e59d6318bc3af07520d03700f49cdc78d0/src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornParser.cs#L92

Since Codec / Resolution / Source / Quality  etc are ensured in the api they could take precidence over the file name and only add whats missing (e.g. the release group) and optionally show warnings for the line items that are "Mismatched" saying "we used api x but file said y"

This would make PTP/HDB smooth as glass within radarr

<3

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.

I _think_ this is handled in v3 now
