### ISSUE TITLE
Preferred tags

### ISSUE THREAD

**Issue by breadcan** [Radarr/Radarr#227]
Couchpotato has preferred tags to push the score. I don't know if and how sonarr sort the results of the findings. Would be nice to push results through "preferred tags".

my preffered tags in CP: "extended, remastered, truehd, dts-hd, hevc, x265, 10bit, atmos, 2160p, dts-x"

**Comment by galli-leo** [comment]
Well 2160p is just Ultra-HD Quality. You can create a profile where you add that. We will take a look at adding prefered tags.

**Comment by piratesam** [comment]
I not suer if it's what You asking for but there are Tags already in Radarr. In advanced view, in indexes at the very end You have Restricion section. There You configure what keyword must be in the title and what cannot be in the title. Then You select a tag for this restriction. You also can add the same tag on Your movie, the effectively through this association this restriction will be applied to Your movie. I.E. results filtering should take it into account.

I'm not sure though if this feature is properly backported from Sonarr.

**Comment by breadcan** [comment]
yes we have tags, but only must or must not have tags. 

I guess it would be better to add the tagging support to the quality definitions and allow custom qualities. 

With this you could for example make a quality for "10bit" which you can put on top of the normal bluray rip so it would download a bluray rip at first but if it finds a 10 bit release it will download it. 

same for "remuxed" + "filesize 20GB and bigger"...

**Comment by galli-leo** [comment]
@breadcan That's actually a good idea. Add the preferred tags to the Qualities.

**Comment by vortexrap** [comment]
+1 for this. Couch potato did this (but it was hit or miss, not to mention it wouldn't pull any results, despite the files being available).

The way CP had it was you could add value / preferred listings, such as prefer certain releases groups (DRONES) or qualities (1080p).

**Comment by Peap0d** [comment]
One of the limitations in this is that it's such a blanket option -- all preferred tags are preferred equally. For example, DTS-HD MA and DTS in the preferred field rates them equally.

Ideally, it would be amazing if each preferred tag was separate and had it's own score, so that each person could set their own ranking system. For example, one person might decide that TrueHD or HD MA audio was twice as important than HEVC/x265 compression for the video, where another person might treat them equally (essentially how it ends up working in CP) and a third might be space constrained and always want the HEVC version regardless of audio quality.

The biggest problem with adding preferred tag directly to qualities is that you quickly get into a multiplication factor where you might have hundreds of options (each video quality multiplied by multiple audio choices multiplied by multiple color depths, multiplied by various editions, multiplied by different codecs, multiplied by different containers, etc.).

**Comment by vortexrap** [comment]
@Peap0d i agree. I liked the granularity of CP in this regard. But it was so convoluted that multiple rules would conflict and affect your snatching (and, for repetition sake, is that CP wouldn't download select releases despite the key words and preferences set properly).

Radarr has the snatching and grabbing down (which is already a huge improvement over CP). If we can implement some of preferential keyword search (with a logical and clear way to monitor and manage), radarr is the holy grail!

**Comment by Forbes256** [comment]
What if the preferred words could be listed rather than comma separated? Top on the list gets the most points, second, and so on. We don't need to see the point values, that's overkill. It could even be done the way qualities are now, to match the look and feel...

List One (Audio)      List Two (Video)
DTS-MA                   UltraHD
DTS                           720p
DD5.1                        1080p
AC3                           Web-DL

If multiple lists could be created (audio, video, custom, etc) then people could pretty easily list their personal preferences for each and have radarr rank accordingly and do it's thing!

**Comment by vortexrap** [comment]
I think this can be achieved in conjunction with custom / editable quality profiles.

Currently, Radarr (and sonarr) don't allow you add custom profiles, and the list is limited to:

![image](https://cloud.githubusercontent.com/assets/15331068/22114605/1c7b6e6e-de38-11e6-8249-565420ece799.png)

I think we can make preferential tag and ranking work and have it integrate with the already existing profile ranking by allow us to specify certain attributes that are required or preferred per profile (we could also have an additional section for global tags).

For example, the standard Bluray-1080p - if there was a way to (maybe a drop down or a separate pop-up window} edit additional wanted fields (audio, video, release group, other, etc.)

You can hide these options by tying this customization under the 'Show/Hide Advanced' and default settings would still be applied.

**Comment by maxcore** [comment]
Required word like : Multi 
i take my releases english and french , you think will be a option  for a futur releases ?

**Comment by galli-leo** [comment]
@vortexrap @breadcan @Peap0d @Forbes256 I am currently thinking about how I should best implement this.
For now I think, I will add those to the profile definition. All Tags will be preferred equally. (But two tags matching should be preferable over one tag.) No visible score system.
I think we should keep this as light as possible or else it's going to confuse more people than help them.

If you have any suggestions on how heavily preferred tags should impact a release, please leave your thoughts here.

**Comment by vortexrap** [comment]
@galli-leo I agree. The place to make this change is inside profiles. So this is the current profile page: 
![image](https://cloud.githubusercontent.com/assets/15331068/22312196/dec47646-e324-11e6-9193-8d9bddbee44c.png)

So based on your idea, we would add and edits tags here? see markup below:
![image](https://cloud.githubusercontent.com/assets/15331068/22312447/debbb9ce-e325-11e6-85c3-7d9b3c71c835.png)

I think its important that we allow users to add tags to a particular quality profile. Because users are not going to be searching for DTS-HD 7.2 surround sound when you select SD or DVD Quality. Users can also make multiple profiles with multiple tags preferences (aka a 'Full Surround Audio Profile'or an 'In Theaters, Hard-coded subs acceptable') and just make the necessary tags inside that profile.

It also leaves the option open for global tags assigned to quality definitions (should we go down that route) since you can make global tag edits somewhere here:

![image](https://cloud.githubusercontent.com/assets/15331068/22312561/5ba8698c-e326-11e6-8605-a8565e2a73a9.png)

**Comment by Peap0d** [comment]
It's very much a tricky one -- I just saw this from reddit:

"Hi there
This project is amazing, so thank you very much for that! :-)
However, there's one thing I really miss: An audio quality filter/profile option. I'm only interested in stuff with DTS (or DTS-HD and so on), but as far as I noticed, there is no possibility to add such a search filter yet.
Are there any plans to implement that in the future?"

I think audio is the big issue. things like x264/x265, HDR, are all good to haves, but ranking them equally as 'preferred' provides a lot of bang for the buck.

Audio isn't normally as big an issue for Sonarr/tv, because bluray rips are generally going to be either DTS or DD (nothing higher because they were mastered for TV), HDTV is always going to be DD, webDLs can often be DD or stereo, but the video options sort of automatically sort them for you.

With movies I (and probably most people) would rather have a 1080p with DTS-HD MA than a 2160p with 2 channel audio for example, and you get this level of variance. Maybe a separate slider just for audio options where you rank your preferences and they automatically get something like half the weight of video preference, so that audio two levels higher gets ranked at the same level as video one level higher and three levels higher would prefer the lower quality video?

Not saying this is the answer, just throwing out an idea to spur further discussion.

**Comment by galli-leo** [comment]
@Peap0d I agree that this a very hard problem to solve. I don't think we will ever get a perfect solution. If DTS-HD is really that important you can just to a quick manual search.

**Comment by Peap0d** [comment]
Equal preferred tags is a huge additional feature for now -- tons of value for less effort.

Somebody's going to have a moment of magic and figure out an elegant solution for this eventually.

**Comment by galli-leo** [comment]
I implemented it in the feature/prefered-words branch. Anyone here care to check it out?
@breadcan @piratesam @vortexrap @Peap0d

**Comment by breadcan** [comment]
Yes, if I don't have to compile it myself.

**Comment by galli-leo** [comment]
@breadcan https://ci.appveyor.com/project/galli-leo/Radarr-usby1/build/artifacts Here you can find the latest build

**Comment by AeonLucid** [comment]
@breadcan To be more specific, you need one of these https://ci.appveyor.com/project/galli-leo/radarr-usby1/build/0.2.0.237-qlkuepqt/artifacts for the feature/prefered-words branch.

**Comment by galli-leo** [comment]
This is in the latest nightly version.

**Comment by Quiksmage** [comment]
Being able to add multiple of qualities would be helpful as well.

For instance, I currently have a cutoff at 1080p bluray.

This likely happens when the first scene bluray releases hit, such as SPARKS.

The problem lies in that radarr stops searching for higher quality releases.

An easy fix to this would the ability to have multiple of the same quality (the ability to add a new quality and define it)

For instance,

1080p-Bluray
preferred words: D-ZON3, BMF, EbP, HiDt, FoRM, CRiSC, HiFi, TayTO, VietHD, ZQ

1080p-Bluray
preferred words: (empty)

This way it gets 1080p BluRay, but continues searching until it gets a release with the preferred word in it. I guess at that point, it would be a quality with required words. Let me know if oyu have any questions about this :D. Thanks,

**Comment by galli-leo** [comment]
@Quiksmage If you can wait, you can set a delay profile for e.g. 24 hours. Then a movie without preferred words will only be added if a better version is not found within this timespan.

**Comment by vertigo235** [comment]
Yes I use a delay profile and it works pretty well, but sometimes the more preferred releases are not released as quickly. 

However, I also understand the effort that would be needed to do as requested above, quality profiles are not dynamic but static and can not be changed / edited easily.

**Comment by Quiksmage** [comment]
I see, and that delay profile option should work for the most part (albeit, I'd prefer not to wait). If there's no intention to add what I mentioned, I completely understand. It may be too time consuming for something a majority of people may not even need or consider. Thanks for taking the time to read it.

**Comment by galli-leo** [comment]
@Quiksmage I can't guarantue you that it will be added. It's definitely something a few people would like. But it's not a pressing feature. I think we would probably implement such a thing differently and blow out the whole quality profile thing.

**Comment by bott0r** [comment]
id like a preferred tag,  just like there are multiple releases prefer release with tag "tag"

**Comment by HeroCC** [comment]
Would there be any chance of backporting this to Sonarr? Relevant issue: https://github.com/Sonarr/Sonarr/issues/385. This is a great feature of Radarr and I'd love to see it make its way back upstream

**Comment by vertigo235** [comment]
Zero chance, the sonarr devs have their own plans to fix his problem and they will do it in their own time.

**Comment by harrv** [comment]
@galli-leo You closed this a year ago and said it was implemented in the nightly build at the time. I'm on the latest develop build and I don't see preferred tags/words implemented anywhere. All I can see are global restrictions at the bottom of the Indexers settings page, where all releases MUST CONTAIN certain words or MUST NOT CONTAIN certain words. Since you closed this issue and said it was implemented, could you point me to where preferred tags/words can be configured? I may just not know where to look.

Let me give you my use case. There are a couple release groups that do low bitrate encodes, and those releases typically include the keyword "yify" or "999mb". Most of the time, I'd like to avoid those. However, I don't want to globally ban releases with those keywords, because there are a number of old movies that I haven't been able to locate yet, and if one of those becomes available I want to get it even if it has one of those keywords. So, I'd *prefer* releases without those keywords, but don't want to exclude them if they are the only ones available for movies that had a physical release more than a few weeks ago.

I do use different quality profiles for upcoming movies that I expect to be released on Blu-ray, vs old movies that came out long ago and I haven't been able to locate them. So, even if the "prefer releases with tags..." and "prefer releases without tags..." thing was not implemented, I could still make this use case work if I had a way of setting required-to-have/required-to-not-have per quality profile. (I would set my blu-ray profile to require releases to NOT have "yify" and "999mb" and leave that restriction off of my hard-to-find profile).

If the required-to-have/required-to-not-have keyword restriction thing remains a global setting, then it really needs two additional sets of keywords: preferred-to-have and preferred-to-not-have.

For this particular use case, I know that another option is to set a minimum size in the quality settings that would exclude movies with low bitrates. But I find those settings to be quite arbitrary, because they don't take the length of the movie into account. I download quite a few shorts, and setting minimum file sizes would block those.

Thanks for any help or guidance you could give. A working suggestion for how to handle the use case I've presented would be nice, but if you don't have time for that I'll settle for a pointer to what specifically you changed before you closed this issue so I can try to figure out what was done and how it works. Thanks.

**Comment by harrv** [comment]
OK, I found where preferred tags was implemented: in the quality profiles. Sorry about not seeing that before. However, it still doesn't help me with my use case, since I want to prefer releases that DON'T have a particular tag. And the require-to-have and require-to-not-have tag feature is still global.

**Comment by vortexrap** [comment]
Since this issue is specifically for preferred tags and you are looking for a blacklist option, I suggest opening a separate issue.

**Comment by vortexrap** [comment]
Since this issue is specifically for preferred tags and you are looking for a blacklist option, I suggest opening a separate issue.

**Comment by harrv** [comment]
@vortexrap Yeah, I commented here because I was having a hard time finding where preferred tags had been implemented, and I didn't know whether what had already been done would help with the use case I had in mind. Now that I know what was implemented for this issue, I'll either create a new issue to suggest changes that would make this feature more flexible, or I'll implement it myself and create a pull request.

**Comment by galli-leo** [comment]
@harrv See this issue: #2433 and the attached document by me. This would probably allow your use case. For the time being, you can make the restrictions only apply to certain tags. This way you can tag  old movies differently than new movies and certains stuff will be or won't be excluded.

**Comment by harrv** [comment]
@galli-leo Thanks. Knowing that you plan on re-working the quality settings and how tags interact with it, I'll look forward to what you do there, and in the meantime I think you've given me a good workaround. I'd forgotten that more than one entry can be added in the restrictions settings and applied via tags. I agree that should work for my use case.
