### ISSUE TITLE
[Features]

### ISSUE THREAD

**Issue by PeterFragon** [Radarr/Radarr#2307]
1. Need the ability to add specific movie directories (multiple) that can be set to scan periodically (importing 2K plus movies manually did not work great)
2. Need to be able to bulk edit profile settings for all movies, bulk imported movies etc.
3. Need to be able to set/toggle auto un monitor movies that meet cutoff criteria. 
4. Identify movies with duplicate/more than one video file  as a clean up process.
5. Movies replaced to meet cutoff auto deleted? 

-Side note this already working way better than CP in many ways..

**Comment by galli-leo** [comment]
3. Is unnecessary. Movies that have a cutoff unmet will not receive any more downloads, except there are propers or repacks.
4. Plex is much more suited for that

Not sure what you mean by 5.

You can already do 2. via the Movie Editor.

1. Will probably not happen, because it will be very hard to determine mismatches afterwards
