### ISSUE TITLE
Help needed for a newbie

### ISSUE THREAD

**Issue by Morphious01** [Radarr/Radarr#2316]
I am new to the radarr setup after a recommendation from a friend.
I have it set up so all is going well with adding movies from search and nzb's and just ventured into the RSS lists.
This has me stumped after numerous google searches.
I have added the RSS feed in from my indexer and all is good when i tested the url.
My issue is all movies on the RSS feed then download whether I want them or not. I thought that it would only check the RSS feed for my watched movies. 
I have seen the auto sync and add movies sliders but the info for both shows they add the contents of the list. Am I doing something wrong?

Thanks guys

**Comment by hotio** [comment]
You are adding a list that tells radarr to add movies to your wanted list.... so it's expected that they are being downloaded, unless you add them unmonitored.

**Comment by matmuilwijk** [comment]
I think you misunderstand the RSS-parts.

There's 2 things you can use RSS for in Radarr. First is the 'Lists', where you can use RSS-feeds (and other things like Trakt-lists) to automatically add Movies to Radarr. With these lists you can either decide to add them Monitored or not, and to Autosync these lists, or not.

The second is the Indexers. Radarr by defaults checks the RSS-feeds of the Indexers that you've set up. This feed contains all the posts/items that are added to such indexer in the time-frame that the feed covers. This RSS-instance is used for downloading movies, instead of adding like with Lists. This RSS-instance prevents Radarr from having to search every indexer regularly for releases, since this uses either much more local resources, and more server-side resources. (Running a server isn't cheap, and every bit of traffic simply adds to the costs)

To finish, may i make a little suggestion (assuming you're using torrents)? You can use a piece of software called [Jackett](https://github.com/Jackett/Jackett) to add additional trackers to Radarr with the Torznab-indexer. This way you'll be able to add more Torrent-indexers to Radarr, with the ability to search as well.
