### ISSUE TITLE
Settings page keeps loading

### ISSUE THREAD

**Issue by RolandGoud** [Radarr/Radarr#2439]
**Description:**
I can't get to the settings, beacause it just keeps loading. All of the tabs are unresponsive. (loading animation is showing)

Version
0.2.0.870

**Logs:**
[log.txt](https://github.com/Radarr/Radarr/files/1649731/log.txt)

**Comment by galli-leo** [comment]
Your database seems corrupt, try using a backup or upgrading your Radarr version.

**Comment by RolandGoud** [comment]
was on .910 had the same issue. Don't have a back-up (was a clean install)

How can i delete the full install (including the db)

**Comment by RolandGoud** [comment]
Uninstalling via windows return a missing unins000.exe error

**Comment by elrock** [comment]
I installed Radarr version 0.2.0.910 on Debian 9 today and am experiencing this same problem. I haven't even managed to import my video files. Is there a way to change settings via a configuration file instead?
Hope you will see this issue even thought it's been closed, because it's preventing me from using Radarr.
