### ISSUE TITLE
[Bug] Movie rename causes high CPU

### ISSUE THREAD

**Issue by Buster14** [Radarr/Radarr#2450]
**Radarr Version:** 0.2.0.910

**Logs:** 
[radarrbug.txt](https://github.com/Radarr/Radarr/files/1669611/radarrbug.txt)

Im not sure whats the case but radarr occasionally pops up rename failed notification multiple times, causing high cpu. 
I have disabled all movie renaming options, but it still persists.

https://imgur.com/asjQp7T

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
Radarr isn't doing any actual renaming, it's just looking whether the folder should be renamed or not (you have turned it off, so it doesn't do anything) and then succeeds with that message. Also everything seems to look normal with the logs. What kind of system do you have (cpu and ram wise)? because 24% cpu while refreshing movies doesn't seem that abnormal.

**Comment by Buster14** [comment]
It's an i3 4130 with 16gb ram, win server 2012

**Comment by galli-leo** [comment]
Yeah this seems like a normal cpu usage with such a weak cpu. The notifications are fixed in the latest version too, so this may free up some cpu.
