### ISSUE TITLE
API: Make movie endpoint searchable

### ISSUE THREAD

**Issue by pannal** [Radarr/Radarr#2490]
Currently Sub-Zero has to iterate throught the full response of the movie endpoint, which consists of all movies in the library. This is a potential performance hit on both sides.

Could you add some kind of filtering method for the movie endpoint? Filtering/searching by `path`, `relativePath` would be awesome.

**Comment by galli-leo** [comment]
Probably not since we don't need that. Feel free to implement it though, I am happy to accept prs.

**Comment by pannal** [comment]
That's a very compelling argument to make when talking about a public API.

**Comment by galli-leo** [comment]
The API is only public as a side effect. It's main purpose is to power the WebUI. So unless the WebUI needs it, probably not gonna implement it, since I have 118 other feature requests also waiting to be implemented. Also iterating through the full movie response isn't that bad. Even if you have 40k movies that will probably take 100ms in python at most. (And most users have between 500-2000 movies, not 40k). The actual request will take at most (with 40k movies) 15s. If you do some intelligent caching (i.e. only request the endpoint again, when you can't find the movie) it shouldn't be a problem.
