### ISSUE TITLE
Enable to force-download anime movies for "[Release Group] Movie Name" format

### ISSUE THREAD

**Issue by enchained** [Radarr/Radarr#2496]
I managed to attach Jackett's Nyaa.si to Radarr and after adjusting indexer settings it finally showed me manual search results for a movie. However, most results are starting with the [Release Group], and there goes the error "Failed to find movie title in release name".

Can current regexps be adjusted so they'll support this naming format too? I think sonarr does that with anime series, so there should be a known solution.
Can at least force-download button be enabled for results with such error? Or, can it be an option of the indexer? "Allow force-download for "Failed to find movie title in release name" error".

**Comment by galli-leo** [comment]
They cannot, since your title has to either contain a year or language tag after the movie title. How is Radarr supposed to find out where the Movie Title ends and where other tags start? So we cannot add force download, since Radarr wouldn't recognize the file afterwards anyways and you would have to manually import it anyways.

**Comment by guyyst** [comment]
Wouldn’t it still make sense to add a force download option, and maybe warn about having to import the movie manually?

As it stands right now the only workaround I have is to manually go to the indexer, copy the magnet and enter it into my client.

Radar could at least take over those steps and allow me to import it manually later on. At least I wouldn’t have to interact with my download client directly.

**Comment by Qstick** [comment]
It's in V2
