### ISSUE TITLE
Radarr deleting existing .nfo files

### ISSUE THREAD

**Issue by tusharbhutt** [Radarr/Radarr#2547]
I have Radarr set up to upgrade movies, but not for metadata.  As a result, when it does upgrade a movie for me, it deletes the existing .nfo files.  

I do not want to use the metadata setting in Radarr because I use meta\<browser\> for that due to greater interactivity.  Is there a setting I am missing or is this a bug?  I had a look at the metadata and media management tabs and nothing obvious jumps out.

This issue only started about a week or so ago and I am on the nightly builds so I am guessing it started around version 0.2.0.961, currently I am on 0.2.0.972.

Thanks.

**Comment by galli-leo** [comment]
@Qstick Here's your issue :P

**Comment by Qstick** [comment]
Had to be something lol. I'll jump on it tonight

**Comment by Qstick** [comment]
@tusharbhutt do you have logs of the upgrade?

**Comment by Taloth** [comment]
Can I invite you guys for some collaboration? https://github.com/Sonarr/Sonarr/issues/2398

Please note that this scenario, as the one with OP, where kodi metadata is actually disabled isn't in the Sonarr issue, but I feel it all has it's roots in the same problem.
I wonder if the nuked .nfo files are scene nfos or kodi nfos.

**Comment by galli-leo** [comment]
@Taloth Sure! Though not sure how helpful we will be, since we probably also need to add some checks for dynamic paths.

**Comment by tusharbhutt** [comment]
Damn it, not sure how I closed this, so sorry :(

**Comment by tusharbhutt** [comment]
@Taloth the nuked .nfo files are from <meta>browser, to be used by Kodi.  When movie upgrades are being done now by Radarr, everything in the folder is wiped out, not just the .nfo.  That includes posters, backdrops, etc.

**Comment by Qstick** [comment]
@tusharbhutt @galli-leo I believe this is the intended behavior (at least in sonarr). https://github.com/Sonarr/Sonarr/issues/756. Basically since we are associating nfo files with movie files it’s wiping them as it wipes the movie file to avoid false info reporting for the new incoming movie file.

**Comment by tusharbhutt** [comment]
@qstick Unfortunately, that also wipes out things like date of import and watched status in the .nfo files, as well as the custom tags.  If I don't have metadata management on, i'd prefer for this not to happen.  Also, even if it's the .nfo file that kind of makes sense to remove, why is the poster and other imagery also being removed?

**Comment by Qstick** [comment]
Yea, I'm not saying its ideal for Radarr. As @Taloth mentions in the Sonarr issue, nfo handling could be better. Currently the way extras are implemented all metadata files are associated with movie files (not simply the movie itself). Becuase of this when the MovieFileDeletedEvent gets triggered the ExtraFileService wipes out all associated extra files in the db (Images and Metadata). I would agree with you that this is not ideal, however it mimics how episode images and metadata are implemented in Sonarr. 

This is likely done for the few reasons:

- If we create the nfo we are including video file info for the movie, thus its specific to that movie file.
- The nfo file name matches the moviefile name for kodi images, thus if {quality} is in the name the file must either be renamed or deleted and re-created for the new upgraded file.

A few options I can think of:

1. We have separate metadata file types for Movie Images, Movie Metadata, and MovieFile Metadata. The issue here being that Kodi/others will only read in one of the two metadata files if you did have both turned on. Thus we should limit to one or the other. Also this gets confusing for the user.

2. We implement some type of logic to associate/not associate metadata/images with file.  (I already have an option put in the Kodi metadata generation settings to "use `movie.nfo` instead of `<filename>.nfo`", maybe do the same for images?) and then only associate the file with the moviefile if the name of the file matches the name of the movie file. [ex. `SomeMovie[2018]-poster.jpg` or `SomeMovie[2018].nfo` would be associated with the movie file, but `Poster.jpg` or `movie.nfo` would not and thus wouldn't be deleted on movie file deletion].

Additionlly we take it further as @Taloth mentions and read the nfo to determine if its actually a metadata file or just an other extra file (scene nfo) which would be treated differently as a `.nfo-orig`

Any other thoughts?

**Comment by Taloth** [comment]
tusharbhutt, what behavior are you expecting? Considering that kodi nfo files contain details about the specific video file and not just the episode, leaving the files in place would create inconsistencies, or the app would leave em behind during normal deletions and people would complain about it ("I deleted an episode and Sonarr didn't delete these extra files!").
And as mentioned, the filenames could be different.
I'm looking for a solution that makes everybody happy.

The scenario is a bit different than I expected, I thought it would be scene .nfo files.

**Comment by tusharbhutt** [comment]
@Taloth Hi, thanks for replying.  I get the idea of upgrading video files and so on, but if I have metadata scraping in Radarr completely off, I'd expect the system to leave the .nfo file alone, or at the worst, perhaps just rename it to match the video.  I would not expect it to delete poster and background images, some of which were collected by me outside of the program  years ago.

I'm certainly not bashing the program, I just don't want it deleting the old .nfo files unless I explicitly give it permission to touch my metadata, which I have not done.  If the program can save the old video file via the option to moving it to another folder instead of deleting it, maybe it can do that for the.nfo and the .jpg files too.  

Interestingly enough, this evening when I got back form work, I see three video files in the "recycling bin" folder that I've pointed Radarr to, but only two sets of images.

**Comment by Qstick** [comment]
@tusharbhutt do you have import extra files enabled under media management settings?

**Comment by hikaricore** [comment]
Any progress on this? I've noticed Radarr retroactively going through and deleting scene nfo (folder.jpg/fanart.jpg are disappearing from time to time as well, but this may be unrelated to this specific bug) files in a number of instances when it's adding a movie.nfo file. In the case that the scene nfo was renamed to nfo-orig, IE Radarr handled the download and import of files and I didn't do it manually, these are left alone. Logically even in a case where metadata handling is done, these files should either be renamed nfo-orig, or moved to the recycle bin. That would alleviate any of the aforementioned conflicts which have been brought up. From the sounds of it though, this is happening even with metadata handling off, which i even more concerning.

For anyone who needs them. Most scene NFO files can be obtained here: https://www.srrdb.com/

**Comment by Taloth** [comment]
@hikaricore For Sonarr it'll be next on my list, since that mono 5.10 debacle is now behind us. But the problem you reported to me (and the one i'll be fixing) is a bit different than OPs since OP wants to preserve kodi .nfo files between episode updates.

**Comment by ben516209** [comment]
Same problem here.

I've been using Radarr to upgrade a bunch of movies from 1080p to 4k. Unfortunately, when the new 4k movie file is copied every other file in the directory is deleted.

For .nfo files I don't mind so much, but I have some custom posters and subtitle files that I use with Plex that have also been deleted.

An option to just copy the movie file and leave other files in place would be ideal.

Thanks for all your work on this fantastic product. So far, this is the only problem I've had with Radarr.

**Comment by Taloth** [comment]
@galli-leo FYI, we haven't actually released the nfo-detector merge to develop. It was merged but the CI build failed due to other reasons. Meaning it hasn't been tested in a production setup yet.

**Comment by galli-leo** [comment]
@Taloth Well consider this your test in production :P

**Comment by John-Gee** [comment]
Hello,

I still see all files being removed when radarr updates a movie.
Is there any option I've missed to not have that issue?

Thanks!
