### ISSUE TITLE
Searching by title with special chars is not optimal for some indexers

### ISSUE THREAD

**Issue by MateEke** [Radarr/Radarr#2565]
**Description:**
Radarr search with "megjoett apuci 2" instead of "megjött apuci 2".
For the "oe" version no release found, with the "ö" search string there would be 5 releases on hungarian tracker.

Another problem is that radarr uses "daddy s home 2", if radarr would use "daddys home 2" too there would be 7 more releases.

**Radarr Version:**
0.2.0.980

**Mono Version:**
5.8.0.108

**Debug Logs:**
```
Feb 21 20:08:51 *** mono[613]: [Info] NzbSearchService: Searching 2 indexers for [Megjött apuci 2]
Feb 21 20:08:56 *** mono[613]: [Info] DownloadDecisionMaker: Processing 7 releases
Feb 21 20:08:56 *** mono[613]: [Info] AcceptableSizeSpecification: [tt5657846][Megjött apuci 2 (2017)] has no runtime information using median movie runtime of 110 minutes.
````

Jackett log:
```
02-21 20:08:52 Info Found 6 (0 new) releases from ***
02-21 20:08:54 Info Found 1 releases from *** for: daddy s home 2
02-21 20:08:56 Info Found 0 releases from *** for: megjoett apuci 2
```

**Comment by galli-leo** [comment]
Do you have the same releases with daddy home 2?
Also not sure what we can do about megjoett since for german, we don't get any releases if we search with megjött.

**Comment by MateEke** [comment]
"daddy home 2" seems fine for all "Daddy's Home 2" and "Daddys.Home.2" formats.

For "megjoett" could you use "megjött" and "megjoett" together? A plus query wouldn't hurt anyone. Maybe this stands for "ü" as well, but I haven't tested it. 

BTW in most cases the english query is enough for my favourite hungarian tracker, but with this title none of the search strings is good, since the english format on the site is  "Daddys.Home.2" and the hungarian format is "Megjött Apuci 2".

**Comment by galli-leo** [comment]
Yeah, but that would increase the time it takes for searches, especially if a movie has a lot of alt titles. I can look into replacing word's with word instead of word s

**Comment by MateEke** [comment]
> Yeah, but that would increase the time it takes for searches, especially if a movie has a lot of alt titles.

I think that not finding releases is a bigger problem than finding them a bit slowly.
There are other solutions:
- per language preferences
- personal settings for this kind of substitutions - maybe a toggle switch is enough

But the most simple solution is one more query without modifying the original query.

> I can look into replacing word's with word instead of word s

Thank you, I hope this will help.

**Comment by Diablobait** [comment]
And let us put the search name manually? To fix when we have this problem

**Comment by galli-leo** [comment]
@Diablobait Letting the user set the search name manually for each movie defeats the purpose of Radarr. Also when I get time to work on this, I would rather do a good solution from the start.

Something along the lines in your second comment is what I had in mind.

**Comment by mikl0s** [comment]
Radarr searches for "world s fastest indian 2005" which yields no results - remove the space between the world and s yields all the right results.

Perhaps remove the '  instead of replacing it with a space would help indexers.

**Comment by galli-leo** [comment]
@mikl0s See my comment above.

**Comment by celeroll** [comment]
In wiki it said that I should paste here my issue.
I have received this log:
[https://pastebin.com/RqcrNtiA](https://pastebin.com/RqcrNtiA).
I wanted to search for a movie Salt 2010.
Result came from limetorrents.
[https://www.limetorrents.info/--Salt-2010-Director%20s-Cut-2in1-BD1080P-X264-DTS-HD-MA-5-1-Mandarin%20English-CHS-ENG-Mp4BaFans-torrent-10759346.html](https://www.limetorrents.info/--Salt-2010-Director%20s-Cut-2in1-BD1080P-X264-DTS-HD-MA-5-1-Mandarin%20English-CHS-ENG-Mp4BaFans-torrent-10759346.html).
Maybe the issue here is "&" in the name?

**Comment by malventano** [comment]
Observing the behavior of searching a special character title such as Amélie suggests that the substitution method @Diablobait alluded to might be the right way to go since other media tools such as Plex will return Amélie as a result when 'amelie' is typed into search. It doesn't have to be a permanent substitution per language or title, but special character titles should also be accompanied by a standard character set version for the purpose of searches. This should cause minimal impact on search speed as you are only adding a duplicate entry for those titles that would benefit from it. Search engines typically strip (convert to standard) special characters from their search database for uniformity and then also treat special characters in the search query as their standard equivalents.
I've also noted that special character titles introduce issues with quality parsing (a title such as 'Le.Fabuleux.Destin.dAmelie.Poulain.2001.1080p.BluRay.DTS.x264-CtrlHD' is reported as a quality of 'unknown' even though all required information is present). This occurs even if the file is renamed to be preceded by 'Amélie (2001) '.

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.
