### ISSUE TITLE
Organize & Rename Move

### ISSUE THREAD

**Issue by fuuss** [Radarr/Radarr#2606]
I use 2 Path to store my movies . /kids_movies /movies
It would be very interesting to have the possibility to move the file from movies to kids_movies in the Organize and Rename Panel .

**Comment by fryfrog** [comment]
I'd be super surprised if there isn't already a feature request for that either here in issues or on https://feathub.com/Radarr/Radarr. Can you give a search and see if you can find it? If you do, close this and upvote the existing one.

**Comment by fryfrog** [comment]
I do the same thing and *occasionally* accidentally put a normal movie in the kids section (or the reverse). Fixing them is a mildly annoying manual process!

**Comment by fuuss** [comment]
@ Fryfro , I searched but could not find any request of this feature , even if it sound that simple.  Maybe I'm to stupid to find anything or there is no request

**Comment by Smaleee** [comment]
+1 here !!! I've just freed up some dic space by doing a batch of 250'ish manually because I couldn't work out any other way to do it? It took forever to delete them from Radarr whilst retaining the files, moving the files to their new locations and then re-adding them to Radarr in that new location!!! There has to be a better way, right! Radarr's Bulk add wont work as it sees them as probably duplicates until the originals have been deleted. FYI. Plex then sorted itself out with all the changes without any user input but it did re-download all the Meta and I then had to empty the trashed originals so still not ideal!

**Comment by fryfrog** [comment]
I believe you, your request doesn't seem vaguely familiar like most that already have feature requests.

**Comment by Ashkaan** [comment]
Sonarr (v3) does this right now. Is this on the roadmap?

**Comment by ta264** [comment]
This is done in v3
