### ISSUE TITLE
Can't update to latest 0.2.0.995 ?

### ISSUE THREAD

**Issue by Smaleee** [Radarr/Radarr#2623]
Would my current problem be related to a forthcoming fix? I cant find anything here that directly relates, hope you can help!
![screen shot 2018-03-10 at 16 17 49](https://user-images.githubusercontent.com/34604361/37244339-900418ca-247f-11e8-96ac-079225e52d58.png)
![screen shot 2018-03-10 at 16 13 26](https://user-images.githubusercontent.com/34604361/37244340-92eb9aa4-247f-11e8-9ed6-6b688f0a8136.png)
![screen shot 2018-03-10 at 16 15 23](https://user-images.githubusercontent.com/34604361/37244342-98db5eae-247f-11e8-8b05-1b598c294516.png)
![screen shot 2018-03-10 at 16 11 44](https://user-images.githubusercontent.com/34604361/37244345-9ceb506c-247f-11e8-9844-594f17c90268.png)
![screen shot 2018-03-10 at 16 12 25](https://user-images.githubusercontent.com/34604361/37244346-9fbaf9aa-247f-11e8-82ef-e5183313cd7f.png)

**Comment by eriji** [comment]
I'm seeing the same problem.  Radarr on Qnap.  Has been happening since the problem with the radarr.video website problem in the last weeks.

Version 0.2.0.980
Mono Version  4.6.2 (Stable 4.6.2.7/08fd525 mercredi 23 novembre 2016, 17:45:54 (UTC+0100))
AppData directory /share/CACHEDEV1_DATA/.qpkg/Radarr/Home/.config/Radarr
Startup directory /share/CACHEDEV1_DATA/.qpkg/Radarr/Radarr


CommandExecutor | Error occurred while executing task ApplicationUpdate: Error: SecureChannelFailure (The authentication or decryption has failed.) | 11:53
-- | -- | --
  | HttpClient | Failed to get response from: https://github.com/Radarr/Radarr/releases/download/v0.2.0.995/Radarr.develop.0.2.0.995.linux.tar.gz Error: SecureChannelFailure (The authentication or decryption has failed.) | 11:53
  | InstallUpdateService | Downloading update 0.2.0.995

**Comment by galli-leo** [comment]
You need to update mono to 5.8 search closed issues to find out why.

**Comment by eriji** [comment]
Thank You

**Comment by Smaleee** [comment]
Sweet, mono 5.8, radar .995, then mono 5.10, all sorted, thank you!
Quick question, .995 is now eventually updating file dates but... your update suggested you'd fixed a pre-1970 exception...
These file dates **have just been created** with .995 doing a library update...
Should these dates be changed to the actual correct dates now?
![screen shot 2018-03-10 at 20 32 24](https://user-images.githubusercontent.com/34604361/37246535-a3d7fa24-24a2-11e8-96d0-e7ad240b4aec.png)

**Comment by galli-leo** [comment]
@Smaleee Apparently you cannot set the file date before 1970 with mono, so I just set it to the earliest date we can without raising an exception. If you look at the original issue, you can see that this was the proposed solution
