### ISSUE TITLE
Failed Update

### ISSUE THREAD

**Issue by darrenclimienewman** [Radarr/Radarr#2638]
Hi Leonardo,

I'm aware people are having issues updating to the latest version, due to changes I believe in Mono.

Before you just close this as a duplicate thread, please can you help me.

I'm currently running Radarr 0.2.0.910 on a QNAP TS453A, and was running QMono 5.10.0.140, which is when I first encountered the issue.

I've downloaded QMono 5.4.1.6.0 and installed this version, and still get the same issue.

PLEASE can you advise on what I need to do, to get Radarr up to 0.2.0.995?

Thanks
Darren

**Comment by galli-leo** [comment]
Easiest would be if you have a qnap package which you can update for Radarr, but AFAIK there isn't an updated one. What's the exact issue you are having (i.e. whats the exception)?  5.4 should work.

Btw. just because a threads closed, doesn't mean you can't comment. So still closing this as a duplicate. And for the future, I would recommend going to the discord for support, since a lot of people are there that can help you. (Bot will have links for support requests).
