### ISSUE TITLE
Cannot setup Radarr on Qnap

### ISSUE THREAD

**Issue by Chacarous** [Radarr/Radarr#2723]
Hi guys, quick one - i've just installed Qmono and Radarr on my Qnap 459 Pro+ but it's not allowing me to access or setup via <ip>:7878.  I'm sure it's something simple, please can someone who has done this point me in the right direction?  Thanks.

Radarr version: 0.2.0.995
Qmono: 5.10.0.160

**Comment by SHIbT** [comment]
I just had the same issue on my TS-253B I attempted to start via /etc/init.d  to be told QMono was not installed I removed and reinstalled QMono Radarr started and web access was fine.

Hope this helps

**Comment by crhammock** [comment]
I am running those exact versions (according to App Center) on my QNAP and it is running fine.  Sorry if this is a stupid question but are you trying to access using http://{ipaddress}:7878 or https://{ipaddress}:7878.  I am not sure what the default is but try both (think the default is http).  Might also be worth installing and trying Sonarr as this might help identify if the issue is with qmono installation or radarr.  Before that though try stopping the qmono and radarr apps from the App Center, make sure qmono is started completely before you start radarr.

Can you confirm the page error you are getting?  Are you getting a page no displayed error or does it appear to load some page (like a black background) and then get stuck.

**Comment by Chacarous** [comment]
Thanks for your replies, i reinstalled Qmono, Sonarr and Radarr and all working now.
