### ISSUE TITLE
issue with radarr not finding desired result

### ISSUE THREAD

**Issue by aniel300** [Radarr/Radarr#2753]
i have this issue where radarr wont find tigole result yet if i do it manually on jackett it does find it. any help is appreciated

radarr version: v0.2.0.1067
jackett version: v0.8.929

proof: https://imgur.com/a/xOsuTgT

**Comment by galli-leo** [comment]
Not sure what tigole is, make sure the releases are correctly tagged with the imdbid on the indexer.

**Comment by aniel300** [comment]
Reddit post [here](https://www.reddit.com/r/radarr/comments/8gnq4f/this_is_driving_me_crazy/)

**Comment by tcheronneau** [comment]
Hi there,

I think it's more than one problem since I'm having the same issue but with an other indexer. 
I've checked all categories and everything is fine. 
If I'm doing jackett manual I'm having 10 results for example but in radarr I'm only seeing one. 

For me no matter what's your configuration in Radarr preferences it should show everything and filter after. But maybe I'm wrong..

**Comment by galli-leo** [comment]
See https://github.com/Radarr/Radarr/wiki/Common-Problems#jackett-shows-more-results-than-radarr-when-manually-searching
