### ISSUE TITLE
Downloaded Movies Scan task set to disabled

### ISSUE THREAD

**Issue by twistabledeer** [Radarr/Radarr#2812]
Hi all,

It appears that my Downloaded Movies Scan task is set to disable so that seems to be affecting how Radarr is importing my movies from my download's folder. I am not using any Drone factory and I am not seeing any errors in the logs but I have attached them to make sure I didn't miss anything. Does anyone have any ideas?

Thanks

<img width="1447" alt="screen shot 2018-05-28 at 2 58 55 pm" src="https://user-images.githubusercontent.com/8947683/40626648-f2e0d938-6287-11e8-957c-6e8ec77c7bc8.png">
[radarr.txt](https://github.com/Radarr/Radarr/files/2045949/radarr.txt)

**Comment by hotio** [comment]
It's disabled for just about everybody I think, it certainly is for me.

I would start with configuring radarr, because the path `C:\Volumes\Untitled\Movies\` does not exist. Also try renaming your files to include the quality.

Al these questions can be asked on the discord or reddit, github is not the place for personal configuration support.

**Comment by Qstick** [comment]
That is only for Drone folder, and thus will be disabled when drone interval is set to 0:
![image](https://user-images.githubusercontent.com/376117/42547622-21e81f22-8491-11e8-8154-bc20ed0a9001.png)

Importing will still happen by use of completed download handling between Radarr and your client. (make sure its enabled)
