### ISSUE TITLE
Flush database

### ISSUE THREAD

**Issue by mattstorey001** [Radarr/Radarr#2827]
A task to flush/clear/clear the database.

I regularly run out of space and have to shift movies around to make some space. If shifting 100 random movies from one drive to another it would be nice for Radarr to flush/clean/clear the database out so i can re-add cleanly, or as part of the task have it automatically search selected folders and auto-re-add?

At the moment i am moving files and then Radarr is having a meltdown on a disk scan and subsequently believes that the file is gone so grabs new copies to the download queue.

**Comment by hotio** [comment]
You could start by cofiguring Radarr `Ignore Deleted Movies`, they'll get unmonitored instead of missing. Afterwards you can update the paths.

If you really wanna flush the database you can always do `rm /path/to/radarr/nzbdrone.db`

But in all honesty if you have to keep juggling files around, you're doing it wrong.

**Comment by mattstorey001** [comment]
What do you mean i am doing it wrong re. juggling files? How i can change and improve?
