### ISSUE TITLE
FEATURE: Bulk import from read-only location

### ISSUE THREAD

**Issue by jj-uk** [Radarr/Radarr#2852]
There is no good reason why Radarr needs writable permissions to my ripped DVD and BlueRay collection. 
I do not want them modified.
I would simply like to import them to Radarr.

Radarr can have writable access to files Radarr downloads, and that is all.

**Comment by hotio** [comment]
There is no good reason to add your ripped dvd and bluray collection to Radarr.

**Comment by jj-uk** [comment]
I add my rips because it prevents radarr from downloading duplicates either added directly in radarr, via tmdb lists or with 3rd party 'add to radarr' apps that can all be used by multiple users that I share my plex media server with.

**Comment by hotio** [comment]
Add them unmonitored

**Comment by jj-uk** [comment]
They can't be added because the folder is read-only and radarr rejects read-only locations.

**Comment by hotio** [comment]
Yes obviously, but just give radarr a temporary writable location with dummy data, that looks like your library, but isn't.

**Comment by fryfrog** [comment]
And turn on recycle bin to be super safe. Also, why *wouldn't* you want to upgrade your ripped DVD collection?

**Comment by kennethx** [comment]
Well, it can be a shared file location where you CAN'T give radarr WRITE access, but you have read access to the files and thus have them in your library and want to add them to prevent radarr downloading duplicates of these files. 

Like previously states radarr flat out denies importing form a read only location, and this is very much a valid use case denied.

**Comment by kennethx** [comment]
As a curiosity I did a very simple hack to TEST importing from readonly folders.

I imported 400 Movies from a readonly folder as monitor:false, without any issues at all!

https://github.com/kennethx/Radarr_ReadOnlyHack/commit/ff9ac9c87c82f81e40b79097f2fb656b8b1755ab

Ofcourse this is not job done by far. It still need to know of folders are really readonly or not, and it should base the available options for monitor based on folder writability. So a read only folder should only have the monitor option false, while a read and write folder can have both true and false like normal.

Point is...it works perfectly fine! There is no reason for an absolute requirement for folders to be writable! Just a little bit of coding need to fix this.

**Comment by jj-uk** [comment]
Also radarr should check that the location is not read only when adding a movie.

It allows read only, but then fails to import when the download completes.

**Comment by ta264** [comment]
It's because of all these edge cases to an already niche use case that we have decided not to support this.

**Comment by kennethx** [comment]
Like I said previously, the reason to add these movies from read only location is to PREVENT downloads from happening at all for movies you already have and dont WANT to download any more copies of. If you add a movie from a writable location and set it to monitor:true, when that movie is downloaded it will replace the one it is monitoring in the writable location. There is no edge case here, and abselutely no reason not to FIX this (a bit better than my quick hack to test it).

Movies added from a read only location shall only be allowed to be monitor:false, obviously. If not facilitation of alternat download location would be needed, and that complicates things.

If the movie exists in your other, writable folders already, Radarr will not allow the import due to duplication any way, no conflict there.

Simple readonly monitor:false import, is relatively simple to add, and would resolv this issue for many.

It is very much a valid usecase that should be covered by Radarr.

**Comment by fryfrog** [comment]
I'd estimate that none of the few active developers consider this a feature worth working on. If you care strongly about this, you have time to learn .NET and work w/ the developers to come up w/ a solution that satisfies both them and you. Otherwise, the chances of this ever coming to Radarr are very slim.

You'd probably actually want to start in *Sonarr* though, since I imagine it applies equally to both. But there, I can also very accurately predict the developers won't consider this worth implementing and so it'd be up to you to learn .NET and write it in such a way that they accepted it.

But don't forget that w/ added complexity comes people messing it up. The "cost" of your feature which 1% of users might want could be 10% of users accidentally "using" it and then needing help understanding/fixing it. What is the difference between a read only library and a library which has permissions that are wrong making it read only? You can't just think about this from the stand point of what *you* want, you have to think about it in the greater context of how *everyone* uses Sonarr/Radarr. And how those users could screw up and need help.

**Comment by ta264** [comment]
I think @fryfrog summed it up nicely. The cost / benefit doesn't stack up for us. But it's all open source so feel free to fork and support a version that allows what you're after

**Comment by Mist-Hunter** [comment]
Thank you for the effort you put into this great software! I also appreciate the thoughtful arguments concerning why adding a read-only option could actually create more problems for the average user. Thinking about the impact on the average user is very important. 

The average user often struggles with basic concepts of web hosting. In my mind the worst case scenario for an average user is not confusion over features, but loss of their underlying media. Allowing the ability to import a library that is read-only from Radarr's perspective enables them to think about and try to enact principles of least privilege. 

Radarr is now a well know piece of software that is scanned for by pen-testers and hackers. See discussion here: https://www.reddit.com/r/sonarr/comments/gqvh09/please_please_please_do_not_leave_sonarr_open_to/ , people have lost their libraries. This is not in anyway a fault of the developers here, but personally, I would love a way to use your software while knowing this risk is mitigated.  The OP's points might be useful relative to this.

Obviously anyone running this software bears responsibility for securing their setup, but since we are presenting arguments on how to best help the average user, I thought I drop this in here.

How this project should balance security options and usability is obviously something people who are actively contributing code to figure out, which I am not. I just thought I'd voice my opinion and say thanks for the software and hard work!

**Comment by bakerboy448** [comment]
No plans at this time.

The use case of a R/O root folder is rather slim

> people have lost their libraries.

Failing to lock one's front door and getting robbed is the individual's fault for not locking their door.

**Comment by jj-uk** [comment]
> Failing to lock one's front door and getting robbed is the individual's fault for not locking their door.

Lol. We did lock the door (we set RO permissions), but radarr doesn't work when people use RO permissions.
Those who's files were robbed didn't lock the door; they left their door set to RW.
