### ISSUE TITLE
Mediainfo videoBitrate is 0 on some videos

### ISSUE THREAD

**Issue by LesKent** [Radarr/Radarr#2860]
Stored in the database in the MediaInfo field that is derived from the results of mediainfo.dll. 

I wanted to use the videoBitrate field to cull out some low quality content. I noticed that about 3% of my library had a videoBitrate of 0. 

In doing research of the ones that worked vs. the ones that didn't and in looking at the code I see that that this data element is populated from a mediainfo.dll result "BitRate" in the video stream section. In these selected videos that don't work I found it does not return "BitRate" but instead returns "BitRate_Nominal". This results in the 0 for the videoBitrate data.

I've attached the mediainfo results from a working vs. not working media files

[mediainfo-not-working.txt](https://github.com/Radarr/Radarr/files/2146334/mediainfo-not-working.txt)
[mediainfo-working.txt](https://github.com/Radarr/Radarr/files/2146335/mediainfo-working.txt)

.

**Comment by Qstick** [comment]
@Taloth have you guys seen this? Would it make sense to try parse both in VideoFileInfoReader and backup to nominal bitrate if bitrate is 0 or unavailable?

**Comment by Taloth** [comment]
My guess would be constant-bitrate vs VBR encodes. I'll swap it around, default to BitRate_Nominal unless unavailable.

**Comment by Qstick** [comment]
Thanks!

**Comment by Taloth** [comment]
PS: I didn't up the schema version, so it won't rescan existing files.

**Comment by Qstick** [comment]
@Taloth wouldn’t this logic also apply to audio bitrate property?

**Comment by Taloth** [comment]
In theory yes, but the audio bitrate field in mediainfo is a string that we split at '/'. Lacking an example I couldn't simply change it based on a guess. We'd need quite a bit of examples to check the various combination, based on the txt posted we'd have to check FromStats_Bitrate as well.

**Comment by Qstick** [comment]
Good point, although per this (https://sourceforge.net/p/mediainfo/discussion/297610/thread/9fc4cae5/?limit=25#b126) that was also possible on video bitrate. I think you are right, more testing in order to cover all cases

**Comment by LesKent** [comment]
I found about 4% of my library has an audio bitrate of 0. 

On some files I checked there was an audio "bitrate" field returned but the database had an audio bitrate of 0 which maybe was caused by changes in the DLL info from when it was first scanned and what is available for the online check at https://mediaarea.net/MediaInfoOnline. 

Is there a way to force a refresh of the MediaInfo database field from the content files?

I did find a specific file that had no bitrate in the audio as follows:

{
"@type": "Audio",
"StreamOrder": "1",
"ID": "2",
"UniqueID": "17075682846773397948",
"Format": "AAC",
"Format_Profile": "LC",
"CodecID": "A_AAC-2",
"Duration": "5749.683",
"Channels": "2",
"ChannelPositions": "Front: L R",
"ChannelLayout": "L R",
"SamplesPerFrame": "1024",
"SamplingRate": "44100",
"SamplingCount": "253561024",
"FrameRate": "43.066",
"Compression_Mode": "Lossy",
"Delay": "0.067",
"Delay_Source": "Container",
"Title": "aac",
"Language": "en",
"Default": "Yes",
"Forced": "No"
}

And another one that had "unknown / xxxx" for the bitrate:
{
"@type": "Audio",
"StreamOrder": "1",
"ID": "2",
"UniqueID": "27848",
"Format": "DTS",
"Format_Profile": "MA",
"Format_Settings_Mode": "16",
"Format_Settings_Endianness": "Big",
"CodecID": "A_DTS",
"Duration": "8050.080",
"BitRate_Mode": "VBR / CBR",
"BitRate": "Unknown / 1509000",
"Channels": "6",
"ChannelPositions": "Front: L C R, Side: L R, LFE",
"ChannelLayout": null,
"SamplesPerFrame": "512",
"SamplingRate": "48000",
"SamplingCount": "386403840",
"FrameRate": "93.750",
"BitDepth": "24",
"Compression_Mode": "Lossless / Lossy",
"Delay": "0.000",
"Delay_Source": "Container",
"Language": "en",
"Default": "Yes",
"Forced": "No"
},

**Comment by Qstick** [comment]
In that second case we would miss the bitrate as we split the string and just return the first index currently. 

I am putting a script together to run thru my library and export the different values for bitrate, bitrate_nominal, fromstats_bitrate for audio and video on each file. While that’s a very small sample size, should give us some idea as to what different values could be.

**Comment by Qstick** [comment]
@Taloth After running a few thousand files the majority of files have a `Bitrate` value, of the 7000 video files I ran in various formats only 9 had a `Bitrate_Nominal` value. Of those 9, 8 had both a `Bitrate` and `Bitrate_Nominal` value and 6 of those 8 had inaccurate values for `Bitrate_Nominal`. Additionally, 20 files had a `Bitrate_Nominal` value for Audio, of those 20, 17 also had a standard `Bitrate` value.

I also tested 30,000 audio files (Not for Radarr use of course :) ) and none of them had a `Bitrate_Nominal` value for audio.

Additionally, none of the files tested had a dual value for `Bitrate` for audio or video utilizing the `/` that we check for. Not sure if that was an issue in a previous version of mediainfo, or if i just didn't find any files that trigger that response. 

My suggestion would be to use `Bitrate` by default and only default back to `Bitrate_Nominal` if `Bitrate` is not available. Also, we should probably look at both values after a `\` split to ensure we are actually picking up a bitrate in cases like above, instead of automatically resulting to the first.

Thoughts?
