### ISSUE TITLE
Respect download client preference on older movies

### ISSUE THREAD

**Issue by Groofster** [Radarr/Radarr#2903]
When adding older (already released) movies to Radarr, the download client preference is not respected. I prefer downloading from newsgroups so I am using a delay profile. This works perfectly for newly released movies but is not respected for older movies.

**Comment by fryfrog** [comment]
Delay profile doesn't apply or make any sense for manually initiated searches.

Download preference does, I believe... but the results are still sorted by values applied to various aspects of results and weighting means the best choice may come from either torrents or usenet. If you want better control of where the download comes from, use the search tab and pick the most appropriate result.

**Comment by Groofster** [comment]
I'm not talking about manual searches, I'm talking about adding a movie that has already been released and then letting Radarr do it's work. It would be nice if there was an option to respect the delay profile then as well. So start the delay not from release date or something but from date added. In this way my preference of usenet will still be granted. Especially now that more and more countries are zooming in on individual torrent downloaders.

**Comment by fryfrog** [comment]
I think you just fundamentally don't understand how Radarr and Sonarr work, which is okay because it is a little weird. The only search is a manual search. The normal mode of operation is watching the feed of newly posted items to your indexer (which is actually really just an empty search for everything). In the torrent world, reposts are super rare, but in usenet they're more common.

When you add a movie, if you know it already has a download available, make sure you're adding it w/ the right settings and then use the add+search button. If you know it *isn't* already available, just use the add button. I suggest using Physical/Web for availability and setting the delay to -28, give or take a week. Note that that one is the *only* one where a negative value is valid. Using this means it won't download anything until about a month before the release date, which is roughly when web-dl/bluray generally become available.

**Comment by galli-leo** [comment]
Delay profile should still be respected for old movies. Can you please post debug logs of a search alongside a screenshot of a manual search result?
