### ISSUE TITLE
Unable to add movie, TMDB ID already correct

### ISSUE THREAD

**Issue by Toucan-Sam** [Radarr/Radarr#2929]
**EDIT: Solved.** Sort of. A new error message needs to be introduced to resolve the issue.

Original comments:
So I've gone through and imported a bunch of movies but there are a few remaining ones that Radarr can't seem to import. Radarr says I can fix the TMDB ID and it will allow me to import them, but Radarr correctly detected the TMDB the first time.

I've tried...
1. Clicking on the cell and then off (and TMDB does refresh).
2. Inputting a different ID then switching back to the correct one.
3. Clearing the ID completely and re-entering.

Screenshot:

![Imgur](https://i.imgur.com/RhSQYAa.png)

This seems similar to #1690 ?
I'm running v0.2.0.1120

**Comment by Toucan-Sam** [comment]
Right. I've solved this after endless frustration.

Ultimately the answer is: **the movie already exists.**

So really there needs to be an error message of some kind to say that there is already a movie using that TMDB ID in the database.

Beneath that however, there are 2 separate causes.

The first: the folder with the movie in it has been manually renamed and Radarr doesn't know and/or hasn't updated yet.

The second: the movie exists and is already found in the Radarr DB. There's just no error message to tell you this.

Either way there should be some kind of highlighted error.
"The movie you're trying to import is already in the database. Please visit the entry and verify the existing path by editing the film. Otherwise you likely have a duplicate."

**Comment by flcowboy7** [comment]
I am having a similar issue, where I know the movie title I'm attempting to import shows the correct TMDB ID in the import list. If another title is using that TMDB ID incorrectly, I have no way of knowing that. None of the list views show me which TMDB ID each title is assigned to. I can't even see it when editing a movie (or using the bulk movie editor). So the only way for me to check is to delete my entire list and re-import everything and then search the import list of that one TMDB ID. Not a very efficient method, obviously.

As it turned out, the movie in question was in fact already in Radarr's list of movies. So why it found it again is beyond me, since it found the exact same file again. I could understand if it had found another file in a different directory or something, or even a duplicate file in the same directory, but that just isn't the case here.

In this case, I had to delete the pre-existing movie title from Radarr's list, then run the import again. After that, it didn't find it a duplicate. Odd. Maybe it something to do with my browser's cache or something?

I second the OP: add custom error messages for disabled movies available from import.

To go above and beyond would be a feature request to include more granular data per movie in the movie list, edit movie screen and bulk movie edit screens to include at least the TMDB ID (since it is used by Radarr for assignment of the title).

**Comment by galli-leo** [comment]
Duplicate movies already have an "error message": As the comment explains, they are disabled. However, maybe we could provide a link to the existing movie with the same TMDB id? Then you could see, which one is correct and fix it?

**Comment by Qstick** [comment]
This is much clearer in v3
