### ISSUE TITLE
[Feature Request] Add option to only scan media info on import (Not when scanning disk)

### ISSUE THREAD

**Issue by danjames92** [Radarr/Radarr#2956]
**Describe the bug**
Analyze video files set to OFF = no MediaInfo used on import on 0.2.0.1154+

**To Reproduce**

Set movie naming to:

`{Movie Title} ({Release Year}) [{Quality Title} - {MEDIAINFO VIDEO} - {MediaInfo VideoBitDepth}bit - {MediaInfo AudioChannels}ch - {MediaInfo AudioCodec} - {Release Group}]`

**Expected behavior**
I would expect to end up with:

```The Movie Title (2010) [Bluray-1080p - X264 - 8bit - 5.1ch - DTS - EVOLVE]```

I actually end up with this:

`The Movie Title (2010) [Bluray-1080p - - bit - ch - - EVOLVE]`

**Comment by galli-leo** [comment]
This is intentional. Previously, the setting wasn't considered, which was an error (taken from the Sonarr source, which have fixed it as well).

You have to enable Analyze Video Files to generate a media info. It shouldn't interfere with disk scan service, since that will only analyze files that aren't in your library.

**Comment by danjames92** [comment]
This will cause lots of network activity for google drive based mounting solutions.
