### ISSUE TITLE
[Feature Request] Clean Library on a per list basis.

### ISSUE THREAD

**Issue by xxsteven69xx** [Radarr/Radarr#2970]
I use multiple categories and genre lists from trakt to keep a full library. I would like to keep them trimmed up by deleting anything that is removed from the lists. Currently though, it also deletes anything I have manually added to my library (My grandfather's Westerns). So my options are to have a fairly automated but ever expanding library, or fully automated keeping a consistent video count but it deletes manually added movies.

[AB#870](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/870)

**Comment by fryfrog** [comment]
I don't think Radarr keeps track of where a movie comes from, so its only option is to delete movies that aren't on the list. It seems like you could "solve" this by also creating your own trakt list of your grandfather's westerns.

**Comment by XDGFX** [comment]
I would love this - I have a pretty large manually added movie collection; but I want to automatically cycle through StevenLu's movie list; removing films as they are removed from the list.

It would be a huge pain to add all my existing movies to some list just so they aren't automatically deleted.

**Comment by geogolem** [comment]
Once the CleanLibrary tag is integrated into Radarr,

Maybe perhaps the specification of CleanLibrarLevel can move to the individual list, so a different level can be specified for each list.

then the CleanLibrary function can use the list tag combined with the cleanLibrary tag, to automatically delete movies removed from certain lists.. 

I'm just brainstorming here --> more thought needs to be done because I'm not quite sure how it all currently works or how it should work. For example, if a movie was on multiple lists, does it get tagged with multiple list tags. 

The cleanlibrary tag is removed if an item is tagged with it, but that item is then found in a list on a subsequent run of listsync. list tags stick around on movies even if they have been removed from the list.

**Comment by geogolem** [comment]
I also noticed this reddit post which involves augmenting the cleanLibrary framework: https://www.reddit.com/r/radarr/comments/irddgs/can_we_expand_on_the_list_import_options/

I am pretty sure PR: https://github.com/Radarr/Radarr/pull/4947 makes this possible, since items could be filtered by cleanlibrary tag and specific path and then removed.

**Comment by Qstick** [comment]
No plans for this in near future
