### ISSUE TITLE
Activity / Queue view, removing film from queue, deleted the movie?

### ISSUE THREAD

**Issue by jaxjexjox** [Radarr/Radarr#2972]
**Describe the bug**
I deleted a film which was incorrectly listed in the queue, I use blackhole mode, the film had completed downloading, had been renamed, imported and was fine. 

I was surprised to see it in the activity / queue view, removing it, deleted the files.

**To Reproduce**
See above, presumably you'll need your test movie to be appearing in the queue view.

**Expected behavior**
Film is removed from the QUEUE of the download package (IF supported, blackhole it's impossible)
AND film is simply removed from the list of active downloads (queue view) - the film itself, should not be deleted

**Screenshots**
N/A

**Desktop (please complete the following information):**
Windows 10
Radarr Ver. 0.2.0.1120
develop

**Debug Logs**
N/A at current time.

IF this is intended behaviour then the tooltip MUST BE CHANGED on the queue view as it clearly says **"Remove from download client"**  That doesn't mean "remove all known copies of film"

**Comment by fryfrog** [comment]
I don't use blackhole (or drone factory) and honestly, neither should you.

But I'm trying to understand what you're describing.

Radarr and Sonarr can't actually get any data from the torrent client, since you're using black hole. So during the download, the only thing it can do is remove the torrent file itself. Once it is downloaded, I assume the movie would show up in some temporary folder like `/somewhere/torrents/movies` and then Radarr would import it. Is this how it works? If so, I don't see any way for a deletion while it shows up in Activity to effect anything. If not, I've got nothing useful.

Why are you using black hole? :/

**Comment by jaxjexjox** [comment]
I need to use black hole, I'm not having this debate again.


The fact is, the package is removing the DOWNLOADED FILM when choosing "remove from queue" - it's as simple as that. Regardless of the method I've opted for, why would the wanted / queue section, remove the film itself?

**Comment by fryfrog** [comment]
I don't use black hole. I don't know anyone that uses black hole. I'm simply trying to understand how it works. Turn your logging up to trace and reproduce it. Give us more details about your setup. I honestly don't even understand how what you describe could be possible. But you also don't give a lot of useful details.

Where do you download to? Does your black hole download to `/whatever/A` and then move to `/whatever/B` when it finishes so that Radarr only sees it when it is fully done (since it can't know when it is done)? Does it move it from `/whatever/B` to `/Movies/Film (Year)`?

I honestly can't think of a single situation where black hole is needed and CDH/FDH can't be used. It is almost the same as the drone factory folder... which I guess you must be using too, right?

**Comment by jaxjexjox** [comment]
My needs for blackhole, will be fixed fairly soon, qbittorrent will be updated to support !categories, which file folders based on !categoryname.

I currently use a multi-blackhole import 

blackhole/tvtorrents will download to  /download/tvToImportPlz
blackhole/movies will download to /download/RadarrMovies
blackhole/torrents will download to /download/normaltorrents

etc.

Anyhow, do you have anything in your queue view?  Perhaps we can reproduce it.

**Comment by fryfrog** [comment]
Tons of stuff and I remove things quite frequently and they only ever impact the torrent / nzb in question, no matter if it is finished or in flight.

So using an example above, it sounds like:
Radarr sends a `.torrent` file to .`blackhole/movies`.
Does it download directly to `/download/RadarrMovies` and then stay there? Or does it download somewhere else and only move when done? I feel like you'd need to do the second thing, otherwise how does Radarr know when the torrent is done downloading?
Do your movies *live* in `/download/RadarrMovies`? Or does Radarr move them from there to another, final location? Do you use hard links or symlinks or anything?

**Comment by galli-leo** [comment]
Please provide some debug logs to work with.
