### ISSUE TITLE
WebUI sorting cosmetics

### ISSUE THREAD

**Issue by jOOc** [Radarr/Radarr#299]
![image](https://cloud.githubusercontent.com/assets/9382342/22015552/dc73495e-dca2-11e6-88f9-bbdc158b9792.png)

Downloaded and iconcolumn (dont know what its called) is missing in dropdown
Column "profile" is called "quality" in dropdown. Shouldnt they be the same?
No arrows in menu showing ascending or descending, like Sonarr have

**Comment by simonk83** [comment]
Galli-leo, also sorted by Status should probably group the various "missing" options together, rather than grouping all missing into one, if that makes sense.  For example in the attached image, all the red Missing should be together, all the blue should be together, rather that mixing and matching.

![image](https://cloud.githubusercontent.com/assets/518440/22138301/f91c9bb2-df33-11e6-978a-384dd28728cc.png)
