### ISSUE TITLE
Info on which list a movie came from on its info page

### ISSUE THREAD

**Issue by Mushin** [Radarr/Radarr#3014]
It would be nice to see on the movie page, under the title with the other info, whether the movie was imported from a list, and if so, which list did it come from. Either that, or put an entry in the history tab for being imported from a list?

**Comment by galli-leo** [comment]
@Qstick Hmm I would have just added the list_id as a foreign key. This way we could also only clean out movies that come from a specific list.

**Comment by Qstick** [comment]
Yea I just don't like the idea of mass cleaning movies like that. They could be on various states what not.

**Comment by geogolem** [comment]
this could have some interplay with this feature request: https://github.com/Radarr/Radarr/issues/1362

I think tagging the movies with the lists they are on would help to solve that issue as well, since then upon successful download, it could check each list it was on, and then remove itself from that list.

These are totally different feature requests - but the added information of keeping track of which lists movies on would make current cleanLibrary obsolete and enable implementing a cleanLists feature also..

**Comment by Qstick** [comment]
@geogolem also related to #3127

**Comment by pbrink231** [comment]
My main thing is as simple as which list added which movie.  I saw the other related ones and they are talking about tags which is great but different lists can have different information.  So you dont know which list actually added the movie.

I think a very simple solution that tells you very clearly what happened is to add it to the history and just dont give a quality.  An example is below.
![radarr with list history](https://user-images.githubusercontent.com/8224560/53981345-57b76700-40e0-11e9-9616-3f683c837de8.png)

this is the icon i grabbed in case you want it
![add-list-32](https://user-images.githubusercontent.com/8224560/53981115-eecfef00-40df-11e9-8665-baa2a1c03060.png)

**Comment by geogolem** [comment]
very similar to: https://github.com/Radarr/Radarr/issues/2306

**Comment by Qstick** [comment]
Just add a unique tag to each list and movies added by that list will be identified by said tag. You can then sort/filter/delete/rename by that tag..
