### ISSUE TITLE
Movie downloaded again after cutoff reached and files deleted

### ISSUE THREAD

**Issue by Rouzax** [Radarr/Radarr#3029]
**Describe the bug**
As I mentioned in https://github.com/Radarr/Radarr/issues/1191#issuecomment-415427213 it happened again. A movie that was downloaded at my cut off quality was downloaded again after I removed it from disk after watching.

**To Reproduce**
1. Download movie at cutoff quality
2. Watch movie and remove it from filesystem (not through Radarr)
3. The movie is downloaded again even though I've set `Ignore Deleted Movies` to `No`

**Expected behavior**
When Cutoff is reached and I delete the movie from disk I expect it to set it to unmonitored and not download it again.

**Screenshots**
![image](https://user-images.githubusercontent.com/4103090/45584325-e685bc80-b8d1-11e8-8874-0a9df5790eb7.png)
![image](https://user-images.githubusercontent.com/4103090/45584328-f2717e80-b8d1-11e8-82e2-f1e8c49aecca.png)

**Desktop (please complete the following information):**
 - OS: Windows 2016
 - Version: 0.2.0.1120

**Debug Logs**
I've compressed all debug starting from before I deleted the files from the filesystem
https://cloud.mgdn.nl/index.php/s/pJBnK5KTt83gsZa

**Comment by Rouzax** [comment]
And doing it again :(

```
18-9-15 10:52:29.9|Info|RefreshMovieService|Updating Info for Jurassic World: Fallen Kingdom
18-9-15 10:52:29.9|Debug|CleanExtraFileService|Cleaning missing metadata files for movie: Jurassic Park
18-9-15 10:52:29.9|Info|MetadataService|Movie folder does not exist, skipping metadata creation
18-9-15 10:52:30.5|Debug|CleanExtraFileService|Cleaning missing metadata files for movie: Jurassic World
18-9-15 10:52:30.5|Info|MetadataService|Movie folder does not exist, skipping metadata creation
18-9-15 10:52:30.7|Debug|RefreshMovieService|Finished movie refresh for Jurassic World: Fallen Kingdom
18-9-15 10:52:30.7|Info|DiskScanService|Scanning disk for Jurassic World: Fallen Kingdom
18-9-15 10:52:30.7|Debug|MediaFileTableCleanupService|File [C:\DATA\Movies\Jurassic World Fallen Kingdom (2018)\Jurassic World Fallen Kingdom (2018) - [Remux-1080p][DTS-X 7.1][X264]-EPSiLON.mkv] no longer exists on disk, removing from db
18-9-15 10:52:30.7|Debug|MovieService|Detaching movie 1201 from file.
18-9-15 10:52:30.7|Debug|DiskScanService|Movies folder doesn't exist: C:\DATA\Movies\Jurassic World Fallen Kingdom (2018)
18-9-15 10:52:30.7|Debug|MetadataFileService|Deleting Extra from database for movie file: [286] Jurassic World Fallen Kingdom (2018) - [Remux-1080p][DTS-X 7.1][X264]-EPSiLON.mkv
18-9-15 10:52:30.7|Debug|SubtitleFileService|Deleting Extra from database for movie file: [286] Jurassic World Fallen Kingdom (2018) - [Remux-1080p][DTS-X 7.1][X264]-EPSiLON.mkv
18-9-15 10:52:30.7|Info|RefreshMovieService|Updating Info for Just Go with It
18-9-15 10:52:30.7|Debug|OtherExtraFileService|Deleting Extra from database for movie file: [286] Jurassic World Fallen Kingdom (2018) - [Remux-1080p][DTS-X 7.1][X264]-EPSiLON.mkv
18-9-15 10:52:31.1|Debug|CleanExtraFileService|Cleaning missing metadata files for movie: Jurassic World: Fallen Kingdom
```
![image](https://user-images.githubusercontent.com/4103090/45584866-459bff00-b8db-11e8-8535-7f38cbe319bc.png)

**Comment by rfgamaral** [comment]
I just did some research on this issue and given your expected behavior:

> When Cutoff is reached and I delete the movie from disk I expect it to set it to unmonitored and not download it again.

You need to have "Ignore Deleted Movies" set to `Yes`. The option name is probably misleading the information tooltip explains it better. So, if you set to `Yes` the movie will become "unmonitored" and if you set to `No` the movie will become "missing".

However, there's a couple of things to notice about this:

1. Something that @galli-leo mentioned as reply to your https://github.com/Radarr/Radarr/issues/1191#issuecomment-415427213. The movie state will only switch from "downloaded" to "unmonitored/missing" on the **next disk scan**. This usually happens once each day (unless you manually force a disk scan for that movie).
2. As per https://github.com/Radarr/Radarr/issues/1191#issuecomment-287067992, Radarr still requires a folder for every movie and it will stop the disk scan if the folder is not there. For me this is the real a bug that needs to be fixed. However, on that same comment, @galli-leo said this:

> Why would you need to delete the folder anyway?

Why would I delete only the movie file and keep an empty movie folder on disk forever? That just doesn't make much sense... IMO, Radarr shouldn't stop the disk scan if a movie folder is missing. In fact, if a movie folder is missing (based on renaming and folder options), it probably means the movie was deleted and the movie state should change to "unmonitored" or "missing" accordingly.

Hope this helps.

**Comment by Rouzax** [comment]
I'll give it a try.

If a cutoff quality is already reached and I delete the folder and movie, how would Radarr know that the movie is missing without a disk scan?

**Comment by rfgamaral** [comment]
> If a cutoff quality is already reached and I delete the folder and movie, how would Radarr know that the movie is missing without a disk scan?

Software like Plex have functionality to actively monitor file/folder changes, if it detects something has changed, it will act upon that (instead of a periodic task like Radarr has). Maybe something like this could be implemented but it wouldn't be trivial to adapt Radarr to that behavior I would imagine.

**Comment by Rouzax** [comment]
I didn't understand why Radarr would know if a folder isissing when I deleted it from the filesystem and downloading it again in the same quality as it previously did.

If the ignore setting is actually the otherway around like you said it would explain it. So it might be my incompetence 😁

**Comment by galli-leo** [comment]
Deleting the folder should work. That was fixed a few months ago. Also yeah you have to enable the setting. If you delete the file from Radarr‘s UI, we might do a disk scan right after, so that would be the better option.

Plex and other programs also have a periodic disk scan. AFAIK there is no way to get filesystem changes in another way, they just do it more frequently. The reason we don’t do it that often, is because people might have network shares or cloud storage and continuous monitoring would cripple that.

**Comment by rfgamaral** [comment]
> Deleting the folder should work. That was fixed a few months ago.

I tested this today, it didn't work for me. I delete the whole folder (with the movie file inside) and the movie was kept in Radarr as "downloaded" (yes, I triggered a disk scan manually for that movie). I tried again, this time I just deleted the `.mkv` and kept the folder and the movie became "unmonitored" ("Ignore Deleted Movies" set to `Yes`, otherwise it would become "missing").

> Plex and other programs also have a periodic disk scan. AFAIK there is no way to get filesystem changes in another way, they just do it more frequently.

I'm not saying they don't but they seem to have other ways to detect changes. Now, I don't know how exactly they do it and if it's really "real time monitoring", but Plex and Emby have options like these:

![image](https://user-images.githubusercontent.com/96476/45589562-b06f2980-b91f-11e8-956d-0a5dfd887fdf.png)
![image](https://user-images.githubusercontent.com/96476/45589566-bb29be80-b91f-11e8-8235-3228a7992004.png)

> The reason we don’t do it that often, is because people might have network shares or cloud storage and continuous monitoring would cripple that.

I understand and that's a reasonable thing to do. But perhaps you could include an advanced option somewhere to change the periodicity of that task? Perhaps with a drop down to pick between a list of internals (so that people don't input things like 1min and have their systems slowing down to a crawl and then you'll have an influx of new issues opened 🤣).

**Comment by rfgamaral** [comment]
> > Deleting the folder should work. That was fixed a few months ago.
> 
> I tested this today, it didn't work for me. I delete the whole folder (with the movie file inside) and the movie was kept in Radarr as "downloaded" (yes, I triggered a disk scan manually for that movie). I tried again, this time I just deleted the `.mkv` and kept the folder and the movie became "unmonitored" ("Ignore Deleted Movies" set to `Yes`, otherwise it would become "missing").

Tested it again today and now it worked, oh well... If it happens again in the future, I'll open a bug a report.

**Comment by galli-leo** [comment]
@rfgamaral Did you maybe delete the root folder instead of the movie folder?

Also after thinking about it, if you have your profiles setup correctly, Radarr shouldn't download another movie, because until the disk scan happens, it will think it still has a good file downloaded.

I did however find a tool for being notified of file system changes, but according to Markus from Sonarr it could be impractical to use on mono or network shares and thus not worth the hassle.

**Comment by rfgamaral** [comment]
> @rfgamaral Did you maybe delete the root folder instead of the movie folder?

I'm pretty sure I didn't... Anyway, let's not be bothered by this until it happens again (if it ever does).

**Comment by Rouzax** [comment]
> 
> 
> Deleting the folder should work. That was fixed a few months ago. Also yeah you have to enable the setting. If you delete the file from Radarr‘s UI, we might do a disk scan right after, so that would be the better option.
> 
> Plex and other programs also have a periodic disk scan. AFAIK there is no way to get filesystem changes in another way, they just do it more frequently. The reason we don’t do it that often, is because people might have network shares or cloud storage and continuous monitoring would cripple that.

I think it might have something to do with the setting that I interpreted wrong.
![image](https://user-images.githubusercontent.com/4103090/45695715-4abeaf80-bb62-11e8-9486-2766dfb4d795.png)

**Comment by Rouzax** [comment]
This can be closed, was my own stupidity that I misunderstood the `Ingore Deleted Movies` option.
