### ISSUE TITLE
Not automatically moving downloaded movie to correct folder

### ISSUE THREAD

**Issue by slumdogbi** [Radarr/Radarr#3052]
**Describe the bug**
Radarr is not automatically moving downloaded movie to correct folder

**To Reproduce**
1. Search for a movie and add
2. Wait file download, wait a day
3. Radarr has now 2 folders, one of the original torrent name and other correct one (created by sonarr)
4. File keep on original torrent folder name and the correct one is empty

**Expected behavior**
Radarr should move the file and delete the old one?

**Screenshots**
http://snpy.in/KHm2UV
http://snpy.in/ZJE7FP
http://snpy.in/AQNKml
http://snpy.in/JVHVg7

**Desktop (please complete the following information):**
 - OS: Windows
 - Mono Version: [e.g. Mono 5.8] (Only needed under Linux and Mac, found under System -> Status)
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues)
 - Radarr Ver. 0.2.0.1120

**Debug Logs**
Attached
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/2412461/radarr.debug.txt)

**Comment by fryfrog** [comment]
I'm guessing the release in question is Ready.Player.One.2018.BRRip.XviD.MP3-XVID, since that is showing up over and over in the logs. Looks like it tries to parse it for details, but never goes past that point. Does it show up in Activity? Turn logging up to trace/debug and see if there is anything obvious. This is support too, so hit up Discord or Reddit. Feel free to link to your issue, since it has useful details. :)
