### ISSUE TITLE
Being able to remove the movie from Trakt's watchlist

### ISSUE THREAD

**Issue by BodingClockchian** [Radarr/Radarr#3061]
Radarr is working pretty nice and stable.
I've used CP before and one important function im missing right now is the watchlist sync with Trakt.

In CP you're able to delete the downloaded movie from the Trakt watchlist, otherwise Radarr will just hold movies that are already downloaded and just tags them as not monitored

![cp1](https://user-images.githubusercontent.com/28387829/46203564-7851e880-c31a-11e8-8626-6e86be8fe7ca.png)

**Comment by fryfrog** [comment]
Can you edit your comment to make it more clear what you're asking for?

Radarr doesn't know watch status, so it obviously can't update that in Trakt. But Plex (and probably Emby) can, so that is probably what you mean. And you want Radarr to *remove* the movie entirely if it gets removed from a Trakt list? Not just unmonitor it? Is that close?

**Comment by BodingClockchian** [comment]
Well the point is that im using Kodi to watch the movies.
The files downloaded with radarr will go to another location/device
While the files are downloaded and ready to play they are still on the watchlist
So every sync with trakt the movies are added again in Radarr right? Unless I change the option to be unmonitored ofcourse if deleted

In CP there's the option to sync downloaded movies to Trakt in the colletion and watchlist

With my setup right now (With Radarr) I have to manual remove downloaded movies from the watchlist

**Comment by fryfrog** [comment]
That doesn't sound like how they work, but I only hear about lists from others.

A list should add movies to Radarr, either monitored or unmonitored. I believe there is a search when added from list option, but could be wrong about that. Once the movie has been added to Radarr, that is it. It doesn't get added again, it is already there.

If you're seeing repeated downloads of the same movie, it is probably due to a bug or configuration issue.

I still don't actually understand what behavior you're describing as what happens currently nor what you want to happen and why. :/
