### ISSUE TITLE
Parse files in sub-folder

### ISSUE THREAD

**Issue by biship** [Radarr/Radarr#3140]
Radarr will not parse (identify) movies in sub-folders, but will in the parent folder.

Does not parse:
Manual Import - E:\Downloaded
\Torrents\Christopher.Robin.2018.1080p.BluRay.x264.DTS-HD.MA.5.1-AvoHD[EtHD]\Christopher.Robin.2018.1080p.BluRay.x264.DTS-HD.MA.5.1-AvoHD[EtHD].mkv

Will Parse:
Manual Import - E:\Downloaded\Torrents
\Christopher.Robin.2018.1080p.BluRay.x264.DTS-HD.MA.5.1-AvoHD[EtHD]\Christopher.Robin.2018.1080p.BluRay.x264.DTS-HD.MA.5.1-AvoHD[EtHD].mkv

I have multiple download locations all sub-folders of E:\Downloaded. For example: 
E:\Downloaded\Torrents\
E:\Downloaded\Newsbin\
E:\Downloaded\Manual\
etc

I have to run a manual import for every folder. 
It would be more convenient if I could have Radarr parse everything under E:\Downloaded

Manual Import -> Import Files Automatically also fails to parse files when given the parent folder.

**Comment by hotio** [comment]
that's probably by design

**Comment by fryfrog** [comment]
This is just how it be.

For your existing movies, your movie files need to be in folders and those folders need to be in a root folder. You can have more than one root folder, but the more you have the more annoying it is going to be for you.

For your *downloads*, it is fine. The import paths come from the clients, so it doesn't matter and your setup is fine. Well, obviously that `Manual` folder isn't going to be used for anything.

Also, consider nzbget or sabnzbd instead of newsbin.
