### ISSUE TITLE
keeps snatching same release 

### ISSUE THREAD

**Issue by SJ50** [Radarr/Radarr#3172]
**Describe the bug**
I use "custom format" to download scene than I want GP when available which works as expected, but Radarr keeps  snatching same release over and over. 

**To Reproduce**
When some one uploads torrent of same movie in different format than Radarr snatches already snatched release.

**Expected behavior**
Just parse new upload and snatch only if criteria matches, if not than do not snatch it, In any case do not snatch already snatched release.

**Screenshots**
![bug image](https://i.imgur.com/4VY2iOh.jpg)

**Desktop (please complete the following information):**
 - OS: docker/Ubuntu
 - Mono Version: 5.16.0.179 (tarball Thu Oct 4 10:29:10 UTC 2018)
 - Version 0.2.0.1216

edit - Expected behavior

**Comment by fryfrog** [comment]
Can you screen shot the custom format settings and the profile that uses it? In the profile, you'd need to make sure it had the right order and cut off.

But that said, it literally downloaded that SPARKS release 12 times, so that can't really be it.

Of interest in your screen shots is that I see a ton of torrent/nzb submissions (the cloud), but *NO* imports. Why didn't those downloads import? I think that is likely to be your actual problem.

**Comment by SJ50** [comment]
@fryfrog 

about No imports, I use filebot to rename movie and place it in appropriate folder and filebot runs script which changes path in radarr using API. when radarr refresh than it marks it as downloaded, more over radarr pointed to my gdrive mount which takes about 8-10 hours after download finishes and my local folder to sync to gdrive mount.
If there is API to add import I can include that in that script.

here is screen shots as you requested. 

![custom formate](https://imgur.com/FkxsUfP.jpg)

![cutoff](https://imgur.com/KCGcTor.jpg)

**Comment by fryfrog** [comment]
Ah, so I think you have a handle on why it download repeatedly, right? It won't stop until it the movie shows as downloaded. And since you're short circuiting the import which *would* do that, it has to wait the 12-24 hours for the disk refresh to catch it. Compounding that, it sounds like it can take some time to show up too?

Why are you using filebot instead of letting Radarr do the import?

**Comment by fryfrog** [comment]
Does [this](https://i.imgur.com/fRxsfw4.png) not work to get your folders named like you want? It seems like `{Movie TitleThe}` is exactly what you want.

**Comment by SJ50** [comment]
I want period instead of space, so I tried {Movie.TitleThe} and it gives "Movie.Title,.The" there is extra period before The and after comma.

**Comment by fryfrog** [comment]
Haha, that sounds like a bug you should report. Let me see what it does on my system. :)

**Comment by fryfrog** [comment]
`Cat.Returns,.The (2002) [Bluray-1080p] [x264 DTS].mkv` seems to do the same for me. What is right, `,The`?

**Comment by SJ50** [comment]
yes `,The` is right.

**Comment by SJ50** [comment]
Does {Movie TitleThe} moves `A` and `An` as well or just `The` ?

**Comment by fryfrog** [comment]
I dunno, you feel like checking? It seems like it should.

Can you make an issue for the `,.The` at least? :)
