### ISSUE TITLE
Add Trakt Collection to lists

### ISSUE THREAD

**Issue by GodsVictory** [Radarr/Radarr#3177]
I currently have no good way to delete movies from my library.

1) If I delete from disk, Radarr has the ability to unmonitor, but it still exists in the library as well as the trakt watchlist.

2) If I remove from the trakt wactchlist, Radarr can delete it from the disk for me. This works well except Radarr will delete anything I watch, since trakt automatically removes them from the watchlist.

Currently, the only solution I see is to make sure it's deleted in all 3 places. Disk, Radarr, and trakt, which makes deletions quite tedious.

Suggested solution:
Add trakt collections to Radarr lists. That way, when a movie is watched, it remains in Radarrs lists. To delete it, simply remove it from your collection in trakt.

Maybe I am missing something, how should we be deleting items?

**Comment by GodsVictory** [comment]
Seems like a pretty simple addition:

https://trakt.docs.apiary.io/#reference/sync/get-collection

**Comment by BluebonnetSK** [comment]
I too would like Trakt Collections added to the supported NetImport types, but for a different reason.  I have 20,000+ movies in Plex that I would like to import into Radarr, and then I would like to keep movies added into Plex first synced into Radarr. Doing this via my Trakt Collection seems the most efficient way.  The standard Radarr import does not work for such a large library.   

Since the Trakt API supports Collections, this would seem to be a straightforward addition, not much different that the already-supported User Lists.  
Thanks!
