### ISSUE TITLE
Radarr preferring torrents

### ISSUE THREAD

**Issue by darksupernova** [Radarr/Radarr#3207]
**Description:** Radarr grabbing torrents before usenet even though delay of 0 on usenet and 7 days on torrents and prefer usenet selected when adding a movie that is already released.

Posted logs even though it appears to be filled with errors on movie names i dont recognise. Checked the path, it doesn't exist. As a side note - how do i clean all that up? Movie names don't match anything on file (except guardians).

**Radarr Version:** 0.2.0.1217

**Mono Version:**

**Debug Logs:** https://pastebin.com/CVYYG6E6

**Comment by fryfrog** [comment]
Delay is only used by the "RSS" feeds, not the user initiated searches. And while prefer usenet influences the choice, if a torrent is considered better, it will get used. For an existing movie that you want to be sure comes from the right place, use the Search tab on that movie. You can also tune indexers to just *not* be used by search, but that probably isn't a great idea since it would limit your results.

**Comment by fryfrog** [comment]
Your other issue is likely from your download clients history. Delete the old items or change their category/label, depending on what client it is.
