### ISSUE TITLE
Movie extras deleted with movie upgrade

### ISSUE THREAD

**Issue by mikenobbs** [Radarr/Radarr#3209]
Radarr Version:
0.2.0.1217

Debug Logs:
https://pastebin.com/FFqjQJTh

I've been having this problem for a while now but have only just got round to turning on debugging and replicating the problem.

Basically every time I upgrade a movie Radarr deletes all the extra files in the movie folder along with the old version of the movie. It's not just artwork that gets deleted, .nfo's and subtitles are also deleted. The issue is particularly annoying because I spend a lot of time and effort finding movie posters and background artwork for my movies, sometimes even creating my own so having it deleted can be depressing, especially when I've only just got the recycling bin setting setup.

It also seems to randomly happen in the background too, movies that aren't even updated just seem to lose all their extra files, but that's not something I can recreate and I haven't managed to catch it in the logs yet.

If there's something I'm missing and I'm just being an idiot then please let me know I just want this sorted. This exact issue was posted a while back and was marked as fixed yet I'm still having the exact same problem.

To make the search through the logs a bit easier, the movie I updated was 'Fast & Furious 6'.

Thank you for any help you can give

Mike

**Comment by Qstick** [comment]
nfo and subfiles should be deleted, most of time they are file specific. I thought the artwork side of this had been fixed, maybe not.

**Comment by mikenobbs** [comment]
Yeah that makes sense, and to be honest the nfo and subfiles being deleted doesn't bother me anyway I know new nfo's will be created and generally I have the subs integrated into the movie file itself, it's just the artwork that's a killer, it's just lucky I have the recycle bin set up now

**Comment by randellhodges** [comment]
I'd like to see an option to filter the deletes or something. In my particular case, I don't want the nfo file deleted.

**Comment by mikenobbs** [comment]
The problems still ongoing

**Comment by Wdavery** [comment]
Having this issue as well. Can be quite frustrating

**Comment by moodiest** [comment]
When is something going to be done about this????

**Comment by ta264** [comment]
When a dev decides to donate some of his free time to fix it? Or when you learn .NET and submit a fix...

**Comment by bozrdang** [comment]
I started using Radarr v3 and also noticed it deletes all my image files during an upgrade.  I don't mind most of them because Emby will re-scrape them and I'm fine with that.  But the movie poster is a different matter for me.  For many movies I do not like the initial poster that is scraped and then have to go and select another one.  Other times there isn't a good cover available at all through Emby and over the years I have managed to source my own high res poster from other sources.  It is very depressing to find that Radarr has deleted them on movies that have been upgraded.  It doesn't seem to matter what they are named either.  Radarr wipes them all out.

Is there any way to prevent this from happening?  I am really loving Radarr but this is kind of a big deal for me.

**Comment by bakerboy448** [comment]
@bozrdang known bug #4650; follow that for updates; the dev's are working on it

**Comment by Qstick** [comment]
@bozrdang what is your image naming like?

**Comment by bozrdang** [comment]
By default my covers are poster.jpg.  That is the file that Emby uses but I
have "archived" my original posters by naming them differently so that Emby
or whatever wouldn't overwrite them.  The naming convention I use has
varied over the years and could be:

47 Ronin original cover.jpg or max1299762062-front-cover.jpg

I also have some covers for sets that I keep in the first movie's folder.
I usually use Photoshop to put a green Bluray case around them to make them
stand out  in lists.  So I will have the Photoshopped image and the
original cover I used.  So in those cases I will also have image files such
as:

The X Files Set.jpg and  The X Files Set original cover.jpg.

I have seen an upgrade delete all of the above.

**Comment by bozrdang** [comment]
Additionally, I don;t think Radarr should delete the poster.jpg either
during an upgrade.  After all it's still the same movie just a better
quality.  I'd much prefer my covers (or any artwork for that matter) don't
change.

**Comment by AwesomeAustn** [comment]
Same issue here. It's annoying. I'm glad I have the recycle bin setup also.

**Comment by AwesomeAustn** [comment]
This is still happening and I'm on version 3.0.0.3964.

**Comment by bakerboy448** [comment]
@AwesomeAustn finally you found the correct issue to comment on...yes it's  known issue.  see #4650

**Comment by austinwbest** [comment]
Actually it still isn't the right one (this ticket is for v0.2). @AwesomeAustn you **need** to open a new issue and fill out the template accordingly. If there is an open ticket then it will be closed and you will be directed to the ticket to reference. If it is valid and a ticket is needed it will be answered.

If all you are going to do is copy/paste a response to multiple tickets, your issue wont be addressed and at some point the posts will start being removed.

So lets keep it simple shall we?

Thanks!

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

Various other GHI are open to address these issues.
