### ISSUE TITLE
Misreported qualities

### ISSUE THREAD

**Issue by bobbintb** [Radarr/Radarr#3223]
**Describe the bug**
I frequently see encodes on my private tracker that Radarr determines to be bluray-1080p quality that are in fact br-disk.

**To Reproduce**
I only use a private tracker and I frequently see this problem when I manually search a release. I also see it frequently in the logs and automatic searches.

**Expected behavior**
It should determine the correct quality.

**Screenshots**
![image](https://user-images.githubusercontent.com/2601376/49331800-0edf9780-f560-11e8-85d3-7f4a3fe3a2ba.png)

**Desktop (please complete the following information):**
OS: Docker
Version: 0.2.0.1217
Mono Version: 5.16.0.220 (tarball Mon Nov 26 17:22:46 UTC 2018)

**Debug Logs**
`18-12-1 12:00:53.3|Debug|Parser|Parsing string 'Name of Movie 2018 1080p 2-Disc Blu-ray Edition-Highvoltage'
18-12-1 12:00:53.3|Debug|Parser|Movie Parsed. Name of Movie - 2018 
18-12-1 12:00:53.3|Debug|ParsingService|Language(s) parsed: 
18-12-1 12:00:53.3|Debug|QualityParser|Trying to parse quality for A Movie 2018 1080p 2-Disc Blu-ray Edition-Highvoltage
18-12-1 12:00:53.3|Debug|ParsingService|Quality parsed: Bluray-1080p v1 (None)`

This could be a feature request or a bug report, depending on how you look at it but I would see this as a bug report. I frequently see Radarr miscatagorize a br-disk release as bluray-1080p. This is either when I manually search or it does an automated job search. I only have one tracker I use for movies (PTP). It's usually not a problem because even if Radarr sees a 40gb br-disk as bluray-1080p quality, it usually finds a smaller release that is actually bluray-1080p and downloads that instead. However, that isn't always the case and it's problematic because it's a hit to my ratio to download that much mistakenly and my ISP has data caps.

For my tracker at least, I frequently see br-disk labeled as bluray-1080p. I've included a screen shot of one manual search where Radarr made the wrong quality determination. It's a very popular private tracker with good quality control and it happens frequently so I don't think it should be written off as bad naming. From what I'm told Radarr makes the quality determination by parsing the release title. This is why I say one might view it as a feature request. I'm not sure about public trackers but every private tracker I know of categorizes releases and that information is made available to the API. I know some public ones categorize releases to some extent as well, although that info may not be available so easily, programatically. I think a fair amount of people use private trackers with Radarr and while it may be an undertaking to program for every indexer available, I think it would be much better if Radarr uses the release information available from the tracker to determine quality, if it is available.

I know some will say as a counterpoint to just adjust the size cutoffs but that doesn't always work either. This is especially true with downloading animated movies as the sizes can vary drastically from those of live action. Some animated movies, like the DC animated ones, have small encodes and br-disk sizes. A live action movie encode is usually around 15gb and I've seen some at 20gb for longer running films or just bloated releases. I've seen br-disk rips of animated movies be 20-25gb or smaller and Radarr still determines them to be bluray-1080p quality. So the problem would still persist. It's really just a work around, not a solution, as the size isn't and shouldn't be used to determine quality but to further refine the quality.

I do have a debug log but I looked at it and it doesn't really have any more information than what is already self evident, so I only posted the relevant snippet. I can still provide the full log if requested.

**Comment by fryfrog** [comment]
Because torrent trackers are all over the place in what they support. The only *reliable* place for information is the release name. And even if they *did* use it from the tracker to decide, once it gets submitted to the torrent client (or usenet client), the *only* thing available is the release name. They don't have a way to match a .torrent or .nzb queued up to the download that happens. It is more like two black boxes, one that submits something to be downloaded and another that looks at everything downloaded and makes decisions based on the download's name.

**Comment by fryfrog** [comment]
Can you put an example release name in here?

**Comment by bobbintb** [comment]
Here is one:
Mission Impossible Fallout 2018 1080p 2-Disc Blu-ray Edition-Highvoltage

The vast majority of br-disk on PTP will show as bluray-1080p. Seeing as how it is the most popular private tracker, I think that's a problem. I know trackers can be all over the place but private ones are pretty consistent and getting the information straight from the tracker, that has already been vetted, is bound to be more reliable than parsing a file name, as evidenced by this issue. Radarr already leverages tracker specific information such as tracker specific flags and freeleech directly from the tracker API. I'm not a super skilled coder but I don't think it would be much of a task for someone that is. If private tracker, include a few extra fields in the API request, assign values, else parse values from filename. 

> And even if they did use it from the tracker to decide, once it gets submitted to the torrent client (or usenet client), the only thing available is the release name. They don't have a way to match a .torrent or .nzb queued up to the download that happens.

I don't know about Radarr but that's not the case with Sonarr. Sonarr uses the torrent/nzb hash as an environmental variable so that the client can be directly linked back to Sonarr, for just such an instance. One of my requests actually and I've found it quite useful for custom scripts. I don't know if that code was merged with Radarr though.

**Comment by galli-leo** [comment]
@bobbintb Can you post as many misidentified blu-ray discs as you can (well if they have the same name except the group / movie name, two examples should suffice)? Best would be a nicely formatted list so I can add them as test cases.

**Comment by bobbintb** [comment]
Sure. I can pretty much find one in almost any movie on my Radarr list.

Annihilation.2018.1080p.Blu-ray.AVC.Atmos.TrueHD7.1-HDChina
Ant Man and the Wasp 2018 BRA 3D Blu-ray 1080p AVC DTS-HD MA 7.1-Highvoltage
Atomic.Blonde.2017.BluRay.1080p.AVC.DTS-HD.MA7.1-MTeam
Avengers.Infinity.War.2018.3D.BluRay.1080p.AVC.DTS-HD.MA7.1-MTeam
Avengers.Infinity.War.2017.BluRay.1080p.AVC.DTS-HD.MA7.1-MTeam
Darkest.Hour.2017.1080p.Blu-ray.AVC.TrueHD.7.1

All of those are determined to be bluray-1080p by Radarr but listed as BD50 on the tracker. Some are ISOs and some are in folder format. I can list more if you need. As I said, there is at least one in most of the movies on my list.

**Comment by galli-leo** [comment]
@bobbintb The problem with all of those, is that we do not know whether those are actually BD50 or not. Nothing in the title separates them from the usual Bluray encodes / remuxes.

Therefore, we cannot really do anything about those releases. Do you have examples that differentiate themselves in the release name?

Btw. according to scene naming standards BD50 should be put in the title, maybe you can get them to do that, so Radarr has more luck parsing it? BD50 is recognized by Radarr.

**Comment by bobbintb** [comment]
If I had examples that differentiate themselves then there wouldn't be an issue. I don't know about the scene rules but PTP is the most well known provite tracker for movies and pretty much all of their BD50 torrents are like this. Where are you looking at the scene rules? The one I looked at makes no mention of BD50 in the title:

https://scenerules.org/n.html?id=2014_BLURAY.nfo

You may not know whether or not those are BD50 based on the file name but the PTP API has that information and is more reliable than file name parsing. Radarr already pulls tracker specific information for a release from private trackers such as GP, freeleech, halfleech, approved torrent, etc. Couldn't Radarr just pull the release type from the API for private trackers and parse filename for public ones.

**Comment by fryfrog** [comment]
That'd make it work for PTP and nothing else, which would be super confusing.

**Comment by bobbintb** [comment]
> > You may not know whether or not those are BD50 based on the file name but the PTP API has that information and is more reliable than file name parsing.
> 
> That'd make it work for PTP and nothing else, which would be super confusing.

How so? It would be transparent to the user and the problem is it doesn't currently work for PTP. It would still work for everything else.

**Comment by fryfrog** [comment]
If a release name *doesn't* contain `BD50`, it won't be parsed correctly, right? So if you depend on data from *one* indexer, it'll now create the confusing situation where poorly named releases from PTP parse *correctly* (because that data comes from API) while all others w/o `BD50` do not.

Also, I think it isn't likely to work for another reason. Radarr/Sonarr are more like two black boxes. One black box parses nzb/torrents and sends them to the downloader. The *other* black box parses the nzb/torrents in the download client and matches up/imports them. There isn't anything that tracks or passes information back and forth between the two.

**Comment by fryfrog** [comment]
Or are you saying that *only* PTP isn't marking the `BD50` releases properly, so fixing it there is all that is needed? In that case, I wonder if Radarr could just insert `BD50` into the torrent name when it sends to the client for download?

**Comment by bobbintb** [comment]
> About the black box thing... you are asking for Radarr to use the PTP metadata. Only the first black box (he download one) would see that metadata. Once the file is downloaded and the second black box for processing kicks it, it has no access to the PTP metadata anymore and only has access to filename.

Oh that's right. I was thinking it kept all the metadata in the history or something and only used filename to match it with the download in the torrent. It's been a while and I was remembering wrong and was a little distracted as I was thinking it through.

Well then, as far as the parsing goes, what's the rule? I don't think I've ever seen BD50 in the file name on any tracker. The naming scene I've shown in the examples is pretty common, and not just at PTP.

**Comment by galli-leo** [comment]
I think this is something we can implement in the future. (It is something I have planned to be included with custom formats, but didn‘t have time). Alongside that, would be the option to „trust“ certain indexers. Meaning Radarr would use the quality parsed when downloading the movie, when importing. Stuff like that.

**Comment by jyggen** [comment]
I'm facing a similar issue where, for example, `The Act Of Killing 2012 SUBBED NTSC DVDR-0MNiDVD` is considered being of the quality `DVD` and not `DVD-R`.

**Comment by xxbiohazrdxx** [comment]
Seeing this a lot too. I get that the only guaranteed bit of info that you have across all trackers is the file/folder name but if the tracker is giving you more....why not use it?

`{"Id":123456,"Quality":"High Definition","Source":"Blu-ray","Container":"m2ts","Codec":"BD25","Resolution":"1080p","Scene":true,"Size":"1234567890","UploadTime":"1970-01-01 00:00:00","Snatched":"1","Seeders":"1","Leechers":"0","ReleaseName":"Example.mkv","ReleaseGroup":"Example","Checked":true,"GoldenPopcorn":false}]}`

Or, since you're already pulling 'Checked' for PTP_Approved and 'GoldenPopcorn' for PTP_Golden; why not just add some additional custom flags? Parse 'Container' and 'Codec' and add the flag PTP_NotBRRip. 

Personally I feel like that's pretty kludgy considering qualities are already defined elsewhere but....

**Comment by xxbiohazrdxx** [comment]
> @bobbintb The problem with all of those, is that we do not know whether those are actually BD50 or not. Nothing in the title separates them from the usual Bluray encodes / remuxes.
> 
> Therefore, we cannot really do anything about those releases. Do you have examples that differentiate themselves in the release name?
> 
> Btw. according to scene naming standards BD50 should be put in the title, maybe you can get them to do that, so Radarr has more luck parsing it? BD50 is recognized by Radarr.

I get that the only guaranteed bit of info that you have across all trackers is the file/folder name but if the tracker is giving you more....why not use it?

`{"Id":123456,"Quality":"High Definition","Source":"Blu-ray","Container":"m2ts","Codec":"BD25","Resolution":"1080p","Scene":true,"Size":"1234567890","UploadTime":"1970-01-01 00:00:00","Snatched":"1","Seeders":"1","Leechers":"0","ReleaseName":"Example.mkv","ReleaseGroup":"Example","Checked":true,"GoldenPopcorn":false}]}`

String parsing and fuzzy matching sucks, especially if you've got a well defined JSON object right there giving you a property with the metadata needed.

Or, since you're already pulling 'Checked' for PTP_Approved and 'GoldenPopcorn' for PTP_Golden; why not just add some additional custom flags? Parse 'Container' and 'Codec' and add the flag PTP_NotBRRip. 

Kinda feels like a hack, especially considering the settings for quality is pretty well confined to one location. Adding a flag in indexer settings to handle quirks in the quality parser disjoints the settings. But if it works....

> About the black box thing... you are asking for Radarr to use the PTP metadata. Only the first black box (he download one) would see that metadata. Once the file is downloaded and the second black box for processing kicks it, it has no access to the PTP metadata anymore and only has access to filename.

I don't feel like this matters all that much. If you're interested in BR-Rips, everything continues to work exactly as before. If you're not interested in them, a change to the first "black box" prevents them from being downloaded at all, so the second black box doesn't come into play.

It at least helps out some people

**Comment by Herjar** [comment]
So many br-disks being downloaded here lately. Any progress on this?

**Comment by arebokert** [comment]
I have this issue as well, I can not allow bluray 1080 in my radarr profile at all due to this.

**Comment by bobbintb** [comment]
For anyone still having this issue, here is a work around until a fix can be implemented:

https://github.com/Radarr/Radarr/wiki/How-to-make-sure-Radarr-doesn%27t-snatch-full-Blu-Rays

**Comment by bakerboy448** [comment]
Use custom formats https://trash-guides.info/Radarr/V3/Collection-of-Custom-Formats-for-RadarrV3/#br-disk and disable BR-Disk quality ib your profile
