### ISSUE TITLE
Priorize Custom Formats above Quality

### ISSUE THREAD

**Issue by wizzardking** [Radarr/Radarr#3252]
Thank you very much for the Custom Formats Feature! It's realy awesome how good this works and it gave me the possibility to customize it completly for my request.

My only problem I have with this is, that it allways give the quality higher priority than the custom formats.
It would be awesome if there would be an option to change this logic.

Why I would like to change this:
I use custom formats for some language specific requests. As an example, I want to have a Dual Language file at the end, but as long there isn't such a thing available, it should fetch the movie in german language only. And if none of them are available, it should download the movie in english.
It happens realy often, that there is a 1080P file with german language only, and a 720p file which is Dual Language. But for me, I would preffer the 720P Dual Language File, instead of the 1080P file (but it still should look for 1080P Dual Language). But because quality tops everything, it will download the 1080P German only Release instead.

**Comment by Firemad03** [comment]
I had another issues like this one but a different case scenario. I have a custom formats (the best new feature around seriously for the multi language congratulations for the team!) for English and French with a regex that is detecting the multi word in the release and everything is working fine without an issue.

My issue is if I downloaded a movie that didn't have at this time the word multi in it because nobody released it well I downloaded for example the 1080p movie but the next day someone uploaded a multi file in 1080p but Radarr can't download it because Radarr detected the movie with the same quality and it doesn't download it because of it so I need to do it manually.

So yeah we need a logic for Radarr that by default the Custom Formats have a higher priority of everything because the Custom Formats is an advance feature that in reality the people that are using it know how to do it.

If the priority was higher I won't need anymore the basic function of the Profile and Quality tab and I can be 100% in the custom format.

In my scenario my issue is more a bug then a feature because Radarr can't download the same quality because of it.

**Comment by Supergamer1337** [comment]
This would indeed be good. This is after all what I thought you already could use it for, but that did not work. So, to me, this has about the same impact as "preferred tags".

**Comment by Floflobel** [comment]
I am exactly the same as you. I am currently using tags.
I have not been interested in "Custom Profiles" yet, but I understood that it did not change the priority to select the language first rather than the quality.

**Comment by s0mm3rb** [comment]
maybe I am missing something
but isn't this already included?

I've just created a custom format for surround audio and 1080p
and although I already had a 1080p bluray on disk (was grabbed by radarr on rss sync)
it just grabbed another release (with the 5.1 tags I set in my custom format) and upgraded to that

in my opinion this means, that custom formats do trump the other cutoff field

**Comment by henkin67** [comment]
@s0mm3rb : I didn't verify that point, but for sure the quality is priori to the custom format.
In the case of equal quality and already downloaded release, I don't know the behavior of Radarr.
My first assumption would be the same then @Firemad03.

**Comment by F4MES** [comment]
> maybe I am missing something
> but isn't this already included?
> 
> I've just created a custom format for surround audio and 1080p
> and although I already had a 1080p bluray on disk (was grabbed by radarr on rss sync)
> it just grabbed another release (with the 5.1 tags I set in my custom format) and upgraded to that
> 
> in my opinion this means, that custom formats do trump the other cutoff field
> and should also work to upgrade to dual language releases?

@s0mm3rb 

What custom format did you use?

**Comment by s0mm3rb** [comment]
@F4MES 
`R_1080,L_RQ_GERMAN,C_RXRQ_DTS(\-?(HD|X))?|TRUEHD|ATMOS|EAC3|(AC3(D)?).(5|7)|DD(\+|P)?.(5|7),C_RXRQ_(X|H)\.?264`

this grabs: any 1080p release, german only, any surround type, h264 only

but be aware that this could result in a lot of downloads if you add this!

make sure to deactivate rss while you add the custom profile and update all movies with the new profile or set them to unmonitored

otherwise radarr could download alot of movies suddenly, even if they already meet the custom profile

**Comment by bakerboy448** [comment]
No plans for this at this time
Solution is to group qualities together

**Comment by henkin67** [comment]
Hi @bakerboy448,

I'm not sure which solution you mean by "grouping qualities together".
In the profile webpage, we cannot group qualities together (as far as I understood).
Or do you suggest to disable ALL qualities and manage them directly in custom format ?

Thanks in advance for your clarification.

**Comment by bakerboy448** [comment]
On v3 you can group qualities together so they are equal. You'd then create custom formats as you see fit and ranking would be based on those effectively bypassing the quality.


You don't want to disable qualities as that means anything matching that quality is rejected.

**Comment by henkin67** [comment]
Ok I got it but I never tried v3.
By the way, do you have any entry point to tell me how to install Radar v3?

**Comment by bakerboy448** [comment]
Be sure to have a backup, you can't go back in time without a backup!
Stuff can break, although it shouldn't, but you've been warned!
If you find a bug, give a detailed description of how we can reproduce the bug in the #support-v3 channel and attach a link with your Trace log, only the parts that matter. Clear your logs, reproduce bug, copy/paste log on hastebin.com for example.

Windows:
https://radarr.servarr.com/v1/update/nightly/updatefile?os=windows&runtime=netcore&arch=x64
Linux:
https://radarr.servarr.com/v1/update/nightly/updatefile?os=linux&runtime=netcore&arch=x64
https://radarr.servarr.com/v1/update/nightly/updatefile?os=linux&runtime=netcore&arch=arm64
https://radarr.servarr.com/v1/update/nightly/updatefile?os=linux&runtime=netcore&arch=arm
macOS:
https://radarr.servarr.com/v1/update/nightly/updatefile?os=osx&runtime=netcore&arch=x64
Docker (Radarr nightly builds):
docker pull hotio/radarr:nightly
docker pull linuxserver/radarr:nightly

**Comment by bakerboy448** [comment]
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/GS7jgXv)

for further help with that

**Comment by DjRicko** [comment]
I want the same thing, this way us non-english natives can do cool things.

Like right now i have quality profile prioritzed to what qualities i would prefer, but it's allowed to download anything pretty much.
However what would be really cool is if i could add "New animation movie X", to the list. Then once an english release of it is found, it'll download this. Then usually some months later the nordic region blurays and dvds are released and a nordic / danish release will be available and it would grab this one over anything, ignoring that the english one might be better "quality".
