### ISSUE TITLE
 Unmonitored movies still searching and downloading because of Quality profile cutoff 

### ISSUE THREAD

**Issue by emko** [Radarr/Radarr#326]
I added my collection into Raddar all with monitor set to NO but i find that some of the movies are getting downloaded still, i think because i have the quality set to Bluray 1080p and the file i have is Bluray 720p but still if i set to monitor NO shouldn't that stop Raddar from searching and grabbing any releases?

**Comment by emko** [comment]
ya i don't know about that maybe its your indexer or your settings.

**Comment by benjmd** [comment]
Same issue here, I suspect it's because we can't set the quality on already-acquired titles. See screenshot:
![downloaded quality](https://cloud.githubusercontent.com/assets/18607108/22061221/e58ee102-ddc3-11e6-9541-9420c72e9cee.PNG)

If we can set the 'Downloaded' quality to x profile and the 'Profile' to x profile it shouldn't download/try and find a better release.

**Comment by emko** [comment]
now i am not sure if this is a quality profiles issue because i have a movie that i already had a download for in bluray 1080p and today i see that Raddar downloads a 1080p remux of the movie 30gb adds it to the correct movie folder and renames it but does not delete the old copy and it does not show up as a file under files only the old one does.

**Comment by emko** [comment]
never mind it still is the profile, it assumed the file was HDTV-1080p so it downloaded a Bluray-1080p, Raddar is just ignoring the monitor state.

**Comment by Kalroth** [comment]
Yup, I am encountering a similar issue.

Radarr keeps downloading proper releases for unmonitored movies.

**Comment by Flippage** [comment]
Same deal here. Downloaded 2x 10gig movies that I already had in great quality, and have already watched. Especially problematic since I have limited internet data each month. I've had to change NZBGet to "Add Paused" until this is sorted out.

**Comment by Flippage** [comment]
Here is the image of a movie for today - You can see it is unmonitored: http://imgur.com/a/Ksg5B

And the log:
17-1-23 16:03:58.1|Info|OwinHostController|Listening on the following URLs:
17-1-23 16:03:58.1|Info|OwinHostController|  http://*:7878/
17-1-23 16:03:58.8|Info|NancyBootstrapper|Starting NzbDrone API
17-1-23 16:04:29.7|Info|RssSyncService|Starting RSS Sync
17-1-23 16:04:30.2|Info|InstallUpdateService|Deleting old update files
17-1-23 16:04:30.4|Info|InstallUpdateService|Downloading update 0.2.0.210
17-1-23 16:05:06.6|Info|DownloadDecisionMaker|Processing 200 releases
17-1-23 16:05:40.4|Info|Nzbget|Adding report [The BFG (2016) - 1080p.BluRay.DTS.x264 - CyTSuNee (Audio : Nederlands, Vlaams, Engels)] to the queue.
17-1-23 16:05:41.5|Info|DownloadService|Report sent to NZBGet. The BFG (2016) - 1080p.BluRay.DTS.x264 - CyTSuNee (Audio : Nederlands, Vlaams, Engels)
17-1-23 16:05:41.5|Info|RssSyncService|RSS Sync Completed. Reports found: 200, Reports grabbed: 1

**Comment by fluffynuts** [comment]
This is quite some time later, and I can see the attached patch to resolve this, but I'm experiencing this now -- several movies downloaded in this last week, except mine aren't necessarily even because of a higher-quality download:

![image](https://user-images.githubusercontent.com/4669340/63955618-4b0b3e80-ca85-11e9-9fff-4db5c436039b.png)
