### ISSUE TITLE
Radarr no longer seeing previously added torrents in Deluge

### ISSUE THREAD

**Issue by the-Dakta** [Radarr/Radarr#3260]
**Describe the bug**
I had a bunch of torrents added to Deluge through both Radarr and Sonarr (only mentioning for the sake of the issue) and now neither see these torrents in activity and are not being handled for sorting after the fact. Newly added torrents work fine, and the Deluge test passes.

**To Reproduce**
Reproducible by viewing both "activity" and the logs.

**Expected behavior**
Torrents previously added by Radarr to Deluge should be viewable in activity, and then handled after completion.

**Screenshots**
https://imgur.com/a/NGd1gDH

**Desktop (please complete the following information):**
 - OS: Debian 9
 - Mono Version: 5.16.0.220
 - Version 0.2.0.1217

**Debug Logs**
Also uploaded prior log since debug log isn't showing the error that seems to be directly related.
https://www.dropbox.com/s/uaqahrrp0louv1u/radarr.debug.txt?dl=0
https://www.dropbox.com/s/tsr9wkngxhojhkg/radarr.txt?dl=0

**Comment by galli-leo** [comment]
So your issue seems to be twofold: For one, deluge seems to not report a download hash for one of your torrents and second, deluge seems to not report a title for one of your torrents. If you want to get your torrents back, I recommend a restart of deluge and / or removing all torrents from the Radarr label and then adding them back one by one, until you find the offending one.

I will try to get a fix out today.
