### ISSUE TITLE
Import upgrades from custom formats

### ISSUE THREAD

**Issue by jamin215** [Radarr/Radarr#3268]
**Describe the bug**
After adding the a custom format to get surround sound the releases are found and downloaded but cannot be imported/upgraded. The error in the log is "destination already exists" this leads me to believe that since the releases are both 1080p the file name is the same and radarr doesnt want to delete the old move. 
**To Reproduce**
1. Add custom format to upgrade sound with same resolution
2. Allow upgrade to download
3. Upgrade will not import due to "file already exists"

**Expected behavior**
I expect the file to upgrade when the new release was downloaded with the custom format cutoff

**Desktop (please complete the following information):**
 - Ubuntu 16,04
 - Mono Version: 5.18.0.225 (tarball Fri Dec 21 19:41:55 UTC 2018)
 - Version : 0.2.0.1217
**Debug Logs**
[radarr.txt](https://github.com/Radarr/Radarr/files/2715039/radarr.txt)

[radarr.debug.txt](https://github.com/Radarr/Radarr/files/2715045/radarr.debug.txt)

**Comment by galli-leo** [comment]
This is because Radarr sees the release it already downloaded as an upgrade, because it does not automatically update the custom formats for already downloaded releases.

Two things to fix this:

1. Either update all your existing files using the movie editor (Update Custom Formats) / by hand.
2. Or only make custom formats an upgrade on a new profile for new movies.
