### ISSUE TITLE
Add a new tag for Rename operation

### ISSUE THREAD

**Issue by Ninjouz** [Radarr/Radarr#3296]
**Is your feature request related to a problem? Please describe.**
I'm french but I like to get dual language release. Most of the time, release name contains information about languages ( ` It.Comes.At.Night.2017.MULTi.TRUEFRENCH.1080p.BluRay.x264.DTS-SOZER`, `Insyriated.2017.MULTi.1080p.HDTV.x264-UKDHD`, ...). With rename tags provided by Radarr I lose the information. 
I cant use AudioLanguages coming from mediainfo because : 
- my stuff is on gdrive and I disabled scanning
- there is no information about the kind of french track included. I mean French can mean 2 things : French Canadian (MULTI) or French from France (MULTI | (TRUEFRENCH / VFF)). My goal is to have a MULTI release with TRUEFRENCH track (thanks Custom Formats for that !)

Release workflow is always like this : 
1/ Release in ENGLISH (no tags in name)
2/ Release in MULTI with FRENCH canadian (tags : MULTI)
3/ Release in MULTI with true FRENCH (tags : MULTI TRUEFRENCH)

**Describe the solution you'd like**
I'd like to have a rename tag to get information about sound track language coming from the name of the release (failback to directory when filename is obfuscated).

A regexp like this should be a good start : 
`(?<lang>(Multi|German|TrueFrench|French|Spanish|Danish)+)
`

**Describe alternatives you've considered**
Another way to do that would be to use Filebot before Radarr move the file and then rename it by keeping the filename. 
Filebot can be used with groovy script thus allowing to do custom regexp and change the filename by directory name when filename is obfuscated.
But I have to admit that keeping only Radarr would be nicer !!!

**Comment by fryfrog** [comment]
A terrible work-a-round / alternative in the mean time might be one of the `{OriginalRelease}` name options. :(

**Comment by hergonoway** [comment]
I played with {OriginalRelease} not so long ago, but it's painfull.

I thought of an indirect way which implies Custom Formats, because , even if there are 2 potential distinct language in French, it's not tagged as well in media info. Being able to tag the filename with VFF, VFI, TRUEFRENCH or else may be better.

I currently deal with TRUEFRENCH in search with this custom format : 
`C_RXRQ_\B(TRUEFRENCH|VFF|VF2|VFI|FR2)\B`

Radarr keep this tag in DB, but it'll be very convenient to be able to insert the Custom Format name or an associated variable in the name during post-processing. That way, we'll be able to insert (for example "TRUEFRENCH" in the filename because it matches the Custom Format named "TRUEFRENCH".

**Comment by Ninjouz** [comment]
{OriginalRelease} wont cut it as I sometimes get release like that : 
`First.Man.2018.MULTi.TRUEFRENCH.1080p.BluRay.x264**.1**-LOST`

Ideally I'd like to get a curated version of it : 
`First.Man.2018.MULTi.TRUEFRENCH.1080p.BluRay.x264-LOST`

Using Regexp from custom tags may be a clever idea as it is true that some non-scene release can be named VFF instead of TRUEFRENCH

**Comment by Qstick** [comment]
You can do this with CFs in V3 now. CFs have options to include in naming if matched

**Comment by fryfrog** [comment]
Are they automatically matched when found in a file name too? Like, they'll get applied to the name... but they'll also apply themselves to a file w/ that in the name?
