### ISSUE TITLE
Movies containing samples causing errors and getting stuck in queue

### ISSUE THREAD

**Issue by a575606** [Radarr/Radarr#3370]
**Describe the bug**
I noticed this issue for the first time a few days ago, and just figured it was a one of glitch, but now it's happened twice I thought it worth reporting. 

Basically in both cases there was a sample included in the torrent, which seemed to create some problems. The result of which is the download sticks in the queue with a yellow import icon. The actual movie itself seems to get imported and renamed properly. But then things get a bit wacky. It looks like it tries to reverse the import or delete the file, I'm not quite sure. Gives some scary entries in the log, such as:

Non-sample file detected: [/downloads/<<title>>/<<title>>.mkv]

then

Failed to properly rollback the file move [/downloads/<<title>>/<<title>>.mkv] to [/movies/<<title>>/<<title>>.mkv], incomplete file may be left in target path.

then

```
Couldn't import movie /downloads/<<title>>/<<title>>.mkv: File move incomplete, data loss may have occurred. [/movies/<<title>>/<<title>>.mkv] was 5868394339 bytes long instead of the expected 2540888064.

System.IO.IOException: File move incomplete, data loss may have occurred. [/movies/Ralph Breaks the Internet (2018)/Ralph Breaks the Internet (2018) [1080p.Bluray.DTS.5.1].mkv] was 5868394339 bytes long instead of the expected 2540888064.
  at NzbDrone.Common.Disk.DiskTransferService.TryMoveFileVerified (System.String sourcePath, System.String targetPath, System.Int64 originalSize) [0x00047] in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskTransferService.cs:564 
  at NzbDrone.Common.Disk.DiskTransferService.TryMoveFileTransactional (System.String sourcePath, System.String targetPath, System.Int64 originalSize, NzbDrone.Common.Disk.DiskTransferVerificationMode verificationMode) [0x0018b] in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskTransferService.cs:522 
  at NzbDrone.Common.Disk.DiskTransferService.TransferFile (System.String sourcePath, System.String targetPath, NzbDrone.Common.Disk.TransferMode mode, System.Boolean overwrite, NzbDrone.Common.Disk.DiskTransferVerificationMode verificationMode) [0x003c2] in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskTransferService.cs:299 
  at NzbDrone.Common.Disk.DiskTransferService.TransferFile (System.String sourcePath, System.String targetPath, NzbDrone.Common.Disk.TransferMode mode, System.Boolean overwrite, System.Boolean verified) [0x0000e] in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskTransferService.cs:183 
  at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile (NzbDrone.Core.MediaFiles.MovieFile movieFile, NzbDrone.Core.Movies.Movie movie, System.String destinationFilePath, NzbDrone.Common.Disk.TransferMode mode) [0x0012b] in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:120 
  at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile (NzbDrone.Core.MediaFiles.MovieFile movieFile, NzbDrone.Core.Parser.Model.LocalMovie localMovie) [0x00052] in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:82 
  at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile (NzbDrone.Core.MediaFiles.MovieFile movieFile, NzbDrone.Core.Parser.Model.LocalMovie localMovie, System.Boolean copyOnly) [0x000b0] in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:69 
  at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import (System.Collections.Generic.List`1[T] decisions, System.Boolean newDownload, NzbDrone.Core.Download.DownloadClientItem downloadClientItem, NzbDrone.Core.MediaFiles.MovieImport.ImportMode importMode) [0x00258] in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieImport\ImportApprovedMovie.cs:109 

```

**To Reproduce**
Can't be sure if this happens every time a sample is included, as I have just noticed the problem

**Expected behavior**
It would be great if it just ignored the sample, imported the movie file and continued seeding both until seeding was complete, then deleted the sample as part of cleanup.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] DSM 6.2 and docker
 - Mono Version: Mono 5.18.0.240
 - Version [e.g. 22] 0.2.0.1293

**Debug Logs**
I didn't have debugging enabled when I noticed the issue, and it's kind of a hassle to purposefully look for a release to download that includes a sample. I can try if absolutely necessary when I have time, but thought I'd report it first. I don't know if it might be related to #2485 or #2501

**Comment by a575606** [comment]
Also forgot to mention. File seems fine on disk, plays fine and renamed properly, but doesn't show up in the 'files' section of the movie in radarr.

**Comment by a575606** [comment]
Um.... no. How is that a support issue?

**Comment by galli-leo** [comment]
According to the error message you posted, Radarr is not importing your files because Radarr sees that the file size has changed after moving. That has nothing to do with samples and is very likely something not related to Radarr

**Comment by a575606** [comment]
I find it pretty unlikely that it's file system related. The chance of a file system error only occurring in radarr and only after it tries to import a torrent containing a sample seems rather unlikely. At the very least, having sample files winding up stuck in the queue doesn't seem to be the intended behavior. Plus the errors imply potential data loss.

I would have thought it's at least worth a look

**Comment by galli-leo** [comment]
Without any log file, it's impossible for me to take a look.

It doesn't have to be file system related, it could also be another program interacting with the file. What is really strange, is that the file seems to be bigger than Radarr expected. Maybe your torrent client wasn't finished with downloading?

The errors imply potential data loss because the file "changed" its size after the move.

I strongly recommend you go to one of our support channels where people can try to help you diagnose the issue. I think it's unlikely that this is caused by Radarr and extremely unlikely to be caused by only Radarr and not something specific to your configuration.

I download a lot of files with samples and they get moved fine without any errors.

**Comment by a575606** [comment]
Well, by happy accident I actually have debug logs. I must have forgotten to turn the log level back last time I set debugging. However, and I don't mean to be touchy, but whenever a dev closes a bug report immediately without researching the issue or offering any kind of solution, I don't really get the feeling there's a lot of interest in looking into the problem. 

If you are arguing that this may be caused outside of radarr, then perhaps I wasn't clear. The error only exists in radarr. On the file system, the movie file gets renamed and imported properly and remains there even after the error. The error snippets I posted are timestamped within 1 min of each other. So even if another program was involved, for it to interfere at that exact moment, twice, seems to leave a lot up to coincidence. 

Honestly, this issue seems way too specific to get much help from a support forum. 

I'm happy to send the log if you want to reopen and take a look at the issue. Just would prefer sending it non-publicly if possible? 

Otherwise, I'll look through the code myself, but would save me a lot of time if you could point me in the direction of the section the handles importing, detection of samples and handling sample files. It's in C#, right?

**Comment by galli-leo** [comment]
> However, and I don't mean to be touchy, but whenever a dev closes a bug report immediately without researching the issue or offering any kind of solution, I don't really get the feeling there's a lot of interest in looking into the problem.

One of the reasons for this (and the support tag) is, that a lot of issues get opened here and most of them without logs, clearly support issues, etc. Rest assured I try to look into issues, if it's not immediately clear if it's a support issue.

I looked at your issue and if the exception you posted is the main one, this has nothing to do with samples. If you look at the exception, you will see the stack trace which shows you the exact file and lines where the issue occured. It's in a part that is long after sample checking etc. Why do you think this has something to do with samples? Maybe there are other errors? I also presented you with some options to get your issue resolved.

You should post the log here, there shouldn't be any important information in there. Else, other people (than me) cannot help you.

> Non-sample file detected: [/downloads/<<title>>/<<title>>.mkv]

This is not a scary message, that's a very normal (and good message) to see.

> System.IO.IOException: File move incomplete, data loss may have occurred.

Yes this is a scary message, but is very likely due to your setup, for a few reasons:

1. I have not have anyone open an issue here or seen someone on discord with this message. So if this was a bug in Radarr, it would have to be extremely rare.
2. While the message says data loss may have occurred, if you read the message it says: file was $currentSize long instead of $originalSize. However, the current size of the file is larger than the original size. This is very strange and I have no idea how you would even have code that has a bug that does this.
3. We just call your system's respective call for moving files, I don't see how that could have a bug that leads to bigger file size after finishing the move.

A few possible causes for the issue:
1. Your drives are failing. I have heard from multiple people who have noticed drives failing only after Radarr had an exception.
2. If you have your movie files on a network storage, the connection might flaky and somehow causes bytes to be transferred twice.
3. Your download client has not finished downloading yet, but told Radarr it was finished.
4. Radarr has a bug in it's file moving code (very unlikely as explained above).
5. Mono has a bug in it's file moving code (also very unlikely, but I have seen some strange mono bugs)

**Comment by a575606** [comment]
Taken as 3 isolated events, I'd understand your questions. However, as I've explained, they're a sequence, which has occured exactly twice, prompted by the import of a movie with a sample included on both occasions. I did run smart tests on my drives (no errors), but what doesn't seem to be sinking in is that there was no change to the actual file. Several imports (without samples) have gone through perfectly fine before and after. The two with samples which prompted the errors haven't actually changed in file size. They aren't corrupted files. Radarr only thinks they are... so I'd be really surprised if Radarr isn't the source here, but I don't want to argue with you about it. 

Are you willing to at least tell me which file to look in to trace through the import procedure and what happens when a sample is detected?

**Comment by galli-leo** [comment]
@a575606 These are not 3 events. There are at most two of them. The failed move and the Non-sample file. But the Non-sample file will be logged after an import has happened. Radarr will import your files, then check if the folder is "empty". If there are non sample files, it will not delete the folder after an import. Hence the message you see.

I recommend you take a look at `DiskTransferService.cs` in `src/NzbDrone.Common/Disk/`, especially the functions you see in the stacktrace of your exception.

If you really want to, you can also take a look at `DownloadedMovieImportService.cs` in `src/NzbDrone.Core/MediaFiles/` (`ProcessFolder` and `ShouldDeleteFolder`). But again, those have nothing to do with your issue.

> The two with samples which prompted the errors haven't actually changed in file size.

They might have in the destination of the move. Are the filesizes Radarr initially had correct for them? e.g. 2540888064 for the one in the exception?

**Comment by a575606** [comment]
I'm happy to provide you a debug log, but not so happy uploading a list of a bunch of movies I've downloaded. Is there no way to provide this non publicly?

**Comment by galli-leo** [comment]
You can send it to me in a mail leonardo.galli@bluewin.ch

**Comment by a575606** [comment]
ok sent

**Comment by galli-leo** [comment]
The log you sent me doesn’t contain the exception you had. Please send me the log files with the exception in it. Also what about the actual file size of the file Radarr tried to import?

**Comment by a575606** [comment]
Sorry about that, I thought it was the right day, but I didn't double check. I did stumble on another piece of the puzzle however. In addition to samples, in both cases the actual movie files were compressed in rar format, which adds another variable into the mix.

After seeing that, I decided to put this to one side for the time being. It seems we got off on the wrong foot, which wasn't my intention, and since it was some days before I noticed the problem, there's a lot to retrace. It's all taken enough of each of time already, especially if it's not a common error. 

I'll clear out the torrents that have the error and see how it goes. If it comes up again, I'll know what to look for and I'll send you a log. Otherwise, perhaps it was a fluke. Thanks anyway. 

Thanks for the

**Comment by galli-leo** [comment]
@a575606 No problem. What torrent client are you using and do you have an auto unpack script? What I think went on, is that the torrent client told radarr your download was finished, but the unpack feature / script did not finish yet. Radarr starts to import, but the file isn’t fully unpacked yet. Hence after the move by Radarr, the file is bigger then it was in the beginning and the error you saw.

**Comment by a575606** [comment]
That's possible. Im using synology disk station which is basically transmission. Auto unpack was disabled, but I have turned it in now and keep an eye out next time I get a packed release. Thanks for the help.
