### ISSUE TITLE
 Problem on search with Slash, Failed to map movie

### ISSUE THREAD

**Issue by ZiemusG** [Radarr/Radarr#3376]
Hi gays 
i have a problem with indexer BtGigs, this is polish privet tracker and serve title in two option separated with slash '/'   polish name / original name.
example:
Matrix: Reaktywacja / The Matrix Reloaded 2003 MULTi 2160p UHD BluRay REMUX HDR HEVC TrueHD ATMOS 7.1-inTGrity

I got "released rejected" with text:
Failed to map movie, found title Matrix Reaktywacja / The Matrix Reloaded, expected one of: The Matrix Reloaded, The Matrix 2, The Matrix 2: Reloaded, The Matrix Reloaded: The IMAX Experience, Matrix 2

this situation repeat itself when title is double "polish/original "

i set Parser Leniency to: Lenient parser 
My Radar: Radarr Ver. 0.2.0.1293 develop
My Jacket: Jackett Version 0.10.804.0

**Comment by galli-leo** [comment]
You can use lenient mapping in the mean time.

**Comment by ZiemusG** [comment]
I wrote in the previous comment that I set it up, unfortunately it did not solve the problem.

**Comment by TomMaSS** [comment]
Hey

Have same problem with russian indexers. I find resources on trackers but not auto-download them because find 'Slash' in movie title

`Failed to map movie, found title Король Лев / The Lion King, expected one of: Король Лев, The Lion King`

`Failed to map movie, found title Человек-паук Вдали от дома / Spider-Man Far from Home, expected one of: Человек-паук: Вдали от дома, Spider-Man: Far from Home, Spider Man 05 Spider Man Far from Home, Spider-Man 2: Far from Home`

How can i solve this problem?

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.

V3 has had significant language improvements

**Comment by Qstick** [comment]
Still an issue, but will be covered in AKA support
