### ISSUE TITLE
No Cast metadata in NFO for Kodi

### ISSUE THREAD

**Issue by triksmelb** [Radarr/Radarr#3421]
Radarr created NFO files for Kodi do not contain any cast information.

Kodi 18.1 default skin displays scraped local NFO metadata correctly but the NFO built by Radarr doesn't contain any Cast information resulting in Kodi displaying "Cast not available".

In Radarr, metadata settings for Kodi are:

Movie Metadata - Enabled
Movie Images - Enabled
Use Movie.nfo - Enabled

The lack of Cast data also causes Kodi to not be able to "Search by Actor".

![IMG_3085](https://user-images.githubusercontent.com/12489962/54194659-dc571a80-4510-11e9-8bad-781e49943076.jpg)

**Comment by hikaricore** [comment]
You can add Genre to the list as well. I hope you don't mind me chiming in, but I figured rather than making a whole new issue/request thread, this was easier.

**Comment by iap3tos** [comment]
This is still an issue

**Comment by hikaricore** [comment]
Just for reference to anyone following this issue, the applicable code for Kodi metadata creation is here: https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs

That said, I'm not about to go mucking around in there right now, but if time permits it doesn't look terribly difficult to add things to, albeit there may be a requirement for Radarr to already have scraped the needed information from TheMovieDb and/or other sources before it can be parsed.. further investigation may be needed here.

**Comment by dmrazor** [comment]
Running in to this issue as well. Good to know it's on the list!

**Comment by Yaff1e** [comment]
Same problem here as well

**Comment by thomas-rabiller** [comment]
Any news on this? I experience the same problem with hardly any metadata being added to the kodi .nfo files beside title/plot/rating/year/studio/premiere date...

**Comment by quachc** [comment]
+1
And it would be nice if collections would be added as well.

**Comment by fryfrog** [comment]
It'll get fixed when some developer has interest in fixing it. If this is important to you, learning .NET and getting started w/ Sonarr/Radarr will probably be the fastest way to get it done.

**Comment by John-Gee** [comment]
> It'll get fixed when some developer has interest in fixing it. If this is important to you, learning .NET and getting started w/ Sonarr/Radarr will probably be the fastest way to get it done.

Fair enough. I've started looking at this, and I have half a prototype working, but I'll need some help to make it clean I think.

**Comment by fryfrog** [comment]
Awesome, I'd suggest hopping on Discord where you can usually find @Qstick and @ta264 around. Depending on how Radarr specific it *isn't*, maybe even @markus101 or @Taloth will chime in.

**Comment by John-Gee** [comment]
I will do that, thank you!

**Comment by ciajus** [comment]
Any good news?

**Comment by John-Gee** [comment]
Not quite, I did a chunk of the work, then got stuck and needed either to unstuck myself or to get back to @Qstick who offered to help but I haven't done either yet.
You can see my current stuff in https://github.com/John-Gee/Radarr/commits/kodi_metadata but it might need rebasing as it is a couple weeks old now.

In summary:
- the code can grab the cast and crew from themoviedb
- the code can write the cast and crew to the nfo

but in between those there are 2 issues:
1- The cast somehow gets lost between those 2 steps and since the whole thing is multithreaded it's not easy to see where I'm missing a copy/save.

2- Adding support for the crew requires a change to the DB that I have not done yet.


(The crew gives the writer, director, etc other things can be nice to filter by in Kodi.)

and of course it is not said my code is up to par quality wise, I have not worked in .Net in many many years... but thank you for reminding me!

**Comment by ciajus** [comment]
Thank you for your hard work, but to be honest I did not understand a word you say :D And I didn't mean that english is not my native language, but I'm not a programmer or anything close to. But I am really glad that someone is still looking at this issue. Is really annoying, but for now the only solution I know is to refresh metadata by Kodi itself after Radarr add movie to collection.

**Comment by John-Gee** [comment]
Well let me try to summarize it in an a nicer way (and English is not my native language ;)):

Imagine instead of computer code, the work is done by 3 humans.
One human reads the information from the website, one human writes the information for Kodi, but the third human that is supposed to get the information from the reader and pass it to the writer is missing and we (I) don't know why.


You probably won't like this any better, but here's a script I use to currently work around this issue instead of manually refreshing the metadata in Kodi:

https://gist.github.com/John-Gee/4818b42424262b1993a336d852007612

This reads Kodi's database, finds all movies without a cast, and force-refreshes them. It's written for Linux but it can be adapted for other OSs.

**Comment by ciajus** [comment]
Ok, now I see what you mean :)

BTW:
This script sounds exactly what I need. However, I have no idea how to implement it into my Kodi. I use Raspberry Pi 3 with LibreELEC connected to my TV and I admit that I am a complete noob when it comes to these matters. That's why I chose LibreELEC because of its simplicity of use and UI.

**Comment by John-Gee** [comment]
Oh, if you use LibreELEC I believe it is Linux-based so it should be fairly easy.

Before I go any further, let me say that, at least in theory, you should never copy paste code you do not understand from untrusted sources on the Internet, as you wouldn't know if it safe or trying to steal stuff from you...

Since this is getting a bit out of topic for this bug it might be better for you to come on the radarr discord, ping me there and I'll try to help you with this (same john-gee name there).

**Comment by Qstick** [comment]
This will be implemented in V3 (Aphrodite), should be available when this is merged: https://github.com/Radarr/Radarr/pull/3993
