### ISSUE TITLE
Movie not being added to activity/queue

### ISSUE THREAD

**Issue by aszwet1** [Radarr/Radarr#3446]
**Describe the bug**
When downloading a specific movie on radarr (docker linuxserver.io) it won't show up in activity/queue.  It does get downloaded (and shows in activity/history), but never picked up.

This issue DOES not appear to happen on windows, only the linux version.

Radarr Ver. 0.2.0.1293

LOGS:
[radarr-logs.txt](https://github.com/Radarr/Radarr/files/3000631/radarr-logs.txt)

**Comment by bserrao** [comment]
I think it's indeed a bug of some sort. I'm also verifying this behaviour on the latest version. 
Before when importing a movie radarr showed it in activity (progress bar and everything), now the movie just gets imported without showing in the activity tab.
I don't know which version introduced this behaviour because i didn't update for a long time...
