### ISSUE TITLE
Net Import Sync adds same movies multiple times

### ISSUE THREAD

**Issue by RaRaRadarr** [Radarr/Radarr#3453]
# Description
Every time Net Import Sync runs, the same movies are added. This issue is related the following posts:
- https://www.reddit.com/r/radarr/comments/9jdwlq/radarr_keeps_downloading_the_same_movie/
- https://github.com/Radarr/Radarr/issues/1428
- https://github.com/Radarr/Radarr/issues/1108

Some issues are left open or didn't receive a response on a question from the original poster, therefore I open this as a new issue and provide as much information as possible.

From this issues and reddit posts, I made sure that I had the following settings checked:
- Download Propers: *disabled*. Why? Even if the Cut-off is met, Propers can override the download of the same movie.
- Check that the Cut-Off is on the lowest quality.
- Update to the latest version

# Expected behavior
Because I have checked the above settings I assumed that Radarr would not download these movies multiple times.

# Screenshots
## File Management
![image](https://user-images.githubusercontent.com/9286611/55071515-256aab00-5089-11e9-92c9-72804e788d48.png)
## Profile
![image](https://user-images.githubusercontent.com/9286611/55071555-3b786b80-5089-11e9-8811-0d44a175a0ea.png)
![image](https://user-images.githubusercontent.com/9286611/55071839-f43eaa80-5089-11e9-9aa0-ba4fc8025e38.png)
## Download Client settings
![image](https://user-images.githubusercontent.com/9286611/55071886-0caec500-508a-11e9-96be-45f3fa9390b2.png)

## Cutoff unmet
![image](https://user-images.githubusercontent.com/9286611/55072179-b2623400-508a-11e9-94e9-4f3c1fc03f17.png)
## !! Notice that the movies of the same quality are downloaded!!
![image](https://user-images.githubusercontent.com/9286611/55072242-dcb3f180-508a-11e9-883b-5ca89af3c4ae.png)
[radarr.txt](https://github.com/Radarr/Radarr/files/3012894/radarr.txt)

## "Interesting Logs" when the duplicates are added:
![image](https://user-images.githubusercontent.com/9286611/55071481-066c1900-5089-11e9-9db1-dbd88b21b592.png)

**Desktop (please complete the following information):**
 - OS: Docker
- Version: 0.2.0.1293
- Mono Version: 5.14.0.177 (tarball Mon Aug 6 09:13:43 UTC 2018)

**Debug Logs**
[radarr.txt](https://github.com/Radarr/Radarr/files/3012911/radarr.txt)
https://mega.nz/#!W2xx1IrQ!Tc5EFbQY2uDogy5NJEOMhy0-4nFefFf94AjPDZs5mos

**Comment by RaRaRadarr** [comment]
Tried it also with another Download client: Qbittorrent, same issue:

![image](https://user-images.githubusercontent.com/48988134/55088809-ab4c1d80-50ac-11e9-8a16-fb0ed2aa846b.png)

**Comment by midnightClub543** [comment]
Getting same issues, 3 to 5 downloads of same movie.

**Comment by fryfrog** [comment]
This is almost always a combination of a few issues that are kind of outside of Radarr's control. It also happens to Sonarr.

Usually it is a miss-tagged movie or a movie named vastly differently than expected. In the RSS, a movie will claim to be imdbid 99999 which is `Movie Title`, but the download queues up and is named `Totally Different Movie Title` and thus doesn't match anything in Radarr (or at least, not the intended movie), so when it shows up *again*, it "matches" again and then also isn't correct.

You need to dig into each movie it happens with to figure out exactly what the issue is, but it'll turn out to be something similar to that.

Turn your logging up to trace and track it as it happens again.
