### ISSUE TITLE
split spanish language

### ISSUE THREAD

**Issue by icf20** [Radarr/Radarr#3467]
imo the spanish langunage (said language does not exist tho) need to be split in two or more

1. spanish-español or castellano
2. spanish-latino or latino 

this is a issues because the accent and certain words, for example coger in spain means to take, while in argentina means to fuck 

every bit of content is doubled once for span and second time latino america

:smiling_imp:  if you want to start a flame war just that the simpsons are better in latino or castellano 

[AB#876](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/876)

**Comment by luismanson** [comment]
Well, i have that exact same problem, i want to get the simpsons in 'español latino' and cant figure how to do it... 
Google brought me here. Is there any workarround ?

**Comment by icf20** [comment]
>  i want to get the simpsons in 'español latino' 

OMFG!!! u monster, do you want to star t war or something

**Comment by mankalan** [comment]
Hello,
I think this is a problem and not a request for "Enhancement".
It really is a problem, because when downloading, it does not differentiate between Spanish-Latin and Spanish-Spain so it downloads from the first thing it sees and we don't get the correct audio and believe me, it is very annoying not to have the correct audio.
This means that we cannot establish an order of preference, it remains stuck in the language that was initially downloaded, some correctly, others incorrectly.

To distinguish it is very simple:
Spanish-Spain = Castellano, ES, Español, Español-España, Español-Castellano, Spanish, Spanish-Spain, Spanish-ES
Spanish-Latin = Latino, LAT, Latinoamericano, Spanish-Latino, Español-Latino, Spanish-USA, Spanish-MX, 

I leave some examples: 
-Ava (2020) [BluRay 720p X264 MKV][AC3 5.1 **Castellano**]
-De amor y monstruos 2020 **SPANISH ENGLISH** BluRay 2160p REMUX x265
-Godzilla.vs.Kong.2021.**SPANiSH**.1080p.HMAX.WEB-DL.x264-dem3nt3
-El Caballero Oscuro (2008) [BluRay 720p X264 MKV][AC3 5.1 **Castellano**]


-El agente topo (2020) BR-RIP 1080p **LAT**
-Batman The Dark Knight 2008 1080p Dual Audio **Espanol Latino**, Ingles Subs
-El caballero oscuro 2008 CAM Xvid **Spanish Latino**
-Batman - The Dark Knight (Audio **Latino**) 2008 TS-Screener HQ 


_Please, the entire Spanish-speaking community would appreciate it._

Thanks.
