### ISSUE TITLE
using hardlinks with synology download station results in duplicated data

### ISSUE THREAD

**Issue by ephur** [Radarr/Radarr#3485]
**Describe the bug**
hard linking a release works in the opposite direction it should when using Synology Download Station

**To Reproduce**
1. Ensure completed download handling is enabled, download station is the client, and 'use hardlinks instead of copy'  on media management.
2. In synology setup download station, and do not have it copy any files.
3. Download a release 

**Expected behavior**
I expected Radarr to make a link to the file from the torrent without any sort of modification to the file that was part of the torrent.

**Screenshots**
```pwd && stat \@download/20/*/*.mkv | grep Links ; stat Media/Movies/T*ll*2012*/*.mkv | grep Links
/volume1
Device: 21h/33d Inode: 35503       Links: 1
Device: 25h/37d Inode: 42692       Links: 1
``` 
The first shows the hard link download station makes upon downloading the media. As can be seen the inode is different, and each file has a single reference/link.

**Desktop (please complete the following information):**
 - OS: Synology DSM (Linux) running Synology Docker
 - Version 0.2.0.1331
- Mono Version 5.20.1.19 (tarball Thu Apr 11 09:09:21 UTC 2019)

**Debug Logs**
```
radarr.debug.txt:19-4-15 15:10:08.4|Debug|MovieFileMovingService|Moving movie file: /volume1/Media/Downloads/---/---.mkv to /volume1/Media/Movies/- (2009)/- (2009) Bluray-1080p.mkv
radarr.debug.txt:19-4-15 15:10:08.4|Debug|DiskTransferService|Move [/volume1/Media/Downloads/-/-.mkv] >
radarr.debug.txt:19-4-15 15:10:11.7|Info|MovieService|Linking [-.mkv] > [[- (2009)][tt-, -]] 
```

**Comment by ephur** [comment]
It occurred to me that the original move can't be the reason for the duplication of data, as the inode wouldn't change as the files are on the same volume. Tested within docker and without on DSM and the inode with move did not change from the download to the movie path. Will continue to dig. Closing.

**Comment by R91g** [comment]
I have the same problem. Did you solve it?
With setting "Use Hardlinks instead of Copy"
When I download a movie, the movie move and rename correctly but the space is duplicated until don't remove the movie from Download Station.
The Download folder is empty, there isn't any hardlink.
The movie seeds without problems in Download Station (thanks to temporary files of DS).

If I download a torrent without Radarr and then I rename or move it, the space isn't duplicated and seed correctly.

Download folder and Movies folder is in the same volume (disk) in DSM.

**Desktop (please complete the following information):**
OS: Synology DSM (Linux) running Synology Docker
Version 0.2.0.1293
Mono Version 5.20.1.19 (tarball Thu Apr 11 09:09:21 UTC 2019)

**Comment by R91g** [comment]
I solve this problem.

When you configure Docker you need to add only one root folder with Download and Movies as subfolder. If you add Download and Movie separately hardlink will fail.

For example:
I have this folder:
/volume1/NAS/Download
/volume1/NAS/Movies

If I configure Docker image with two folder separately [Local path ---> Docker Container path]:
/volume1/NAS/Download ---> /Download
/volume1/NAS/Movies---> /Movies

Hardlink fail and Radarr duplicate space, but if I configue Docker image with only one root folder:
/volume1/NAS/ ---> /volume1/NAS/

Radarr works perfects without duplicate data.
