### ISSUE TITLE
Refresh Movie	time

### ISSUE THREAD

**Issue by jscottdouglas** [Radarr/Radarr#3556]
Is there any way to increase the refresh movie time frame or to stop it from auto doing a refresh there is really no reason for it to constantly keep scanning my entire library of existing content daily. for example currently i have a rather large library and it seems to take 6 days to do a whole refresh.  (over 2k movies) it's slow it says this process runs daily.  I am currently on 0.2.0.1350 - 30 May 2019 build

**Comment by tkdrob** [comment]
I currently have a pull request open and waiting to be approved that gives you this option. In the mean time, you are welcome to try my fork

**Comment by jscottdouglas** [comment]
@tkdrob I installed your version thank you.

**Comment by Qstick** [comment]
This should be better handled in V2 as you can decide if scanning is done after refresh and old movies get refreshed every 180 days instead of 30.

**Comment by bob454522** [comment]
Please merge this, Please!  
i have a massive radarr library of ~ 20k movies,  radarr and its db are on NVMe and movies are on fast HW raid card, however this still runs for several days due to the large size of my lib.  thus it ends up such that this is just about always running 24/7.  It does not make sense that we cant disable or change this.  thanks

**Comment by Qstick** [comment]
Switch to V3 and get your Radarr settings right.. we have users with 160k movies that take 16min on a refresh. Jump on discord if you want to discuss but we are not planning a setting for this.
