### ISSUE TITLE
Incorrect values from lookup

### ISSUE THREAD

**Issue by jurpeedurp** [Radarr/Radarr#3576]
Please advise as to whether this is a valid issue(maybe I misunderstand the expected behaviour), why this may be, and if you would be interested in a PR.

**Describe the bug**
An http get request to /api/movie/lookup does not return valid values for downloaded, hasFile, sizeOnDisk, and folderName even though the movie does exist on disk.  The UI does correctly show that the movie already exists.  This endpoint should reflect that and return appropriate values.

**To Reproduce**
Send an http get request to /api/movie/lookup?term=iron man

**Expected behavior**
The json returned should have correct values for the aforementioned properties

**Screenshots**
<img width="872" alt="Screen Shot 2019-06-19 at 7 27 40 AM" src="https://user-images.githubusercontent.com/46579599/59769632-c40b4000-9263-11e9-99a1-6e2be42d2427.png">

**Desktop (please complete the following information):**
 - OS: Docker
 - Mono Version: Mono Version: 5.20.1.19 (tarball Thu Apr 11 09:02:17 UTC 2019)
 - Version  0.2.0.1344

**Debug Logs**
N/A

**Comment by hmhrex** [comment]
I'm running into this issue as well. This pretty much breaks what I'm trying to build. Has anyone found a workaround for this?

**Comment by alangregory** [comment]
Confirmed same problem on :
- Version 0.2.0.1293
- Mono Version 6.0.0.319 (tarball Fri Aug 9 16:23:57 UTC 2019)

**Comment by jd4883** [comment]
I also hit this issue in the latest Aphrodite build. Definitely limits my ability to write code around it. Are there alternate endpoints to get similar data? I haven't seen any documented but peeking at Aphrodites code base with minimal familiarity it looks like there may be some new endpoints.

The characteristics that are missing are file level information that are specific towards the collection being worked with instead of grabbing imdb values. 

Would be really nice to see this fixed or have additional endpoints to hit to get file level information on a given movie. Thanks!
