### ISSUE TITLE
Successfully Imported Movie generates failed import errors

### ISSUE THREAD

**Issue by jennec** [Radarr/Radarr#3585]
Describe the bug
Setup: Radarr & SAB (Running in Docker Containers from Linuxserver.io)
Paths are identical
Permissions are set to 777 for file and folders plus both apps run as same PUID and PGID

When Radarr process is a successful download from SAB it does not remove the movie from the Activity queue and does not tell SAB to remove the entry from SABs history.  

Log files fill up with error from the DownloadedMovieImportService stating "import failed, path does not exist or is not accessible by Radarr: /downloads/movies/foldername"
if you check this location the error log is correct as the folder has been cleaned up by Radarr after is successfully imports the movie.

FYI:  SAB is also used by Sonarr which does not exhibit this issue. 

To Reproduce

- Choose a movie
- Radarr submits to SAB
- SAB Downloads and move to completed folder
- Radarr process files, renames and moves to the appropriate Movie folder and cleans up the download folder.
- Radarr scans folder and updates files tab of movie entry.
- Radarr keeps movie download in the Activity Queue
- Movie is not removed from SAB History.
- Radarr keeps trying to process the movie every minute because SAB still has it in its History.

Expected behavior
Radarr should remove entry from Activity queue and mark as completed
Radarr should also remove entry from SAB's History to avoid attempting to process a non-existent file path.  

Screenshots
![image](https://user-images.githubusercontent.com/4245161/60182759-d1ed3200-981c-11e9-8bd4-c0324f798c44.png)
![image](https://user-images.githubusercontent.com/4245161/60182789-e3ced500-981c-11e9-9a89-ebd28f91bb93.png)
![image](https://user-images.githubusercontent.com/4245161/60182866-08c34800-981d-11e9-8c6e-e0773c2b335e.png)
![image](https://user-images.githubusercontent.com/4245161/60182909-1d074500-981d-11e9-9060-cee7f6207a1f.png)

****Desktop (please complete the following information):****
 - OS: Docker Containers running from LinuxServer.io running on Linux Mint 19.1
 - Mono Version: 
           Radarr Container: 5.20.1.19
           Linux Mint Version: 4.6.2 (But this should not be relevant)
 - Radarr Version: 0.2.0.1344
 - SAB Version: 2.3.9 [03c10dc]

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3330152/radarr.debug.txt)

**Comment by onetonson** [comment]
Also have this issue.  In my case, from what I can tell, it's related to the Language field being null on import.  In the History table, the Language field does not allow nulls thus the history record import fails.  This happens after the file has been succesfully moved so the info remains in the queue but now Radarr can't do anything with it since the file doesn't exist.

Workaround (hack):
Modify the History table Language field to allow nulls.

NAS: Drobo5N (Linux)
Mono Version: 5.21.0.610
Radarr Version: 0.2.0.1359 (Aphrodite)

trace excerpt:

19-6-28 21:41:20.6|Trace|EventAggregator|MovieImportedEvent -> HistoryService
19-6-28 21:41:20.6|Trace|Owin|SQLite error (1299): abort at 20 in [INSERT INTO [History] ([MovieId],[SourceTitle],[Quality],[Date],[EventType],[Data],[Languages],[DownloadId]) VALUES (@MovieId,@SourceTitle,@Quality,@Date,@EventType,@Data,@Languages,@DownloadId

19-6-28 21:41:20.6|Error|EventAggregator|HistoryService failed while processing [MovieImportedEvent]

[v2.0.0.1359] System.Data.SQLite.SQLiteException (0x80004005): constraint failed
NOT NULL constraint failed: History.Languages

[radarr.trace.0.txt](https://github.com/Radarr/Radarr/files/3342419/radarr.trace.0.txt)
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/3342420/radarr.trace.txt)

**Comment by Qstick** [comment]
You really shouldn’t be using Aphrodite if you want Radarr to function @onetonson .... unless you don’t care and just want to test

**Comment by onetonson** [comment]
@Qstick, I just cant get the 'develop' branch to use Mono TLS or curl fallback on my Drobo5N, e.g. manual movie searches hang and peg the CPU.  I have the curl libraries and have set the dll.config helper file to point to it.  However, the Aphrodite branch properly fails Mono TLS and uses curl with the above setup.  I noticed the Aphrodite branch is used in the linuxserver/Radarr ARM docker repository.

**Comment by fryfrog** [comment]
Yeah, LSIO really jumped the gun. Aphrodite is *not* ready for use. Are they setting the `MONO_TLS_PROVIDER` env var?

**Comment by onetonson** [comment]
that env is not present when I list the env vars.  Also it's not explicitly set in the command line that starts Radarr in the LinuxServer. 

After Qstick suggested not to use Aphrodite, I found that there are differences in the FallbackHttpDispatcher.cs between Aphrodite and Develop.  In my case, Im in a NAS jail and Develop/Radarr would only CurlFallback if the error contained "The authentication or decryption has failed".  The error I was getting was a Webexception that contained "TLS not available" or "SecureChannelFailure" and it would just throw.
I ended up customizing the NZBDrone.Common FallbackHttpDispatcher.cs to catch Webexceptions that contained the error text I was seeing.  I then set the _curlTLSFallbackCache so Radarr would use the _curlDispatcher instead of the _managedDispatcher or worse just throwing.  Develop branch seems to be working for me now.

**Comment by fryfrog** [comment]
You're using Docker? In that case, none of them use it anymore so you're fine. But why would it even be having a problem? What version of Mono is in the container? There are some issues w/ 6.x, I *think* they have a version that uses the older 5.x line. And there are a couple other container makers like binhex and hotio that have different Mono.

**Comment by onetonson** [comment]
I'm using a Drobo5N.  Develop barfed on Drobo until I customized the fallbackhttpdispatcher.  I used docker to see how Radarr worked on a Linux box.  That's when I found they where using the Aphrodite branch.  I was able to install Aphrodite on Drobo, it worked.  It kind of helped me fix the NZBdrone.common.dll in the Develop branch.
So, I'm using Develop branch on Drobo5N natively with my custom dll.
Thx

________________________________
