### ISSUE TITLE
Importing and searching via imdb

### ISSUE THREAD

**Issue by c0rnflake** [Radarr/Radarr#362]
While importing my existing movie library there are a few titles that aren't being added,

Searching for these, ie. tt0068168 using imdb:tt0068168 in the search field returns no result.

If you go back and add a movie searching with imdb:tt0068168 returns the movie correctly.

**Comment by turkeyphant** [comment]
Can't import at all using imdb: prefix.

e.g. using "imdb:tt1322932" returns noting:

`There Was An Error Searching For 'Imdb: Tt1322932'.
If the movie title contains non-alphanumeric characters try removing them, otherwise try your search again later.`

However, http://www.imdb.com/title/tt1322932/ exists.
