### ISSUE TITLE
Add The Ability Add Filed Date in Fomat YYYYMMDD

### ISSUE THREAD

**Issue by rhettcawood** [Radarr/Radarr#3626]
I would really appreciate being able to rename a file but include the original file accessed date in the name like - {FileLastAccessedDate} ({Release Year}) {Movie Title} - This way Watched Movies and Downloaded will stay at the top of the List on Media Devices used to watch downloads...

**Comment by fryfrog** [comment]
I'll be honest, this just doesn't sound like something that will ever happen. What media server software are you using that would even need it? This would cause the file to get renamed *every* time it was accessed, which happens who knows how often. And many file systems get mounted w/ `atime` turned *off* because it has a big performance impact.
