### ISSUE TITLE
Race condition when using deluge's extractor plugin

### ISSUE THREAD

**Issue by hawken93** [Radarr/Radarr#3641]
**problem**

I think one of the more common ways to extract rar-releases is to have deluge unrar them for you into the same folder. However, there are two main problems with this:
* Nobody takes responsibility for deleting the extra files
* radarr sees that deluge is seeding and starts importing before unrar completes, leaving truncated or missing files in the library

**Describe the solution you'd like**

* In the related thread #1771 a comment shifts the responsibility to the download client to process the downloads, so of course one possibility would be for the torrent client to delay going to seeding or having a processing stage before seeding stage.
* It's also possible to ask for radarr to implement unrar-ing, however this is platform specific if using external binaries and I understand that this is more complex
* A hacky way could be to look for unrar processes in the system and wait until they are gone. This is platform specific but less work.

**Describe alternatives you've considered**
I have no idea what to do about this. Maybe have deluge unrar to a different path and then move the files back in once they are done with a hacky script? Will radarr give up as the files will show up later? Maybe radarr could have some command or script hooks that we could use for this kind of stuff?

**Additional context**
* related to #1771,  but specific to the deluge client + extractor plugin
* Solving this would be a big win for me because I end up with double the amount of downloaded stuff because files fail and I end up trying again

**Comment by hawken93** [comment]
I started with a feature request tag, but depending on perspective it may differ

**Comment by NineBall8** [comment]
> **problem**
> 
> I think one of the more common ways to extract rar-releases is to have deluge unrar them for you into the same folder. However, there are two main problems with this:
> 
> * Nobody takes responsibility for deleting the extra files
> * radarr sees that deluge is seeding and starts importing before unrar completes, leaving truncated or missing files in the library

A workaround I can recommend is using rar2fs and let it handle any compressed files.

**Comment by hawken93** [comment]
I'll try out rar2fs :)

I also forgot to mention that my download client resides in a different vm and so the unrar process won't be visible...

**Comment by fryfrog** [comment]
The post processing on *all* torrent clients *sucks*. The torrent finishes downloading, they declare it done and *then* they start unpacking (or whatever).

You have two-ish choices. Make your unpack go somewhere near by and then atomic move it into the torrent folder so it *instantly* appears *or* use a setup where hard links work, since it can import as soon as it shows up and the unpacking will continue even *after* the import.

I don't think Sonarr or Radarr really deal w/ this very well.

You might also like a [post-import cleanup script](https://gist.github.com/fryfrog/d1f38b805a270a92bff085536dcfd7e2) to remove the video file from packed torrents, so you maybe don't waste space or have a super messy torrent folder.
