### ISSUE TITLE
Force Download - Adding a secondary year is not remembered for future searches.

### ISSUE THREAD

**Issue by MollyBe** [Radarr/Radarr#3667]
A movie is listed in Radarr with year 2010. When you search the correct movies are listed as 2011.
When you use force download it says

"Force Download: The year 2011 does not match the expected release year. This could lead to problems when Radarr wants to import your movie, if you click force download below, the year will be added as a secondary year for this movie."

Based on this you would expect future searches to identify the second year. This is not happening. After forcing a download all future searches still display 2011 as an incorrect year with the following error:

"Failed to map movie, expected year is 2010, but found 2011"

**Comment by MollyBe** [comment]
It should be added that after the information is corrected in TMDB, and time is given for Radarr to update its API information, using the Radarr function "Update movie info and scan disk" does not update the year. The current work around requires deleting and adding the movie again.

**Comment by MollyBe** [comment]
b

**Comment by fryfrog** [comment]
Check the alternate titles in TMDB, you might have to edit it to see them. I bet there is a wrong year in there.

**Comment by MollyBe** [comment]
Thank you that is a great work around. 

As I outlined in this issue though, when refreshing the movie after updating the year on TMDB, the year is not updated in Radarr. The year is only updated if you delete the movie, and then import the movie to Radarr again.

**Comment by fryfrog** [comment]
Ah, right sorry! I think I've even seen this issue reported in the past. Sorry I missed that. :)

**Comment by MollyBe** [comment]
No worries, I think https://mappings.radarr.video/ is also meant to list secondary years and show them on your the radarr movie's pages' but is currently nonoperational in this scenario.

**Comment by lebnet** [comment]
Sorry to dig up this topic. But after searching on several other pages, I can't find a solution.
https://mappings.radarr.video is no longer active as far as I can see.
I'm in v3. I have an example (among others) with the movie 300. IMDB says 2006. TMDB says 2007. My tracker lists many films with 2007 and which correspond to my profiles, custom format etc but none in 2006 so automatic grabbing doesn't work because it finds nothing in 2006.

Other issue https://www.reddit.com/r/radarr/comments/asip90/release_year_causing_radarr_not_to_pull_release/

Other issue #1886
