### ISSUE TITLE
Radarr remove some part of title while searching torrent (the % and) missing from search

### ISSUE THREAD

**Issue by antipiot** [Radarr/Radarr#3679]
Hello everybody! 

New user here facing some troubles :-)

**Describe the bug**
When looking for torrent "The Nutcracker and the Four Realms" Raddar only look for "The Nutcracker Four Realms" wich prevent all results to be found: if i do the search manually using full title: every results are shown correctly

**To Reproduce**
Radarr:
Manually search or let raddar search for "The Nutcracker and the Four Realms" movie: only 2 torrent reported 

Manual test:
go on https://www2.yggtorrent.ch/
search for "The Nutcracker and the Four Realms": every results found correctly.
search for "The Nutcracker Four Realms" Only 2 results found wich prevent good finds.
Manually search or let raddar search the movies: only 2 torrent reported when there are plenty avaible searching with the full movie name:

**Expected behavior**
Radarr remove as it can be seen on debug logs some parts of the title, wich prevent all the torrent to be found:
**nutcracker%20four%20realms%202018**

**Desktop (please complete the following information):**
Docker

**Debug Logs**
`19-8-12 19:38:46.0|Info|NzbSearchService|Searching 1 indexers for [The Nutcracker and the Four Realms]
19-8-12 19:38:46.0|Debug|Torznab|Downloading Feed http://nas:9117/api/v2.0/indexers/yggtorrent/results/torznab/api?t=search&cat=2000,2010,2020,2030,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=nutcracker%20four%20realms%202018
19-8-12 19:38:46.3|Debug|NzbSearchService|Total of 2 reports were found for [The Nutcracker and the Four Realms] from 1 indexers
19-8-12 19:38:46.3|Info|DownloadDecisionMaker|Processing 2 releases
19-8-12 19:38:46.3|Debug|Parser|Parsing string 'The Nutcracker Four Realms 2018 MULTi TRUEFRENCH 2160p UHD BluRay REMUX HDR HEVC EAC3 7 1-TOXIC'
19-8-12 19:38:46.3|Debug|Parser|Movie Parsed. The Nutcracker Four Realms - 2018 
19-8-12 19:38:46.3|Debug|ParsingService|Language(s) parsed: French
19-8-12 19:38:46.3|Debug|QualityParser|Trying to parse quality for A Movie 2018 MULTi TRUEFRENCH 2160p UHD BluRay REMUX HDR HEVC EAC3 7 1-TOXIC
19-8-12 19:38:46.3|Debug|ParsingService|Quality parsed: Remux-2160p v1 (None)`

Sorry if this has already been asked: tried to find answers but cant find anything for this.

Regards!

JS

**Comment by twolaw** [comment]
I can reproduce this bug too.
Searching for "Into the Wild" returns 0 results because request becomes "into wild".
Doing the search directly in Jackett ui returns 11 results.

debug log:
`19-8-13 11:54:44.3|Info|NzbSearchService|Searching 1 indexers for [Into the Wild]19-8-13 11:54:44.3|Debug|Torznab|Downloading Feed http://localhost:9117/api/v2.0/indexers/yggtorrent/results/torznab/api?t=search&cat=102183&extended=1&apikey=(removed)&offset=0&limit=100&q=into%20wild%202007
19-8-13 11:54:45.0|Debug|NzbSearchService|Total of 0 reports were found for [Into the Wild] from 1 indexers
`

**Comment by fryfrog** [comment]
Might also be worth asking Jackett about this. Seems weird that indexers aren't doing an and type search of "into" and "wild" rather than "into wild".

**Comment by antipiot** [comment]
> 
> 
> Might also be worth asking Jackett about this. Seems weird that indexers aren't doing an and type search of "into" and "wild" rather than "into wild".

It's really what Radarr send to Jackett: jackett has nothing to do with it.

**Comment by fryfrog** [comment]
It kind of does because the indexer's search sucks and won't do partial matches or maybe Jackett is sending the search as a full "quoted text" maybe. It is worth asking, to be clear I'm not saying it is a bug w/ Jackett. I'm just saying that at the deepest level it is because the search isn't done well. The best fix for that is as high up the stack as possible. *Not* stripping out those "useless" words would make searches on *other* sites worse.

**Comment by twolaw** [comment]
This indexer is known tout handle requests quite badly.
Yggtracker takes requests as if they are between quotes.
I agree it is a Jackett problem.
À solution would be that jackett sends each word of the request between quotes (for this indexer).
Exemple: "into" "wild"

**Comment by twolaw** [comment]
Ok Jackett dev did the correction.
Next version of Jackett should give better results. 👍

**Comment by fryfrog** [comment]
Awesome!

**Comment by antipiot** [comment]
Nice!
Many thanks!
