### ISSUE TITLE
Use custom feature language for search

### ISSUE THREAD

**Issue by rubasace** [Radarr/Radarr#3703]
I have a custom format for dual releases (English and Spanish). If I add the movie in Spanish, it's queried properly both in Spanish and English trackers, but if I add it in English it only gets queried in English. I think Radarr should use the language tags of the custom formats to search for movies in trackers that have that language too, so if the profile has a custom format that adds Spanish as a language, it should search Spanish trackers using the Spanish title.

**Comment by henkin67** [comment]
Hello,
In your profile, did you set "Language" to any?
![image](https://user-images.githubusercontent.com/29369709/63408121-8b681e00-c3ee-11e9-884b-b4d0134d2531.png)
For Radarr this setting is prior to custom format. Then if you specify a langage in this setting, it will download this langage (and maybe other according with your custom format).
To download in multiple languages I have done like this:
1. Create 3 custom formats: FR (L_french), EN (L_english) and MULTI (L_RQ_french L_RQ_english)
![image](https://user-images.githubusercontent.com/29369709/63408668-db93b000-c3ef-11e9-8d0b-1a1afd16cdb7.png)
2. Create a profile with the langage set to "any"
3. In this profile, set the custom format (from lowest to highest priority): EN, FR, MULTI
![image](https://user-images.githubusercontent.com/29369709/63408726-fa924200-c3ef-11e9-99b7-1911d3209e88.png)
4. In this profile, set the Custom Format Cutoff to MULTI

By this way for release with the same quality it will try to download first in english AND french (two audio tracks), if not available, in french, if not available in english.
I have done like this because usually it's easier to find the english version of a movies.
And to be fare, the multi version is very rare...

**Comment by rubasace** [comment]
It works thanks!!

**Comment by rubasace** [comment]
Even when I set the profile language to any, and the cutoff custom format is L_ENGLISH L_SPANISH Radarr only searches movies with the English title. In order to search with both titles, I need to set the profile language to Spanish.
