### ISSUE TITLE
Search For Missing Fails

### ISSUE THREAD

**Issue by zero77** [Radarr/Radarr#3728]
**Describe the bug**
The option to search all missing films fails.

**To Reproduce**
1. Click the dropdown next to search and select search missing on the movies page.
2. An error is displayed in the bottom left corner that says failed, then nothing else happens.

**Expected behavior**
A search should start that looks for all missing films and a notification should be displayed in the bottom left corner.

**Screenshots**
If still necessary, please let me know.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Mono Version: 6.0.0.319
 - Browser and Version: Firefox
 - Version: 2.0.0.1423 (aphrodite)

**Debug Logs**
https://pastebin.com/raw/t6A9t4qY

**I know aphrodite is unstable and being developed but, i am happy to test it and report bugs if this helps.**

**Comment by Qstick** [comment]
Thanks for reporting

**Comment by tehniemer** [comment]
I'm having this issue with Linuxio Docker version 2.0.0.2090

Debug logs:
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3707397/radarr.debug.txt)

**Comment by Qstick** [comment]
closing with 5eb7fe958ff26e4a4ebe0bd418e79d0698cbfc70, missing search works from calendar and index screen

**Comment by tehniemer** [comment]
@Qstick I'm able to search for missing from the calendar, but not the Movies page, if that's what you mean by "index screen"

![Image 1571661602](https://user-images.githubusercontent.com/11021632/67205766-055c5980-f3d6-11e9-8dd9-d0a63b40b9d0.png)

**Comment by Qstick** [comment]
Thanks, should be really fixed now. Fixed build is building now

**Comment by tehniemer** [comment]
It seems to be working as expected now, thank you.

**Comment by Skrumpy** [comment]
I have this issue with;

Version: 3.0.0.2915
Package Version: aphrodite-ef0e248-852 by hotio 

Adding an unmonitored/unsearched movie in Radarr will not display it as "Missing" in the "Movies" list tab when using filter "Missing". I get "All movies are hidden due to applied filter".

Instead, I have to search by size on disk and look for 0 sized files to accomplish this as a workaround.

**Comment by ta264** [comment]
Unmonitored is not missing. Unmonitored means "I don't want this".

**Comment by Skrumpy** [comment]
> 
> 
> Unmonitored is not missing. Unmonitored means "I don't want this".

Correct. However, you can have an unmonitored movie that is missing. In V2 an unmonitored movie that is not on the disk (i.e. missing) is filtered as such regardless of monitoring status. In V3, if it is unmonitored it will not show as missing and you need to search for movies without any size. This is problematic as I have 1000 unmonitored movies.. I am just wondering if this was an intentional change or if it was overlooked and intended to remain the same as V2 for the sake of consistency.

![image](https://user-images.githubusercontent.com/20248002/81738717-c1a76b00-945f-11ea-8686-1901fe9776e0.png)
