### ISSUE TITLE
Import failed, path does not exist or is not accessible by Radarr

### ISSUE THREAD

**Issue by Generalnoob** [Radarr/Radarr#3751]
**Describe the bug**
I'm not sure if this is a bug or a feature request but could you please add in a simple line saying if path does not exist  or accessible to simply remove it from nzbget and move on please, currently every time this happens (which for the last month it's been happening a lot I'm not sure why the folder just isn't there) it completely locks down radarr and stops radarr from importing anything else causing a massive backlog of stuff to import.
"Import failed, path does not exist or is not accessible by Radarr: /mnt/downloads/nzbget/movies/The"

**To Reproduce**
if the folder is deleted by nzbget due to being a sample (or any other reason im not aware of) it will stop all other imports in radarr

**Expected behavior**
I would like it to just remove it from the nzbget history and move on

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Mono Version: [e.g. Mono 5.8] (Only needed under Linux and Mac, found under System -> Status)
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues)

**Debug Logs**
Import failed, path does not exist or is not accessible by Radarr: /mnt/downloads/nzbget/movies/The----

**Comment by fryfrog** [comment]
Do your setup right.

Configure nzbget to move deleted items to hidden history (so you retain that information), setup Sonarr/Radarr to Remove in Completed and Failed Download Handler. When you have items like this, *remove them* from your download client's history. This error is to show you that something weird is up. It shouldn't be "fixed" manually because there is something messed up.

**Comment by Generalnoob** [comment]
well first of all it is set up correctly but the sample/fake detector and time/date ressetter was removing them some times, so nothing that nzbget can do about that when a fake is found the plugins remove it. but regardless of nzbget radarr should be able to handle a simple error like this, the coding for it takes no more than a hour and stops a users radarr from stopping

**Comment by fryfrog** [comment]
Radarr/Sonarr read the download client history for items to try and import, so having nzbget/sabnzbd remove incorrect downloads is fine. It just needs to remove them from history. Once they're not there, Radarr/Sonarr have no idea about them. Detecting fakes, samples and even unfinishable downloads is fine as long as it markes them as failed (if you want Radarr/Sonarr to retry a different one) or just totally removes them.

It doesn't *remove* them because that isn't a safe thing to do. What if they're needed? What if they're failed for some other reason? What if the path is different from its point of view? What if it is a permissions issue?

Radarr is open source and the few developers love working w/ new developers. If you wanted to come up w/ a well thought out solution to this, it'd be very welcome. But your grasp of the issue is very one sided, from your experience. You'd need to explore the other ways this can happen to full appreciate it and come up w/ a workable solution.

Sonarr's v3 (being ported to Radarr v2) has a *close* "fix" for this, it has an option to show unmatched items. I don't think that *quite* applies to this case, but it might.
