### ISSUE TITLE
Upgading movies with unknown quality with new versions having the same file size

### ISSUE THREAD

**Issue by ejalal** [Radarr/Radarr#3771]
**Is your feature request related to a problem? Please describe.**
I just installed Radarr on my OMV NAS and imported my movies library already renamed with filebot, so lost all indication of source and quality (BRip/720p/1080p etc...).

I started upgrading my movies which currently have "unknown" quality (because of the above) in Radarr by newer versions up to BRip 1080p. The problem with this is that when Rararr finds an "upgrade", it has to wait until it's completely downloaded before telling me that the file I already have has the exact same file size than the old one.

**Describe the solution you'd like**
Radarr should check the torrent file size from Deluge/Transmission and warn at the beginning if the new file has the exact same size or not instead of waiting until it's completely downloaded.

**Describe alternatives you've considered**
An alternative solution would be to automatically stop the download when the size is identical, and rename the existing movie and set the quality from "unknown" to whatever quality/source was in the upgraded torrent.

**Additional context**

**Comment by fryfrog** [comment]
Being the same size is a really strong indicator is is the same, but it isn't guaranteed. And while the final size may be known w/ torrents, it generally isn't w/ usenet. This issue is self inflicted in that you lost all your irreplaceable metadata. I hope you're preserving it in file names from now on.

I'm closing this feature request, but if you're lucky maybe someone who develops will have this same concern and just do it.
