### ISSUE TITLE
Can't add 2 different existing movies with same name and year.

### ISSUE THREAD

**Issue by mattman86** [Radarr/Radarr#396]
I'm trying to add these 2 movies that already exist on the disk.

Emma (1996) IMDB: tt0116191
Emma (1996) IMDB: tt0118308

The first one adds fine but the second one does nothing when I click the '+' button.

**Comment by onedr0p** [comment]
This is because the system sees `Emma (1996)` for one and `Emma (1996)` for the other causing an error.

**Comment by boulogne75** [comment]
Had the same problem trying to add 2 versions of the same movies (3D/2D). Only 1 movie imported.

**Comment by galli-leo** [comment]
@mattman86 Do you have any logs you could provide?
@boulogne75 Well you don't need to add the second version, since the movie is already added.

**Comment by boulogne75** [comment]
I agree with you for 2D movies. But most of the time, for the same movie, normal 2D bluray has better picture quality than the 2D video in 3D bluray. That's why usually I archive both versions.
Not a big deal, I can just add/monitor 2D version ;)
I thought it was worth mentioning just in case.

BTW, great work you guys are doing! This app was much needed, thanks.

**Comment by onedr0p** [comment]
Fixed in next release
