### ISSUE TITLE
Unable to map non-English movies

### ISSUE THREAD

**Issue by kSotin** [Radarr/Radarr#3972]
**Describe the bug**
Since a few days ago, under a profile with its language set to 'Any', Radarr has started to name non-English movies using titles in their original language, causing failure in mapping them with indexer search results, since most indexers name movies in English regardless of their original language. 

**To Reproduce**
1. Go to a German movie entry added before this happened, seeing an English title
<img width="801" alt="image" src="https://user-images.githubusercontent.com/57791410/71149282-1526db80-2269-11ea-8c26-0af8732c3959.png">

2. Click on 'Update movie info and scan disk'
3. Go to the same movie entry, seeing a German title, with no alternative titles listed below
<img width="802" alt="image" src="https://user-images.githubusercontent.com/57791410/71149347-3d163f00-2269-11ea-92dc-8599bad92ec1.png">

4. Perform a manual search, seeing failure to map
<img width="438" alt="image" src="https://user-images.githubusercontent.com/57791410/71149429-777fdc00-2269-11ea-8b68-b4b9c81a937c.png">

**Expected behavior**
Not sure if this is related to the recent malfunction and restoration of the TMDB API, but Radarr had been working well with non-English movies before, even if the movies are under a profile with 'Any' language setting. 

**Desktop (please complete the following information):**
 - OS: Linux
 - Mono Version: 6.6.0.161
 - Version 0.2.0.1450

**Comment by Moffe666** [comment]
I can agree that this is a mess when you have to search for a movie and so on.
Here is an example taken from my collection...

![image](https://user-images.githubusercontent.com/59139766/71322140-70a0d580-24c4-11ea-9c1c-a04531984434.png)

**Comment by SF4L** [comment]
Yoooooooo I thought I was going crazy ... Radarr was always working perfectly for foreign movies (except this one issue: https://github.com/Radarr/Radarr/issues/3748) but after updating to 0.2.0.1450 all the foreign stuff is wacky!

Here's my example:

It seems Radarr in the newest develop branch is making all the titles of my foreign releases show up in foreign characters which is making it A) impossible to search for the movie in my list of movies, B) creating wacky 404s from the search page, and C) not matching completed downloads

Searching for Aftershock 2010 and creating the new entry brings me to:
![image](https://user-images.githubusercontent.com/36459489/71369960-617c5f00-257a-11ea-88da-376b2c5cbcb6.png)

Clicking on that brings me to:
![image](https://user-images.githubusercontent.com/36459489/71369969-6a6d3080-257a-11ea-9187-61b36edc89f4.png)

I can find it by searching for TMDB ID:
![image](https://user-images.githubusercontent.com/36459489/71369981-76f18900-257a-11ea-865c-562ba2fac547.png)

But it won't automatically match the downloaded content anymore, so I have to manually import (which is quite a pain since I don't speak any Asian languages or have them in my keyboard). It happens for any non-English film (just tried with Thirst 1949 as well)

**Comment by tvebax** [comment]
Same issue here. Radarr can no longer search indexers for the english title of a foreign language movie, can't match it to import it, shows titles in languages and characters I do not understand, I can't search for existing foreign language movies anymore (even if I could remember the incomprehensible names, I do not have a arabic and chinese keyboards lying around), 404 pages happen all the time, - etc. 

Regression caused by multilingual features implementation.

**Comment by mraniki** [comment]
Got the same issue.

**Comment by SF4L** [comment]
Is there anyone who _doesn't_ have the issue at this point? I can't imagine everybody has it or there would be more efforts to fix it. I mean, literally, all foreign movies with translations on TMDB are broken!

**Comment by SF4L** [comment]
Seems to be fixed in 0.2.0.1480

**Comment by kSotin** [comment]
> Seems to be fixed in 0.2.0.1480

It's working within Radarr, not between Radarr and the download client. Radarr doesn't respond upon download finishes.
