### ISSUE TITLE
Renamer fails to parse {Release Group} correctly.

### ISSUE THREAD

**Issue by translit** [Radarr/Radarr#4007]
**Describe the bug**
Renamer fails to parse ```{Release Group}``` correctly.

**To Reproduce**
1. Set Standard movie format to ```{Movie Title} ({Release Year}) - {[EDITION TAGS]}{[QUALITY FULL]}{[MEDIAINFO AUDIOCODEC}{ MEDIAINFO AUDIOCHANNELS]}{[MEDIAINFO VIDEOCODEC]}{-RELEASE GROUP}```
2. Download ```Resident.Evil.Apocalypse.2004.MULTi.1080p.BluRay.x264-AiRLiNE```
3. See it renamed to ```Resident Evil  Apocalypse (2004) - [BLURAY-1080P][DTS 5.1][X264]-RESIDENT.mkv```

**Expected behavior**
```Resident Evil  Apocalypse (2004) - [BLURAY-1080P][DTS 5.1][X264]-AIRLINE```

**Environment**
- OS: Synology DSM, Docker
- Version 0.2.0.1450

**Comment by fryfrog** [comment]
Could you turn logging up to trace and reproduce? Show us the context around the import in a pastebin.

**Comment by Mushin** [comment]
I'm also experiencing this issue, specifically with release groups that name their torrents like the following:

Star Trek (2009) (2160p BluRay x265 10bit HDR Tigole)
The Matrix Revolutions (2003) (2160p BluRay X265 HEVC 10bit HDR AAC 7.1 Tigole) [QxR]
Stargirl (2020) [2160p x265 10bit S82 Joy]

The problem seems like it happens because the release group does not use -RELEASEGROUP or similar.
