### ISSUE TITLE
Enhance the links below movie posters

### ISSUE THREAD

**Issue by juanchristian** [Radarr/Radarr#403]
Today we have this:

![image](https://cloud.githubusercontent.com/assets/4141392/22218395/a302d97e-e18d-11e6-9e50-d4acf4740a15.png)

My suggestion is that we have something like this:

![image](https://cloud.githubusercontent.com/assets/4141392/22219747/2e52a22a-e193-11e6-9e30-5719ffb2222c.png)

Something like that would be better because it's simpler and smaller, instead of taking up 4 lines to show this additional info, it would only take 2 lines in height. When you have a lot of movies in the Poster view those homepage/TMDB/IMDB/Trailer links end up consuming a lot of space.

**Comment by fedoranimus** [comment]
@galli-leo I think this would be better suited to be addressed with a UI redesign than with the current UI.

**Comment by galli-leo** [comment]
@fedoranimus Well I think, it should be fairly easy to implement that. So I think we could do that now or in the near future.

**Comment by hotio** [comment]
Just as long it doesn't look like in that mockup...because...no offence, but that looks horrible

**Comment by jcchristian** [comment]
@hotio I did this in 2 min on Photoshop, it was just to give an idea, it's up to the contributors of the project to build the final version :p

**Comment by hotio** [comment]
Howww settle down boy :)

**Comment by jcchristian** [comment]
I was just kindly replying your comment. I was indeed expecting that you could post something better to help the project :)

**Comment by hotio** [comment]
Dude, get of your high horse, I already contributed more than you with this issue. Design the images, make a PR and stop crying!

**Comment by jcchristian** [comment]
Look what we have here, a rage boy, at least your mask dropped hum, so depressing. How to be a jerk on GitHub 101:

1. Go to someone else issue ticket and critique their work without providing something useful (an alternative, how to make it better, etc)
2. Receive a normal reply and face it like it was an insult
3. Tell the other guy to settle down, because they are the ones doing the bad thing
4. Tell them to get of their high horses, because no you, but they are the ones doing bad things
5. Activate rage mode and tell how brilliant you're and how you contribute more to the project than others

I'll refrain from arguing with kids, bye. You should learn two things before trying to talk with people: education and social skills.

**Comment by galli-leo** [comment]
Leaving this open, since it's a valid concern.

**Comment by onedr0p** [comment]
https://github.com/Radarr/Radarr/issues/424
