### ISSUE TITLE
Prefer original language otherwise ban dubs, down prioritise MULTi/DL

### ISSUE THREAD

**Issue by scs3jb** [Radarr/Radarr#4077]
**Is your feature request related to a problem? Please describe.**
I would like to download the original language version of a movie in all cases, unless when it is not available when I would like to download the language I speak.  The issue at the moment is that in profiles there only seems to be ways to ban words, like MULTi and FRENCH/SPANISH/ITALIAN, but no way to say 'except if the movie is foreign language'.

**Describe the solution you'd like**
I would like an option to ban dubs and prefer the original language, this could be done by checking the language on imdb/tmdb and then preferring that language when calculating downloads.  In the case that nothing is found, that is when we go and check the 'system' language or the keyword 'DUBBED' and/or  'MULTi'.  For native movies, FRENCH/SPANISH/ITALIAN should be banned, whilst MULTI and DL are degraded in priority.  Ideally the tags should be configurable under a language setting.

**Describe alternatives you've considered**
Any variation on tagging and filtering that could be used, for example different profiles selected based on language, although this would be more complex to setup and monitor.

**Additional context**
I hate dubs, and unfortunately I have to ban FRENCH/SPANISH/ITALIAN tags, along with dubbed.  What's happening is I'm getting a lot of MULTi and DL and have to strip the audio tracks (shaving off ~1-2gb of wastage).  The issue is when it comes to old movies, and especially horror that might be dubbed originally (i.e. pan-european production), or when MULTi/DL is the only option.

**Comment by Qstick** [comment]
Can you not do this with custom formats?

**Comment by scs3jb** [comment]
> Can you not do this with custom formats?

Where is the option to check if the movie is foreign language from imdb in custom formats?

**Comment by hergonoway** [comment]
Well it's kinda tricky, from what I know original dub is not a viable concept in imdb, take [1492 Christophe Colomb](https://www.imdb.com/title/tt0103594/?ref_=ttls_li_tt) for example : 
it's a Spain-France colaboration (as tagged in imdb), directed by Ridley Scott, about an historical Spanish protagonist, but in France it's "common knowledge" that's a French movie (because Depardieu, French production (Gaumont, etc) and first released in France) but the movie was shot in English. (and also Spanish, Latin, Arabic, dixit imdb)

so what's the "real" original language, and is it the same expected from a French, a Spanish or an English guy, meh kinda tricky. I'm not telling that you're wrong, I totally agree with you about the benefit of an "original language" option (specially for asian movies) , and I'd be the first to use it :), I'm just saying that's is not as trivial as it seems, it may lead to false-positive if the source of the info is non-unique for each movie.

**Comment by scs3jb** [comment]
That's pretty straightforward, where more than one language is listed as original language, then fall back to as-is logic and prefer untagged (i.e. MULTi is not used got mixed language, not is GERMAN, FRENCH)

If you own the BluRay, the mixed track is identified as English (which is the main language, but wrong), and the original version track releases don't have a tagged language.

**Comment by Qstick** [comment]
Original Language Option is in V3
