### ISSUE TITLE
couldn't import movie/destination already exists

### ISSUE THREAD

**Issue by jayposton** [Radarr/Radarr#4079]
Get the following error when radar goes to update a movie to a better version: 
couldn't import movie destination already exists

Looks like Radarr won't remove the old file and replace it with the new one

**Comment by Qstick** [comment]
Please provide version, logs, etc. all of the information that was asked for in the template that was presented to you when opening this bug report.

A fix was just put into Aphrodite so that if your root folder is not accessible Radarr will fail the import, this ensures you don’t get multiple copies of movies if Radarr isn’t able to delete.

**Comment by beyondmeat** [comment]
This will also occur if the file exists but it's not imported.

To check for this, go to the movie page and click refresh and scan, then click manual import. It will probably have an unmapped file. Go ahead and import it. Then go back to the activity queue and refresh it. It will now import it if it's an upgrade

**Comment by Qstick** [comment]
Closing until more info is provided
