### ISSUE TITLE
Password protected rarfiles - proposed simple solution

### ISSUE THREAD

**Issue by blastermaster0** [Radarr/Radarr#4121]
**Is your feature request related to a problem? Please describe.**
Radarr is unable to send password metadata to download clients for protected archives.

**Describe the solution you'd like**
Many downloaders support including the password within the nzb filename: https://sabnzbd.org/wiki/advanced/password-protected-rars

Proposed Solution: Currently, radarr seems to rename the nzb file before sending it to download clients. If we could configure or disable this behavior, the download clients would be able to locate passwords correctly and this problem would be solved.

**Comment by Qstick** [comment]
Radarr is able to sent password metadata to the client when it’s added to the nzb head metadata by the indexer per nzb spec (https://sabnzbd.org/wiki/extra/nzb-spec). Radarr uses the original release title it got from the indexer when sending over the nzb so that it can maintain parsability through the download process.
