### ISSUE TITLE
Remap Legacy Invalid {MediaInfo HDR} to {MediaInfo VideoDynamicRange}

### ISSUE THREAD

**Issue by Lonli-Lokli** [Radarr/Radarr#4132]
**Describe the bug**

I am using Radarr on Docker on my Synology with this renaming schema 
{Movie Title} {Release Year} {Quality Title} {MediaInfo HDR}
And of of my movies does not get HDR suffix in file name.

MediaInfo (taken from desktop)

{
"@type": "General",
"UniqueID": "256143243861113792480417357864206929579",
"VideoCount": "1",
"AudioCount": "17",
"TextCount": "5",
"MenuCount": "1",
"FileExtension": "mkv",
"Format": "Matroska",
"Format_Version": "4",
"FileSize": "52424824863",
"Duration": "6246.272",
"OverallBitRate_Mode": "VBR",
"OverallBitRate": "67143826",
"FrameRate": "23.976",
"FrameCount": "149760",
"StreamSize": "61748022",
"IsStreamable": "Yes",
"Encoded_Date": "UTC 2019-12-05 07:53:38",
"File_Modified_Date": "UTC 2020-01-02 13:59:58",
"File_Modified_Date_Local": "2020-01-02 16:59:58",
"Encoded_Application": "mkvmerge v40.0.0 ('Old Town Road + Pony') 64-bit",
"Encoded_Library": "libebml v1.3.9 + libmatroska v1.5.2",
"extra": {
"Attachments": "poster.jpg"
}
},
{
"@type": "Video",
"StreamOrder": "0",
"ID": "1",
"UniqueID": "7107362514932922067",
"Format": "HEVC",
"Format_Profile": "Main 10",
"Format_Level": "5.1",
"Format_Tier": "High",
"HDR_Format": "SMPTE ST 2086",
"HDR_Format_Compatibility": "HDR10",
"CodecID": "V_MPEGH/ISO/HEVC",
"Duration": "6246.240000000",
"BitRate": "51636158",
"Width": "3840",
"Height": "2160",
"Sampled_Width": "3840",
"Sampled_Height": "2160",
"PixelAspectRatio": "1.000",
"DisplayAspectRatio": "1.778",
"FrameRate_Mode": "CFR",
"FrameRate": "23.976",
"FrameCount": "149760",
"ColorSpace": "YUV",
"ChromaSubsampling": "4:2:0",
"ChromaSubsampling_Position": "Type 2",
"BitDepth": "10",
"Delay": "0.000",
"StreamSize": "40316479449",
"Default": "Yes",
"Forced": "No",
"colour_description_present": "Yes",
"colour_description_present_Source": "Stream",
"colour_range": "Limited",
"colour_range_Source": "Stream",
"colour_primaries": "BT.2020",
"colour_primaries_Source": "Stream",
"transfer_characteristics": "PQ",
"transfer_characteristics_Source": "Stream",
"matrix_coefficients": "BT.2020 non-constant",
"matrix_coefficients_Source": "Stream",
"MasteringDisplay_ColorPrimaries": "Display P3",
"MasteringDisplay_ColorPrimaries_Source": "Stream",
"MasteringDisplay_Luminance": "min: 0.0050 cd/m2, max: 4000 cd/m2",
"MasteringDisplay_Luminance_Source": "Stream",
"MaxCLL": "3938 cd/m2",
"MaxCLL_Source": "Stream",
"MaxFALL": "676 cd/m2",
"MaxFALL_Source": "Stream"
},

**Desktop (please complete the following information):**
Version
3.0.0.2609
.NET Core
Yes
Docker
Yes
DB Migration
167
AppData directory
/config/app
Startup directory
/app
Mode
Console

[AB#1042](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1042)

**Comment by fryfrog** [comment]
It's called something else in aphrodite, `{MediaInfo VideoDynamicRange}`, from Sonarr and it is actually in the `?` for the media naming.

**Comment by fryfrog** [comment]
@Qstick or @ta264, could we *convert* the old `{MediaInfo HDR}` token to `{MediaInfo VideoDynamicRange}`? And maybe also have a health check warning for unkown `{Tokens}`?

**Comment by Qstick** [comment]
Great idea

**Comment by raymondtrueman** [comment]
@Qstick @ta264 @fryfrog 

While this is being worked on, is it possible to expand the HDR tokens a little bit please? I would like to put the actual HDR standard in my movie file names. For example "HDR10", "HDR10+", "Dolby Vision", "HLG". This is very important information for everybody who cares about dynamic range in their movies. MediaInfo provides this under a tag called "HDR Format". At the moment I have to manually run MediaInfo every time I need to check the type of HDR. There will be a fair amount of parsing and logic to accomplish this though because the strings look something like this

Example 1 for HDR10: 
SMPTE ST 2086, HDR10 compatible

Example 2 for Dolby Vision:
**Dolby Vision**, Version 1.0, dvhe.07.06, BL+EL+RPU, Blu-ray compatible / SMPTE ST 2086, **HDR10** compatible

There are some rules as well. For example if the phrase "Dolby Vision" is found the output should be "Dolby Vision" even if "HDR10" is also found in the same string because Dolby Vision always incorporates HDR10 and everybody knows that

I am also looking forward to a day where I can set a quality profile to only grab a movie from an indexer if it has Dolby Vision for example

I will add a feature request as well
