### ISSUE TITLE
Bulk Change Exisitng Movie file quality

### ISSUE THREAD

**Issue by tusharbhutt** [Radarr/Radarr#4135]
**Is your feature request related to a problem? Please describe.**

It would be useful to edit the quality (DVD, Bluray, WEBDL, etc) of existing files in bulk.  Since we can rename and tag files, this would also be a nice feature to have.

**Describe the solution you'd like**
 In the movie editor, add a drop down box that would allow the user to edit the quality of existing movie files.  This would be like the drop down to change the monitored/unmonitored state, root folder, or profile desired. Some logic would have to be in place to ensure this only works for files that have been downloaded.

**Describe alternatives you've considered**
Currently this can only be done on a one-by-one basis which is fine for one or two movies but if dozens of movies were not correctly named when imported (i..e no quality description was in the file name) then it becomes very tedious.  One could remove all files, do a bulk name change with a another utility, and then re-import, but then the history of downloads, if any, would be lost, no?

**Comment by Qstick** [comment]
Don’t think we want to do this, Seems like this would get users in trouble more than it would help anyone. A bulk resetting of qualities on a page where a user has no info about what the file(s) actually is(are) or should be.

**Comment by krugster** [comment]
I’ve searched for different ways to do this and came across this closed ticket. I have a bunch of old movie files whose qualities are mislabelled. The file name might say 1080, but the size is 1gb or less. Radarr thinks the existing file is 1080 already and so excludes any higher bitrate/larger file size. 

I’ve found that if I manually set the file quality to “unknown” then it will pick up an upgraded version. But I’ve got >300 of these so I was hoping to bulk edit the existing qualities to “unknown” and then re-search. 

Any other suggestions?  I DO have “allow upgrades” on my quality profile but I still get the message saying a new download is excluded because my file/quality profile settings “don’t allow upgrades”. Is that perhaps a different bug?
