### ISSUE TITLE
Plex connect fails on V.3.0.0.2619

### ISSUE THREAD

**Issue by casperse** [Radarr/Radarr#4154]
Please let me know if you have another place to report v3 bugs

The connect to Plex fails and provide error message to host (IP)
Same information works in old version Radarr Ver. 0.2.0.1450

**Expected behavior**
Connect to plex with provided token
I have used same token on both versions the token is ok!

**Screenshots**
[https://ibb.co/dJ4JWfR](url)

**Desktop (please complete the following information):**
Linux server Docker : preview

**Debug Logs**
Unable to connect to Plex Server: Unable to connect to Plex Media Server
(It does fetch new token if I login to Plex)

**Comment by casperse** [comment]
Ok found that SSL works in old Radarr and in the new V3 you need to disable SSL in order ffor the connection to work

**Comment by ta264** [comment]
Huh I suspect it's not that ssl is broken on the new one but that it's actually checking the certificate is valid properly. Please can you provide trace logs of it failing? I don't use Plex to be able to verify

**Comment by tezgno** [comment]
This isn't a big, but rather a SSL validation issue. The issue happens because your Plex server is using a Digicert signed certificate that has a DNS mismatch locally on your network (plex.direct vs plex.tv). You have to adjust your SSL validation settings in Radarr to not validate on your local network. You should not turn it completely off since that creates a situation in which it will not validate certificates off your network (which can be a security issue if your Radarr server talks to Internet facing services). This is a new feature introduced in the new code that doesn't exist in the older code, thus the problem

**Comment by ta264** [comment]
Seems this is either a config issue or an issue with Plex so closing
