### ISSUE TITLE
Movie editor - select limit circa 575-600 movies

### ISSUE THREAD

**Issue by mattystorey** [Radarr/Radarr#4188]
**Describe the bug**
Movie editor only allows selection of circa 575-600 movies. UI does not permit limitation of movies per page. 

**To Reproduce**
1. Go to movie editor
2. Click on 'select all' (over 575 or 600 movies)
3. Scroll down and click delete
4. select delete (do not delete files or exclude)
5. nothing happens. nothing in logs.

Version
3.0.0.2432
.NET Core
Yes
Docker
Yes
DB Migration
163
AppData directory
/config
Startup directory
/opt/radarr
Mode
Console
Uptime

**Expected behavior**
delete movies from database.

**Comment by ta264** [comment]
Try again on 3.0.0.2651

**Comment by Qstick** [comment]
I'm hopeful this is fixed in 9ccdb48. In addition to the deleteFiles and addExclusion parameters, the frontend was appending a query parameter `movieIds=(id)` to the request to the backend for every movie selected. This likely resulted in a massive url upward of 500 movies. All of this should be handled in the JSON body of the DELETE request now.
