### ISSUE TITLE
Movie incorrectly showing as cutoff unmet

### ISSUE THREAD

**Issue by alvintc** [Radarr/Radarr#4208]
**Describe the bug**
Wanted -> Cutoff Unmet shows movies where the cutoff is actually already met (this happens for a couple of movies):
![Cut-off unmet](https://user-images.githubusercontent.com/7372692/75655934-ce873180-5c5a-11ea-8538-5fa8a9af8332.jpg)
![Current files](https://user-images.githubusercontent.com/7372692/75655942-d1822200-5c5a-11ea-91a3-a5e97e34af47.jpg)
![Profiles](https://user-images.githubusercontent.com/7372692/75655945-d3e47c00-5c5a-11ea-8e27-b6ffd4e914fa.jpg)

Radarr Version: 0.2.0.1480

**Comment by fryfrog** [comment]
Crazy!

Since development is all on v3 now, I don't think this is going to get much of a look. And I want to ask for logs, but I'm not sure how you could even get them. Maybe turn logging up to Debug and cross your fingers and hope it happens again and you notice in time to dig through the logs and find it?

I assume it stays like this after a restart? After a library refresh? Even harder to trigger would be another WEBDL coming across via RSS. Do you have any Custom Formats (though I swear *those* don't show up in Wanted).

**Comment by Qstick** [comment]
Unless this can be reproduced in v3 Aphrodite as fryfrog mentioned, it likely will not be fixed. Marking v0.2 for closure unless can be verified in V3
