### ISSUE TITLE
Add Filter To Only Show Released Movies

### ISSUE THREAD

**Issue by kiityman1** [Radarr/Radarr#4221]
**Is your feature request related to a problem? Please describe.**
When navigating Radarr, it is very hard to tell if a movie has been released or not without searching the internet. When the filter is set to missing, I don't think unreleased (physical/digital) movies should be shown.

**Describe the solution you'd like**
I would like either a change to the missing filter, or a new released missing filter. (Or similar)

**Describe alternatives you've considered**
An alternative to new filters would be to simply use a custom filter.

**Additional context**
https://i.imgur.com/8Yj0S88.jpg
https://i.imgur.com/CVmn6q2.jpg
https://i.imgur.com/jarqWd9.jpg

I am using Anphorite Docker.

**Comment by geogolem** [comment]
Internally Radarr has a field called isAvailable. 

If the physical release date is known a movie is considered available if the current date is after the physical release date. If the physical release date is not known but an "In Cinemas" date is known, the movie is considered available if it has been 3 months since the "In Cinemas" date.

A movie that is "Not Available" is still considered "Missing". "Missing" means the movie is Monitored but has not yet been downloaded and has nothing to do with release date. It simply means the movie is "Missing".

Missing corresponds rather to movies that are monitored but not yet downloaded. 

in Radarr the filter "Wanted" corresponds to movies that are Missing and Available.. 

Please let me know if this makes sense?

**Comment by kiityman1** [comment]
> Internally Radarr has a field called isAvailable.
> 
> If the physical release date is known a movie is considered available if the current date is after the physical release date. If the physical release date is not known but an "In Cinemas" date is known, the movie is considered available if it has been 3 months since the "In Cinemas" date.
> 
> A movie that is "Not Available" is still considered "Missing". "Missing" means the movie is Monitored but has not yet been downloaded and has nothing to do with release date. It simply means the movie is "Missing".
> 
> Missing corresponds rather to movies that are monitored but not yet downloaded.
> 
> In Radarr the filter "Wanted" corresponds to movies that are Missing and Available. Does this not meet your requirement?
> 
> Please let me know if this makes sense?

That makes perfect sense. I swear I did not see the wanted filter there. Thank you :)
