### ISSUE TITLE
Radarr downloading the same movie NZB multiple times

### ISSUE THREAD

**Issue by morganzero** [Radarr/Radarr#4262]
**Describe the bug**
I'm having an issue where Radarr is downloading multiple NZB's and adding them to Sabs queue.

**To Reproduce**
The last month or so, I've been struggling with duplicates in my sabs-queue. I cannot tell you how to reproduce the issue.

**Expected behavior**
The expected behavior is that I Radarr adds 1 copy to Sabs and not multiple.

**Screenshots**
This is my queue, I've highlted the duplicate ares on this page. I suspect I have a few hundreds.
![dup](https://user-images.githubusercontent.com/57449785/78032149-d8d54200-7364-11ea-8fbb-8cd74f7a490d.png)
This is a screenshot of my Sabs-queue.
![Screenshot_2020-03-31 107 9 MB s - 80 6 GB left - SABnzbd](https://user-images.githubusercontent.com/57449785/78032217-f86c6a80-7364-11ea-930c-9056a1e9d041.png)
And this is a screenshot of my queue in Radarr. Thus why I suspect a few hundreds of dupes.
![Screenshot_2020-03-31 Log Files - Radarr](https://user-images.githubusercontent.com/57449785/78032222-fb675b00-7364-11ea-8b19-f0b6e905ed02.png)

**Desktop (please complete the following information):**
 - Linux 18.04
 - Mono Version: [e.g. Mono 5.8] (Only needed under Linux and Mac, found under System -> Status) I cannot find mono version. This is all I get:
```
Version
    3.0.0.2756
.NET Core
    Yes
Docker
    Yes
DB Migration
    169
AppData directory
    /config
Startup directory
    /opt/radarr
Mode
    Console
Uptime
    05:08:40
```
 - Browser and Version Firefox 74.0 (64-bit)
 - Version 3.0.0.2756

**Debug Logs**
This is what I found in logs.
```
2020-3-31 13:29:57.0|Debug|Parser|Movie Parsed. Manzinger Z. Infinity - 2017 
2020-3-31 13:29:57.0|Debug|Parser|Languages parsed: French, English
2020-3-31 13:29:57.0|Debug|QualityParser|Trying to parse quality for Manzinger.Z.Infinity.2017.MULTi.1080p.BluRay.x264-Ulysse French
2020-3-31 13:29:57.0|Debug|Parser|Quality parsed: Bluray-1080p v1
2020-3-31 13:29:57.0|Debug|Parser|Release Group parsed: Ulysse
2020-3-31 13:29:57.0|Trace|ConfigService|Using default config value for 'parsingleniency' defaultValue:'Strict'
2020-3-31 13:29:57.0|Trace|ConfigService|Using default config value for 'parsingleniency' defaultValue:'Strict'
2020-3-31 13:29:57.0|Debug|Parser|Parsing string 'Manzinger.Z.Infinity.2017.MULTi.1080p.BluRay.x264-Ulysse French'
2020-3-31 13:29:57.0|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
2020-3-31 13:29:57.0|Debug|Parser|Movie Parsed. Manzinger Z. Infinity - 2017 
2020-3-31 13:29:57.0|Debug|Parser|Languages parsed: French, English
2020-3-31 13:29:57.0|Debug|QualityParser|Trying to parse quality for Manzinger.Z.Infinity.2017.MULTi.1080p.BluRay.x264-Ulysse French
2020-3-31 13:29:57.0|Debug|Parser|Quality parsed: Bluray-1080p v1
2020-3-31 13:29:57.0|Debug|Parser|Release Group parsed: Ulysse
```
And here is the log attached.
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/4409343/radarr.trace.txt)

**Comment by Qstick** [comment]
Please fix the issue title and add all information from the bug template that you wiped out. Version, platform, etc...

**Comment by morganzero** [comment]
Thank you for noticing. I have updated title and included the bug template.

**Comment by pazport** [comment]
i am having the same problem too. it keeps downloading 2 sometimes 3 of the same movie.

**Comment by morganzero** [comment]
I want to update with two more screenshots from today. My radarr is in version 3.0.0.2830 as of today.

A total of 9 copies of the exact same release with the exact same resolutionprofile. 
![Screenshot_2020-04-20 Paused - 66 6 GB left - SABnzbd(1)](https://user-images.githubusercontent.com/57449785/79734543-2f47f780-82f7-11ea-82bb-e81bc2a589ea.png)
According to history it grabbed only 3, all of them the same day.
![image](https://user-images.githubusercontent.com/57449785/79734617-48e93f00-82f7-11ea-8cf0-d9ae7983701c.png)

**Comment by morganzero** [comment]
Got some more dupes today. I'm uploading what I could find in Trace and debugging.
[trace_ and_debug.txt](https://github.com/Radarr/Radarr/files/4522642/trace_.and_debug.txt)

![Screenshot_2020-04-23 Faith, Hope Love - Radarr](https://user-images.githubusercontent.com/57449785/80102587-41ce6500-8573-11ea-829f-c9747c721cfe.jpg)
SAB Queue
![Screenshot_2020-04-23 Paused - 176 8 GB left - SABnzbd](https://user-images.githubusercontent.com/57449785/80102591-4430bf00-8573-11ea-9098-dcab11677255.jpg)

**Comment by OuticNZ** [comment]
This is also happening for me as well.  I've noticed it occurs during the RSS Sync.  If the scheduled RSS Sync occurs or I manually trigger it I'll get duplicates for some items.  I think for items that do not yet meet cut-off.  

I'm running v3.0.0.2915

**Comment by OuticNZ** [comment]
The issue can't easily be re-created for a single item.  RSS Sync process behaves as expected and doesn't create multiple items in the download queue.  I suspect the issue only occurs when a large number of items are being tracked in the download clients.

**Comment by OuticNZ** [comment]
Running in Docker using v3.0.0.2915 -  The issue is easy to reproduce.  

As an example:
Remote Movie is : Onward.2020.BluRay.1080p.DTS.5.1.X264-MTeam,  size of 9GB
This needs to be in the RSS Sync list

Steps to reproduce:
1. Clear Movie DB so that it is empty, and have dummy downloader setup for NZB
2. Setup 2 custom formats so that the example file will result in a modifier of +2
    CF1:   Size: 1 - 10GB
    CF2:   Size: 10 - 20GB
3. Modify the Profile 1080p and set the CF modifiers as follows
    CF1:  +2
    CF2:  +4
4.  In the profile set the minimum and upgrade to CF values
    minimum: 2
    upgrade to: 6
5. Add Movie Onward, set profile to 1080p
6. Run RSS Sync
7. The Movie Onward should be added to the download list
8 Run RSS Sync again
9. The Movie Onward is added again to the download list

This can be repeated over and over again and each time its added again.  

In the code below there doesn't appear to be any evaluation done to see if it is already in the download list.   The method __downloadDescisionMaker.GetRssDecision_ will always return True for this file even when there's an existing entry already being downloaded that is the same quality/CF value.


           private ProcessedDecisions Sync() 
           {

            _logger.ProgressInfo("Starting RSS Sync");

            var rssReleases = _rssFetcherAndParser.Fetch();
            var pendingReleases = _pendingReleaseService.GetPending();

            var reports = rssReleases.Concat(pendingReleases).ToList();
            var decisions = _downloadDecisionMaker.GetRssDecision(reports);
            var processed = _processDownloadDecisions.ProcessDecisions(decisions);

            var message = string.Format("RSS Sync Completed. Reports found: {0}, Reports grabbed: {1}", reports.Count, processed.Grabbed.Count);

            if (processed.Pending.Any())
            {
                message += ", Reports pending: " + processed.Pending.Count;
            }

            _logger.ProgressInfo(message);

            return processed;
        }

**Comment by ta264** [comment]
The queue check should be happening here https://github.com/Radarr/Radarr/blob/aphrodite/src/NzbDrone.Core/DecisionEngine/Specifications/QueueSpecification.cs not sure why it wouldn't be working

**Comment by Qstick** [comment]
Yea, a debug log should show it going thru queue spec and testing... @OuticNZ can you jump on discord?

**Comment by OuticNZ** [comment]
Yep, on discord, and I have a debug log

**Comment by henrikx** [comment]
Having a similar issue right now, for seemingly random movies. A download is sent to nzbget, but never shows up in radarr queue, causing it not to import. That will keep happening because once the download has been sent to nzbget radarr does not track it anymore causing no import. I found a workaround where if you remove the movie in radarr and then add it again it will suddenly start working.

I don't have debug logs for it right now unfortunately (just normal info/warn logs that don't really show anything), but the next time I see it happen I'll get a debug log and send it here.

@ta264 to consider reopen?
