### ISSUE TITLE
Option to not create a parent folder for every movie

### ISSUE THREAD

**Issue by Drewster727** [Radarr/Radarr#436]
I store my movies as follows:
```...\Movies\{QualityType}\{Movie Title} ({Movie Year}) - {Simple Quality}.mkv```

Example
```...\Movies\HD\Doctor Strange (2016) - 1080p.mkv```

That leads me to a couple issues with trying to switch to Radarr:

1. I do not want a folder for every movie. It's unnecessary. Please give us an option to avoid doing that. I understand *some* people want a folder to store subs with the file, but I pretty much stick to hard sub files anyway, as do a lot of people.
2. I'm unable to segregate my standard definition (SD) and high definition (HD) movies at the parent level. However, I can get around this by just merging them all. More of an annoyance.
3. Can we get the "simple" quality in the title formatting settings... i.e. "1080p" instead of "Blu-Ray 1080p" -- also not a big deal, just an annoyance.

Did a little searching and found some related items, but nothing direct. Apologies if this has been brought up before.

Thanks for your consideration and fantastic job on this.

**Comment by galli-leo** [comment]
Regarding 2.: You can still keep the root folder of your HD movies set to /Movies/HD. When you add a new movie just use /Movies/HD/ as a parent folder.
Regarding 1.: We plan on doing that eventually, however it will require a significant rewrite of existing code. See #153 for more details. I personally think each movie in its own folder is much more organized.
Regarding 3.: Not sure what advantage that has, since you then cannot differentiate between a poor WEB-DL and a BRRip. However, maybe we will implement that in the future.

**Comment by galli-leo** [comment]
Also please create a feature request here for your inquiries: http://feathub.com/Radarr/Radarr

**Comment by remirr** [comment]
I totally agree on all of these... have these been implemented yet?

**Comment by medjai** [comment]
@galli-leo do you have a target release that will implement this feature? We understand your preference may fall in line with some of the other users out there but I have to agree with @remirr and @Drewster727 I personally find this only necessary for a series to place in a folder but movies in my opinion do not need it.
