### ISSUE TITLE
Don't delete movies when list becomes empty

### ISSUE THREAD

**Issue by azumukupoe** [Radarr/Radarr#4492]
**Is your feature request related to a problem? Please describe.**
I use [letterboxd-list-radarr](https://github.com/screeny05/letterboxd-list-radarr) and it sometimes fails to retrieve films and the lists become empty. I want a workaround to not get movies removed from my disk when import fails.

**Describe the solution you'd like**
Don't delete movies associated with empty lists.

**Describe alternatives you've considered**

**Additional context**

**Comment by Qstick** [comment]
By default we do not clean/delete any movies when they drop off a list. If you have movies being deleted it's because you have cleaning enabled.

**Comment by Qstick** [comment]
So how do we know when list becomes empty in error vs when list is empty because you cleared everything out? This sounds like we are trying to cover up a bug on letterboxd-list-radarr by adding an option to Radarr which I’m not apt to do. They should return error instead of an empty list if they have issues with requests downstream.

**Comment by azumukupoe** [comment]
> 
> 
> So how do we know when list becomes empty in error vs when list is empty because you cleared everything out?

You wouldn't clear the listwhen when you have it synced with Radarr, or you would?
