### ISSUE TITLE
Make Movie Detail Page Mobile Friendly

### ISSUE THREAD

**Issue by Fringe09** [Radarr/Radarr#4523]
**Is your feature request related to a problem? Please describe.**
The feature is somewhat related to a problem. I've attached a screenshot from my iPhone where the summary of the movie is cutoff because of a static size window.

**Describe the solution you'd like**
I would like to have a button to click on to expand the window to show everything.

**Describe alternatives you've considered**
Auto size windows based on content

**Additional context**
Screenshot attached showing the problem.

![radarr_01](https://user-images.githubusercontent.com/4276475/84918697-cd490b80-b075-11ea-9958-efbff699e2c6.jpeg)

**Comment by VilDegard** [comment]
+1

**Comment by Qstick** [comment]
Think this should be much better on latest build?

**Comment by JBou** [comment]
![Screenshot_20200711-110827__01](https://user-images.githubusercontent.com/4021928/87220861-d7ee7c00-c367-11ea-948d-0d75abb1c2d3.jpg)


Tags icon is on a new line. this depends on the screen size of the device, but maybe we find a way to fix it.

It still cut's off the overview. It should have a dynamic height based on the content instead of having a fixed height.

When you click on the links icon, the button group is aligned centered under the link icon and you have to scroll out of the view to see all of it:
![Screenshot_20200711-111122__01](https://user-images.githubusercontent.com/4021928/87220858-d02ed780-c367-11ea-9b90-a94f7a45ac68.jpg)

**Comment by Fringe09** [comment]
Looks a little better

![IMG_1538](https://user-images.githubusercontent.com/4276475/87237538-481ef100-c3ac-11ea-8311-963808adce94.jpeg)

**Comment by Qstick** [comment]
So we still need:

- [ ] Fix Links Tooltip from going off page
- [ ] Fix Tag Icon from wrapping on supper small screens and PG-13 (abbreviation for minutes on small screens may work)
- [ ] Truncate overview correctly on small screens
