### ISSUE TITLE
[api] movie/lookup/ imdbid seems to be interpreted different

### ISSUE THREAD

**Issue by grabbel** [Radarr/Radarr#4533]
putting this in firefox:
/api/movie/lookup/?term=imdbid:tt0468569&apikey=
=joy
resolves in a json with movie information

/api/movie/lookup/?term=imdbid:tt1302006&apikey=
=nojoy
resolves in []

**Expected behavior**
json with movie information not dependent on the imdbid.

**Platform Information (please complete the following information):**
 - Radarr Version aphrodite and develop

IMDB that fails:
tt0472033
tt1302006
tt0472062

Best guess is that Radarr sees the last 4 numbers as a year and fails.

**Comment by Qstick** [comment]
You were pretty much correct. Radarr did some stuff to try and be "smart" on user searches by parsing the search string and seeing if it contained a year to narrow results a while back... unfortunately in the logic used to check if a Imdb parameter was passed we used this parsed (cleaned) title instead of the actual user passed search, thus the colon was removed for those which the parser thought were movie titles and years and so search would proceed with a normal search using "imdbidtt130" instead of the Imdb lookup.

Thanks for reporting as this has likely been around a while, also this lead to me finding and fixing another bug on Aphrodite. 😃
