### ISSUE TITLE
Support Deluge file moves

### ISSUE THREAD

**Issue by arcreigh** [Radarr/Radarr#4552]
**Is your feature request related to a problem? Please describe.**
Yes, when deluge is set to move files after download Radarr will not be able to find the files as they are not in their original location.

**Describe the solution you'd like**
Allow Radarr to watch a destination folder rather than the original folder reported by Deluge.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Qstick** [comment]
Like other clients Deluge should report the final path to Radarr if it's going to move files (post process) after downloading. We only know what the client tells us. If Radarr is looking in the wrong spot it's because deluge passed that as the download location.

**Comment by Qstick** [comment]
What version of deluge and what version of Radarr are you using?

**Comment by austinwbest** [comment]
I did this in Deluge and also do this with QBT & use the path mapping to account for the move.

All my movies download to T:/Movies/Pending and when complete they are moved to T:/Movies/Complete (by the download client) & then i have a post processing script that moves them to S for seeding. Point of this is you can move them all over the place and it wont matter if you know where *arr is looking :)

Since QBT reports to *arr that they are located at T:/Movies/Complete but my script moves them to S i have a path map setup that tells *arr to look at S when told to look at T:/Movies/Complete.. You should be able to do the same thing & tell *arr to look at the moved location when passed the download location.
