### ISSUE TITLE
Fallback to trying query as an ID if the search yields no results

### ISSUE THREAD

**Issue by Silent-Remux** [Radarr/Radarr#4574]
Would like to be able to avoid entering `ttNUMBER_HERE` or `tmdb:NUMBER HERE` and just enter the ID number. Thank you for considering.

![wavebox_0l1H5sTAaN](https://user-images.githubusercontent.com/16107603/86542164-0f45ce80-bf0b-11ea-9ea7-cbe872e6af24.png)

[AB#856](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/856)

**Comment by austinwbest** [comment]
Not sure this is ideal. TMDB is numeric so if you use numeric you are going to potentially get the wrong result from IMDB

Search for 516486
title = doesn't exist (default search)
tmdbId  = Greyhound (default if tmdb: is used)
imdbId = doesn't exist (default if imdb: is used (or tt, whichever))

You're trying to squash 3 possible queries into 1, and this can be done but i am not sure at what cost to the result times and organization of the results. So it will **require** multiple queries every time a search is done (joins/ors/etc) to try and figure out which one you want. Then comes the problem of what happens when there is a valid number for more than one and you get conflicting results from both. The UI would have to be updated to show which one the result(s) came from as well (incase of conflict).

Turn off real time searching and add a TMDB | IMDB button for the "Search" maybe? Also not ideal for those who like the real time results without having to press enter or click a search button.
