### ISSUE TITLE
PTP auth - use user/pass/passkey instead of manually entering cookie

### ISSUE THREAD

**Issue by evulhotdog** [Radarr/Radarr#458]

**Comment by amishtechie** [comment]
Please add this feature. It is a more standard way of doing it. Thank you.

**Comment by RainDear** [comment]
+1 for this feature.

I've still never managed to get it working with the cookie, and it spams the PTP site resulting in the error "Your popcorn quota has been reached, come back later!". The standard user/pass/passkey would both be more reliable and much more user friendly.

**Comment by onedr0p** [comment]
@raindear that means your are hitting their API to much with requests.

**Comment by RainDear** [comment]
@onedr0p thanks but I'm aware of that yes. This always happens when I paste in my PTP cookie and test the settings.

 I've done tests, and this is the way it seems to be:
1. I'm able to access the PTP site (no popcorn quota error)
2. I add PTP as an indexer and enter my cookie
3. I press "Test", which will fail
4. The logs show I failed because of the popcorn quota error
5. I'm no longer able to access PTP because of the popcorn quota error

Somehow Radarr must be hitting PTP with too many API requests, because it is definitely causing this error. Not sure what else I can to try and get around this, because I love Radarr but it just won't work with PTP for me.

**Comment by onedr0p** [comment]
Do you have anything else that queries the PTP API like couch potato?? I doubt adding the other fields will help you out, because the code it takes will still pass a cookie thru with username, password and passkey. In other words Radarr will still pass a cookie to PTP when you apply username, password and passkey.

Are you able to access the following URL on the machine with radarr?

https://passthepopcorn.me/torrents.php?json=noredirect

**Comment by RainDear** [comment]
I've disabled couchpotato in case it was causing it, but it made no difference. I can access that URL yes, but after trying to test the indexer with Radarr I won't be able to. If the user/pass wouldn't make a difference, could you even add a label describing the format the cookie string should be in?

Mine just looks like:
__cfduid=example; session=example; PHPSESSID=example

Is that correct?
I haven't looked at the code, but does Radarr retry lots of times if it fails to log in with the cookie?

**Comment by RainDear** [comment]
I've just got it working - the only difference was that I checked the "Keep me logged in" box when logging in on PTP to get my cookie. Maybe that creates a cookie that's valid for a longer period of time?

But anyway, it's working now and thanks a lot for your help - I really appreciate it.

**Comment by onedr0p** [comment]
Ahhh yes, nice catch. That will do it! I hope to add the other fields in the future, just haven't gotten time to implement it yet.

**Comment by evulhotdog** [comment]
@RainDear that's exactly what it does. It changes the expiration of the cookie, and essentially what you were doing was logging in, and then trying to use the same already-expired session.

**Comment by RainDear** [comment]
Good to know. Might be worth adding that to the page to let people know - I'm sure I'm not the only one who doesn't usually tick that box!
