### ISSUE TITLE
Radarr falsely warns of docker directory problems

### ISSUE THREAD

**Issue by ShadwDrgn** [Radarr/Radarr#4803]
Radarr issues a warning:
You are using docker; download client dlg places downloads in /finished but this directory does not appear to exist inside the container. Review your remote path mappings and container volume settings. 

However, as Radarr should be well aware, since it requires it, I have a label for Radarr in my client (deluge) that has settings specific to it that don't use that directory, so I've constantly got a big error that isn't valid up on my Radarr install.

**To Reproduce**
1. install Radarr in a docker container with a *default* download directory not mounted in your radarr container, but a label with alternative move on completed settings that IS mounted.
2. Open Radarr
3. See error

**Expected behavior**
Radarr knows of the label that's configured in it's own settings and doesn't produce an error provided that the label is configured to a directory it knows of.

**Platform Information (please complete the following information):**
 - OS: Docker: Linuxserver/radarr, linuxserver/deluge
 - Mono Version: Whatever version is in the above image's latest container
 - Radarr Version 3.0.0.3284

**Debug Logs**
No crash, so no debug logs.

**Comment by slavikme** [comment]
Same here.

I am using Deluge, as my download client. Although the remote path is set correctly, Radarr still shows this error:

> You are using docker; download client Deluge places downloads in /downloads/Deluge/Completed but this directory does not appear to exist inside the container. Review your remote path mappings and container volume settings.

My remote path settings:
Remote Path: `/downloads/Movies/`
Local Path: `/downloads/`

The remote path settings are correct, as all of my downloads that coming from Radarr, are labeled with `radarr` label in Deluge. And in Deluge the download path is actually `/downloads/Movies/`. I think that Radarr mistakenly takes the general settings path in Deluge, which is `/downloads/Deluge/Completed`, as the error message indicates.
This looks like bug to me, because if Radarr want to verify the path, it should take the Deluge label's settings into consideration.

**Comment by casperse** [comment]
Same problem here always get the error but everything is working perfectly (Mapping remote seedhost)
Version: 3.0.0.3860
Package Version: 3.0.0.3860-ls25 by linuxserver.io
.NET Core: Yes
Docker: Yes
