### ISSUE TITLE
Trakt watchlist can't be used as a list in Radarr

### ISSUE THREAD

**Issue by chtk** [Radarr/Radarr#502]
The watchlist on Trakt is a special kind of user list. It seems the watchlist can't be added to Radarr as a use list. This results in a HTTP 404 error in the log:
`[v0.1.0.1157] NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [https://api.trakt.tv/users/[redacted]/lists/watchlist/items/movies]`

**Comment by JourneyOver** [comment]
I just went through adding a little over 450+ movies to radarr from my trakt watchlist manually since I didn't even know this was even semi-possible.. Hope this can be fixed as it would help out tremendously on keeping radarr up to date with my trakt stuff.

**Comment by onedr0p** [comment]
Right now trakt works with users lists, can anyone point me in the right direction on trakt for getting the watchlist feed?

**Comment by onedr0p** [comment]
It looks like you need to pay for trakt vip for RSS feeds.

**Comment by JourneyOver** [comment]
hmm would it be possible to do it through the trakt api instead maybe? http://docs.trakt.apiary.io/

**Comment by onedr0p** [comment]
Okay, awesome, I see the problem here. I'll push an update in a jiffy.

**Comment by JourneyOver** [comment]
@onedr0p if possible could you have an option so that if the movie disappears from your watchlist it won't be deleted from radarr, because the way things are on trakt as soon as you watch something on your watchlist it gets taken off the list (unlike custom created lists where it stays unless you take it off manually)

**Comment by onedr0p** [comment]
Lists don't remove movies from Radarr, it's a one way sync.

**Comment by JourneyOver** [comment]
Alright that's good, was hoping it was that going to be way :D 

now if only I could import all my movies from my watch history to radarr as well so I can get that all ready for when I get my bigger hard drives soon and need to redownload a lot of stuff from my watch history since I have over 700+ movies in my history...

**Comment by onedr0p** [comment]
![image](https://cloud.githubusercontent.com/assets/213795/22401368/572f91a8-e59e-11e6-9f19-b5b77d1515ee.png)

I added a Trakt List Type selectbox, you have options between WatchList or CustomList. I can look into adding watch history type too.

**Comment by JourneyOver** [comment]
Looks good!

 @onedr0p How do I go about accessing this once it's radarr grabs this update? because I don't see any option anywhere to add movies from lists and such, only thing I see is add stuff from on disk already or typing the name of a movie into the search box thing..

I'm on the Dev Ver. 0.2.0.238

**Comment by onedr0p** [comment]
You can switch the branch to 'nightly' in the Settings > General make sure you click show advanced to see the options.

**Comment by JourneyOver** [comment]
Alright cool :D now does importing from a list take into account any duplicates?

Like say I already have a movie on radarr, and on my list that I import has the same movie on it, will it skip the one on the list and move onto the next?

**Comment by onedr0p** [comment]
I don't think it will show up as a movie to import, it checks for you. (I think) hah. Let me know if I'm wrong.

**Comment by JourneyOver** [comment]
Alright lol will report back in a few on everything ^^ see if I run into any bugs or anything of the sort that needs to be changed or anything :p

**Comment by JourneyOver** [comment]
@onedr0p 

1. Usernames that have spaces in them you need to add a "-" where the spaces are (trakt is weird in that they add a "-" inbetween usernames if they have spaces in the name anywhere.. (either make a note of this on the trakt popup thing or force it some how? (it's without quotations btw)

2. Importing movies, does skip movies already added into radarr from the looks of it. 

2.5 I have a  few movies that don't import for some reason though they are titled as

* The Chronicles of Narnia: The Magician's Nephew
* The Amazing Spider-Man 4
* The Fantastic Four 2
* Inhumans
* Black Widow
(there might be more but that's just mainly from my watchlist) might be because even if you do a search for them on the "Add new movie" page they don't come up in search at all..

3. For Custom List you need to provide an option to input a name for the custom list you want to import from instead of it trying to pull from a list called "customlist" as it'll error out with "Unable to connect to list, check the log for more details" because you are pulling from a list that doesn't exist. so maybe instead of using a dropdown for Trakt List Type maybe make it a textbox instead to type the list name that you'll want to import from?

**Comment by onedr0p** [comment]
1. Seems easily enough to handle, just replace spaces with dashes
2.5. We might need a little more info, was there anything in the logs as to why they didn't get imported?
3. There is a textbox to fill in the name for a custom list. (see screen-shot above) "Trakt List Name", I should rename this to "Custom List Name" to avoid confusion.

**Comment by JourneyOver** [comment]
@onedr0p  yep yep 

1 should be pretty easy to deal with

2. Ah I did not know that, I was using it as a name convention to remember what the list I was importing was instead xD (maybe make a seperate box under the trakt list type for the use of the custom list name?)

2.5 just get errored out with these errors for (example with "The Chronicles of Narnia: The Magician's Nephew")  "Movie with TmdbId 145226 could not be found. This is probably the case when the movie was deleted from TMDB." & "Couldn't map movie The Chronicles of Narnia: The Magician's Nephew to a movie on The Movie DB. It will not be added :(" so it appears to be because it's not on the TMDB site.. 

another issue (when importing from a big list it seems to have trouble (tried importing all my movies from my watched history and it grabbed 633 movies let it go for a while and nothing seemed to happen at all) doing small bursts of movies seems to do the trick though..

on an unrelated note --
Why does my log keep getting spammed every 2-3 minutes with this http://i.imgur.com/RE6mrr5.png kinda annoying when trying to test things :x

**Comment by onedr0p** [comment]
Searching on TMDB I cannot find that movie:
https://www.themoviedb.org/search?language=en-US&query=The+Chronicles+of+Narnia

Same with Fantastic 4 2 (looks to be this movie)
https://www.themoviedb.org/movie/1979-4-rise-of-the-silver-surfer?language=en-US

The rest look like their names are not found on tmdb, you might have to rename manually to get them to be recognized.

3. Use the "Name" field at the very first field to give it a unique name, "Custom List Name" will be for trakt custom list.

That last part should have been fixed in an update, The media covers weren't downloaded yet so it complains (I think)

**Comment by JourneyOver** [comment]
it might be because the movies that are in the above list are not anywhere near a release date yet as some movies are years and years away from any sorta release (or possibly not being released at all (ex. fantastic 4 2 is in a complete limbo right now) )

3. Okay I actually see that now, idk why but I read password there for some reason and input my password into the spot for the watchlist history list I did woops >..<


and sadly not fixed at all :/ as it still spams my logs like crazy every few minutes.

**Comment by onedr0p** [comment]
you can edit the list by going to where you added them.

**Comment by JourneyOver** [comment]
all I get is "all" then my 2 lists I have made and then "add a new list" in the dropdown, if I select one of my two lists I want to edit the info on there is no edit button just "fetch"

**Comment by onedr0p** [comment]
Go to the settings page and click the lists tab. You can manage them there.

**Comment by JourneyOver** [comment]
oooh I didn't even notice a new setting in the settings page.. I really need to look around better at things >...< well there's that done, everything seems to be working well now thanks :D 

now to figure out why MediaCoverMapper is constantly spamming my logs complaining about pictures not being found since it's supposedly fixed as you say :s

**Comment by LordApples** [comment]
I am unable to add my Trakt watchlist to radarr. I keep getting a `Unable to connect to list: HTTP request failed: [401:Unauthorized]`
I'm on version 0.2.0.269

**Comment by JourneyOver** [comment]
working fine here, make sure you are entering all the info correctly and you aren't trying to add a list from a private trakt account.

**Comment by onedr0p** [comment]
What determines a private trakt account?

**Comment by JourneyOver** [comment]
@onedr0p there's not much that determines a private trakt account, as anyone can have one and esentially what it does is block any outside access from seeing the account watch history/lists and everything else unless you add them as a friend (and they accept the request) .. 

so only real way to do a get a list from a private account is to make a login system for the trakt stuff in some form or fashion.

as an example -- here is my profile (completely open to the public so everything is viewable)
https://trakt.tv/users/journey-over

and then here is a private account that I have laying around for testing things out --
https://trakt.tv/users/omgberrix34

as you can see from the second profile you can't access anything to do with the second profile other than "following them" and even if you do follow them you won't be able to do anything still unless said profile would accept your request to follow them.

**Comment by LordApples** [comment]
@JourneyOver you were right, it was a private trakt account issue. It works now after I've made it public. 
Thanks for the tip!

**Comment by JourneyOver** [comment]
@LordApples not a problem, glad you got it sorted out for now :)
