### ISSUE TITLE
Add a colour picker for colour blind mode

### ISSUE THREAD

**Issue by Akirainblack** [Radarr/Radarr#5095]
**Is your feature request related to a problem? Please describe.**
Due to there being multiple forms of colour blindness the current colour blind option doesn't work for me.

**Describe the solution you'd like**
Have a colour picker instead of defined colours for colour blind mode

**Describe alternatives you've considered**
Enabling the "detailed progress bar" option helps.

**Additional context**
bakerboy448 will hopefully be adding as discussed on discord.

[AB#796](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/796)

**Comment by bakerboy448** [comment]
Screenshots of existing UI (not perfect)

![image](https://user-images.githubusercontent.com/55419169/94827818-7cfc7c00-03ce-11eb-8224-ff8742fe2a59.png)
![image](https://user-images.githubusercontent.com/55419169/94827857-84bc2080-03ce-11eb-9003-1ef83f9b4b02.png)
![image](https://user-images.githubusercontent.com/55419169/94827879-8be32e80-03ce-11eb-994c-87ea1de38839.png)

Rough Testing here https://www.color-blindness.com/coblis-color-blindness-simulator/

**Comment by Qstick** [comment]
@Taloth what are your thoughts on how we could improve this?

**Comment by Taloth** [comment]
Step one is to isolate the actual problems that the user experiences. Specifics are important here.
Don't rely on color blind simulators when tweaking stuff, they can be useful for educating ppl, but don't give you an accurate representation.

The original color blind mode in Sonarr was implemented for v2, which has larger colored surfaces. v3 is a bit more complicated.
For Green-Red in the calendar. The colors are pastel (bright + low saturation) which generally poses a problem for color blind people. Biggest issue is of course that Green and Red represent to opposite states. So Missing was striped in color blind mode for that reason.
If @Akirainblack has problems discerning the two, then we need to know which part exactly.

The Series posters overview has a 'show progress' option which effectively increases the height of the colored bar. So what information isn't properly conveyed?
![image](https://user-images.githubusercontent.com/6383890/94871413-3187b380-044a-11eb-8591-451a977e093f.png)
vs
![image](https://user-images.githubusercontent.com/6383890/94871289-f2f1f900-0449-11eb-9865-0906dc15620e.png)
The first one is very hard to distinguish for me, the second one much easier. Note how the second doesn't just stripe it, it also effectively darkens the red bar. As mentioned people experience color blindness differently, that's why it's important to identify where the problem lies. Note that we're not trying to convey colors, we're trying to convey information.

I'm not in favor of a color picker. But I'm not opposed to swapping the checkbox for a dropdown if it is absolutely necessary.

PS: I've moderate deuteranomaly.

**Comment by bakerboy448** [comment]
I think the larger immediate issue is not so much the color blind mode, but I am sure that is a problem. Instead it’s that there is insufficient contrast between the bars and the posters...they blend in.

**Comment by austinwbest** [comment]
It was also said that downloaded & missing are very hard to tell apart without showing the text on the progress bar.

A drop down with how many options when it is all said & done?

**Comment by Akirainblack** [comment]
@Taloth I have protanomoly which is probably why we're seeing this very differently.
As I said on discord, the show progress option does help but I still find it quite difficult.
I maybe changing the colours in the stripes?
I simply linked a colour blindness simulator so that people could in some way see what the problem is, trying to describe it is impossible as it's not something which develops. 

The problem with a set of colours is that whilst it will work perfectly for one person who is colourblind it quite probably won't work for the next. (I have a pair of colour correcting glasses which help me immensely, however they have no effect for a friend with the same form of colour blindness but much more pronounced).

**Comment by Taloth** [comment]
> I have protanomaly

Good to know. So that's probably affecting how you perceive the striped red bar in the screenshots I posted earlier. What can you say about those two screenshots?
Also, can you make a screenshot of what's hard for you to distinguish?

> I simply linked a colour blindness simulator so that people could in some way see what the problem is

Of course, I do that too, I just wanted to warn @bakerboy448 not to use it to compare/fix things but only to understand it.

Note that for Color Impaired mode it was expected that the progress bar on the posters would have to be enabled as well, simply because the lines are otherwise too thin.
One step that we could take is force the height even when the percentage is not enabled. But you mentioned that the detailed progress bar was insufficient, so we need to find out in which way it's insufficient.
I have no problem with tweaking the contrast of it. On one of my monitors the striped red bar is easily distinguishable for me, on my other monitor it's much harder to 'glance'.

Also, how does it compare to the progress bars in the 'table' view?

**Comment by Akirainblack** [comment]
Sorry, I was called away whilst we were discussing this and I can't find the discord conversation again.
Possible ideas, for the missing it being red/black striped?
Yes, I always try to have the "progress bar" option selected but this seems to randomly reset on me for some reason.
Even if the striping was the bar split into 4 and being red/black/red/black that would make it far more obvious.

**Comment by Taloth** [comment]
@Qstick some mockups from sonarr, but probably better to do it for radarr. I'm thinking 50% width centered and 20% left aligned.
![image](https://user-images.githubusercontent.com/6383890/95104271-ea453f80-0735-11eb-96a5-fc04b9397ebb.png)

@Akirainblack I'm asking specifically about the contrast in the red bar itself since it has darkened. I'm ok with darkening it a bit more, but I need to know if that's the problem.
UI settings are stored in the browser. So if you're switching systems or have a privacy plugin that purges it then those would be reset.
Does the color impaired mode also reset when it happens?

**Comment by Akirainblack** [comment]
@Taloth I'm more than happy to answer any questions, however many times. 
Of the mockups the middle left is pretty clear. Sadly for me (at least on this screen) the red bars blend together and whilst I can just about see they're there they appear and disappear in a very uncomfortable way. (sorry if that doesn't make any sense). I can't quite remember, I'll check next time it happens. I was suggesting something like:
![image](https://user-images.githubusercontent.com/37367305/95183250-9d0cb080-07bd-11eb-8072-138b448867ae.png)
(sorry for the horrible mockup, I'm not very good at editing images)

**Comment by Taloth** [comment]
> sorry if that doesn't make any sense

yoohooo, I'm colorblind too. We experience similar problems that simply manifest differently.

Slide around here and let me know what range of values work for you: https://jsfiddle.net/3ne6g4qc/
Both in terms of visibility and comfort. If you set it to 95 it'll be opaque, which is likely comfortable to the eyes.
I'm more interested in the severity you experience since that'll help me in the future, it's not that I'll just copy paste the values.
I really don't want to go for black coz it's is soooo ugly.
Note that the stripes are the same color tint, it's just darkening the bands. (5% and 15%)

**Comment by Akirainblack** [comment]
@Taloth Fair enough, I've always liked black. It goes with everything ;) so I can't end up wearing colours that clash LoL.
Starting around 75 the bars start to get more defined. 55 really starts being incredibly clear. 88/89 starts giving me a headache making the bar flicker and 92+ everything is the same. 
I hope that helps.

**Comment by Taloth** [comment]
> so I can't end up wearing colours that clash LoL.

yeah.... _(sigh)_ FML

But, thanks that's exactly what I needed to know.

I read about it being uncomfortable for you which is why I mocked up the jsfiddle because I don't have that.

When I test it with 65% in Sonarr it's rather strong, it's at a point that i'd rather have opaque than striped: (I intentionally limited green to 50% width as well, we're looking at colors atm, finalized green would be 100% width and red 50% or something similar)
![image](https://user-images.githubusercontent.com/6383890/95198156-0bac3700-07db-11eb-9605-aad65b9f6027.png)

This is 75%:
![image](https://user-images.githubusercontent.com/6383890/95198313-50d06900-07db-11eb-8341-2265e2cd8e3c.png)

And opaque 75%:
![image](https://user-images.githubusercontent.com/6383890/95198374-6d6ca100-07db-11eb-95b7-b41eba307a98.png)

And finally opaque 85%: (this one starts to be borderline between the left green one and middle red, the middle one could be red or brown, dark green w/e)
![image](https://user-images.githubusercontent.com/6383890/95198422-8412f800-07db-11eb-93ac-4be4fa78c691.png)

Note the yellow/orange at the right is also striped (diagonally) it has the original 5%/15% colors. Do you have the same discomfort with those?

**Comment by Akirainblack** [comment]
Yes, slight discomfort, as with the original red it's essentially behaving as though there's some optical illusion going on and I can't quite work it out.
The 3rd and 4th red have fuzzy edges for me (3rd far more than 4th), not sure why. All other boxes have clearly defined edges.
The first is by far the best for me.

**Comment by Taloth** [comment]
3rd and 4th have contrasts that are much closer to the background. Could your monitor be a factor here?

The discomfort you experience with small variations of the same color is rather concerning. I should check if they have an official term for that.   
It would be a good idea to check it on another monitor as well.

Fun fact, the 1st appears brighter to me compared to 2nd due to the increased contrast, despite being darker.

Here's the yellow one lowered to 75% (down from 85%), it should alleviate the discomfort, correct?
![image](https://user-images.githubusercontent.com/6383890/95199768-a574e380-07dd-11eb-9a38-b1f81fbb2040.png)

**Comment by Akirainblack** [comment]
On my laptop (to change screen) and the "fuzzy" effect on the 3rd red is not there.
Absolutely that removes the discomfort.

**Comment by vtt-lair** [comment]
Why not just use icons instead of colours for the various statuses? Using colours will always be difficult for the different types of colour blindness.

So have an icon for each downloaded, for each missing, for queued and unvailable. Make it standard and not behind a colour blindness mode (I didn't even know about the colour blind mode until I saw this issue).
