### ISSUE TITLE
Filter on status = Downloading

### ISSUE THREAD

**Issue by springjools** [Radarr/Radarr#5272]
![Untitled](https://user-images.githubusercontent.com/5911982/97272527-be037700-183a-11eb-8592-98e3db61da11.png)

**Is your feature request related to a problem? Please describe.**
Filter on status = Downloading
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by springjools** [comment]
I have a bunch of movies that are downloaded but not automatically imported. I want to filter to see these.

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/pull/4924

@geogolem you've been working on this area, thoughts?

**Comment by geogolem** [comment]
I think that is the purpose of Activity/Queue, is it not?

If you click activity don't you see those movies that have been downloaded but not imported?

**Comment by springjools** [comment]
Activity queue shows that and a bunch of other stuff as well. This would be convenient in that dropdown box, since you can already filter by monitored and unmonitored as status.

**Comment by austinwbest** [comment]
That is the purpose of activity as geo mentions. No need for a filter when it has its own dedicated page.

**Comment by springjools** [comment]
There is already a filter though

**Comment by bakerboy448** [comment]
The confusion largely stems from the filter of "Status" really being an "Availability" filter.

There are a few PRs that geo has that will clean all this up.

**Comment by springjools** [comment]
But status is much better than availability. Availability is binary, status can have more data points

**Comment by bakerboy448** [comment]
Availability is not binary; there are multiple options:
TBA
Announced
In Cinemas
Released
PreDB - (Need to remove from Movie Edit Dropdown)
Deleted - (only if TMDB ID no longer exists)

**Comment by springjools** [comment]
You forgot:
Missing
Wanted

**Comment by bakerboy448** [comment]
> You forgot:
> Missing
> Wanted

I did not.  Those are not availability statuses.  Those are movie statuses.  Also filters for those exist already

**Comment by geogolem** [comment]
Its very confusing right now, because it is messed up. There are a couple PR's that clean it up and add a bit more functionality; however, the functionality regarding the "downloading" status or Missing, Wanted can be specified in other ways alrady.

"Downloading" etc. is on the Activity Queue, 

Missing/Wanted are either already possible, or will be clarified/possible with the changes in the existing PR's.

For example Missing = IsAvailable & NoFile
Wanted is Missing & Monitored

There have been discussions about adding custom filters for the "Status" column but this column doesn't really consistently map to anything. Sometimes it shows Quality Profiles, other times it shows Availability info and other Downloading etc.

All of the things it shows can be filtered using other means (once the PR's are integrated), so there is really no need to filter this column directly. Its more of an informational column...

**Comment by bakerboy448** [comment]
@austinwbest, @Qstick   I'm thinking we can close this one as it is a FR based on a misunderstanding of "Status" which @geogolem's PRs should clean up and clarify.

And Activity covers the overall request
