### ISSUE TITLE
Custom Formats Changing in ms when Comparing Existing to Potential Grab

### ISSUE THREAD

**Issue by bakerboy448** [Radarr/Radarr#5296]
**Describe the bug**
"so the file on disk is 4k remaster and then milliseconds later just remaster"

Simply put: Existing file is Remux-1080p v1 [DTS-HD DTS-X, 4K Remaster]  vs. New item's custom formats [DTS-HD DTS-X, Remaster] do not improve on [DTS-HD DTS-X, Remaster]  thus it should not be grabbed; but it is

**To Reproduce**
Described above

**Expected behavior**
Described above

**Screenshots**

**Platform Information (please complete the following information):**
Version
-3.0.0.3978
-Linux

**Debug Logs**
https://pastebin.com/uMeBeyeg

See Line 38 per austinwbest

**Comment by Qstick** [comment]
Line 38 is very likely the call to isUpgradable from HistorySpecification. This call is checking the most recent grabbed release compared to the current release in question, thus it wouldn't show the current files CFs only the CFs of the release in from history vs the CFs of the release its seeing from RSS or Search. So I don't think they are "changing in ms" because it's not actually comparing existing file CFs here. The most recent grab could be some other release in queue, failed, etc..

**Comment by Qstick** [comment]
We can track the real issue that is happening in #5295, as this is not an issue (though it maybe confusing looking at the logs if you are not familiar with the decision engine process).
