### ISSUE TITLE
Cutoff - Size issue

### ISSUE THREAD

**Issue by Firemad03** [Radarr/Radarr#534]
Hi,

Little issue that I found with the cutoff. If a movie found a release with 8GB for the Bluray1080 for example and later on the web we have a release of 32GB with an unlimited quality Radarr won't download it because both are tagged to the same quality (Bluray1080).

Radarr should check for the quality type and after the maximum limit.

Example:

I downloaded:

![image](https://cloud.githubusercontent.com/assets/24792889/22445367/181c7fc6-e715-11e6-9778-e091319230a9.png)

Now the release available:

![image](https://cloud.githubusercontent.com/assets/24792889/22445391/37c97bbc-e715-11e6-94b6-1edb799ce5c4.png)

Because it's the same quality it doesn't upgrade it.

Maybe one of the solution is to add a Remux Quality for the Bluray1080 (and you will need it for 720 and 4k too). Remux quality have always the tag Remux in the title.

I saw that on build 0.2.0.267 you added more quality profile.

I don't know if it's the best approach for the cutoff.

Thanks

**Comment by Crowley007** [comment]
This is the reason why I have requested the Remux quality be added separately here http://feathub.com/Radarr/Radarr/+24. The new preferred tags are nice, but do not fix this issue. 

Of course, "Upgrade to larger size until this size is met" would work, but then there is no telling how many unnecessary releases would be downloaded until the preferred Remux version is found.

**Comment by ryanborstelmann** [comment]
I'd like to touch on this again, as I'm currently using the new bulk-importer to add movies to Radarr and ran into an example case which I think is relevant (and i'll run into a couple hundred times in my 1100 movies). Example:

Movie1 has a size on disk of 1.4GB and is 1080p. When I import it, it's tagged as "BluRay 1080p". My "BluRay 1080p" quality profile has a size constraint of 10.29GB to 22.16GB (for 140m movie), so the 1.4GB is well outside these bounds.

When I add the movie and search for new releases to upgrade, all would-be eligible releases are marked as "same quality" in the results, since Radarr tagged the file as BluRay 1080p. Ideally, this would use the logic "the movie tagged as BluRay 1080p, but the file size doesn't match the constraints set in the Quality Profiles, so Radarr should download a version that is properly sized".

I'm not sure the best way to implement this, either an application-wide option to "upgrade" current files, or a movie-by-movie basis could be used.

I'd love to hear the team's thoughts.

**Comment by onedr0p** [comment]
You guys can use the Blu-ray remux quality to upgrade to a better 1080p release. That is currently the only way to do what you ask. Otherwise open a issue on feathub if there isn't one for upgrading quality sizes. We don't really want to implement this though and the remux is prolly the best way to handle it.

**Comment by marshalleq** [comment]
I have the opposite issue - I've re-encoded many things as h265 and it keeps downloading bigger versions of the files and doesn't seem to recognise the new and smaller codec.  So just noting for future readers that ehrm, it's not the size that matters, but the quality.  Unfortunately, we have a very dumb method for determining quality that should probably be revisited and advanced based on media scanning.
