### ISSUE TITLE
Adding Cardigann/Jackett torznab feeds produces error

### ISSUE THREAD

**Issue by paulmorabito** [Radarr/Radarr#536]
Trying to add a torznab feed, using exactly the same settings as in Sonarr (where it works) but with Radarr I get:

[v0.2.0.267] System.InvalidOperationException: Sequence contains no elements
  at System.Linq.Enumerable.First[TSource] (IEnumerable`1 source) <0x411613f0 + 0x00143> in <filename unknown>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () <0x415ba850 + 0x000b7> in <filename unknown>:0 

17-1-31 08:56:15.5|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details

**Comment by onedr0p** [comment]
Should work with Jackett (I have tested it), however cardigann will not work because of the this issue: https://github.com/cardigann/cardigann/issues/327

**Comment by paulmorabito** [comment]
I get the same error in Jackett (Jackett-public). 

Thanks for confirming re: cardigann. I'll await the fixes.

**Comment by onedr0p** [comment]
Make sure you are on the latest jackett release, works on my end ;)

**Comment by Dnkhatri** [comment]
You don't need jackett public anymore as with Cardigann definitions support
you can use public trackers on the latest version of jackett. Cardigann
developer is missing so unlikely to get many updates apart from definitions
that kaso maintains for jackett and Cardigann both.

**Comment by paulmorabito** [comment]
Are you saying there is a Jackett definition for Cardigann so therefore can have a Cardigan source feed into Jackett? Why would I want to do that?

Cardigann was also just updated a few days ago. Is it not being developed?

Sorry, I am just confused on your reply.

**Comment by Dnkhatri** [comment]
Cardigann not being developed anymore the Cardigann guy has disappeared.
The releases that have happened recently is kaso mostly adding new
definitions and he says he is unwilling to take the responsibility to
maintain or update Cardigann app itself. So unless someone steps up to
maintain and update Cardigann you are unlikely to get any fixes for
Cardigann just cardigann definitions file updates.
     Kaso built the ability to use Cardigann definitions inside the latest
version of jackett. So the same definition file in Jackett works better
than in Cardigann example being in Cardigann you don't get the correct
torrent release dates or sizes for piratebay, kat but do so in Jackett. And
the latest version of jackett unlike jackett public because of regular
updates is a lot Stabler.

**Comment by rafacapa** [comment]
This issue has been solved in Cardigann as it already works when adding a Torznab 
The problem now is that it's Radarr is not showing any result when performming the search against Cardigann
