### ISSUE TITLE
{Movie OriginalTitle} not 'valid' in v3 Movie Folder Format

### ISSUE THREAD

**Issue by bakerboy448** [Radarr/Radarr#5426]
**Describe the bug**
Title

**To Reproduce**
Not needed

**Expected behavior**
Per Q "We should allow that tag in lieu of title tag"

**Screenshots**
none.

**Platform Information (please complete the following information):**
skipping this...we know its an issue on v3 stable.

**Trace Logs**
Not needed.

**Comment by Qstick** [comment]
Right, it works but the validation expects {title} param to always be there... we should allow either or

**Comment by douglas24** [comment]
Not sure if I should open a new issue, but in my original reddit help post the issue is that {Original Title} and {Original Filename} don't change the movie folder name to the original movie folder name. It still uses some internal default of {Movie CleanTitle} for the folder name. I've tested using the 'Preview Rename' on an individual movie page, 'Organize' function in movie editor, and adding a new movie after the changes but it is still defaulting to {Movie CleanTitle} despite {Original Filename} set and accepted as valid for folder name.

**Comment by bakerboy448** [comment]
Dynamic movie folder names are not supported in v3 as they caused nothing but issues and logically don't make sense. (Why does a movie folder...for a movie change based on a file? That's not logical as they are not related.)

You can do something like SubFolder\MovieName  in your file naming scheme.

**Comment by douglas24** [comment]
I just want to keep the original folder name. Since the original folder name and movie file name both match (aside from the video extension), it was the only way I knew of to accomplish it. Is there an {Folder OriginalName} option?

**Comment by austinwbest** [comment]
Sorry, no there isn't. The folder can not use file properties.

**Comment by bakerboy448** [comment]
work around that should get you close enough

Movie Folder Naming `{Movie CleanTitle} ({Release Year}) {imdb-{imdbid}}`

File Naming `{Original Title}/{Movie CleanTitle} {(Release Year)} {Edition Tags} [imdb-{ImdbId}]{[Custom Formats]}{[Quality Full]}{[MediaInfo 3D]}{[MediaInfo VideoDynamicRange]}[{Mediainfo VideoBitDepth}bit][{Mediainfo VideoCodec}]{[Mediainfo AudioCodec}{ Mediainfo AudioChannels}]{-Release Group}`
