### ISSUE TITLE
Unable to import non-wanted movies from CouchPotato list

### ISSUE THREAD

**Issue by crafty35a** [Radarr/Radarr#550]
I added a CouchPotato list with the "Only Wanted" option set to No. I believe with this setup I should be able to import my existing collection items from CP to Radarr. But when fetching the list, only my CP Wanted items are returned, regardless of the "Only Wanted" setting being disabled.

**Comment by galli-leo** [comment]
Personally, I wouldn't add existing movies with the Couchpotato import feature as it won't add your existing files. I would wait until the bulk add is completed.

**Comment by onedr0p** [comment]
Yes, closing this issue because bulk import will handle it.

**Comment by bernieke** [comment]
Hi,

I'd like this ticket to be re-opened as well.

My flow is actually to delete movies after I've watched them, but keep them in couchpotato (now radarr, if this gets fixed), so I can keep track of the movies I've watched as well. (And avoid re-downloading movies I've already seen but forgotten I'd seen them.)

So to me this is something completely separate from the bulk import (which I've already done), which imports the movies I still have on disk.

I was hoping to do the following:
1) bulk import movies on disk as unmonitored (OK)
2) list import couchpotato only wanted as monitored (OK)
3) list import couchpotato not only wanted as unmonitored (NOT OK) -> Assuming this would leave existing movies already in the database alone, otherwise I'd have to switch 2) and 3).
4) disable couchpotato list import

Actually, even better would be if I could skip step 1) and just have step 3) take care of that as well? (I don't know how much information about files on disk you get through the couchpotato api?) But I would already be extremely happy if step 3) could just import the deleted movies for me!

**Comment by bernieke** [comment]
I managed to get around the whole problem by using the couchpotato api to get the whole list of 2450 movies, extracting the imdb numbers from that json, and using the trakt api to input them to my watchlist there. Which then allowed me to use the trakt list import to get them back into radarr.

So for me it's no longer required.

Some form of generic csv list import (just a list of tmdb numbers would suffice I imagine?) would be useful for other people in my position though...
