### ISSUE TITLE
Web and Bluray Release Dates

### ISSUE THREAD

**Issue by McGriddle** [Radarr/Radarr#553]
Is there some sort of api where both the bluray release AND web (itunes, amazon) release dates can be found? Manually I can go to http://www.dvdsreleasedates.com/ and see the two different release dates. With CouchPotato it won't grab a release until the bluray release date (unless you change the settings ignore the bluray date).

Is it possible to only grab a movie say when today is >= the web release date?

**Comment by onedr0p** [comment]
Can't you just use profiles, and let it upgrade the movie until it reaches your cut off? For example:

![image](https://cloud.githubusercontent.com/assets/213795/22495729/5270ebba-e811-11e6-8c93-51f3cec40073.png)

**Comment by galli-leo** [comment]
You can just set the profile to bluray

**Comment by McGriddle** [comment]
I guess my concern is from two different points.
1. fake detection - I wouldn't want a release grabbed until a known date
2. ~web-dls release names in CP are matched are matched as 1080p, 720p and brrip for me.~ I didn't see radarr supports web-dl release types.

**Comment by galli-leo** [comment]
@McGriddle Yup keywords and file sizes. Regarding fake detection: I would just use a reputable public tracker or only allow verified uploaders.

**Comment by geogolem** [comment]
I realize this might be unreleated and my intention is not to highjack this discussion, but I was curious as to how radarr currently determines which release dates it displays for a given movie...

Consider how radarr currently handles the following examples:
-------------start of examples----------------
"90 Minutes in Heaven", "Released", "Available 28. April 2016"
"Rogue One: A Star Wars Story", "In Cinemas", "In Cinemas: December 2016"
"The Fifth Estate", "Released", "In Cinemas: October 2013"
---------------end of examples--------------

"90 Minutes in Heaven" and "Rogue One" seem to display what I expect but it seems "The Fifth Estate is showing the cinema release date despite knowing the fact that it has been physically released.

Which services does it use to determine this information?

Also does this release date information effect downloading at all???

Also, what about if the physical release date for Rogue one was announced and advertised (and populated on tmdb etc.) will we show the physical release date, but not indicate "Released" if we haven't hit that date yet?

I'm asking these questions because I did implement some fixes related to this on couchpotato as well as integrate some netflix release info for couchpotato. I am looking for doing the same with radarr but want to understand exactly whats going on here first.

You can look at the  corresponding couchpotato feature here: https://github.com/CouchPotato/CouchPotatoServer/pull/7126

radarr is really great so far. I think it has alot of potential and will usurp couchpotato eventually..

**Comment by onedr0p** [comment]
@geogolem is working on availability filter for movie release dates. Closing this.
