### ISSUE TITLE
More Descriptive Status Banners/Tags

### ISSUE THREAD

**Issue by theebanka** [Radarr/Radarr#554]
I understand a lot of the existing tags for movie availability are coming from sonarr and expect this to land pretty low on the priority list but could we possibly get more descriptive movie status banners across the posters?

Instead of just having Announced, In Cinemas, and Released maybe add something in between like  Awaiting Release for a movie that has been in cinema for 2+ weeks? I realize movies can be in theaters across the world for varying lengths of time but to me personally its a bit bothersome seeing movies being monitored with the "In Cinemas" status for 4 months.

Also maybe have the "availability" that the monitoring system goes off of be based off the BluRay/DVD release date? Currently the only movies in my setup that have the blue "missing but not yet available" tag are those that have been announced but not hit theaters. All others are showing as "missing and available" despite not being anywhere near the release date of these movies.

**Comment by simonk83** [comment]
It seems fairly reliable that movies (or at least 1080p versions, ie the only format that matters :D) start to show up around 2 weeks before the bluray release date.  This has been the case for a fair while now so that's probably not a bad metric to use.   Whenever I want to know when I'm likely to be able to grab a movie, I just check it's release date on bluray.com and subtract 2 weeks or so :D

**Comment by galli-leo** [comment]
@theebanka Your second point is now integrated into Radarr. Not sure if we are going to do the first one.

**Comment by galli-leo** [comment]
Closing this for now. 2. is implemented in Radarr, and first point we are not going to integrate for now, too much of a hassle and current setup works great.
