### ISSUE TITLE
Add upload feature to log files

### ISSUE THREAD

**Issue by Drazzilb08** [Radarr/Radarr#5596]
**Is your feature request related to a problem? Please describe.**
Not really a frustration or problem but more of just a thought to make things simpler. 
Instead of sifting through a log file to figure out what happened the ability to just simply click upload and then Radarr would spit out a link to paste to say Reddit or Discord. 
This could possibly even parse the log files for `Known` errors or issues (key words) and format a paste to be easier to read while containing enough of the actual issue for context for support peoples.

**Describe the solution you'd like**
Add an `Upload` feature to log files to a pastebin site such as [ubuntu paste](https://paste.ubuntu.com) or the classic [Pastebin](pastebin.com)
I feel pastebin would be a great source for this as it has an API that can be utalized
https://pastebin.com/doc_api
This button would be right below or above the current `Download` button
After the paste has been uploaded a new popup could open up with a link to the new paste with a copy button available.

**Describe alternatives you've considered**
None. This is `Just a thought`

**Additional context**
None

[AB#738](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/738)

**Comment by flying-sausages** [comment]
pastebin gets a lot of bad flack and there's some very valid reasons.
FWIW, I'm implementing something similar and I'd highly suggest considering the following requirements:
- Encrypt pastes
- Un-public pastes
- Wash the pastes of anything sensitive like usernames, hostnames, IPs, passwords, api tokens, etc
- Ensure users can delete their own pastes (remember they are likely uploading them from a different IP)
- Make it so that any user knows what to paste where

I've got this written in bash using `privatebincli` which is a node app. You can check here https://github.com/swizzin/swizzin/pull/504

**Comment by Qstick** [comment]
No plans for this right now
