### ISSUE TITLE
PROPER rejected, although "Propers and Repacks" option is set to  "Prefer and Upgrade"

### ISSUE THREAD

**Issue by SugarDroid** [Radarr/Radarr#5637]
**Describe the bug**
If the existing file meets cutoff then the PROPER is rejected even if it's wanted.

**Expected behavior**
Grab the PROPER version and replace the one already exist.

**Platform Information (please complete the following information):**

- Version 3.0.1.4326
- Package Version 3.0.1.4326-ls5 by linuxserver.io
- .NET Core Yes (3.1.10)
- Docker Yes

**Trace Logs**
https://pastebin.com/J6gBM4wR

[AB#2329](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2329)

**Comment by Qstick** [comment]
Logs seem to show two things

1. the release you have is already a proper/repack (the v2 in quality). Is this another proper on top of the original? What is the release you have? Could be an issue with us handling multiple propers but would need more info

`2020-12-26 22:21:46.6|Debug|UpgradeAllowedSpecification|Comparing file quality with report. Existing file is Bluray-480p v2 [x264]`

2. Your profile is set not to upgrade, meaning it would prevent the grab anyway.

`2020-12-26 22:21:46.6|Debug|UpgradeAllowedSpecification|Upgrading is not allowed by the quality profile`

**Comment by SugarDroid** [comment]
> Is this another proper on top of the original? What is the release you have? Could be an issue with us handling multiple propers but would need more info

Yes. The file which already exist is a REPACK from Jul, and this is a PROPER over that from a few days back.

> 1. Your profile is set not to upgrade, meaning it would prevent the grab anyway.
 
The profile's cutoff is set to Bluray-480p which is already met by the existing file -21.Bridges.2019.REPACK.BDRip.x264.-, so i guess this is why it says what it says. Otherwise upgrade is enabled:
![image](https://user-images.githubusercontent.com/56313144/103202693-6a251500-48f3-11eb-87b6-da981b079da8.png)

The exact chronology of the movie:

1. 21.Bridges.2019.BDRip.x264.                (Original)
2. 21.Bridges.2019.REPACK.BDRip.x264.  (This upgraded the original.)
3. 21.Bridges.2019.PROPER.BDRip.x264.  (This is rejected.)

**Comment by Qstick** [comment]
Great thanks! Let me have a look at things to see what we can do.

**Comment by SugarDroid** [comment]
Just tested something now. If I uncheck proper attribute in file's properties then the PROPER becomes available to download. So seems the only thing holds it back is that a proper/repack has been downloaded already. 

I don't think it should be allowed to auto upgrade infinitely, but for sure should be more than 1. Could be a good solution to let it go up to v5 -if that makes sense, and v3-4-5 are not used already for something- when it could stop auto upgrading. That would allow 1 original and 4 auto upgrades, what could be enough for almost everything.

**Comment by austinwbest** [comment]
Disagree with this. If someone sets it to a proper & gets one, that's that. The only other way it upgrades is from a repack from the same group. Grabbing a proper from one group to another doesn't seem logical.

Then why not do the same for everything else? Defeats a cut off if it doesn't stop & leads to more downloading than necessary.

Adding another option for how many times to upgrade a proper is also not something I would think is necessary.

Then again, maybe I am not understanding it all.

**Comment by Qstick** [comment]
@austinwbest Basically your argument is there will never be anything wrong with a proper so we should never upgrade it?

Scene rules do allow for groups to proper a proper, however the example above isn’t correctly named per that standard (should be REAL PROPER which we handle). I agree, we don’t to make this an option, but we should handle the rare case when a proper is properly propered due to issue (which reviewing everything, I think we do)

**Comment by SugarDroid** [comment]
@austinwbest repack is also a proper but it's called repack because it's from the same group which made the original. The proper which is called proper is from a different group.
original-groupA > proper-groupA = repack
original-groupA > proper-groupB = proper

>Grabbing a proper from one group to another doesn't seem logical.

Let's explain things related to this movie -this ofc can apply to whichever release-, and I think you'll see the logic behind it.

Original movie from groupA had only stereo audio, after a while the same groupA made a repack -which is actually a proper against themselves- with 5.1 hybrid audio. But again after a while, now groupB made a proper against groupA -this time called also proper- with the reason: the repack from groupA had watermarked audio.

Which version would you like to keep?

**Comment by austinwbest** [comment]
@Qstick my statement allows for upgrades in the save group, which is already done.

As for crossing groups. that becomes a potentially never ending upgrade cycle, creates support issues with why does it keep upgrading when it has met its cutoff, when is enough enough & who determines that, how does one stop it from doing it as they are fine with what they have & that's off the top of my head

**Comment by Qstick** [comment]
But the definition of a `proper` is crossing groups... same group is a repack as Sugar mentioned.

**Comment by austinwbest** [comment]
If you already have a proper, upgrading to another proper for the sake of it being newer doesn't seem right. Nor does having to disable it to keep from getting multiple for that reason. 

I'm guessing the thought process requires other factors too such as CF's and not just being newer?

Surely I'm just missing something in my head that justifies it

**Comment by bakerboy448** [comment]
Yeah there was a case i saw (Reddit i think) where an upgrade per CFs was rejected due to the proper logic and it refusing to upgrade an existing proper

**Comment by Qstick** [comment]
> Yeah there was a case i saw (Reddit i think) where an upgrade per CFs was rejected due to the proper logic and it refusing to upgrade an existing proper

While somewhat off-topic to this issue, this can be controlled by toggling "Prefer Propers". If Propers are preferred then they are considered higher than CF, if they are not, then they are not..... 

The issue at hand is how and when to handle revision upgrades between REPACKS and PROPERS.

> If you already have a proper, upgrading to another proper (diff group) for the sake of it being newer doesn't seem right

Currently we will upgrade a normal release to either a REPACK (same group) or PROPER (different group) when preferred... at that point we will then further upgrade to REAL if the PROPER is propered by another group (all of this is existing functionality that works, same as in Sonarr). However, we currently treat REPACKS and PROPERS as identical version weight, meaning we won't upgrade a repack to a proper and vise versa... this is what the OP is running into.

If group 1 issues a repack to their own release, but group 2 nukes the repack and issues a proper, we will not grab it. Additionally if group 2 issues a proper for the original release from group 1, but then group 1 comes back with repack of their original release... we won't grab it. 

I'd venture to say these cases happen very rarely, also Radarr doesn't have the knowledge of knowing why each release was released and what release it replaces, all we know is which was published and when. Simply going by release date isn't enough I'd argue due to releases being reposted etc.. It's a guess at that point if we are getting the better release, and near impossible to get right in every scenario

**Comment by bakerboy448** [comment]
For reference this was the Reddit post I was talking about https://www.reddit.com/r/radarr/comments/kkyqus/radar_not_upgrading_to_same_quality_with_better/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by Qstick** [comment]
> For reference this was the Reddit post I was talking about https://www.reddit.com/r/radarr/comments/kkyqus/radar_not_upgrading_to_same_quality_with_better/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

I’ll take a look, thx @bakerboy448

**Comment by bakerboy448** [comment]
@RobinDadswell  did https://github.com/Radarr/Radarr/commit/ce6f52552af15f1184c5eaa816d92dc92d1f232c handle this?

**Comment by bakerboy448** [comment]
Likely partially related to https://github.com/Radarr/Radarr/issues/6595

**Comment by Qstick** [comment]
Is this fixed in 4.4?
