### ISSUE TITLE
Ability to use L_Original tag (Match Original Language) (Need to add a field in the db for that)

### ISSUE THREAD

**Issue by benbar21** [Radarr/Radarr#568]
Hey! 

So currently I have all my profiles set to english. However there are a few foreign, non-english films that I want to download. Radarr doesn't grab them automatically as it is designed to only download films the match the profile language. I think it would be great if Radarr could detect that a movie's language is different from the profile language and then automatically download the foreign release, if no profile-language releases are available. 

So, for example, suppose a film I want is available only in French. 

I add it to my standard 1080p english profile. 

Currently Radarr will not download this film if there are no english releases. 

What I think it should do is detect that the film is a french film (from IMDB or whatever), and then override the profile to allow french downloads.

Thanks!

**Comment by willmonahan** [comment]
I'm also having that problem. Could it be possible to set a preferred language as its own profile, separate from the resolution profiles? Maybe that would be able to help this problem.

**Comment by benbar21** [comment]
@willmonahan you'd still need to make many different profiles that way/it wouldn't be automatic. Hopefully my suggestion is possible since it would be fully automatic!

**Comment by roboticsound** [comment]
I agree that I think language should be separate from profile. I think that language should be an option when adding a movie.

**Comment by emmanuelgee** [comment]
Hi,  I would be great to have an option to search for all films/series in Sonarr/Radarr in original language or profile language.  I think it would be rare for anyone to download anything but the these two options.  I would prefer to have any international item show up first in its original language and then have the option to have it dubbed.  Just me thoughts.  Thanks!

**Comment by silentmiles** [comment]
I'm posting this comment in a few different issues, since there seems to be a lot of overlap. Perhaps these should all be consolidated into a single issue about supporting multiple languages?

Anyway, the core problem here seems to be that the profiles are rigid in requiring the selection of just one language. A lot of people, I think, prefer to always get a movie in it's original language, and use subtitles, so in this case, ANY language is preferred. Others would like to be able to select multiple languages, and even set a priority among them. 

Of course, this logic only works if the movie is tagged with appropriate language tags, but in my experience this is not very common. Non-English movies often do not specify their language. It's been suggested that this is a tracker issue, and that it should be raised with the tracker -- yes, I guess that is right, but with the way trackers are constantly coming and going these days, this is really an impossible solution.

I know that there is a long-term solution being worked on, but couldn't we get an interim solution? I think just NOT requiring a specific language would be at least a partial solution for most people. Surely, just disabling the language matching logic (via a config toggle) would be easy to implement?

**Comment by DahliaDear** [comment]
I have a similar issue, (Sonarr as well) where a movie or show is also dubbed in several languages, but only English gets downloaded when I was trying to get the original version; and often a different language each time. I agree that each individual search should come with an option to find that file with the desired audio, regardless of profile language.

**Comment by alpe12** [comment]
@galli-leo Almost 2020 and no solution added for this? :(
