### ISSUE TITLE
Can't search movies or add movies: Failed to load search results please try again

### ISSUE THREAD

**Issue by deyarmond** [Radarr/Radarr#5727]
**Describe the bug**
As mentioned above, I am unable to search any movies or add any movies. Attempting to do so results in the error message described in title. Viewing the log appears to show an SSL verify issue. Unsure if this is a general bug or user isolated issue. Also unable to fetch update. Behaviour should be captured in the attached log.

**To Reproduce**
Within the UI, try to add a movie or search for movie and download. Error above is the general result.

**Expected behavior**
Movie should be found via TMDB and able to add to download client or library.

**Platform Information (please complete the following information):**
 - OS: [OSMC Debian 10]
 - Docker: [No]
 - Mono or.NET Core Version: [e.g. Mono 6.12.0.90]
 - Radarr Version [3.0.0.4204]
 - Radarr Branch [Develop I think]

**Trace Logs**
Trace Log: https://pastebin.com/pgqVcNn4
Normal Log: https://pastebin.com/R0WRAenM

**Comment by bakerboy448** [comment]
1) that release is old update

2) you're running it on mono still, when[ you should be using .netcore] https://wiki.servarr.com/Radarr_System#update_to_net_core_version)

3) issue is likely mono's certs needing to be synced

2b) upgrade manually to latest since you need to get over to .netcore anyway
