### ISSUE TITLE
IMDB tag not found when naming folder

### ISSUE THREAD

**Issue by Cerothen** [Radarr/Radarr#582]
Renaming Settings and Preview
![image](https://cloud.githubusercontent.com/assets/9008757/22565307/a922ba3e-e955-11e6-88c7-e4e1416051fc.png)

Media Example 1:
![image](https://cloud.githubusercontent.com/assets/9008757/22565335/bd57ab2c-e955-11e6-8189-b778bfd67094.png)
Media Example 2:
![image](https://cloud.githubusercontent.com/assets/9008757/22565348/c75a6ee8-e955-11e6-8bd7-0aaa18b1a821.png)

The imdb code is missing from the media folder naming.

**Comment by galli-leo** [comment]
This is a current limitation of how folders are handeled. Currently, after a movie is added the folder name cannot change. Since we do not have the imdbid until after the movie has been added, that wont work. However, allowing folders to be renamed will hopefully be released over the next few weeks.
