### ISSUE TITLE
Show 'snatched' instead of 'missing' in movie list and movie details page when the movie is being downloaded

### ISSUE THREAD

**Issue by onedr0p** [Radarr/Radarr#588]
Would be neat :)

**Comment by fedoranimus** [comment]
I always hated this term (especially since it was never defined in a UI).

If we do decide to support additional states, this is what I suggest:
* Missing
* In Queue or Downloading
* Downloaded

"Snatched" is not a term descriptive of what is occurring and legacy is not to be respected when it doesn't provide context to define the jargon.

**Comment by edru** [comment]
Basically same thing requested here if you want to merge:

https://github.com/Radarr/Radarr/issues/296

**Comment by geogolem** [comment]
wouldnt it be more accurate to use the term "grabbed" as that is what is being used in the queue/download monitor?

**Comment by joelm3103** [comment]
I believe this is a duplicate of #252 (except instead of _snatched_, label was _downloaded_) as well.

**Comment by onedr0p** [comment]
It is :) closing!
