### ISSUE TITLE
[Request] Option to automatically turn off movie monitoring after downloaded

### ISSUE THREAD

**Issue by zerrikan** [Radarr/Radarr#596]
I've had a few cases where after a movie is downloaded Radarr will randomly go out and download what I assume it thinks is a better version. Turning off monitoring for that movie stops this. It would be nice if there was an option for monitoring to be turned off after the movie is downloaded to avoid Radarr re-downloading the movie.

**Comment by simonk83** [comment]
Hi mate, add that here instead:  http://feathub.com/Radarr/Radarr

:)

**Comment by vertigo235** [comment]
You can turn off download of Propers, and then as long as your cutoff is met, Radarr should not download any new releases to replace your existing one.

**Comment by zerrikan** [comment]
Thanks! I'll make that change in my settings.

**Comment by galli-leo** [comment]
@zerrikan No you have to set your cutoff correctly in your profile. Auto download propers is something else.

**Comment by darknessgp** [comment]
I was looking at this, and noticed that Radarr downloaded a movie that met my cutoff for the profile (cutoff was set to the lowest). But it did not move the movie from being monitored to not being monitored. I understand that maybe it wouldn't have downloaded another copy, but I don't want it monitored at all since I use that to really determine what I have outstanding to get.
