### ISSUE TITLE
API: add movie unmonitored adds movie monitored

### ISSUE THREAD

**Issue by woiza** [Radarr/Radarr#5969]
Adding a new movie via `/movie` and setting `monitored` to `false` in the request body succeeds. However, the movie is monitored.
Is this behavior somehow related to the following Sonarr bug (hard coded)?

https://github.com/Sonarr/Sonarr/issues/1404

Is there a workaround?

**Comment by austinwbest** [comment]
Ok, so just to be safe i went ahead and did some testing with the bot (outside of Radarr directly). Radarr works fine passing in monitored: false and handles it fine.

With that being said there isn't much more that can be done to help you since you provided no logs, no code, no scenario, no usecase, no template, nothing.

Make sure something isn't stripping off the monitored in the request is about all i can suggest for ya.

As this isn't a bug and there isn't anything provided that is requested when opening tickets, i'm gonna go ahead and close this.
