### ISSUE TITLE
Allow alternate release dates

### ISSUE THREAD

**Issue by ghost** [Radarr/Radarr#5996]
**Is your feature request related to a problem? Please describe.**
Some movies might premier in one year and get released another. In such cases, I've seen inconsistencies with torrent naming.
Most torrents will have the Theatrical/Premiere year but some will use the Physical Release Year, hence getting rejected by Radarr for
`Failed to map movie, expected year XXXX, but found YYYY`

**Describe the solution you'd like**
Fallback to any release dates on TMDB, be it physical, theatrical, or premiere

[AB#639](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/639)

**Comment by nloveladyallen** [comment]
This is a problem with a lot of movies that premiere at film festivals in one year and are publicly released a different year. TMDb gives the theatrical release as the main year and Radarr uses that, but scene groups use the premiere date, so Radarr can't find them unless the indexer supports search by IMDb ID.

**Comment by alex-ikse** [comment]
Example : Nightmare Cinema
https://www.themoviedb.org/movie/480100-nightmare-cinema/releases

**Comment by austinwbest** [comment]
Personally, I'm not a fan of this. Fixing it on tmdb would be the solution if it is wrong & if it's the release that are wrong, well that is a never ending challenge.

**Comment by austinwbest** [comment]
I am aware the problem would have existed before hand, likely since day one. Crowd source data makes that par for the course :)

I am still not personally good with the idea. This opens up more searches, more api hits, more possible false matches, more complaints from false matches.

There kind of is a definitive right from radarrs perspective, TMDb as that is what radarr uses. I think from this workflow you mean radarr gives precedence to that release type, not tmdb? Randomly picking one of four or five dates and calling it a match just doesn't seem to be the best solution here.

ta or Q can also weigh in on what they feel, maybe one of them disagree with me and will change it for ya :)

**Comment by Qstick** [comment]
Currently we allow Premier (IMDB) or TMDB year to pass in mapping
