### ISSUE TITLE
Permissions in compiled linux tar.gz

### ISSUE THREAD

**Issue by fryfrog** [Radarr/Radarr#60]
They come out 700 now, should be 644 based on what I see in Sonarr, previous Radarr releases and personal opinion.

Radarr.develop.0.2.0.2.linux.tar.gz
-rwx------ 1 fryfrog fryfrog  47K Jan  8 02:31 Radarr.exe

Radarr_Mono_v0.1-f.zip
-rw-r--r-- 1 fryfrog fryfrog  23K Jan  6 19:08 Radarr.exe

**Comment by AeonLucid** [comment]
I'll check this out, probably forgot something.

**Comment by onedr0p** [comment]
Also, I noticed when using the auto updater a couple things:

first is: `Error occurred while executing task ApplicationUpdate: Startup folder not writable by user 'radarr'`
which I fixed by issuing: `sudo chown -R radarr:radarr /usr/lib/radarr/`

second is: `Error occurred while executing task ApplicationUpdate: Access to the path "/tmp/nzbdrone_backup/config.xml" is denied.`
which is unfixable because sonarr also uses this path.
