### ISSUE TITLE
Double row height caused by long movie title

### ISSUE THREAD

**Issue by evulhotdog** [Radarr/Radarr#612]
When adding moves with very long titles, one movie will cause every single others row height to be twice as big. 

Also when the movie title is long, it should wrap around, and if it doesn't wrap like below, it shouldn't cause every other row to be twice the height. 

Might be the Bluray-1080 that is causing the double height.

![image](https://cloud.githubusercontent.com/assets/365456/22630045/336a2602-ebc0-11e6-9c48-042b8292acc7.png)

**Comment by Wesleyl89** [comment]
Same here with 'Pirates of the Caribbean: Dead Men Tell No Tales'. If I delete the row via element inspector it goes back to singlerow. 

Not a big issue, but it makes the tableview look rather "unorganized" (which is the main reason I use the table view)

**Comment by fedoranimus** [comment]
This is an unavoidable issue because of several reasons:

- I made the Movie column smaller, this helps a bit.
- Depending on screen width, the columns will resize; this causes columns with more content to spill onto 2 lines
- Column widths are not user-controllable
- Column sets are not user-controllable

These are all issues that can be addressed in a later version of the UI, but I am closing this issue.
