### ISSUE TITLE
`<movie-search available="no"/>` in caps ignored when searching

### ISSUE THREAD

**Issue by animetosho** [Radarr/Radarr#6123]
I'm just going off my interpretation of the code here, and I'm not familiar with the code base, so apologies if I'm completely wrong.

Looking at [this](https://github.com/Radarr/Radarr/blob/2161f081404ab1eedb9a7d428ea2b08573310640/src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs#L135-L152), it seems like there's a check for `<search available="yes" supportedParams="q"/>`, then it sends a movie search.

My understanding is that it *should* be more like [this](https://github.com/Radarr/Radarr/blob/2161f081404ab1eedb9a7d428ea2b08573310640/src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs#L75-L82) and check for *movie-search* availability before doing a movie search, then falling back to a regular search.

Does this sound right?

**Comment by Qstick** [comment]
You are correct, that logic was checking for `search` available but then doing a `movie-search`. In an ideal world we would try both as you mention, however there are many indexers that fail miserably on a movie `q` search due to issues with sphinx full text searching. Thus I've fixed this to do a `search` in this case given that is what we are checking for.

**Comment by animetosho** [comment]
Awesome, thanks!
