### ISSUE TITLE
Ignore 'download root folder' warning

### ISSUE THREAD

**Issue by viggy96** [Radarr/Radarr#6137]
**Is your feature request related to a problem? Please describe.**
Radarr is complaining about qBittorrent downloading to a "root directory", /downloads. However, qBittorrent is a container. And that location in the container is mapped to a different location on the host. Radarr has no concept of this. Therefore its warning is invalid. 

**Describe the solution you'd like**
- Allow for warnings to be ignored and never shown again. 
- Eliminate this warning completely

**Comment by bakerboy448** [comment]
@RobinDadswell docker case that needs handling in the new logic?  Is it possible has a docker download client and native radarr and we're not factoring in a remote path mount?

@ OP

> Allow for warnings to be ignored and never shown again. 

Is covered by https://github.com/Radarr/Radarr/issues/5393

> Eliminate this warning completely

no plans the whole point of the new warning is to yell at users who download into their root folder which always causes problems eventually.  It appears you've found a case with the new detection logic that isn't being handled great

(Side note if your using docker and have /downloads you're dockering wrong...see the docker guide in the wiki or trash's guide;  otherwise if only the download client is in docker then you'd need a remote path map to translate docker to non docker)

**Comment by ta264** [comment]
The paths coming from qbittorent already have a remote path mapping applied.  My best guess is that the error is correct and you have the root folder `/downloads` added to radarr and don't realise.  It would be great if you could come by the discord so we can work out exactly what (if anything) is going wrong.  https://radarr.video/discord

**Comment by viggy96** [comment]
Issue solved via Discord. Thanks @ta264.
