### ISSUE TITLE
Movie marked missing after download completition 

### ISSUE THREAD

**Issue by gabri94** [Radarr/Radarr#6184]
Several times i add movies to radarr, then i send the release to rutorrent (or deluge) and when the release is download radarr get stucks.
I cannot manually import the release trough activity, the only solution is to manually move the file from the download directory to the directory where radarr expect to save the file after the download, then manual import it.

Why does it happens? Is there a manual way to force the movie import besides the activity tab that often doesn't works?

**Screenshots**
![immagine](https://user-images.githubusercontent.com/2878661/114539946-48a72980-9c55-11eb-8b31-390d94b571e1.png)

![immagine](https://user-images.githubusercontent.com/2878661/114540066-65dbf800-9c55-11eb-9612-fa4b1a1e604c.png)

![immagine](https://user-images.githubusercontent.com/2878661/114540130-78563180-9c55-11eb-9468-85610d45ad8b.png)

**Platform Information (please complete the following information):**
 Version:     3.0.2.4488
Package Version:    3.0.2.4488-ls10 by linuxserver.io 
.NET:    Yes (5.0.2)
Docker:    Yes
DB Migration:     188
AppData directory:    /config
Startup directory:    /app/radarr/bin
Mode:    Console

**Trace Logs**
[radarr.txt](https://github.com/Radarr/Radarr/files/6303092/radarr.txt)

**Comment by gabri94** [comment]
Here is the trace:
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/6303164/radarr.trace.txt)

**Comment by gabri94** [comment]
I do not really see how this is not a bug. 
- I add a movie to radarr
- I manually grab it and send it to rutorrent
- The movie is completed and radarr gets stuck, not giving me any possibility of manually importing the file.

Radarr knows that torrent and that filename because i grabbed it and it's literally written in the history, so why it can't associate the movie and the file and import it?
Why it doesn't gives me a manual way to do it?

**Comment by bakerboy448** [comment]
The trace file you provided is not a trace file.

The log file you provided initially is not a log file.

This is not a bug because you've provided no information to indicate it is a bug nor are we aware of any issues (and this would more than likely be known) it is more than likely a user configuration issue.  Again, please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

>Radarr knows that torrent and that filename because i grabbed it and it's literally written in the history, so why it can't associate the movie and the file and import it?

The searching parser and the importing/downloading parser are two seperate black boxes.


Importing from the activity tab 100% works, if you're having issues with it they are caused by you or your setup, not by radarr.

>The movie is completed and radarr gets stuck, not giving me any possibility of manually importing the file.

This comes from a material lack of understanding of Radarr's functionality.

Movie Index  -> Manual Import  = import from anywhere
Movie Index -> Movie -> Manual Import = import from within the movies specific folder
Activity -> Release requiring human intervention -> Manual Import = manual import for releases unable to be imported yet are complete in clients queue (may also require enabling options -> show unknown)

For further discussion and assistance, swing by reddit or discord.
