### ISSUE TITLE
Custom script variable HealthCheck Wiki returns wrong link

### ISSUE THREAD

**Issue by NiNiyas** [Radarr/Radarr#6216]
**Describe the bug**
When calling `radarr_health_issue_wiki` from a custom script, it returns wrong wiki link from Servarr Wiki for `IndexerRssCheck` and `IndexerSearchCheck`.

**To Reproduce**
Create a custom script and call `radarr_health_issue_wiki`.

**Expected behavior**
It should return the right link.

**Platform Information:**
 - OS: Windows 10 20H2 build 19042.906
 - Docker:No
 - Mono or .NET Version: 5.0.5
 - Radarr Version: 3.1.0.4893
 - Radarr Branch: develop

**Comment by bakerboy448** [comment]
> Radarr Version: 3.1.0.4893
> Radarr Branch: master

well that's just not possible, but i digress.

What link is it returning for both?

Not sure if this will be a wiki update or a code update yet

**Comment by ta264** [comment]
> When calling `radarr_health_issue_wiki` from a custom script

I have no idea what this means...

**Comment by NiNiyas** [comment]
> > Radarr Version: 3.1.0.4893
> > Radarr Branch: master
> 
> well that's just not possible unless you just switched to master and are waiting for 3.1 to hit, but i digress.
> 
> What link is it returning for both?
> 
> Not sure if this will be a wiki update or a code update yet

For `IndexerRssCheck ` it returns `https://wiki.servarr.com/Radarr_System#no_indexers_available_with_rss_sync_enabled_radarr_will_not_grab_new_releases_automatically` and for `IndexerSearchCheck` it returns `https://wiki.servarr.com/Radarr_System#no_indexers_available_with_automatic_search_enabled_radarr_will_not_provide_any_automatic_search_results`

**Comment by bakerboy448** [comment]
Ta, I think we'll need a code change here.  Looking at it...why are we localizing the string?  is the localized string what gets fed in to the link generator, if so that's a problem...we're not making a link for each and every translation..

https://github.com/Radarr/Radarr/blob/627ab64fd023269c8bedece61e529329600a3419/src/NzbDrone.Core/HealthCheck/Checks/IndexerRssCheck.cs

https://github.com/Radarr/Radarr/blob/627ab64fd023269c8bedece61e529329600a3419/src/NzbDrone.Core/HealthCheck/Checks/IndexerSearchCheck.cs

(also interesting no one has stumbled across this since it was implemented?)
