### ISSUE TITLE
Broken: Health Check for Downloads to Root Folder [common]

### ISSUE THREAD

**Issue by sienar1** [Radarr/Radarr#6291]
**Describe the bug**

this new health check feature is telling me my download clients download folder is a root folder when it is not. It is a mount point inside my LXC container that runs SABNZBD. 

**To Reproduce**
have a mount point inside an LXC container be your download client folder

**Expected behavior**
Not give false errors

**Platform Information (please complete the following information):**
 - OS: Proxmox/Ubuntu container
 - Docker: no
 - Mono or .NET Version (System -> Status): .net
 - Radarr Version: 3.2.0.4997
 - Radarr Branch: nightly

**Comment by sienar1** [comment]
Can I suggest that radarr do a check on manual import and if it’s a download clients download folder, don’t add it as a media root folder?

**Comment by RobinDadswell** [comment]
It sounds like you are using the wrong import location to grab from that folder. Instead of using library import use "manual import" as per this following screenshot. 

![image](https://user-images.githubusercontent.com/19610103/117575060-195ecd80-b0d8-11eb-80d5-c914c17ae30d.jpeg)

If you want more help on this please go to Reddit or discord.

**Comment by sienar1** [comment]
That’s exactly how I do manual imports.

**Comment by sienar1** [comment]
I don’t need help, I’m reporting bugs. I’m reporting Radarr doing things it shouldn’t be doing.

Maybe it’s not the bug I thought it was, but this health check is interacting with another bug that’s errantly adding paths as media root folders.

**Comment by ta264** [comment]
If you believe that's what's happening please provide logs of the erroneous root folder being added. So far it sounds like you have radarr misconfigured in exactly the way this check is aiming to detect.

If you want to convince us there is a bug around this then please join us in the discord channel to discuss.

**Comment by bakerboy448** [comment]
Please use our discord to troubleshoot further.

Again, it's been stated when and how root folders are added. That's the only way they can be added.

I'd also suggest bringing trace logs of you doing a manual import that show radarr adding that folder as a root folder as well.

this is much more likely to be user error than a bug as you claim.

**Comment by Qstick** [comment]
> In fact, I’ve only ever configured 3 root folders yet I have about a dozen media root folders in the configuration now and all are locations where I’ve done manual imports.

And do they get re-added from a manual import after you remove them? Have you tested a manual import on a new location since this discussion to see how it behaved? If you can reproduce this, then logs would certainly be helpful as currently we can’t.

> 
> I would never add my download path as a media root folder, it’s moronic. It’s also moronic for Radarr to do that on its own too. So maybe a sane thing to do is fix/enhance Radarr so that it doesn’t automatically add the download clients download path as a media root folder. Ever. For any reason. Make it only addable by manual user configuration.

We understand you wouldn’t purposely do this, that doesn’t mean it wasn’t done... or that it wasn’t from a past bug.. The behavior you describe is essentially the behavior now, a root folder doesn’t get added without the user specifically asking for it. We’d be more than happy to investigate it further (and fix if needed) if you can find a reproducible method in which this happens.

> 
> Sorry this is coming off as offensive, but that’s the nature of a design bug versus a code bug. I know this makes me the person calling someone’s kid ugly, but that doesn’t make me wrong.

No one is offended, and trust me the kid has many ugly features. What makes you wrong is not you reporting the bug, but you not being able to produce evidence it is one. No logs, no reproducible steps, etc.. We’d  welcome further discussion on discord (or here if that’s where you are comfortable), but we need more help from you before we can say something is wrong and then go about fixing it

**Comment by thelittlemike** [comment]
Just wanted to chime in saying I have this exact same issue as sienar1. I'm running Radarr 3.2.0.4994 in a docker container within unRAID. In NZBGet, I have the following mappings:

/downloads <-> /mnt/user/downloads/nzbget (in order to distinguish between other download clients)
/config <-> /mnt/user/appdata/nzbget (the normal default config folder)

in Radarr I have:

/downloads <-> /mnt/user/downloads/nzbget (matches host path with NZBGet)
/movies <-> /mnt/user/movies (where Sonarr should move movies to)
/config <-> /mnt/user/appdata/radarr (the normal default config folder)

Today I noticed a warning, "Download client NZBGet places downloads in the root folder /downloads/completed. You should not download to a root folder."

I have not changed any settings on these containers since I moved over to the :nightly tag months ago when I wanted to move over to the 3.x builds.

I noticed that it shows up as a root folder, though I couldn't tell you how it got there. I also noticed that /movies shows as a root folder as well. I also don't know how that got there either.

Prior to changing the tag to nightly, I had not touched this container in literally 3 years. It's always just worked, so I had no reason to muck about with it. Let me know if there's anything I can do to help.

I tried clicking the x on the right under the Root Folders section to remove the download folder. It disappeared, yet the "1" warning under the System header is still there.

**Comment by bakerboy448** [comment]
@thelittlemike again, not a bug.  Someone or something added your download folder as a root folder in Radarr. The error is accurate: you have your downloads folder set as a root folder in radarr.  Root folders are never automatically added and were added by you at one point.

Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

PS  your paths are suboptimal 
https://trash-guides.info/Hardlinks/Hardlinks-and-Instant-Moves/

**Comment by thelittlemike** [comment]
> @thelittlemike again, not a bug. Someone or something added your download folder as a root folder in Radarr. The error is accurate: you have your downloads folder set as a root folder in radarr. Root folders are never automatically added and were added by you at one point.
> 
> once corrected you probably need to re-run the Healthcheck in system -> tasks
> 
> Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://radarr.video/discord) for support/questions.
> 
> PS your paths are suboptimal
> https://trash-guides.info/Hardlinks/Hardlinks-and-Instant-Moves/

I only recently noticed they were even there, so maybe it was added by a previous bug? Like I said, I haven't touched the config in literal years, so apologies, but I can't offer any insight into how they got there. Is it possible I added it years ago? Sure. I have no recollection of doing so, but I won't tell you I didn't. I only just noticed it because of the warning. So in that regard, yes, the health check is accurate. Just not sure how that path got there in the first place. Is the health check new? This is the first time I'm seeing that warning.

I ran the health check as you suggested and the error went away, so thank you.

I set up my paths exactly as instructed by the unRAID container maintainer. I'll go through that link, though.

For reference, one of the unRAID devs suggests the setup here:

https://forums.unraid.net/topic/57181-docker-faq/?tab=comments#comment-566086

The example says Sonarr, but the same dev maintains Radarr and recommends the same setup for both.
