### ISSUE TITLE
Chinese/Jap Characters on some movies

### ISSUE THREAD

**Issue by jscottdouglas** [Radarr/Radarr#651]
added movies to my wanted list from couchpotato as a list and allowing radarr to create empty dir, looks like for some movies where they are asia originating it is not giving the localized name, example Ghost In the Shell the new movie is giving me 攻殻機動隊 新劇場版

![image](https://cloud.githubusercontent.com/assets/15646181/22718721/deb3e4b6-ed6f-11e6-9aa4-cf2c86e3af6f.png)
![image](https://cloud.githubusercontent.com/assets/15646181/22718753/1158857a-ed70-11e6-84b2-3677b7af69be.png)

Can this be fixed to use the localized name for creating the folders... 

On debian sid latest radarr

**Comment by galli-leo** [comment]
This will have to wait until folder renaming is in, because we do not get the localised name until after we created the folder.

**Comment by geogolem** [comment]
@galli-leo : will this be fixed when the folder renaming is in? I'm just double chekcing because the issue is closed and I and others also ran into this issue:

![image](https://cloud.githubusercontent.com/assets/23205277/22847255/d89ecc84-efb9-11e6-9e61-5b499d7c92cf.png)
![image](https://cloud.githubusercontent.com/assets/23205277/22847269/ecfa960e-efb9-11e6-8870-bc0716cdf796.png)

**Comment by geogolem** [comment]
In my opinion the default folder name should be the same as the folder name radarr uses...   Im just leaving these comments here for reference -- I understand this will likely have to wait until folder renaming is implemented.

**Comment by galli-leo** [comment]
It should be fixed by then
