### ISSUE TITLE
Syno Package:  Radarr in app update kills package

### ISSUE THREAD

**Issue by madvtak** [Radarr/Radarr#654]
Hi all,

Anyone experiencing this issue? There was a new update tonight so i updated, within the app. After the updated downloaded completed, i was presented with the app has been updated click here to reload the page. I reload the page and it never loads. I check the package.

![image](https://cloud.githubusercontent.com/assets/18261123/22724318/2d6aa81a-ed7a-11e6-96d2-c89de4cab960.png)

I try to run the package, it says its starting but it never runs. 

![image](https://cloud.githubusercontent.com/assets/18261123/22724366/6d20b3a0-ed7a-11e6-8b4a-13e484e972e7.png)

I try to refresh the page a min or two later just in case it actually did start.

![image](https://cloud.githubusercontent.com/assets/18261123/22724377/8019b6f0-ed7a-11e6-87e4-c663765aec36.png)

The only way to fix this is to uninstall and start over from scratch again.

**Comment by madvtak** [comment]
`admin:/var/packages/radarr/scripts$ ./start-stop-status start

Starting Radarr ...
admin@:/var/packages/radarr/scripts$`

I try to start from SSH and this is what i am presented with.

**Comment by onedr0p** [comment]
Any chance you can get ahold of developer of the package for help? The in-app auto update works fine. Maybe you have to wait for him to release an update like docker?

**Comment by madvtak** [comment]
I still have the docker one running, I wanted to see if the Syno Pacakge one will fix my permission issues.

**Comment by madvtak** [comment]
In case someone wants to see the logs, not a lot of info /shrug

![image](https://cloud.githubusercontent.com/assets/18261123/22724561/e79fd33a-ed7b-11e6-9d7a-8af62ffca2b2.png)

**Comment by onedr0p** [comment]
You definitely need to get ahold of ressu for questions.

**Comment by newkind** [comment]
Got the same issue.

**Comment by ressu** [comment]
This is most likely caused by an underlying bug in the DSM6. You can verify whether this is the bug in question by running `grep radarr /etc/shadow` as root:

```
ressu@BWNAS01:~$ sudo grep radarr /etc/shadow
radarr:*:17187:0:99999:7:::
```

If there is no output the issue is in DSM. You can manually work around the issue by adding the line above to the end of `/etc/shadow`. Please be careful while doing it though, this is the file that contains all your passwords, it's possible to lock yourself out from your NAS here.

**Comment by schumi2004** [comment]
Mostly a reboot would resolve it also but since it already ran the first time with same package i doubt this shadow file thing is the issue.

Check if it's not running multiple times 
root@DS715:~# ps aux | grep radarr
root      6254  0.0  0.0   4800  1728 pts/8    S+   14:40   0:00 grep --color=auto radarr
radarr   12717  0.9  4.7 210656 99712 ?        SNl  01:21   7:22 /usr/local/mono/bin/mono --debug /volume1/@appstore/radarr/share/Radarr/Radarr.exe /nobrowser
root@DS715:~#

and as last resort remove your config files and start over configuring. (that should definitely fix it)
remove files here /volume1/@appstore/radarr/var/.config/Radarr
Haven't tested if importing backup works but i think it should.
