### ISSUE TITLE
[FEAT]: Send Tags to Download clients instead of a single "Category" 

### ISSUE THREAD

**Issue by markraub** [Radarr/Radarr#6565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

NZBGET can execute custom post-download commands based on different categories handed to it by software like radarr/sonarr. Radarr can currently only send a single "category" string to download clients, making it hard to breakout movies by genre 

### Describe the solution you'd like

I'd like to have the existing "tags" system replace the "categories" data that is sent with each download to the destination client. That way, in software like nzbget, you can manage files based on genre, or other tags, after they have finished downloading. 

### Describe alternatives you've considered

I've considered using nzbget postinstall scripts, but I couldn't find anything that could leverage genre information, or tags in radarr. 

### Anything else?

.

[AB#1499](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1499)

**Comment by bakerboy448** [comment]
Closing
- Not possible due to download client limitations, see below.  
- Multiple categories cannot be sent and given a movie can have multiple tags that would not work. Which if there are 10 tags on a movie, which tag should be used as the category? (hypothetical)
- This seems like an X-Y problem.  What possible nzbget post-processing scripts would be required to be ran on a per-genre basis?  It sounds perhaps you are having NZBget sort your download and not radarr which frequently causes problems.
- What post-download script would be required to run in nzbget on a per-tag basis?
- I would say use a custom script triggered by radarr on download / on upgrade, but a movie's tag is not a property of those release/file events. https://wiki.servarr.com/radarr/custom-scripts
- Tags are properties of the movie, not the release.  This would require some decent rejiggering at face value.

[Per NZBGet's API document this is not possible to send tags (i.e. alt category) nor multiple categories.](https://nzbget.net/api/append)
![image](https://user-images.githubusercontent.com/55419169/130728938-1b287b79-4207-4875-b504-e5bce7212cde.png)
