### ISSUE TITLE
Intermediate Download path inside drone factory, Skipping.

### ISSUE THREAD

**Issue by rickytin** [Radarr/Radarr#671]
Radarr downloaded 2 movies but it did not move to my movie folder because "Intermediate Download path inside drone factory, Skipping." What it mean this problem.
Also I try to do a manual import and it stay thinking with the moving ball and it docent let me do anything.

**Comment by zductiv** [comment]
You don't need to use the drone folder in order to have movie files moved after download. The drone factory folder should not be set to same path as your download location in your download client. It should be a totally separate folder if you want to use it that you can drop files in that are not downloaded through radarr to have radarr import them. Or just turn it off completely and use the manual import option for stuff that is downloaded outside of radarr.
