### ISSUE TITLE
Add Tag to radarr custom script api

### ISSUE THREAD

**Issue by andrew-kennedy** [Radarr/Radarr#6769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I want to be able to write a radarr custom script to do certain things based on the tags present on a movie. Currently the api does not seem to expose the tags set on a movie.

### Describe the solution you'd like

Expose the tags as radarr_movie_tags in the api.

### Describe alternatives you've considered

There is currently no way to access tag data and expose it outside of radarr to be able to act on it.

### Anything else?

Nothing else.

[AB#1998](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1998)

**Comment by bakerboy448** [comment]
The entire UI is lipstick on the API and the API has tags available for movies - see the API docs.

The Custom Script connection has nothing to do with the API.

are you saying you want the movie's tag(s) added as a a variable within a custom script? if so that's a rather different request.

note: you can accomplish what you want easily given connections support tags, so I'm not sure if adding this to duplicate existing functionality is something in the cards - depends on the effort which I'll defer to the others.

**Comment by andrew-kennedy** [comment]
I'm currently trying to write a script that can delete movies with certain tags periodically, and even add tags to certain movies based on watched user characteristics from tautulli or plex. You're saying this is currently possible?

**Comment by ta264** [comment]
Sure, you just have to make the right api queries

**Comment by bakerboy448** [comment]
API docs
https://radarr.video/docs/api/

Closing for now - doesn't sound like any action is needed at this point, can reopen as/if needed.   Swing by discord for api questions
