### ISSUE TITLE
Indexers using the unsupported Jackett 'all' endpoint: Jackett

### ISSUE THREAD

**Issue by StephenTPD** [Radarr/Radarr#6899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Indexers using the unsupported Jackett 'all' endpoint: Jackett

![Capture](https://user-images.githubusercontent.com/97120187/148100003-c5140028-6151-4a9c-b625-f8dff3aabf57.PNG)

### Expected Behavior

for /all to be excepted as an indexer option.

### Environment

```markdown
- OS: Windows 10 21H2
- Radarr:4.0.0.5745
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Firefox 95.0.2 (64-bit)
```

### What branch are you running?

Develop

### Trace Logs?

[radarr.txt](https://github.com/Radarr/Radarr/files/7809361/radarr.txt)

[AB#2310](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2310)

**Comment by bakerboy448** [comment]
This is not a bug.  Jackett's `/all` endpoint should not be used given the absence of benefits and downsides.

You're receiving a warning - which can be force saved and bypassed.

[Covered on the FAQ](https://wiki.servarr.com/radarr/faq#jacketts-all-endpoint)

And simply following [Jackett's own recommendation](https://github.com/Jackett/Jackett#aggregate-indexers)

**Comment by nydave69** [comment]
> absence of benefits

It keeps me from having to configure 25+ indexers
and reconfigure every time they go down and come back with a different url..//

**Comment by bakerboy448** [comment]
> > absence of benefits
> 
> 
> 
> It keeps me from having to configure 25+ indexers
> 
> and reconfigure every time they go down and come back with a different url..//
> 
> 
> 
>  

25 trackers is more than likely causing you more harm than good given public trackers all scrape each other.

You'd never need to update your indexer in \*arr if an indexer changes it's URL. Pretty sure jacket's torznab endpoint doesn't change for an tracker. Same for if a tracker is removed from jakcett and later brought back, dont think their torznab url changes there either since the id is still the same.

If you're adding and removing trackers that often then the issue is with your process and neither Jackett nor Radarr.

You're also likely never seeing all the results for all 25 trackers due to the issues noted with /all.

This will not be added back nor changed. There are no benefits to /all other than reduced management overhead which is negated by Prowlarr and Hydra's ability to sync to \*Arrs.


Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for further support/questions.

**Comment by nydave69** [comment]
Jacket lists all known url's for an indexer and gives the option to select one if the one your using stopped working.

> negated by Prowlarr and Hydra's ability to sync to *Arrs.

not sure what those are...

**Comment by bakerboy448** [comment]
> Jacket lists all known url's for an indexer and gives the option to select one if the one your using stopped working.
> 
> 
> 
> > negated by Prowlarr and Hydra's ability to sync to *Arrs.
> 
> 
> 
> not sure what those are...
> 
> 

Changing Jackett's selected URL has no impact on the tracker's torznab endpoint created by Jackett that Radarr uses.  So your reason doesn't really make sense as that scenario does not exist. 


https://github.com/Prowlarr/Prowlarr 

https://github.com/theotherp/nzbhydra2


As said previously - please use Reddit or discord for these further support discussions.
