### ISSUE TITLE
Unable to add Mapped Drive in Windows

### ISSUE THREAD

**Issue by rjwaters147** [Radarr/Radarr#698]
I have my main computer on the same network running plex with a 7TB Storage Space, in Radarr I am unable to set this as main Movie folder like I did for television in Sonarr.

In sonarr typing (with the * changed correctly)
  \ \ (*network-pc) \ (*StorageSpace)\Television
will allow me to add all my TV shows, doing the same in Radarr yields no results.

[-Here](http://imgur.com/MpXF0z9) is what happens in Sonarr and would be the expected Radarr behaviour aswell.

[-Here](http://imgur.com/DyxAXAW) is what actually happens when trying in Radarr currently.

I simply get a "Path does not exist" when I know it exists and its mapped and working in Sonarr, weird how I can't get Radarr to see it.

I've had Radarr working great till now, then I move my main Storage Space to my Plex computer and this happens... I guess I'll have to be moving the Storage Space back to this PC unfortunately.

**Comment by geogolem** [comment]
This is different but unrelated -- though I just thought I would chime in with my issue here because it could be related and/or help:.. I also have a network drive... though I have it mapped to a letter drive, so I simply access this drive as z:\

![image](https://cloud.githubusercontent.com/assets/23205277/22848840/5edebf4c-efc5-11e6-90c2-ec36a8d52394.png)

interestingly enough, in radarr this works fine. I can access the drive using its letter z:\ and my movie files will be detected and picked up etc. The only issue is on the "System Page"

In Sonarr it the Z:\ drive shows up fine, but in radarr it doesn;t.
Sonarr: 
![image](https://cloud.githubusercontent.com/assets/23205277/22848884/a24728aa-efc5-11e6-8b14-c70c6e60f056.png)

Radarr:
![image](https://cloud.githubusercontent.com/assets/23205277/22848893/b1d8f104-efc5-11e6-99ed-3167e6a6760c.png)

not sure why it doesnt show up there -- it doesnt effect me because everything seems to work with z:\ in radarr -- its just not showing up in the system page.

**Comment by danpowell88** [comment]
Im using the \\server\share syntax fine.

One thing to check if the account that is running the radarr service, if it is not the same account that mapped the network drive it will not have access to it, ie. running as local service or administrator instead of your actual account

**Comment by notapantso** [comment]
I have the same issue as **geogolem**, where my Samba shares don't show up in Radarr's system page.
I am however able to specify a NAS location as the save path of an added movie;  what happens after a movie has been downloaded is that it is not transferred to that path but stays in the temp/unrar localhost folder.  I am also able to successfully scan the NAS share for existing films.  I have checked security permissions for all folders and binaries, and run Radarr both as an exe and as a service.
Again, Sonarr runs fine.

The syntax I use to add a path in the 'Add Movie' dialogue is \\nas_name\share_name\location.

Win 7 64b
Radarr 0.2.0.299

**Comment by rjwaters147** [comment]
danpowell88, you were correct NZBDrone service was running under my PC's username and Radarr's service was running under Local System, changed it to my account but I will now have to swap my Storage Space back from this PC to my Plex PC, but at least you helped me fix the issue.

**Comment by geogolem** [comment]
@rjwaters147 : does this also account for my and @notapantso 's issue with it not showing up in the system page (though for me radarr has no issues downloading and movies files over there)
