### ISSUE TITLE
Can’t sort RSS feed by posting date

### ISSUE THREAD

**Issue by dblviking** [Radarr/Radarr#7012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I have a nzbgeek RSS feed. The current Radar sorting list item is not useful to me. I just want to see the movie list in the exact order  of the RSS feed, not cinema/bluray release date etc. 

If I want to see today’s posts, it’s not possible. 

### Describe the solution you'd like

A sort list item that preserves the RSS feed posting date. 

### Describe alternatives you've considered

Only a sort by rss posting date 

### Anything else?

Nope

[AB#2536](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2536)

**Comment by bakerboy448** [comment]
There's no way to view an RSS Feed in Radarr, so I'm not sure what you're asking?

If you're talking about an interactive search - that is not an RSS Feed, that is a search.  Which can be sorted by age for an Interactive Search (Search Tab on the movie page) and does what you request.

**Comment by dblviking** [comment]
Oh I’m confused then. I usually go to Discover and then filter and then choose my geek list. All the postings are listed there but sorted by Status by default. I’m not sure what that means though.

**Comment by bakerboy448** [comment]
So you use NZB's list of new movie uploads as a List in Radarr.

That's a rather highly unusual use case and doesn't really make too much sense given the purpose of lists.

Are you basically just trying to add everything that is ever uploaded?

**Comment by 6twenty** [comment]
@bakerboy448 for what it's worth lists aren't just used for automatically adding movies to be downloaded. They're also for finding/discovering movies you might wish to add. (Hence the name of the page in Radarr is "Discover".) I can see a valid case for wanting to order the results on this page by the order that they appear naturally in the list source. However I can also see that being a difficult job because the Discover page bundles multiple lists together, so reconciling the order from multiple lists might prove problematic.
