### ISSUE TITLE
Library Import - Display existing/detected File Quality

### ISSUE THREAD

**Issue by bakerboy448** [Radarr/Radarr#7158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Splitting off from #7157 for @YouveGotMeowxy

> 4\. In the screenshot I highlighted at the middle-top where the above column, and this column could go. One of the columns would be the current file's resolution (let's say it's currently an SD movie), THEN we'd easily be able to see whether or not we want to choose "yes or now" in the Monitor field. Currently there's no way to tell whether or not we want to upgrade (sometimes we don't) w/out referring to the actual folder itself (my server is remote, and I have to RDP into it, which for things like this can be a PITA).

### Describe the solution you'd like

For Library Import - display existing file quality

### Describe alternatives you've considered

N/A

### Anything else?

On Hold due to mutli-edition support needing to be figured out as part of this

[AB#2846](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2846)

**Comment by bakerboy448** [comment]
Relies on / Related to https://github.com/Radarr/Radarr/issues/1910

**Comment by austinwbest** [comment]
The current logic is just parsing a folder to find a movie match so it can be added to Radarr. I dont think it even looks in the folder for a file so that would have to be added and then another drop down to make it so it can be changed which might cause other issues with how the file is handled after the folder/movie is added..  This also means a request to see the actual file name will be next i'm sure. Might end up being a rabbit hole on this one

**Comment by Qstick** [comment]
This was previously in Radarr v0.2 and we stripped it out during our simplification. No plans on it coming back
