### ISSUE TITLE
Convert Restrictions to Release Profiles

### ISSUE THREAD

**Issue by Qstick** [Radarr/Radarr#7163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Convert the current state of `Restrictions` to become Release Profiles. For Radarr restrictions is still hidden under indexers, unlike Lidarr, Readarr, Sonarr. This proposal is to move restrictions to become `Release Profiles` however without preferred words given we have custom formats. 

- Migrate Restrictions to Release Profiles
- Allow use by Indexer (Like Sonarr)
- Allow use by Tags
- Leave Custom Formats in place (Don't add Preferred Words) - (Aligns with Sonarr v4 and future plans)

This is mainly to align UI with the other apps and allow users to more easily find "Must Contain" and "Must Not Contain"

Current State
![image](https://user-images.githubusercontent.com/376117/160300179-cef02d01-ed02-42cd-9bca-685347b585a1.png)

Future
![image](https://user-images.githubusercontent.com/376117/160300194-4a79c0b0-8a5d-4fcb-93c0-a5edca281e1d.png)
![image](https://user-images.githubusercontent.com/376117/160300259-73e3eb2f-997d-4585-90c5-71846bb24a1d.png)

[AB#2855](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2855)

**Comment by ricci2511** [comment]
I took care of this and it seems to work as expected, will do a PR soon.

**Comment by Qstick** [comment]
Nice work, was waiting for v5, but we may be able to get away with sliding this in. It's got some API impacts as well as some usability impacts.

Thoughts?

**Comment by ricci2511** [comment]
> Nice work, was waiting for v5, but we may be able to get away with sliding this in. It's got some API impacts as well as some usability impacts.
> 
> Thoughts?

Thanks. I think the usability impacts bring some improvements to the overall user experience since now it will be consistent with all other "*Arrs", and it brings some additional features like allowing the use by tags and indexers which were not present for Restrictions. 

In the API side of things [Restriction](https://radarr.video/docs/api/#/Restriction) is completely replaced in favour of something like Sonarr's [ReleaseProfile](https://sonarr.tv/docs/api/#/ReleaseProfile).

The request body for the new `releaseprofile` route in POST and PUT methods looks like this:

```
{
    "enabled": true,
    "required": [ "string" ] or "string", // Accepts JSON array or comma-separated string values for backwards compatibility?
    "ignored": [ "string" ] or "string",
    "indexerId": 0,
    "tags": [ 0 ],
    "id": 0
}
```

The only thing that differs in the response body for pretty much all HTTP methods is that both "ignored" and "required" properties are now always returned as JSON arrays, which makes the handling of "ignored" and "required" easier in the server code since we just work with `List<string>` instead of handling comma-separated string values.

For some info on the migration see the linked PR.
