### ISSUE TITLE
postgres - same database, different users for main and log

### ISSUE THREAD

**Issue by volker-raschek** [Radarr/Radarr#7267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

To start radarr with postgres, two separate databases are needed. In the documentation these are called main and log. 

It is not possible, or at least not documented, how to configure radarr so that one and the same database is used for main and log and they only differ in schemas/users.

### Expected Behavior

Possibility to configure two users/schemas of one database instead of two databases (main and log).

### Environment

```markdown
- OS: Arch Linux
- Radarr: 4.1.0.6175
- Docker Install: Kubernetes Installation 
- Using Reverse Proxy: nginx-ingress
- Browser: Firefox
```

### What branch are you running?

Master

### Trace Logs?

No logs needed

[AB#3106](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3106)

**Comment by RobinDadswell** [comment]
Postgres is only implemented in the Nightly branch at the moment and is not available on the version you have stated (latest stable master). 

The reasoning behind Postgres is  that it is supposed to be an alternative database to SQLite for advanced users only and not a global replacement. Due to the complexities surrounding having a single database with multiple users and schemas whilst supporting multiple database types there are no plans for this change.
