### ISSUE TITLE
Archiving history items

### ISSUE THREAD

**Issue by 4C3T** [Radarr/Radarr#7282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Once Radarr's been set to roam free (a.k.a. search for missing movies, importing from lists etc.), the download history contains tons of items.
It would be nice if these could be archived, to clear the list.
It's not that it takes an obscene amount of time to load the page, but it's cluttered with pages of items that becomes irrelevant in time (due to upgrades, lost due to broken HDDs etc). Sometimes you need to make a list, like the day after a 'session' and it would be nice to have a clean slate to work with, yet have it accessible.

### Describe the solution you'd like

I'm thinking some nifty way to update the database, either a "simple" DIY guide for users, or some conversion tool to add a boolean column (can't remember the correct name for it right now) to the table in the database, or something like that, then add the appropriate code in the page to add a check box for archiving it. If this would become a reality that is.

Perhaps the option or filter function could in- or exclude these.
I would at the same time like to suggest that perhaps a numeric value, date or date range could be implemented instead of just a boolean value? That would also be useful to see history for specific dates.

Perhaps an alternative solution could be to mimic the logs function with download dates, so at midnight all items gets exported to a dated log file and then have them listed, just like with the log files?
And then removed from the database, if possible.
I don't know if this historic data is read from the movie pages history function so it might not be doable?

### Describe alternatives you've considered

None that I can think of.

### Anything else?

No, I think that's about it.

[AB#3136](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3136)

**Comment by bakerboy448** [comment]
The History page has filters for types (Grab/Deletes/Imports/etc.) and can be expanded to show up to 250 items.

Just trying to talk/think out the use for needing to see more than 250 items of a given type on any given day? (Since it sounds like you don't mind if they roll over daily)

Though I don't disagree that there are some improvements that can be made to improve usability. 

It almost sounds like requesting archiving history is a solution in search of a problem   or a type X-Y thing?

History is also tied to movies / blocklist/etc there's a whole chain.

Also you can clear out the history for a movie by deleting it from radarr - not the files - and reimporting it.   Note that'll lose all history including the original file name that are used for any custom formats.

**Comment by 4C3T** [comment]
Don't really have any need for more than 250 items, not the issue at all, if there would be more entries, then you just click >> or >>| to scroll to the next page

Yes, can be improved for sure.

"It almost sounds like requesting archiving history is a solution in search of a problem or a type X-Y thing?" - What..?

Yeah, kind of figures that it would be tied to those. Perhaps there could be an export to a "new" log function that would allow this feature that I'm requesting? At least the original log would be intact and the copy would allow for manipulating its content. It's a though.

Deleting movies just to clear the log is not a good solution. I'm not going to comment on how stupid that is.

Something else I'd like to see implemented, if nothing more is to be done to this log function I'm requesting is a copy-button for that (i)-button which opens a window for movies "All/Imported/Failed/Deleted etc) so that you can copy these posts without having to select and Ctrl+C or right click to copy.
That would cut down time significantly not having to do this every time.

**Comment by bakerboy448** [comment]
I don't follow. Some clarifying questions hopefully:

- Why do you need to manually archive/copy history?
- Why do you need to browse history often?
- What process does the "noise" impact and how?
- Basically, why does history need to be cleared on a daily basis and what benefit does that bring to the workflow?
- Flipside of that, what problems does the current system cause?  Based on what you're saying it sounds like you want to get rid of history just because you want to? 
- What's the larger end goal that having less history would accomplish ?

**Comment by 4C3T** [comment]
I'm using an external application to which I need to copy these. This requires manual input of text strings. No API.

Not sure what you mean by "noise", but it does makes it more difficult to sort through earlier items, so the ability to clear the list would help greatly, and having that put into archive would mean that it wouldn't be lost, in case you're trying to find the historic events for a particular entry, like when & what was imported/grabbed/failed etc.

Perhaps it's easy for you to use the API, but I'm no programmer and I also don't know any programs that would allow me to extrapolate the log, then further manipulate it to my needs since I need it in plain text, preferably with a copy-button as per my last message.

**Comment by bakerboy448** [comment]
What does the external application need? What does it do with the information? The imported file names? The release name of the grab? That can be accomplished with any of the various connections/notifications.  You can setup emails that send you the details or some sort of custom script etc. Thus removing the need to even view history.

A quick and easy custom script can be made with some googling to append the release name or file name to a text file for you use case.  The wiki lists the variables the custom script connect passes and a quick google of "how to append {bash/power shell/batch/your favorite scripting language} variable to text file"

I don't think there's any appetite at all to remove history or archive it; it also doesn't serve much benefit and requires a fair amount of effort for a single user's niche use case.


So to level set you're going in to history on a daily basis, filtering for Grabs?Imported? What type 
? And then manually copying all the file names? Release names? What data point? And then pasting it to a plain text file for your external program?

**Comment by 4C3T** [comment]
Forget I even asked...
