### ISSUE TITLE
Web-Rip parsed as web-DL

### ISSUE THREAD

**Issue by ItsME6969** [Radarr/Radarr#7424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Some releases are named as `WEB-Rip` instead of the usual `WEBRip` and radarr parses those as WEBDL.

### Expected Behavior

WEB-Rip parsed as WEBRip

### Steps To Reproduce

Movie.Title.2019.1080p.AMZN.WEB-Rip.DDP.5.1.HEVC

### Environment

```markdown
- OS: linux
- Radarr: 4.1.0.6175
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Develop

### Trace Logs?

.

[AB#3373](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3373)

**Comment by bakerboy448** [comment]
Trace Logs are typically not optional for bug reports.

normally Web-Rip is treated as Web-Rip.
https://github.com/Radarr/Radarr/blob/005431865808947cb7031e20ded427e49158f10c/src/NzbDrone.Core/Parser/QualityParser.cs#L20

since it's "AMZN.WEB"  it's being matched as Web-DL  @TRaSH- is this accurate?   Or should we truly be treating this as web-rip?
https://github.com/Radarr/Radarr/blob/005431865808947cb7031e20ded427e49158f10c/src/NzbDrone.Core/Parser/QualityParser.cs#L19

Regardless of the quality matching - TBD.
There is still a bug given we're detecting -Rip as the group.
![E0A500AE-DE97-4556-BC67-40E3F065099B](https://user-images.githubusercontent.com/55419169/179754377-da2d932b-c4e5-4199-b856-feb9d4376060.png)

**Comment by ItsME6969** [comment]
"AMZN.WEB" has no effect here, there is a different underlying issue
![Screenshot 2022-07-19 065825 - Copy](https://user-images.githubusercontent.com/89707006/179768764-c7304213-eb3d-4059-bce7-6be79d32dd9f.jpg)
