### ISSUE TITLE
Chmod the osx binary with executable

### ISSUE THREAD

**Issue by AeonLucid** [Radarr/Radarr#745]
**Description:**

There's currently and issue where the OSX package gives "The application 'Radarr' cannot be opened", which is fixed by **chmod +x** on the **Contents/MacOS/Sonarr** file.

I will update the cake build script to setup the permissions correctly.

**Comment by AeonLucid** [comment]
Relevant: https://github.com/Radarr/Radarr/issues/60

**Comment by eriksneff** [comment]
FYI - this is still happening as of build 0.2.0.535. For now, I've put up a little [PSA on reddit](https://www.reddit.com/r/radarr/comments/5vvqnu/radarr_osx_download_not_working/) telling people how to get it working.

**Comment by eriksneff** [comment]
And I've updated the PSA to align with the renaming of the main executable that changed from a file called "Sonarr" to one called "Radarr".

Note: I also just confirmed by downloading the latest mac package:
Radarr.develop.0.2.0.696.osx-app.zip
That the main executable in the Radarr.app container is still now executable by default, as seen here:
![image](https://content.screencast.com/users/eneff1599/folders/Snagit/media/d0b96b2a-fdd5-4168-ac1b-efd9849abad9/2017-05-16_15-10-48.png)

**Comment by AeonLucid** [comment]
@eriksneff Can you confirm if it's fixed since 0.2.0.710?

**Comment by eriksneff** [comment]
@AeonLucid unfortunately that didn't do it. I think this may be the solution - if you'll give my github username permissions, I'll submit a pull request with the solution - have a look:
![image](https://cloud.githubusercontent.com/assets/6926543/26168067/b3a8039e-3aed-11e7-863b-254da8f4ba39.png)

**Comment by AeonLucid** [comment]
@eriksneff Wait I think I know whats wrong. I'm doing chmod on the wrong file at the moment.

**Comment by AeonLucid** [comment]
@eriksneff Didn't mean to close this yet, can you check again if it's fixed with **0.2.0.711** once it's done building?

**Comment by eriksneff** [comment]
Just left a comment on your commit - if you'll give me pull request perms I'll push the solution I have waiting.

**Comment by eriksneff** [comment]
Argh - #1548 didn't help either... since I'm really foreign to most of the technologies involved in the build process, it'll take me a while to dig into this. @AeonLucid - have a look at what I did - I suspected the issue was a typo in the cygwin call with an errant @ symbol, and when I cleared that out, the appveyor build process bombed out saying the windows backslash was an incorrect escape character. I was honestly hopeful that double escaping would solve it, but it doesn't appear to have worked. All I have time for tonight...

**Comment by AeonLucid** [comment]
AppVeyor runs on a window machine, that's why the path was using `\`. You can read about the `@` symbol [here](https://msdn.microsoft.com/en-us/library/aa691090(v=vs.71).aspx). The tools available in AppVeyor can be found [here](https://www.appveyor.com/docs/build-environment/).

I'll have a go at fixing it too. 😅

**Comment by eriksneff** [comment]
FYI - I can confirm 2 things - a) this is definitely resolved now, and b) For me personally, there may have been another issue at play - my 3rd-party mac unzip tool Keka (that adds 7zip support which i needed), it appears has a bug (here: https://github.com/aonez/Keka/issues/2 ) where it sometimes loses file permissions during the unzip process, causing the "Radarr" file that is the key to the Radarr.app file being able to run, to not be executable. I've joined the thread discussing this bug, but for Radarr's purposes, this issue is officially put to rest IMHO!

**Comment by AeonLucid** [comment]
@eriksneff How did you confirm that it was fixed? I still don't get the executable flag on linux.

![image](https://user-images.githubusercontent.com/4643257/27758481-39966578-5e15-11e7-83ae-0f71c5d3a6ff.png)

**Comment by eriksneff** [comment]
On Radarr.develop.0.2.0.778.osx-app.zip, unzipping using the native mac archive app, it works just fine for me - here's an animated gif for proof:

![2017-07-02_13-22-47](https://user-images.githubusercontent.com/6926543/27773253-89c1388c-5f2a-11e7-947e-0290b2aaa6c6.gif)

**Comment by galli-leo** [comment]
@eriksneff Could it be that the native zip utility automatically adds the executable bits?

**Comment by galli-leo** [comment]
What happens when you use unzip?

**Comment by eriksneff** [comment]
Oh, and here's the unzip flow for the 783 version Aeon mentioned (permissions looking good as well):

https://ci.appveyor.com/api/buildjobs/mr9ko5iof0k02dgt/artifacts/Radarr.develop.0.2.0.783.osx-app.zip

**Comment by eriksneff** [comment]
@galli-leo - you might be right - I just confirmed that every single file contained within the executable "file" (.app container) called Radarr.app was marked as executable, css files, plist files, all of them. At this point, I'm guessing that this is intended behavior of the Archive.app utility, although I definitely hadn't heard of that before, and my other unzip utilities definitely do not do this...

**Comment by drnikki** [comment]
This happened on downloading the latest release (v0.2.0.1480) running OSX 10.15.1. Chmodding the .app file fixed it and it opened.
