### ISSUE TITLE
[BUG] Movie Sort by YEAR

### ISSUE THREAD

**Issue by ItsME6969** [Radarr/Radarr#7484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Movie sorting by year doesn't work. Seems to be bugged out somewhere.
..
![Screenshot 2022-08-16 174746 - Copy](https://user-images.githubusercontent.com/89707006/185012320-ca99622c-ccb6-479b-ac57-391f02494c38.jpg)
..
In the attached screenshot you can see it starts off well sep 2004, Dec 2004, then after 2007 the next movie has no date. Its an unreleased movie thats only premiered at film festivals so has only premier dates on tmdb no theatrical yet. Then the date sorting reverses and now goes from August down to May and then back again to the one that is supposed to release this coming friday.

### Expected Behavior

Sort oldest to newest and vice versa properly.

### Steps To Reproduce

Sort >> Year

### Environment

```markdown
- OS: linux
- Radarr: 4.2.2.6487
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: chrome
```

### What branch are you running?

Nightly

### Trace Logs?

Screenshot attached

[AB#3471](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3471)

**Comment by Qstick** [comment]
What you are looking at is 2 different fields. Year is calculated differently (backs up to premier or other, etc) than is In Cinemas date. So, all of those movies have a value for "Year", not all of them have a value for "In Cinemas" which is what you have shown under the posters.

**Comment by ItsME6969** [comment]
I see, yea that makes sense. Thanks for the clarification. Follow up question is wouldn't it be better when clicking `show release date under poster` to actually show that calculated date instead? That would serve a couple purposes
1) Show the actual value that is really being sorted by
2) Each movie would atleast show a year on it instead of blanks 
3) visualy it would look better if the dates were not all over the place with that sort
look at the screenshot I've confirmed the sorting is indeed right but the missing dates on some releases and the dates not being chronological looks abit messy
..
![Screenshot 2022-08-16 214107 - Copy](https://user-images.githubusercontent.com/89707006/185036409-7dce1f90-7f13-4f53-a0d7-118f1aa72116.jpg)

**Comment by girtsl** [comment]
My 2c - when sorted by year, movies without a year (announced?) show up before all other movies - presumably because the missing year value has a fallback to 0. Since the movies haven't been released yet but will/should be in the future - I'd expect them to be at the end of the collection, after all others.
Right now I've added a "workaround" - a custom filter that combines my preferred filter with `year >= 1` which hides them. Not ideal but at least they are not at the beginning taking up space.

**Comment by andrew-hill** [comment]
> So, all of those movies have a value for "Year"

I think the main issue is that unreleased movies have a value that sorts “below” old movies, rather than “above” the latest release.

I’ve only seen movies that lack any kind of release date showing up like this, so presumably they could default to a very large number, rather than 0 or negative, as they appear to now.
