### ISSUE TITLE
Add option to not write collection data to nfos

### ISSUE THREAD

**Issue by laryan61** [Radarr/Radarr#7571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Radarr automatically, with no way to disable adds the movie collection <set> tags to the movie NFO files. Which are then read into other media servers like Emby. Creating 100's of unwanted movie collections.

### Describe the solution you'd like

I'd like to be able to control/manage Movie Collections within Radarr. The ability to disable the feature completely and selectively delete individual movie collections from Radarr and not have them automatically added them back in.

### Describe alternatives you've considered

There is no alternatives. If the collection <set> tags are removed from the movie NFO files. Radarr will automatically rewrite the NFO with the <set> tags. Un-monitoring the collections has no effect on the movies within those collections. The <set> tags still remain.

### Anything else?

Nope.

[AB#3684](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3684)

**Comment by bakerboy448** [comment]
- don't believe there's any plans to remove collections at all. They have _always_ existed in Radarr.  They're just now easier to work with rather than via a list.  Movies with a collection have always shown that collection on the movie page in the UI and it'd be arguably a (now fixed) bug if the collection previously was failing to be wrote to the file 
- It sounds like the only actual issue here is 
- Emby fails to to give an option to not automatically create collections from nfo files (not a radarr issue, make a feature request for them)
- Radarr doesn't have a setting to _not_ write the collection to the nfo....which was the feature request suggested to you to request

**Comment by bakerboy448** [comment]
Looking further at Git Blame - radarr has always wrote the collections to the nfo.

https://github.com/Radarr/Radarr/blame/1576bf1f17c085b2fbbb8fdfa28b03a16a881a82/src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs#L254

Thus if this problem just started occurring it would seem Emby must have made a change that caused it to automatically create collections against the user's wishes with no ability to turn it off.

**Comment by laryan61** [comment]
I believe my request was pretty clear. Having the movie collections displaying and managed in Radarr is a great feature. Allowing a user to select a collection to seek out and find those movies. But I would like the option to disable collections, ie. writing to NFO file.

**Comment by laryan61** [comment]
Until I added Emby I was unaware of this issue. But I'm working with the Emby group as well on this issue. They should have the feature/option to ignore the NFO <set> collection tags.
