### ISSUE TITLE
Prioritize choosing downloads with more seeds

### ISSUE THREAD

**Issue by codeswhite** [Radarr/Radarr#7667]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When I perform automatic search often I find the chosen download is not the optimal in terms of seeds and peers.

In context when there is more than one "suitable" release for grabbing.
(example and explanation below)

It seems the algorithm does not prioritize seed/peers count in the array of available releases.

### Describe the solution you'd like

I would like to review the "automatic release grabbing" code.

For it to prioritize suitable releases with highest count of seeds and peers.

### Describe alternatives you've considered

I have found this issue was addressed before: (#3093) but I'm not satisfied with the resolution there: 

> Increase your minimum seed requirements as a solution right now

This does not solve the problem.

And so i ask you to reassess this topic.

### Anything else?

Here's an example:

> Added the title: "Star Wars: Episode II - Attack of the Clones" (`tmdb:1894`)
> The quality profile is set to: `stock HD-1080p`

The automatic release choice algorithm have chosen and started this download: {annotated `1` in the image below}
Which is not the optimal download (it stalled in the download client).

The optimal would be: {annotated `3` in the image below}.

After marking the download as failed and removing it from the download client (`deluge` in this case, if it matters)
I hit again the `Search Movie` button and see Radarr grab a new download, this time its: {annotated `2` in the image below}.

At this moment i was like:
> Thats enough! I gotta contribute that feature request!

Clearly this choice logic is:
    `"Get set of releases for title -> filter by profile, blacklisted, etc. -> take the first one from the remaining set"`
I suppose the algorithm is missing a sort by seeds so the logic should become:
    `"Get set of releases for title -> filter by profile, blacklisted, etc. -> sort by seeds(or other criteria) -> take the first one from the remaining set"`

![image](https://user-images.githubusercontent.com/13444627/194773649-c8c05cf7-d369-4d69-8a9f-2ea4db8346f9.png)

Running `Linux (x86_64)   Radarr: 4.2.4.6635`

---

I would like to personally suggest a PR for this, but unfortunately i was unable to locate the relevant code inside the codebase.
I'd like for someone to point me in the right direction in the code.

[AB#3887](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3887)

**Comment by austinwbest** [comment]
I don't see a chage coming that prioritizes a 1gb file over a 5gb file because it has higher seeds bud

**Comment by codeswhite** [comment]
@austinwbest 
What good is a 5.9GB over a 1.9GB if it just stalls with a download size of one kilobyte?

BTW I personally prefer smaller download sizes.

**Comment by austinwbest** [comment]
I understand your dilemma and your preference however a minority prefers lower quality to higher. So there surely won't be any change to that logic to make a 1gb file trump a 5gb file based on default settings as that effects 300k+ users.

There is also not likely going to be a setting to allow users to change the ranking of items.

What you do have at your disposal is custom formats and quality definitions to help tune to your preference.

An example, by lowering the values for bluray 1080 that 5gb file wouldn't even be an option to pick from since you want lower.

Another factor is the indexers used, lower end & public ones are known for skewing peer counters so they are not even reliable as a point of truth to use.

**Comment by Qstick** [comment]
Hi @codeswhite,

Lets talk exact code, cause just talking in assumptions isn't going to answer your questions. 

> It seems the algorithm does not prioritize seed/peers count in the array of available releases.

We do actually prioritize based on the swarm size (seeds and peers), and it's actually higher in the priority list than size. However, we go by buckets of peers instead of exact count. The compare order logic is here: https://github.com/Radarr/Radarr/blob/a8362511f954cb00d2d6e55caaa6683b03ba8c3e/src/NzbDrone.Core/DecisionEngine/DownloadDecisionComparer.cs#L30-L40

For swarm size we use the buckets as outlined here, these bucket the swarms using Log10 base approach. Essentially a super small swarm is bucketed under a mid-sized swarm, bucketed under a large swarm. It's not by exact number of seeds as we lose any further prioritization at that point lower in the list (size). 
https://github.com/Radarr/Radarr/blob/a8362511f954cb00d2d6e55caaa6683b03ba8c3e/src/NzbDrone.Core/DecisionEngine/DownloadDecisionComparer.cs#L113-L137

A torrent with a swarm size of 40+ really should not be stalling (prioritizing one with slightly higher per your example isn't going to be a sure thing). As austin alluded to this is really a case of the indexer falsely overstating the swarm size. With an indexer doing this, nothing is to say that it wouldn't have said 300 and stalled. Radarr know's not but what it's been told by `Kat`

> "Get set of releases for title -> filter by profile, blacklisted, etc. -> take the first one from the remaining set"

This is not accurate, see above code reference. 

> BTW I personally prefer smaller download sizes.

There are actually options to set this, use the preferred size slider in quality definitions. Moving this to the bottom will always prefer smaller releases. 

You can also utilize Custom Formats as mentioned to really dial in your preferences.

**Comment by codeswhite** [comment]
I understand now the bigger picture, thanks for clearing out!
Totally missed out the swarm size skew, it does seem to be the root of the problem as it gives false hopes to Radarr.

I will definitely tweak my indexers list after this

Hope this thread will come as useful to those who undergo the same experience as I have.
