### ISSUE TITLE
Being able to rename the movie when the system doesn't recognize correctly a film or a serie

### ISSUE THREAD

**Issue by sched75** [Radarr/Radarr#7943]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

The problem is that if the search engine doesn't correctly associate a movie or a serie with an indexer db (imdb, ...) there is no way to correct the issue afterward. for example : the pilot of a british serie called "hard sun" has been associated to a serie called "descedant of the sun". 

### Describe the solution you'd like

would be nice to be able to rename the movie or serie and then the directory is renamed the research is redone etc...

### Describe alternatives you've considered

none. there is no-way to correct those issues. very frustrating.

### Anything else?

nope

[AB#4583](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4583)

**Comment by RobinDadswell** [comment]
The correct way of handling this is to resolve the issue at the metadata provider (tmdb for Radarr) as then it is corrected for everyone

**Comment by bakerboy448** [comment]
See https://wiki.servarr.com/radarr/faq#path-is-already-configured-for-an-existing-movie

> none. there is no-way to correct those issues. very frustrating.

Incorrect. A user assigning the wrong movie/series to the folder is easily fixable and also only caused by the user.

> The problem is that if the search engine doesn't correctly associate a movie or a serie with an indexer db (imdb, ...) there is no way to correct the issue afterward.

if the user told radarr/sonarr the wrong movie/series for a given folder....simply delete that movie/series from the app and then library import again selecting the correct movie.

Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.
