### ISSUE TITLE
Radarr not recognizing network drive

### ISSUE THREAD

**Issue by english06** [Radarr/Radarr#800]
**Description:**

I mount my Google Drive via Expandrive as a mounted network drive on Windows 10. Radarr does not recognize this drive. Sonarr is able to do so. This naturally causes many problems as my "Movies" folder is unable to be seen by Radarr.

**Radarr Version:**  0.2.0.299

**Comment by english06** [comment]
Preemptive questions. Yes it is running as administrator. Yes I have used hostname paths as well. Neither change the result.

**Comment by galli-leo** [comment]
Can you install radarr as a service? And make sure the Account under which services are run has access to the network drives.

**Comment by english06** [comment]
Also installed as a service. User account has access to network drives. That did not work.

**Comment by richardjarrell** [comment]
I am having the same issue.  Sonarr can use the public folder of my NAS, but Radarr says "Path does not exist"

**Comment by galli-leo** [comment]
@english06 @richardjarrell Try mapping the Folder to a drive. Also try setting the permissions so that everyone can access that folder.

**Comment by krazydave** [comment]
In Windows 10 I could not access or even see any network paths, mapped or otherwise when running Radarr as a service. Folder permissions are open to everyone. 
Tried setting the service to run as the logged in (admin) user and still couldn't get it to work. 
I ended up just adding a shortcut to the startup folder as a workaround. 
Sonarr on the same machine running as a service can see the drives, however.

**Comment by english06** [comment]
Just downloaded a different piece of software to mount Google Drive and it has same error. So that rules out Expandrive.

> Try mapping the Folder to a drive

I am unable to mount any folder as a new drive as the folders are already in a network drive.

> Also try setting the permissions so that everyone can access that folder.

Permissions are set and valid as well so that my personal user and admins can access them.

_____

I also just discovered that Radarr.exe is not starting from the shortcut placed in my startup folder. Beyond me why that isn't working. Radarr.exe is set to run as administrator. Running as service still produces same results.

Does location of Radarr folder matter?

**Comment by clarenceb5** [comment]
Hi, I currently have Sonarr setup on one computer with my sabnzbd+ client on another computer. In Sonarr in the Download Client settings down at the bottom is the Remote Path Mappings settings.  In this section in Sonarr I am able to set the local path with the following "\\computername\c\Complete\TV Shows\". In Radarr I am unable to even set the same local path, returns error saying 'path does not exist' but it works in Sonarr.  I am running Windows 10 and I have Radarr installed as service, installed and running with admin rights.  I can use windows explorer to get to "\\computername\c\complete\tv shows\" no problems.

**Comment by tj1816** [comment]
I'm having the exact issue.  It doesn't matter if I'm running Radarr.exe or as a service, it won't see my mapped drive.  Sonarr does not have this problem.  I also have the issue of Radarr.exe not starting from the shortcut in the startup folder.

**Comment by galli-leo** [comment]
@tj1816 @clarenceb5 @english06 Can you guys try the solutions recommended by Sonarr here?: https://github.com/Sonarr/Sonarr/wiki/FAQ#why-cant-sonarr-see-my-files-on-a-remote-server 
For launching from the Startup folder you will first have to uninstall the service.

**Comment by clarenceb5** [comment]
That worked for me. The service is now using the proper admin credentials and allows me to find the remote path. Thank you for that suggestion.

**Comment by tj1816** [comment]
Neither worked for me.  I was able to get Radarr to recognize my mapped drive when I changed the Startup directory to my user folder (C:\Users\TJ\Radarr\Bin).  I created a shortcut to radarr.exe and placed it in the startup folder.  I reset my computer to see if it would run on startup and it did not, and radarr.exe was no longer in C:\Users\TJ\Radarr\Bin

**Comment by galli-leo** [comment]
@tj1816 That's very strange. Try placing all the exe files in C:\ProgramData\Radarr\Bin

**Comment by tj1816** [comment]
I'll give that a try later tonight when I get home. I'm really surprised it doesn't work when I run the service with my login credentials.  It makes sense that it should work that way.

**Comment by tj1816** [comment]
I should clarify; Radarr CAN see my network drive when I use a UNC path, but it doesn't see it as a mapped network drive (Z:\).  This becomes an issue because (I think) Deluge tells Radarr that the path for the file it just downloaded is in the Z drive and Radarr gives me an error saying the path (to the Z drive) doesn't exist.

**Comment by delphiactual** [comment]
Settings -> Download Client -> Remote Path Mappings -> `+`

**Comment by tj1816** [comment]
I tried that before and it still didn't recognize the mapped drive when I tried to import movies (maybe that's not what it does). Let me try downloading something and see if that works.

**Comment by galli-leo** [comment]
@tj1816 You have to make sure the paths match up exactly in Remote Path Mappings.

**Comment by tj1816** [comment]
@galli-leo Maybe I'm using Remote Path Mapping incorrectly.  Deluge and Radarr are on the same machine (Windows 10), but my download and movie folders are on my Synology NAS (mapped to Z:\).  To make sure I'm configuring this correctly, Host should be "localhost" (since it's on the same machine as Radarr).  Should root path be "Z:\" or "Z:\Downloads"?  And then I assume Local Path should just be the UNC Path to the Z drive, or the download folder in the Z drive.  Is that correct?

**Comment by SirAce135** [comment]
Having the same exact issue reported here. Radarr is running as a service now and it can not see my mapped drives at all. When it was not running as a service it was able to see them just fine.

I also tried editing the service account logon and changing it to an admin account, and it did not make a difference.

Thank You

**Comment by clarenceb5** [comment]
Can you just use the network path and forget about the mapped drive letter?
My sabnzbd client is on a different pc than radarr
example:
Host: 192.168.0.105
Remote path: c:\complete\Movies\
Local path: \\computername\c\complete\Movies\

**Comment by SirAce135** [comment]
The direct network path worked beautifully! Now I just have to edit all of my current movie path's to it. I will also have to setup the path conversion so it knows where to look for NZBget content since NZBget and uTorrent are both using the mapped drive letter. I'll try my luck with that now and report back.

**Comment by SuperGaco** [comment]
I'm having the same issue. I have google drive mounted via netdrive. On Sonarr it works great, I have it in my startup folder, but Radarr says in the logs "Invalid request Validation failed: 
 -- Folder is not writable by user SuperGaco", which is obviously untrue. The funny thing is, it was working fine before, but stopped working as I detailed in this reddit post here [https://redd.it/5vte9y](url)

**Comment by jdchandler** [comment]
Same issue.

Sonarr sees /FQDN/movie-share just fine
Radarr (when ran as a service or not) it failed to find any videos.

When running as a service, I did change it to run as Administrator, this allowed me to ADD the UNC path and it detected how much free space, but when detecting files, it could not SEE anything

**Comment by fryfrog** [comment]
@tj1816: Can you switch Deluge to use UNC paths? You'll also need to switch Sonarr to UNC paths too, I think. If it is working now, it is probably using the mapped network drive.

**Comment by tj1816** [comment]
@fryfrog: I could be wrong, but I don't think Deluge can use UNC paths, at least I couldn't figure it out. I was able to remedy my problem by just changing my download folder to a drive on the same system that radar is on, then radarr moves it to the correct UNC path on my NAS.

**Comment by galli-leo** [comment]
Closing issue. If new problems pop up with networked drives open a separate issue after having done everything on: https://github.com/Sonarr/Sonarr/wiki/FAQ#why-cant-sonarr-see-my-files-on-a-remote-server

**Comment by english06** [comment]
I mean the issue is still present even after going through those steps for multiple people now. This is definitely not working as intended.

I have switched back to CouchPotato in the mean time. Hope it gets figured out in some future version.

**Comment by jdchandler** [comment]
Ya idk why this is closing. I still have the issue with or without service. And I am using UNC paths. I also went back to CouchPotato until this is fixed. sonarr works fine with this.

**Comment by galli-leo** [comment]
@english06 @jdchandler As I said, please open a new issue if your problems still persist. I closed this issue, because a lot of people with different problems posted here, making this issue very convoluted.

That being said, if everything from the Sonarr FAQ failed, please try:

1. Giving all accounts permission to read / write to the networked drive.
2. Running Radarr from a command prompt under the user that setup the networked drives.
3. Remapping the networked drive.

I am sorry for any issues caused here, but it's very difficult to debug such things and probably a configuration issue. We did not change anything from Sonarr here.

**Comment by english06** [comment]
> Note: Try to use Radarr.Console.exe for the Shortcut in the Startup folder.

I believe that did the trick. It seems to be working as intended now. Thanks!

**Comment by contherad** [comment]
> Note: Try to use Radarr.Console.exe for the Shortcut in the Startup folder.

This worked for me as well.

**Comment by somehost** [comment]
I have had success creating a symbolic link on Windows 7 and the specific shared folder having no security in that everyone/anyone can read/write.

e.g. mklink /D C:\myLink \\127.0.0.1\c$

From: 
[https://superuser.com/questions/650025/how-to-access-mapped-directory-from-a-windows-service](url)

**Comment by NickC4555** [comment]
I had a Windows 10 update and a QNAP NAS firmware update on the same day last week, so I don't know which of those was responsible, but since then neither Sonarr or Radarr can see my network share when running as a service. They both work fine as an application. I tried (only in Sonarr) running the service under a different account with full control, but that didn't work either.

**Comment by HWiese1980** [comment]
By the end of 2019, more than 2 years later, it is *still* an issue. I request reopening it!

**Comment by HWiese1980** [comment]
... or at least linking the latest issues related to this one...

**Comment by WizarrdCodely** [comment]
Have you already tried exiting Radarr and starting it back up again? 

I was just dealing with this issue where Sonarr, but not Radarr could see my mapped network drives. 
Shutting Radarr down and bringing it back solved the issue for me.

Not sure, but I wonder if maybe Radarr started up while the drives weren't available, and then refused to reconigze they existed (even if I manually entered a path to the network drive, I'd get an error telling me the folder didn't exist)

**Comment by doyoyob** [comment]
I had the same issue too, after bought a NAS and have it mapped to Win10 as a network drive.
After searching and poking around I finally got it work.

OS: Win 10 Pro 1903, running Plex Media Server, Jackett, Sonarr and Radarr. 
NAS: Synology DS918+, three 4TB HDD mounted. SMB enabled mapped to Win 10 as "Z:\"
drive.

Plex deal with the mapped drive with no issues (also running as a local service), but neither sonarr or radarr could see the mapped drive. I tried the UNC path but did not work. I can see the NAS from my "Network" btw.

The solution took three steps (actually just two).
**1)** create a symbolic link to the mapped drive.
**2)** run service sonarr and radarr as user.
**3)** delay service start, in order to avoid "can't communicate with XXX" error.

But the interesting thing it will not work if you do only 1) or 2), had to do both.
As @somehost mentioned, symbolic link works like a charm, but this command only works in CMD but not PowerShell, also you have to run CMD as an administrator.
