### ISSUE TITLE
Rectificarr fix shit file names from Trackers

### ISSUE THREAD

**Issue by fe80Grau** [Radarr/Radarr#8092]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sometimes Torrent Trackers set shit names in movie files.
This shit causes "Unable to parse file" error in Radarr Activity, then Radarr can't rewrite file to setted Path.

### Describe the solution you'd like

I dev the next mini-script [Rectificarr](https://github.com/fe80Grau/Rectificarr)

- This script uses Radarr API to check if exist an activity with this error and force rename
- Optional, This project contains posttorrent.sh Bash script integrated with Transmission Daemon to auto-unrar torrent downloads.

### Describe alternatives you've considered

I like to integrate this feature as native feature in Radarr

### Anything else?

I found many issues arround the network, specially with Spanish language torrents. Rectificarr is simple but efficient, and is easy to integrate as a native feature.
I'm working to support Sonarr to solve same problem.

**Comment by bakerboy448** [comment]
-  you're blindly trusting that the tracker and torrent is correct and doesn't contain a random video file instead
- It'd likely be better to rename the file to the release name rather than losing all info and only naming it movie / year / quality that radarr parsed
- This is really something the trackers need to enforce on their end; they shouldn't allow uploads with files that are named non-standard / don't even match the release name
- unable to parse file likely means the file has no year in the name which is required

**Comment by fe80Grau** [comment]
- In Spanish torrents we have a lot of these trash name, and is this or nothing... This is not a 100% name corrector, but allows to unatended publish content. Maybe with a log that advertise "public content for  review" for "manual revision", but keep alive the content flow. It's a feature for homemade implementations...

- About the rename, you're right. It's very improvable with ffmpeg and parse metadata. I will work about it

**Comment by Qstick** [comment]
CLosing this for now, no plans to implement this natively.
