### ISSUE TITLE
Improve manual import view

### ISSUE THREAD

**Issue by imajes** [Radarr/Radarr#8122]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sometimes, especially for foreign language or poorly named (think: arthouse) movies, auto matching and import doesn't work. So periodically I have to purge the import dump folder and manually process them. In doing so, I have to spend a lot of time trying to determine why a release was rejected (other than when just renaming/matching). It's a laborious process, and prone to failure, as the only way to know why a release failed is to hover over the exclamation icon to see the reason. 

I think with a little bit of UX improvement, it'd become a very useful interface. I have heard that some of the *darr folks would rather get rid of it or keep it unusable so that people don't rely on it or over use it, however it's a fact of life with how some of this process works, and at this point it'd be great to have a working interface.

### Describe the solution you'd like

First, it probably makes sense to shift from a modal to an actual page + route. The form itself is pretty chunky, and already has nine columns -- so it's probable that it's time to reconsider.

As a seperate page, it should then be easy to unwrap both the custom format and issues / warning graphics, and probably inline the popover message/labels.

If switching to a full page is unlikely, then I did a quick mockup to show a potential way to improve the UX -

1: make the manual import form wider -- i think you can rely on a avg width of 1200px at least at this point.
2: unwrap the reason for failure and make it a column of the primary import form
3: consider folding the release group into the movie name column
4: consider migrating the custom-formats icon into a singular "Issues" column

<img width="1421" alt="Screenshot 2023-02-14 at 14 47 24" src="https://user-images.githubusercontent.com/2073/218861180-70d12fb7-a446-4cbb-b21c-3e80b12ea776.png">

### **_As an added value, it'd be exceptionally useful to have an option to delete as well as import._** 

Why is this better?

Because I could then easily sort by the specific reason for issue, then quickly uncheck import / check delete for all the "not an upgrade" items. I'd probably process those ones, and then work on the unknowns. Once they were identified, i'd again re-sort on issue and quickly eradicate (uncheck import; check delete) the not-an-upgrade, sample, etc. Finally, that should leave the list i should be able to more specifically import. 

### Describe alternatives you've considered

I guess I could use the api to generate the list i'd want, and then action it ... but I don't think that's a good way about this. :)

### Anything else?

(mockup above ;))

**Comment by bakerboy448** [comment]
> Sometimes, especially for foreign language 

these should never be an issue; if they are then TMDb is missing data. https://wiki.servarr.com/radarr/faq#how-does-radarr-handle-foreign-movies-or-foreign-titles

> I have to spend a lot of time trying to determine why a release was rejected (other than when just renaming/matching)

If they don't match to a movie
- the movie is not a title on tmdb
- The movie does not exist in your radarr
- The name is missing the year and not parsable

> So periodically I have to purge the import dump folder and manually process them. 

are they no longer in your download client's queue - if not why? They should be easily manual importable from the queue

don't disagree that manual import could use improvements, but this seems like a solution in search of a problem / and doing things the hard way via bulk manual import instead of just importing from queue.

everything in your download client in radarr's category that isn't ignored shows in Activity => Queue

=======

> unwrap the reason for failure and make it a column of the primary import form

Agree this can be very helpful


> consider folding the release group into the movie name column

disagree; it's a distinct field that may require user input 

> consider migrating the custom-formats icon into a singular "Issues" column

disagreeish; not an issue, distinct info for the user

**Comment by imajes** [comment]
> If they don't match to a movie
> 
> * the movie is not a title on tmdb
> * The movie does not exist in your radarr
> * The name is missing the year and not parsable

Yep, those are the sorts of issues. Especially e.g. right now where movies got delayed due to covid, and have different release years than whatever was in tmdb. And yes, there have been several movies downloaded that did not match a movie in radarr -- not entirely sure how, but regardless - they exist. 

I've heard the argument a few times now about how it should all just work tied to the queue -- but honestly sometimes it just gets messed up and proper manual purges are required.

Either way-- it'd be nice to make the page more useful, as it could definitely use those improvements :)

**Comment by bakerboy448** [comment]
> Especially e.g. right now where movies got delayed due to covid, and have different release years than whatever was in tmdb.

these shouldn't be an issue if TMDb was updated. https://wiki.servarr.com/radarr/faq#how-does-radarr-determine-the-year-of-a-movie

> And yes, there have been several movies downloaded that did not match a movie in radarr -- not entirely sure how

grabbed by ID and the downloaded file is missing the year or otherwise doesn't match a TMDb title

> but honestly sometimes it just gets messed up and proper manual purges are required.

doesn't make sense?  the queue comes directly from the download client.  The only items that would be stuck in queue with a yellow icon indicating a human is needed would be those that can't be imported.   If the queue is getting messed up then the user is telling starr to ignore releases or is removing them from the client - the later isn't supported behavior.

================

sounds like the only change to manual import to make would be to move the reject from a tool-tip to an actual message?
Can you update the title and OP accordingly then?  Also it'd probably be best to get this change into Sonarr first and then it'd flow downstream accordingly.

**Comment by bakerboy448** [comment]
@imajes should we close this given the original request won't happen or are you planning to update as previously discussed?

**Comment by bakerboy448** [comment]
Closing, abandoned by OP; won't fix as-is requested in op
