### ISSUE TITLE
[Feature request] Forbidden words, Required words, Preffered words

### ISSUE THREAD

**Issue by ajkis** [Radarr/Radarr#820]
It would be great if we could have the functionality offered by CouchPotato eg to set certain type of words when searching for download. With series that Sonarr handles thats not such a big problem since majority of releases are eng one but with movies there are tons of releases in other languages. 

For example in CP those were my settings:
`PREFFERED. BluRay, 1080p, HD, DTS, DTS-HD, DC, DL, Repack, Proper, Uncut, Extended`
`REQUIRED: 1080p, 720p`
`IGNORED: german, dutch, french, truefrench, danish, swedish, spanish, italian, korean, dubbed, swesub, korsub, dksubs, vain, HC, AC3MD, DVDScr, HDCAM, TELESYNC, WebHD, WebRip, AC3LD, DTSD, AC3D, MD, SCR, LD, TS, 3D, trailer, Blurred`

**Comment by galli-leo** [comment]
Everything you asked is already in Radarr. Under Indexers restrictions you can set required and forbidden words. In your profile you can set preferred words

**Comment by ajkis** [comment]
Huh I missed it, well preferred would be nice too but this is good enoug.

**Comment by galli-leo** [comment]
You can set preferred words in your quality profile

**Comment by richardjgreen** [comment]
It is great that the options for preferred (per profile) and ignored (per indexer) are there, however, it does present a problem for me unless I am missing something?

In CouchPotato, I had a profile for 3D and a profile for 1080p. I have some 3D movies but I am very specific about which titles I want in 3D and when. Would it not be better to move the restrictions to the profile so that we can create per-profile restrictions?
