### ISSUE TITLE
"Semi-Automatic Parse File" Restore the automation with  shitty  torrent names

### ISSUE THREAD

**Issue by Crosus97** [Radarr/Radarr#8240]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

In spain we have a problem,  with a unique public, good quality tracker called DonTorrent

But their torrent name are soo shitty and produce this problem: 
![image](https://user-images.githubusercontent.com/46854222/226123330-0c67b5a4-277a-4818-943c-b9ee0067fdd4.png)

The best part of radarr is the autommation, and wouldn't have

### Describe the solution you'd like

If there is a (Activate or deactivate option) that auto-fill the missing fields with the default detected, not by the torrent name 

![Sin título-1](https://user-images.githubusercontent.com/46854222/226124076-1d90c5f6-b26e-4eda-a0ae-04f16b81d465.png)
and auto fill the  releset Group  with the  Indexer name (i dont know what is  release group ¯\_(ツ)_/¯)

### Describe alternatives you've considered

the alternative... (that torrent change the name of the files?  i tried and they ignore me ¯\_(ツ)_/¯)

### Anything else?

no  more

**Comment by bakerboy448** [comment]
There's no year in the file name so the file cannot / will not be parsed

**Comment by bakerboy448** [comment]
Because the grab logic and import logic are two different blackboxes that intentionally do not talk to each other.   Indexers from time to time have releases with the wrong id or wrong name versus the actual contents of the release.

Radarr will never automagically parse that file as it is invalid and year is required in the name.  All of the subsequent parsing regex relies on the name/year being determined.

These types of issues are also specific to only a handful of groups/sites that can't be bothered to follow or make any attempt to follow common sense file release naming, let alone scene standards.

**Comment by Crosus97** [comment]
I am not saying that this is done for everyone, but if an option could be created (a button in advanced options) for those of us who suffer from this, since I am from Spain, and public torrent trackers (good and of good quality ) there is only this one.
We can't do anything since they don't listen to us.

**Comment by Crosus97** [comment]
and why this ocurred?
![image](https://user-images.githubusercontent.com/46854222/228676206-68e89799-74c6-4648-bd11-3aecda778680.png)

**Comment by edrock200** [comment]
Looks like it was trying to parse from the folder name, or whatever that is in the box header with more details. But it's still formatted wrong. E.g. it's 1080p but radar shows 720p. It's ac3 audio but since they did ...-AC3... In the folder name, it thinks the group name is ac3. That tracker needs to conform to some common naming standard.
