### ISSUE TITLE
Fallback language movie information 

### ISSUE THREAD

**Issue by dtalens** [Radarr/Radarr#8405]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Is it possible to add a option to select a fallback language other than the original?
In my case, I want to have movie information primarily in Catalan and spanish as a second language. 

### Describe the solution you'd like

Add fallback language option in UI menú. 

### Describe alternatives you've considered

.. 

### Anything else?

..

**Comment by bakerboy448** [comment]
> Is it possible to add an option to select a fallback language other than the original?

no plans nor does this make sense.
TMDb spoken language is used if only 1 language exists; otherwise TMDb original language would use.   It does not make sense for the user to be able to arbitrarily dictate what the original language of the movie is.

> movie information primarily in Catalan and spanish as a second language.

movie original language has nothing to do with movie information displayed in the UI nor can you / it doesn't make sense for multiple languages for movie information. How would that even work? 

Movie Info Language can already be configured and has nothing to do with the language a file or release is detected as (where the fallback logic comes into play)....
Settings => UI => Language => Movie Info Language

**Comment by dtalens** [comment]
Obviously I don't mean changing the original language of the movies just the synopsis in an alternative language as allowed by themoviedb.
![Screenshot_2023-04-29-14-50-13-24_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/6631832/235303343-f6580988-7442-48c7-b724-b399c93ac6ed.jpg)
