### ISSUE TITLE
After update to version 4.7.5.7809 all indexers fail.

### ISSUE THREAD

**Issue by juhenriquez** [Radarr/Radarr#9201]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Get the following in the logs:
![image](https://github.com/Radarr/Radarr/assets/8250019/30559578-b424-4afe-b8ff-c064cfe037e1)

`Invalid request Validation failed: 
 -- : Unable to connect to indexer, please check your DNS settings and ensure IPv6 is working or disabled. Operation timed out (192.168.86.244:9696)`

https://gist.github.com/juhenriquez/9b8fb36f2612a238f07da3a3fed65e67

### Expected Behavior

It used to sync correctly, sonarr still syncs correctly.

### Environment

```markdown
- OS: Docker
- Radarr: 4.7.5.7809
- Docker Install: 4.7.5.7809-ls187 by linuxserver.io
- Using Reverse Proxy: NO
- Browser: Chrome
- Database: Sqlite 3.41.2
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

https://gist.github.com/juhenriquez/9b8fb36f2612a238f07da3a3fed65e67

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by juhenriquez** [comment]
> 👋 @juhenriquez, In order to help you further we'll need to see logs. You'll need to enable trace logging and replicate the problem that you encountered. Guidance on how to enable trace logging can be found in our [troubleshooting guide](https://wiki.servarr.com/radarr/troubleshooting#logging-and-log-files).

https://gist.github.com/juhenriquez/6e3d79c472efbef1ec2513a1d3c0b233

**Comment by bakerboy448** [comment]
The provided log files are not what the wiki requests / bug report template requires / checkbox attests was provided.

This appears to be a LAN issue and a support issue

**Comment by BK-STAR77** [comment]
Hello same issue since update radarr

`[v4.7.5.7809] NzbDrone.Common.Http.HttpException: HTTP request failed: [403:Forbidden] [GET] at [https://jackett.bardejess.com/api/v2.0/indexers/gktorrent/results/torznab/api?t=caps&apikey=XXXXXXXXX]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Radarr.Common/Http/HttpClient.cs:line 119
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in ./Radarr.Common/Http/HttpClient.cs:line 326
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.FetchCapabilities(NewznabSettings indexerSettings) in ./Radarr.Core/Indexers/Newznab/NewznabCapabilitiesProvider.cs:line 83
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in ./Radarr.Common/Cache/Cached.cs:line 99
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.GetCapabilities(NewznabSettings indexerSettings) in ./Radarr.Core/Indexers/Newznab/NewznabCapabilitiesProvider.cs:line 36
   at NzbDrone.Core.Indexers.Newznab.NewznabRequestGenerator.GetRecentRequests() in ./Radarr.Core/Indexers/Newznab/NewznabRequestGenerator.cs:line 92
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Radarr.Core/Indexers/HttpIndexerBase.cs:line 344
<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="/cdn-cgi/styles/challenges.css" rel="stylesheet"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div id="challenge-error-title"><div class="h2"><span class="icon-wrapper"><div class="heading-icon warning-icon"></div></span><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '2',cZone: "jackett.bardejess.com",cType: 'managed',cNounce: '57282',cRay: '80e5529b9df935fa',cHash: '7c61c77f5271274',cUPMDTk: "\/api\/v2.0\/indexers\/gktorrent\/results\/torznab\/api?t=caps&apikey=XXXXXXXXXXXX&__cf_chl_tk=BKDC4SwGfH0dFhrua.LCZ8w99LJFEwqemWxVn59vn_g-1696002006-0-gaNycGzNClA",cFPWv: 'g',cTTimeMs: '1000',cMTimeMs: '0',cTplV: 5,cTplB: 'cf',cK: "visitor-time",fa: "\/api\/v2.0\/indexers\/gktorrent\/results\/torznab\/api?t=caps&apikey=XXXXXXXXXXXXXX&__cf_chl_f_tk=BKDC4SwGfH0dFhrua.LCZ8w99LJFEwqemWxVn59vn_g-1696002006-0-gaNycGzNClA",md: "YrThJ2pQ5s5CQKSEA5pfEDUpAmRYfm4JSCEK2OAaItM-1696002006-0-Ab2PsNE3yk3ZlkLTe1fBImmeW5Ix8FJTUZ0_Z34OKe4Oyy4PeEGFjHP0CPiKj0oX_rr5MEnHXVPyPNIY398aSXYYFYaJea2V-Z8TuG7uWRYPYIFgM0WbnXm6ER6tdQ57wG2v32mXagjXT6G6hmx9NZ-jfzlH8CC6WaoE7KKz6-AzGGLNCF1mBKJTzN-GEhJ3SnhUhH_IgAT46-lwP-gal2wzXTgYesxJf8awAm1ikT0i5iMMOSsjlNucsCxBzp0R1vLmPuiCqrsqa2Vumq9ZqAu6EuiYaxEeTsRS-THqvhmOQXj8gZ20EVmsIzBuxubCFtpFjVKzRUAQQ9BUHaywI8vHDvr1ZYV_l5j6mF4mzzWB78AlWzfPfZbP6vKLU6Qb-SmbJdmOAmN_g6wzX3Sq6K8joeWpX_v3uvU9UekRjJukEfWL6aUyDct8VA4vQAzaA12d0LsYTMAqNeMhg5qPEDk6ZL5jBus9Ajggbr6LId92MkYCz7Z58jL_tuPQMU-eUYISuXY83y5mfnrudi4JaPyTzn9h1IigIRfz1PUFiJ5a5bUGi1SeIZiyLcvzYNQi4hVvPABJ9eGNIa9Ir5WTlLN-W7WAZ1hBpnWYm4ykkMKSNMHbJXJz8iMXvYsrUir3_aBXFkSTApoGDpWhfLF5-yG1O-bjv1PQ_jfeD8dTUP3HjlfDEDd2SM_AIFA__gUFNx-pOjlmPdBthfhpiibExoct5SBrLbvzxGehhnRzKJ5On74duqEohLNwhdAjDRx_D_beJlJ--7NZsiEprmCPnWl9IslRxqbd5u5Mu_mDjOr2EDCXfpuzf4Es_vVh95nA6qKzbshuN2YfRoQRnbDVektEjbmFqLei4pY1WoS9dnvJrEZu_KuG1PM5bg1xL9YxNaapUZrXsL2Ar3290Nr9THNsKMOHYkbV2LW4CvYlUyHl8xOCtitgtnS9rPOcWQABpHy6Le_Hq8cr3kmeOyfplYjyJS1hpHrfRicvUV1_H8mevcxP0iTvjSuAkwysbAvr1rODQx4_e_1wi1bOevSB9oGTZgbdpw_xCC92FCrcAK4CHxl420pK-y4bg5b2SngnD-K-eBnAxc1Reu5qp3SL--BpDFr5TvqYHdxvfIUebzAzhE2kdqGWBrr-zIqd9mfwyJ8-Rt3psaPNUB4MYallKxzjgRgRJrkCk6N9OxoP9Y0NuoJwRFxzdcJXjB6V0tPjYwaL2yphHIKuebk_9DHPcea415zX8o3tfcgmM2Np9uixc7uRabGspFr7OVQnLFDCo5vqrl0X9bBrp72hjbkRkqK0Dn19669zO9_VtWHlxRbVkbFfUzOcA0EweL9fnIoP564b879A3YGFnnmhxENskcnBGsHNRGKEZE_PPcRXaOSO2ZkvkA2iF-1-NXCcOVMCATEA3LHqGDvUUHuw084h5C2Bw-SEnLOYrAIZ4hs22Ip1PnKZdbt92bM-E0Ph_MiZLgkNJjcH2CxfEh2K9U7X5Nk7KDr4A1SZGbHf0hQ1bthArAyw6JmSlyOzXQkt4vCiswUqkvMnYW8mfhhhetj2dqGRVEw1fpINjKq9SzI1UkZZR8_AU9B9q0-EdWYqxGCuHAxQ8q6SEMTHjeWrd_IptiL-MfzLNtV_ts9STYmSgaFKIlirWMMPmSk5VmQGLENLFz3MYjQj18Gfu-UivKbd9gpqucv-4AhNfD93so3-cjMFrFP4ebvWVltdNEL66uXDivozRPHDTFMvcFS-yIznrjXWRAzqd4r0TBg7DACkhjQvl7hxTlcY60DZMX6iRLrFDdJdQrs00hpPs63tBj5RdSi-mU2n_AnVtihQ8KsPDxJZqCcYyZRHHo4NO8ixMq45nM13znduVAOOlcNJQRYjgXViLc_FDELoVtfSEHLIR1BWVHeUGy3mgour3pC_YlJCwSPtjFxwmc0KkJSe5AOlzatp_74v1sr8iqlgyWrgAaLxa_IUZPP_rJFCa0ezDoKjF1Pn0BhMD13IjOXMhCVnn2MVMD8W9whGUI-fajoSmAkixThiexU8sx9QIQ5D5ylrdG3Hb1vSLrWwPbsrNkO1Rys0SI027YT8ADUayZwk9_TA09Ju_BE3dh3CwLgkEd1kjxrA181vC87GEJ8ZUK24-SRuZT52GuZtCCS5pjzBLv85rJHeN9zI4QqAO6er4pSYREgcgGWNx3CugD5n-CjrNx5ENkgW8CVAJoVtUWYs7A9UdJiwObjM-Bd3lFOFheBrvtzi9_bApMU2kSGGIuZBPTT87nYnAhWSjxph4bgY-2-wxsyGjOPZgXvJm6T4fCs3Lbh0AfoOSDlXl6uzUypS8wl0tF3AV451vZzTmkKQx0vGNNkVOTbzMKvyS2oR-CC0Nd9j1MB8_2qYVQe0PNE3mNMy7l0jUM1NkvMY0eovoG9I3h7XmHmfjigHpsZDknYs1oWTcgn4iphdySBRQYbHsN8PYaYcWlUBfIjGyYB9CdoCzPNRmNF8wZEvmafcTJrxc8s5AzCNLGEVi-MhI0Pq0JuoJ5ADpDYCcdbDeuvn221c0udiIaNSNISVP5b_Ho8Q5qf_wLGhfAXbUSx0zN3Gzug",cRq: {ru: 'aHR0cHM6Ly9qYWNrZXR0LmJhcmRlamVzcy5jb20vYXBpL3YyLjAvaW5kZXhlcnMvZ2t0b3JyZW50L3Jlc3VsdHMvdG9yem5hYi9hcGk/dD1jYXBzJmFwaWtleT1ibWxqMXV5b3FxbW9hYzMwemlpbWN2a3A4bGxwNjVyNg==',ra: 'UmFkYXJyLzQuNy41Ljc4MDkgKGFscGluZSAzLjE4LjMp',rm: 'R0VU',d: 'eT40ifIw3IkUmtk8DEKd/vPsjEtRJ2JjZ6r/BEnn3PiOSjFo63U7BUersT1bDpIFIVbikRmoR0Ih2hh1MOjbnx2xwcWeeFeCCjHsEtJ1qbE5CU5IwLsFQKcjF6lUb4eDEehUHigf7T996bg183ZuJhpVQjFApZ4g4QI6we/qGHvdX8jjol2FSG0uWNw/QJeYd9keVL5Jh0Qq0Di6NvTljfaJtYPvRjMV6ZE35QBvXjucJxNPoJ1lwyMUeD+XGp0xtinLnVjKGq65qoWdjlyD6RQqqMbQ+gtD5dcEv0ec5KWMJkUXDFOHhOjHGAV6aOmBTyDw2Mia+tmAgHznS4lDYfaZBcQRNhLxBRWTJ359CtjaZReDZP2mok0M6vrzb0pJE7hLq+kFNClnAIFOYXVschjahfHi6F8UXmrgaQu1NU8a1eqqWPDL4ayttjlKZRPl+br5SipPAtG4ReUs8Uge4w==',t: 'MTY5NjAwMjAwNi4zMzIwMDA=',cT: Math.floor(Date.now() / 1000),m: 'cRK0MT0ToP1wgrfaAmMPeN+ReYjheL8chxqEWeLTkso=',i1: 'Q+nmgxbfjy5Plft+mCAasg==',i2: '+rSo/IfX2rnRC3PqdZnkZA==',zh: 'viNwq01Y/PNu6GQ3dEDA2bz+FHo1Y3H75sKkkd/B/ig=',uh: 'ABDSykvIcuWbqfRHl2soUmgWik7oTvigNLjbvU2P8Qo=',hh: 'UcKwIAiTL7avBTS7rEUJwz3cv0wYjrhtRQ4af+dSi0I=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1?ray=80e5529b9df935fa';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/api\/v2.0\/indexers\/gktorrent\/results\/torznab\/api?t=caps&apikey=XXXXXXXXXXXX&__cf_chl_rt_tk=BKDC4SwGfH0dFhrua.LCZ8w99LJFEwqemWxVn59vn_g-1696002006-0-gaNycGzNClA" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>


[Warn] RadarrErrorPipeline: Invalid request Validation failed:
 -- : Unable to connect to indexer, invalid credentials. HTTP request failed: [403:Forbidden] [GET] at [https://jackett.bardejess.com/api/v2.0/indexers/gktorrent/results/torznab/api?t=caps&apikey=XXXXXXXXXXXXX]`
