### ISSUE TITLE
SQLite error (5): database is locked in "PRAGMA cache_size=-10000"

### ISSUE THREAD

**Issue by lee-costa** [Radarr/Radarr#9237]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I keep seeing these error messages in the logs but everything works as it should.

    SQLite error (5): database is locked in "PRAGMA cache_size=-10000"

### Expected Behavior

No database errors.

### Steps To Reproduce

1. Run radarr
2. Watch logs

### Environment

```markdown
- OS: Ubuntu 20.04
- Radarr: 4.7.5.7809
- Docker Install: NO
- Using Reverse Proxy: NO
- Browser: 
- Database: Sqlite 3.31.1
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

SQLite error (5): database is locked in "PRAGMA cache_size=-10000"

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
- Trace logs not provided
- Database locks are generally due to the storage not able to keep up with the database operations
- Some improvements in v5 for those; some improvements being worked on.
- Bring your trace logs covering the issue and support can give some guidance
- Known issues at times with list syncs and other operations causing locks
