### ISSUE TITLE
No need to reject Disks

### ISSUE THREAD

**Issue by ItsME6969** [Radarr/Radarr#9306]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Already commented on the PR but just incase it wasn't seen. I really dont think there is a reason for this change. There are people who actually grab these stuff and there is no reason to reject them for everybody just because Plex doesn't play them. There are other players like Infuse that Plays Bluray Disks, DVDs and even ISOs. If someone does not want disks, literally all they have to do is disable them, its that easy.
https://github.com/Radarr/Radarr/commit/79c03f2fe64dc7f45ee1a01cb281de34aeca8234

### Expected Behavior

Don't autoreject any quality that can be disabled by just going to the settings.

### Steps To Reproduce

...

### Environment

```markdown
- OS: Linux
- Radarr: 5.1.0.8168
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome
- Database:
```

### What branch are you running?

Nightly

### Trace Logs? **Not Optional**

...

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
- isos are supported; raw disks (folder dumps) are not which is what the spec I believe is attempting to block

**Comment by Qstick** [comment]
Right, this is simply aligning DVD raw disc logic with what we already do for other raw disc releases. Radarr doesn't support the releases so it makes sense not to grab them

**Comment by bakerboy448** [comment]
- adding support for rawdisk is under https://github.com/Radarr/Radarr/issues/8286
- The issue comes down - I believe - to needing multi file support similar to https://github.com/Radarr/Radarr/issues/145
- 1 movie; 1 file

**Comment by Qstick** [comment]
It's not sweeping anything under the rug. It's correctly handling releases that we know we don't support yet instead of letting them blow through the stack knowing they are going to fail.

It's like saying we don't support multi part files but instead of stopping them before grab and import we just yolo them into the importer to see what happens (hint. Only one gets imported and users complain).

Sure when we actually support full discs, it makes to remove it. Until then this keeps users out of our shorts by letting them know what's going on.
