### ISSUE TITLE
Feature Request: Download Slots/Queue

### ISSUE THREAD

**Issue by RossValler** [Radarr/Radarr#940]
**Description:**

I know some solutions exist to have torrent clients only run one download at a time but it might be cool to have Radarr delay the adding to the torrent client if something is actively downloading? New movies added would queue up behind the current download and not get added to the download client until a new slot is available. I'm not sure what would be involved here but might be useful :)

**Comment by joelm3103** [comment]
If torrent clients can queue downloads (given you set the number of active downloads) then why is this necessary? It is already adding to the client + you see it queue for download on Radarr so you already know it's there.

**Comment by RossValler** [comment]
Well the idea comes from only some clients having the ability to queue downloads so I was thinking if Radarr itself can queue them internally and only send the torrents to the client as they finish, we can achieve blanket support of all clients for queueing.

**Comment by fent** [comment]
What kind of client can't queue?

**Comment by RossValler** [comment]
Sorry, I meant queue out of the box.

**Comment by joelm3103** [comment]
> Sorry, I meant queue out of the box. rTorrent is an example of that.

Oh never knew that. All the torrent clients I've used previously had it built in so I thought it was a native feature across the board.

**Comment by onedr0p** [comment]
I think we want to leave this up to the download client. In rtorrent can't you set max downloads to 1?

**Comment by RossValler** [comment]
Max downloads in rTorrent is download connections per torrent rather than maximum running torrents. It's been a known bug for years unfortunately :(

**Comment by SJ50** [comment]
I am rtorrent user, rtorrent does not support queue. I have script which copy one torrent file from blackhole folder to watch folder, if there is no file in watch folder.
so,  I am able to queue in rtorrent.

**Comment by RossValler** [comment]
Does your script work with Radarr without using the drone factory?

**Comment by SJ50** [comment]
I use filebot to rename, move and symlink purpose, I do not use radarr media management and drone factory pointed at some empty hidden folder. At this moment my script can not mark movie downloaded/finished in radarr as radarr has api issue #915 .

**Comment by galli-leo** [comment]
IMO as onedrop pointed out, this should be handled by your dl client. I am leaving this open for now, but I don't think we will ever implement this.

**Comment by josh-sachs** [comment]
I know this Issue is stale and recently closed, so I assume this will go into a void but...

FWIW I don't think passing this off to the client is appropriate, especially considering Radarr is coordinating downloads across multiple clients (nzb, torrent). 

I actually came across this thread b/c I've run into a circumstance where IO and temp storage bottlenecks could be all be alleviated by an intelligent queuing system within Radarr. 

Ideally I could do the following: 

1. Define a maximum number of downloads that can be active globally, across all clients. 
2. Each client config should give a mechanism for supplying it's own max (or 0 to defer to global)
3. Define a global setting for how long a download can be "active" before being marked "stale"
4. Each client config should give a mechanism for supplying it's own ttl->stale config (or 0 to use global). 

Alleviates the following pain points: 
1. Allows more control over the I/O onto the disk, without having to guess at what ratio of your content comes in via different clients. 
2. If you set a maximum number of downloads in a client (e.g. transmission), it's possible that the queue will become deadlocked by incomplete downloads with not enough seeders.  Radarr needs to fail downloads after some period of time in order to free up space in the queue.
