### ISSUE TITLE
Import Exclusions slow down loading Settings

### ISSUE THREAD

**Issue by IvanJosipovic** [Radarr/Radarr#945]
**Description:**
I added ~100 "Import Exclusions". I noticed that loading the Settings screen takes over a minute to load.
Looking at the Chrome Debugger, it appears that a request is issued to "/api/movies/lookup/imdb?imdbId={id}" for every movie in the Import Exclusions list. This is presumably to translate the IMDB id to a Title.

**Radarr Version:** 0.2.0.415

**Comment by onedr0p** [comment]
@geogolem we may want to cache the titles, or only show IDs.

For now please do not use this feature.

**Comment by geogolem** [comment]
I'll look into this. I suppose, we can just search for titles once, and keep them.. instead of searching all the time... I'll try to fix this today or tomorrow.../ ... also we already have the title when they are being deleted and added automatically, so just cache it right away.. the only time that anybody would have to wait.. would be if they were adding them one by one, but we would only be checking as they add one at a time.. so it would be a non issue... 

this isnt a hard fix.. will do it in the next day or 2.

**Comment by geogolem** [comment]
for now I will just show the imdb or tmdb id.. i merged that fix.. will look into caching the title when i have time.

**Comment by geogolem** [comment]
I changed to priority low: /enhancement.. because I made it just show the id ... so the slow loading problem is gone.... but might wanna get and cache the title as an enhancement in the future..
