### ISSUE TITLE
The Ballad of Songbirds & Snakes actually searches The Hunger Games: The Ballad of Songbirds AND Snakes - no results

### ISSUE THREAD

**Issue by journeym** [Radarr/Radarr#9470]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

The Ballad of Songbirds & Snakes actually searches The Hunger Games: The Ballad of Songbirds AND Snakes - no results

### Expected Behavior

Get results

### Steps To Reproduce

-

### Environment

```markdown
- OS: -
- Radarr: 
- Docker Install: 
- Using Reverse Proxy: 
- Browser: 
- Database:
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/13618829/radarr.trace.txt)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by journeym** [comment]
Lets be real, trackers dont care about "scene" and their naming policy.
There needs to be option to customize how's the releases are searched. There lot's of local trackers with different naming.
Ideall possibility would be regex customization with pre-defined variables for each indexer.
Point me where is it in your code, and i can try to customize it myself.

**Comment by bakerboy448** [comment]
> This is radarr who send invalid data, jackett is working fine.

https://wiki.servarr.com/radarr/troubleshooting#tracker-needs-rawsearch-caps

Jackett problem. Radarr has nothing to do with whether the tracker reports rawsearch or not.

Please stop using github for support & ignoring the wiki links that indicate how to resolve.

**Comment by bakerboy448** [comment]
> Wiki link you provided has no resolution for jackett

![image](https://github.com/Radarr/Radarr/assets/55419169/5f1ab7cb-048d-456f-8cf3-c46f1ad48100)

**Comment by journeym** [comment]
This is clearly not a solution, to send ppl writing to another product support for the problem that can be easly circumvented inside your product.

**Comment by bakerboy448** [comment]
>easly circumvented inside your product.

It already can be....the tracker must indicate it is RawSearch not Sphinx (default) as detailed numerous times above.

The issue is your tracker failing to report that it needs the non-modified search terms (raw search). Radarr has nothing to do with the capabilities of your tracker reported from Jackett or Prowlarr. Radarr does not and will likely never support your indexer natively.....it supports it via torznab which jackett and prowlarr handle as the middleware and that is where this needs to be resolved.

It appears at this point given your refusal to take a support issue to the support channels and refusal to resolve the issue with the correct applications you are only here to troll or spam.
