### ISSUE TITLE
Delay causing movies not to be added to queue or being removed

### ISSUE THREAD

**Issue by 16golfr** [Radarr/Radarr#9823]

**Comment by 16golfr** [comment]
Just want to add, if go into that movie and click automatic search it will grab it just fine and bypass the "delay"

**Comment by bakerboy448** [comment]
> You have a movie in queue that has a score of 3000, it will be downloaded in 10 days
RSS feed finds that movie but with a score of 6000
So the logic is to replace that 3000 with a 6000, and have a new 10 day delay
now what happens is that 3000 movie gets removed from queue, to be replaced with the 6000 score movie, but that 6000 movie doesn't get added because of the delay set in "Minimum Age"

to confirm understanding: 

- When a delay profile is used, the new item is accepted from rss, existing item is removed from queue, then the new item is rejected due to minimum age and the queue ends as empty?
- we need trace logs of this 
- Why are you using minimum age? It should jsut about never be needed with modern Usenet provider as there is effectively no need to wait for the release to propagate these days

> have movie with lower score download, no minimum age, but delay of X days
better score movie just released, force rss. it won't get added to the queue.

- it should be added to the queue as a delayed/waiting item, does it not?

> if go into that movie and click automatic search it will grab it just fine and bypass the "delay"

things correct; delay profile is only applies to the preferred release type for rss grabs not automatic or interactive searches

**Comment by 16golfr** [comment]
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/14517869/radarr.trace.txt)
I did it, holy that took forever to re produce this
And same thing happened the file vanished from queue :)

**Comment by 16golfr** [comment]
<img width="806" alt="Screenshot 2024-03-06 at 9 28 25 PM" src="https://github.com/Radarr/Radarr/assets/87627355/88ad96b0-3d5f-4701-9402-4a2d6d5552df">

I added the first movie to the queue , then changed scoring to make the top one higher, so it would pickup the newer one but made it so the min age was higher, so even though the release was better it wouldn't get added to the queue. "which is how it should be", but then it took out the existing one that met the minimum age

**Comment by bakerboy448** [comment]
```
2024-03-06 21:21:43.6|Debug|DownloadDecisionMaker|Release 'Coming.to.America.1988.UHD.BluRay.2160p.DD5.1.HDR.x265-BHDStudio' from 'site' rejected for the following reasons: [Temporary] Only 43.3 minutes old, minimum age is 180 minutes, [Temporary] Waiting for better quality release
	```

**Comment by 16golfr** [comment]
Ah I see that I can fix that up, but the 2nd issue still stands and is serious flaw

**Comment by 16golfr** [comment]
My 2nd issue trace log portion is in the 1st post.
